### ISSUE TITLE
Sometimes hangs when focusing neovide from other vulcan/metal based window (osx)

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#100]
My setup:
* Neovim 0.4.3
* Neovide
* Macbook pro 2018
* Macos 10.14.6

It's pretty strange.  I can only seem to consistently reproduce it by doing this:
* Open neovide with nvim with an no config file
* Open Unity3D version 2018.4.0f
* Click around on different transforms
* Hit CMD+Tab to select neovide
* Hit CMD+Tab to select Unity
* Repeat this process, clicking around to cause more rendering to occur for both apps, until neovide hangs

This issue happens often enough for me that I've had to return to using nvim-qt instead (which doesn't have this issue)

My only guess is that it has to do with with the hardware rendering via metal, since other windows that aren't Unity (which also uses metal) do not cause neovide to hang like this

**Comment by Kethku** [comment]
Bummer you were running into this so frequently. I suspect this will be improved once I get the opengl renderer up and going.

Can you be more specific about what hanging means?

**Comment by Kethku** [comment]
Further I'm almost done with adding logging which may help to figure out where the logging happened (but you're probably right it likely has something to do with either winit or the renderer)

**Comment by Kethku** [comment]
Any chance I could trouble you to try with any of the winit examples and see if the freezing happens then? And further it sounds like you can't get it to happen in any apps other than unity?

**Comment by svermeulen** [comment]
By hanging I mean that nothing happens for about half a second then my mouse turns into the loading icon, then several seconds pass and then it seems to just give up on focusing on it.  After this happens I can try focusing on it again and it often works the second time (so it doesn't hang indefinitely)

It's a bit weird because either it focuses on neovide immediately without issue or it gets stuck attempting to focus for maybe 5 seconds

I'll keep an eye out for updates here to try again when there's more logging or different rendering options.

How do I try the winit examples?

**Comment by Kethku** [comment]
The fact that refocusing causes it to wake up is interesting...

As for the winit examples none of them look appropriate for testing, so I guess nevermind. Either the demo isn't obvious if its hung, or it renders in a full loop. One option I can give you as a temporary fix would be a mode which doesn't shut down between renders, and just renders 60 fps. For most frames this is fine as it is just cycling the image to and from the gpu and not doing any work, but it will take a hit on cpu and gpu.

Would that be an interesting option for you as a temporary fix?

**Comment by svermeulen** [comment]
Sure, I'd be happy to try that mode to see if it resolves my issue

**Comment by Kethku** [comment]
I'll ping here when it's ready

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Just pushed a big change which adds the feature via a --noIdle command line argument. This means the app will always use some cpu and gpu, but it shouldn't be toooo much. Let me know if that fixes the issue for you as it would be a good hint for how to potentially fix it.

**Comment by svermeulen** [comment]
Ok so I updated to HEAD, rebuilt, and then added `--noIdle` command line parameter, but that did not help this issue.

I also spent some time going back and forth between including the `--noIdle` parameter and not including it, but found that using the `--noIdle` was either the same or worse.

Happy to try more things if it's helpful

**Comment by Kethku** [comment]
Very interesting. Can you confirm that neovide uses more resources with --noIdle set just to confirm it is doing anything?

**Comment by svermeulen** [comment]
Hmm yeah so I tried that but the CPU usage seems identical in both cases.  It shoots up to maybe 7-10% when focused and moving around, then when unfocused in both cases it goes down to 0.0 -> 0.4% CPU.  I didn't look at GPU usage though

**Comment by Kethku** [comment]
That sounds like the argument isn't working... Hrmmm let me think on it and get back to you. Its late here.

**Comment by Kethku** [comment]
@svermeulen could you try from the sdl2 branch? It may have improved things

**Comment by Kethku** [comment]
I believe this should be fixed with the merging of sdl2 branch. Please reopen if you discover it isn't
