### ISSUE TITLE
cargo build --release error: "failed to parse lock file"

### ISSUE THREAD

**Issue by Asheq** [Kethku/neovide#101]
```
$ cargo build --release
error: failed to parse lock file at: ~/dev/github.com/Kethku/neovide/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

**System info:**
- OS: macOS Mojave 10.14.6
- cargo --version: cargo 1.37.0 (9edd08916 2019-08-02)

(Looking forward to trying out Neovide. It looks great!)

**Comment by Kethku** [comment]
Try deleting the lock file and trying again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asheq** [comment]
Thanks! I deleted the lock file, and I see this error now:
```
$ cargo build --release
   Compiling bytes v0.5.4
   Compiling clap v2.33.0
   Compiling clang-sys v0.28.1
   Compiling syn v1.0.14
   Compiling curl-sys v0.4.25
   Compiling bytes v0.4.12
   Compiling tar v0.4.26
   Compiling mio v0.6.21
   Compiling winres v0.1.11
   Compiling ash v0.29.0
   Compiling memoffset v0.5.3
   Compiling env_logger v0.7.1
   Compiling core-graphics v0.17.3
   Compiling euclid v0.20.7
   Compiling objc v0.2.7
   Compiling syn v0.15.44
   Compiling num-integer v0.1.42
   Compiling rmp v0.8.9
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /Users/asheq.imran/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Kethku** [comment]
Do you have a recent version of rust?

**Comment by Asheq** [comment]
How do I check? Sorry, I'm not very familiar with a rust dev environment.

I installed rust from here as shown in the README: https://rustup.rs/

And I see this:
```
$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

**Comment by Kethku** [comment]
Cargo --version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
And it's all good!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asheq** [comment]
```
$ Cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
```

**Comment by Kethku** [comment]
Hrmm I'm not sure if that is the rust version but if it is I'd recommend updating and try again.

If that doesn't work I will take a closer look in an hour or so when I have access to a machine

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Actually now that I think about it, likely both the above issues were caused by an old version of rust. I could be wrong though

**Comment by Asheq** [comment]
I ran `rustup install stable` and `rustup update` and it worked (not sure if both commands were needed). Here are my latest versions:
```
$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)

$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)

$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
```

Thanks again for your help! Loving the animated cursor!

**Comment by Kethku** [comment]
Beautiful. let me know if anything isn't working for you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
