### ISSUE TITLE
Neovide captures keystrokes in other windows

### ISSUE THREAD

**Issue by tailhook** [Kethku/neovide#1019]
**Describe the bug**
Often when I switch from neovide to other window neovide continues to capture keystrokes.

**To Reproduce**
1. Open neovide (perhaps start insert mode to reproduce easier, but it's not required)
2. Switch to a different workspace using window manager shortcut
3. Type something in the new focused window 
4. Switch back to the neovide window and see your keystrokes worked in neovide

Sometimes it also works with windows in the same workspace (so you can see text appearing in both windows simultaneonsly). But I couldn't find way to reproduce it reliably.

**Expected behavior**
neovide doesn't capture keystrokes when is hidden or not focused (and/or different window is focused)

**Screenshots**

https://user-images.githubusercontent.com/321799/137625049-0245c7cc-854b-4e31-85b9-52cbb6b15039.mp4

**Desktop (please complete the following information):**
 - OS: NixOS (Linux 5.14)
 - X.Org X Server 1.20.13
 - X Protocol Version 11, Revision 0
 - Neovide Version: git revision 725f12cafd4
 - Neovim Version: 0.5.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Almost empty:
```
TRACE [neovide] Neovide version: 0.8.0
```

**Additional context**

I'm using quite weird tiling window manager, but this is the only program that experience this behavior, so I think the bug should be in the neovide.

**Comment by phi-mah** [comment]
This looks pretty similar to the issue that I reported here: #958
