### ISSUE TITLE
Does not compile on FreeBSD

### ISSUE THREAD

**Issue by devosalain** [Kethku/neovide#1025]
cargo build --release
Error:
Compiling skia-bindings v0.40.2
Compiling smithay-client-toolkit v0.12.3
error: failed to run custom build command for `skia-bindings v0.40.2`

FreeBSD 13.0-RELEASE-p4
cargo 1.55.0
rust-1.55.0

**Comment by qiu-x** [comment]
@shaunsingh FreeBSD uses it's own libc and not musl
