### ISSUE TITLE
Add cargo-bundle to actions

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#105]
As mentioned here: https://github.com/Kethku/neovide/pull/103#issuecomment-581736977 cargo bundle seems like a good option for producing macos and linux release assets. On windows the single exe with everything linked in should be more than sufficient, but the other platforms need some help.

In particular it is important that we add the icon to the resulting bundle, but that appears to be well supported.

**Comment by rahuliyer95** [comment]
Another small thing I noticed. The macOS binary only works if the Vulkan SDK is installed. There
must be a way to bundle the Vulkan SDK along with the build
