### ISSUE TITLE
On Windows, clicking on text doesn't take into account hidpi settings

### ISSUE THREAD

**Issue by jonvaldes** [Kethku/neovide#107]
If neovide is on a monitor with a hidpi scaling != 100%, clicking on it will send the cursor to the wrong line. 

This is the setting, under "Display settings":
![image](https://user-images.githubusercontent.com/48644/73760121-39813d80-476d-11ea-8569-9672a7b7b570.png)

Moving the window to a monitor with normal hidpi scaling will make clicking work correctly

**Comment by Kethku** [comment]
Yeah this I think was a bug that just got introduced. Not sure whats up. I will look into it later tonight

**Comment by Kethku** [comment]
I was just about to make an issue but you beat me to it :P

**Comment by Kethku** [comment]
Fixed
