### ISSUE TITLE
Alternate communication channel? 

### ISSUE THREAD

**Issue by jonvaldes** [Kethku/neovide#110]
Communicating through Github issues is not great. Maybe we could settle on some other communication mechanism to coordinate development?

Mailing list, IRC channel, something else...?

**Comment by Kethku** [comment]
Seems like people like gitter. I'd like an option which has good mobile support, but honestly I'm not picky. To you have a preference?

**Comment by Kethku** [comment]
Added benefit of gitter is that neovim uses it for their communication

**Comment by Kethku** [comment]
That said, mobile for gitter is very bad

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonvaldes** [comment]
I don't really have a preference, other than I'd rather use an open source solution (so I'd prefer not to use Slack, Discord, etc).

We could try gitter and reevaluate some time from now, I guess?

**Comment by Kethku** [comment]
That sounds good to me. I'll figure out how to add a readme link later today

**Comment by jonvaldes** [comment]
I can start by creating the neovide "community" in gitter. Or would you rather create it yourself?

**Comment by Kethku** [comment]
Nope, I'm good. go for it.

Thanks,
Keith
________________________________

**Comment by jonvaldes** [comment]
Hummm do you know if the community can be linked to the repo later?
![Screenshot_2020-02-04_21-02-1580849022](https://user-images.githubusercontent.com/48644/73785517-b2958a80-4797-11ea-9e99-4f3f0fc0ca7e.png)
If not, maybe you should create it instead

**Comment by Kethku** [comment]
No idea. Let me take a look

**Comment by Kethku** [comment]
[![Gitter](https://badges.gitter.im/neovide/community.svg)](https://gitter.im/neovide/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
It's supposed to make a PR to add the gitter badge

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by justinmk** [comment]
> mobile for gitter is very bad

I use the web app on mobile browser. It's ok. Typically these chats aren't high traffic, or for deep conversations mobile is unpleasant no matter what service you use..

**Comment by Kethku** [comment]
Done. Added a link to gitter in the readme
