### ISSUE TITLE
[Feature Request]: System clipboard integration

### ISSUE THREAD

**Issue by MobiusHorizons** [Kethku/neovide#113]
Hello, thanks for building this great project.

On my mac, I noticed that I don't get system paste using CMD+V as I would expect. I would love to have this functionality.

I have not personally used it, but I believe this crate may provide a cross platform way of doing this: https://github.com/aweinstock314/rust-clipboard

**Comment by justinmk** [comment]
That can be done with a mapping:

    nnoremap <D-v> "+p

**Comment by Kethku** [comment]
Yes this is out of scope for the gui. Handling paste bindings should be done inside of the vim init scripts, not the gui. If you'd like some more help feel free to comment here, but I am closing for now.

**Comment by x37v** [comment]
In case anyone else runs into this, it looks like neovim provides system clipboard integration by using external applications.
`:help clipboard-tool`

On my linux machine I ran `sudo apt install xclip` and now I have system clipboard integration.

**Comment by ouuan** [comment]
For anyone who found this and don't know how to paste in insert/command mode, here's my config:

```vim
" system clipboard
nmap cp "+y
nmap <c-v> "+p
inoremap <c-v> <c-r>+
cnoremap <c-v> <c-r>+
" use <c-r> to insert original character without triggering things like auto-pairs
inoremap <c-r> <c-v>
```

**Comment by MobiusHorizons** [comment]
Just for a little clarification, the original intention of this request was for an interesting WFH setup where I was running neovide locally calling neovim on a remote machine over ssh. (I put a shell script in my path that called neovim over ssh and passed all arguments). In this configuration, the regular copy to clipboard integration in neovim was not useful, since it copies to the remote clipboard. I would still like to be able to copy (at least through a menu) to the system clipboard from neovide in order to make this use-case work better.

**Comment by bmulholland** [comment]
Sadly none of the above solutions work in command mode, e.g. when I'm trying to paste a filename to open for edit with `:e `

**Comment by sonofjack** [comment]
> It might if I had one :). And of course that kinda defeats the keyboard centrism I use vim for.

I hear you loud and clear. I had the same problem.
In command mode, try `ctrl+r + "`

**Comment by Lite5h4dow** [comment]
saying " this should be handled in nvim" is just a cop out honestly. if you open nvim in a terminal that supports copy and paste, you can paste from the system clipboard.

**Comment by MultisampledNight** [comment]
Sorry, but what's wrong with using an external program? If you install `xclip`/`wl-clipboard` on your system, you'll never actually use it and `"+p` magically works. So I'm not quite sure what you mean by

> only windows(kinda) and mac with "+p, linux dosen't have such luxuries

**Comment by MultisampledNight** [comment]
Also, because I haven't seen it here yet: It's possible to use the normal buffer which

**Comment by Kethku** [comment]
Couple things:
1. Making cuts around features is life or death for a project like this. We can't make every feature, and especially when something could be done upstream to the benefit of all neovim guis, it's not a bad tradeoff to say that we won't do it ourselves
2. Recently someone contributed this feature already. If you take a build from main and set clipboard+=unnamed plus it will transparently use the system clipboard over the gui socket. Have you tried just using the clipboard like normal from a recent build from main? It should just work the way you describe. 

Saying my explanation for why we don't do a feature is a "cop-out" is unhelpful. Building a case for why a feature should be done is absolutely reasonable, and it may shift priorities, but the way you did it wasnt great. We would be more than willing to help anybody navigate the code and build a feature if we don't have the cycles to do it ourselves.

**Comment by Lite5h4dow** [comment]
cool i wouldnt mind taking a crack at this myself but my plate is full with other projects. my current buildis off the neovide-git on the AUR which i believe pulls off main, however using `"+p` dosent work. i havent mapped anything onto it so its default functionality should work if it ever did which it dosent.  i constantly have to print other command buffers into a file to get some thing pasted, also using exernal programs for me would be a pain, i am constantly switching platforms between windows and linux, accessing remotely or editing something inside a docker container, so setting that up, all the time, everywhere is extreemly painful just for copy and paste.

**Comment by Kethku** [comment]
Then I think that's a bug. Can you create an issue with minimal issue repro steps and your platform info?

**Comment by njkevlani** [comment]
For folks not being able to paste in command mode, this mapping worked for me:

```vim
cnoremap <c-v> <c-r>+
```

**Comment by Lite5h4dow** [comment]
> For folks not being able to paste in command mode, this mapping worked for me:
> 
> ```viml
> cnoremap <c-v> <c-r>+
> ```

this is about something completely different, this ticket was about system clipboard integration not internal

**Comment by chardskarth** [comment]
![image](https://user-images.githubusercontent.com/26249511/195976838-bca26114-3800-4e61-8d02-a55fda037e1b.png)
This is how I set it in mac, but it's not pasting when I'm in exec mode. ("typing :", is it called exec mode)

**Comment by bmulholland** [comment]
I've filed https://github.com/neovide/neovide/issues/1602 for the specific subset problem of "paste from system clipboard to command mode/exec mode/whatever it's called"

**Comment by sleeptightAnsiC** [comment]
If someone is still looking for copy/paste bindings introduced by most terminal emulators - Ctrl+Shift+C to Copy, Ctrl+Shitf+V to paste - this can be achieved with:
```lua
if vim.g.neovide then
	vim.api.nvim_set_keymap('v', '<sc-c>', '"+y', {noremap = true})
	vim.api.nvim_set_keymap('n', '<sc-v>', '"+P', {noremap = true})
	vim.api.nvim_set_keymap('v', '<sc-v>', '"+P', {noremap = true})
	vim.api.nvim_set_keymap('c', '<sc-v>', '<C-R>+', {noremap = true})
	vim.api.nvim_set_keymap('i', '<sc-v>', '<ESC>"+Pi', {noremap = true})
	vim.api.nvim_set_keymap('t', '<sc-v>', '<C-\\><C-n>"+Pi', {noremap = true})
end
```
Apologies for necroing this thread. It shows up on the very top of search results.

**Comment by dmolin** [comment]
@sleeptightAnsiC Thank you so much for your comment!  could you explain what all these mappings do exactly? when using neovim in the terminal I'm used to yank (as usual in Neovim) and then paste with Ctrl+S+v when using things like a file picker (where I cannot just "paste" with the usual keymap since I'm in insert mode there). With your keymaps I can still work this out but I noticed that I've to paste by using Ctrl+S+v + p (it's like Ctrl+S+v puts me out of insert mode, so "p" then does the trick of "pasting" my clipboard).  I'm already happy with this but I'm curious to understand how this is the result of all those mappings you posted

**Comment by sleeptightAnsiC** [comment]
@dmolin Hmn... I think this behavior did broke due to some small internal Neovim changes (not sure though).

Each of these bindings was supposed to get you into the normal mode, potentially move the cursor to the right with `l`, trigger paste with `+P`, and get you back to the previous mode.

However, right now it seems that if you try to paste on the empty line, the part _"potentially move the cursor to the right with `l`"_ will break the whole chain. That's probably what you're experiencing on your side.

Also, the bindings for command line seem broken. Maybe I was using some kind of plugin that was replacing command line with buffer. I really don't remember the details about these. I'm not using neovide anymore.

**Comment by sleeptightAnsiC** [comment]
@dmolin Take a look at this linked comment, someone fixed it there :)

https://github.com/neovide/neovide/issues/1282#issuecomment-2496204257

**Comment by dmolin** [comment]
@sleeptightAnsiC  YES! that seems to work just fine! thanks for pointing me in the right direction 😃

**Comment by TRPB** [comment]
I'm not sure if it's because I'm using noice.nvim but I had to use this for command mode:

```
vim.api.nvim_set_keymap('c', '<C-v>', '<C-r>+', {noremap = true})
```
