### ISSUE TITLE
Cursor move to bottom when deoplete is open

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#116]
when the deoplete menu opens, the cursor moves downward. It should not moving as we still type character.

![2020-02-05-131151_1920x1080_scrot](https://user-images.githubusercontent.com/12698940/73840753-27f56f80-4819-11ea-9f36-4d328e06d35a.png)

**Comment by Kethku** [comment]
Any chance you have lazyredraw set?

**Comment by kiuKisas** [comment]
Good catch, it was set. Unset it fixed the issue. I guess it should be specify in the Readme ? 

Now, my question is: Is it plan to make this option compatible with neovide or it's an incompatibility by design ?  

If it's not the case, what about overwritting the config file with this kind of options ? With a warning maybe ? (sound dirty but can prevent people from believing it's a bug [if it isn't ])

Just for this thread information:

```
'lazyredraw' 'lz'	boolean	(default off)
			global
	When this option is set, the screen will not be redrawn while
	executing macros, registers and other commands that have not been
	typed.  Also, updating the window title is postponed.  To force an
	update use |:redraw|.

```

**Comment by Kethku** [comment]
This is an upstream issue which I opened a day or two ago. https://github.com/neovim/neovim/issues/11806

I think it is useful in general but neovim guis interact weirdly with it.

At least in theory a more recent version of neovide should handle this already on startup. I'm not actually in charge of publishing to AUR (not sure who is doing that) so maybe a new build would help?

**Comment by kiuKisas** [comment]
Actually it works with a new build, thank's !
