### ISSUE TITLE
init.vim error on startup freezes application

### ISSUE THREAD

**Issue by SirJson** [Kethku/neovide#119]
Found another bug:

neovide seems to freeze up if there is a problem in the init.vim file.

![grafik](https://user-images.githubusercontent.com/1042414/73899167-0e414000-488c-11ea-8b8f-86a32331b90b.png)

This screenshot is after I maximised, I hope it illustrates the issue a little bit better. But the freeze up is also happening on a normal untouched window.
Pressing enter or anything else does nothing. The application is still frozen on that screen.

I'm running the latest master version of neovide with NVIM v0.4.3 on Windows.

**Comment by Kethku** [comment]
My bad. Should be fixed.
