### ISSUE TITLE
Handle horizontal scrolling

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#12]

**Comment by gokulsoumya** [comment]
There seems to be a difference in how scrolling works for horizontal vs vertical mode - vertical scrolling follows natural scrolling (moving the finger down scrolls up and vice versa) but horizontal scrolling follows the normal method (moving the finger right scrolls right instead of left).

**Comment by Kethku** [comment]
Thats a separate issue that I believe may be upstream. Could you create another issue for it?

**Comment by gokulsoumya** [comment]
New issue created #582.
