### ISSUE TITLE
Instructions for creating the .app on osx

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#123]
I use this on osx by directly executing the file generated at `neovide/target/release/neovide` after following the build instructions in the readme.  However - it would be nice if I could build an actual `.app` directory.  I see there some code in `.github/workflows` that appears to be doing this?  Is the build that that generates available for download somewhere?  If not, is there a way for me to do the same locally?

**Comment by Kethku** [comment]
Currently binaries for windows mac and linux can be found here: https://github.com/Kethku/neovide/actions

I don't really understand how macos works though. It looks like it just produces a folder... is that enough?

**Comment by svermeulen** [comment]
Yeah, there should be a `.app` folder.  Most apps are distributed this way and then run using `open -a Foo.app`.  I tried downloading the generated `.app` folder but it doesn't seem to run when I try it.  I get this error:
```
>open -a Neovide.app
LSOpenURLsWithRole() failed for the application Neovide.app with error -10825.
```
For now I can just keep running the `neovide` executable so not a big problem.  But it would be easier as an app so that I don't always need a terminal open for it.

**Comment by svermeulen** [comment]
Oh I see the problem now:

![image](https://user-images.githubusercontent.com/810762/74079256-0940e400-4a78-11ea-9760-5d6e5c55e063.png)

I'll try it again when I upgrade

**Comment by Kethku** [comment]
I have no idea if that requirement is real. Not sure where the version requirement came from...

**Comment by smesko85** [comment]
It looks like the package executable has wrong permissions set. After running `chmod +x neovide` in `Contents/MacOS`, I was able to start the app. But unfortunately on my machine it just seg-faulted

**Comment by JorisDeRidder** [comment]
Same on my Mac.
