### ISSUE TITLE
NERDTree Menu not showing anything

### ISSUE THREAD

**Issue by neelu0** [Kethku/neovide#130]
there is a weird problem, when opening nerdtree menu the command height increases like usual but its completely empty, when it should have different options like `(a)dd child node` etc, while they actually are working if i press a or m or whatever, its just they are not showing,
also if i press arrow keys or press <C-w><C-w> (mapping for cycling through splits) the out put that is supposed to be shown just flickers.
![issue](https://user-images.githubusercontent.com/45328066/74586957-e762d680-500e-11ea-8119-89fa89373577.png)
right one's is expected output and left one is neovide,
i also tried it on nvim-qt and there too it works as expected and tried another gui called fvim and it was working there too, it just fails on neovide.
also i am using windows by the way.

**Comment by Kethku** [comment]
Thats... very weird. Did you build from scratch or just run from the release?

**Comment by neelu0** [comment]
run from release

**Comment by Kethku** [comment]
Could you try building from master? Release hasn't been updated for a while.

**Comment by Kethku** [comment]
I'm 99% sure this is because the release is an old build. Closing, but if you come back to this and notice that its something else, please reopen.

**Comment by neelu0** [comment]
nah man, i don't have visual c++ build tools, i can live with this small bug, and can wait for new release build, as long as there are plans for it, otherwise :(
