### ISSUE TITLE
neovide panics with 'index out of bounds' after an arbitrary number of keyboard interactions

### ISSUE THREAD

**Issue by vivlim** [Kethku/neovide#131]
Neovide is panicing after a small number of keyboard inputs.
The quickest I've seen it is when typing a `:` to start a command, but on other runs that has been fine. Other times I see it when I type a few characters into an empty buffer.

OS: Ubuntu 19.10
Video: Intel HD Graphics 5500
WM: kwin_x11 5.16.5

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4209042/neovide_rCURRENT.log)
[stack.txt](https://github.com/Kethku/neovide/files/4209043/stack.txt)

I attached a debugger and it seems like the panic is happening inside of skulpin. Something is trying to draw on a skia_surface at index 4, but there are only 4 surfaces in the array.

![image](https://user-images.githubusercontent.com/1565930/74596065-e45fea00-4ffe-11ea-9c45-5a6c8bc3800e.png)
![image](https://user-images.githubusercontent.com/1565930/74596068-fa6daa80-4ffe-11ea-83fe-ee0d04067a93.png)

**Comment by Kethku** [comment]
Hey! Could you try running on the new sdl2 branch? Its very possible there are build errors since I've only tested it on windows, but it should fix the rendering error I think

**Comment by Kethku** [comment]
Merged sdl2

**Comment by Kethku** [comment]
Closing for now. If this is still an issue, please reopen

**Comment by vivlim** [comment]
Works with sdl2.

**Comment by Kethku** [comment]
yay!
