### ISSUE TITLE
blank whitescreen when switch tags in dwm-win32

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#133]
I use [dwm-win32](https://github.com/prabirshrestha/dwm-win32) as a tiling manager on windows. When I switch tags and come back to the tag which neovide exists it shows a blank white screen and I have to press a key to force it to redraw.

Most likely an easy fix as in when an external program hides neovide and shows it back it should redraw.

**Comment by Kethku** [comment]
Could you try the sdl2 branch? I just pushed a change which should do what you are saying and moving forward sdl2 is going to be the new default

**Comment by prabirshrestha** [comment]
Works in sdl2 branch. closing for now.
