### ISSUE TITLE
[Sdl2][Arch Linux] Win + up/down/left/right

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#137]
I use `Win` + Arrow directions to move between my system windows, neovide trigger a regular arrow directions when focused on it

**Comment by Kethku** [comment]
This is very weird. I will add some logging soon to help debug this. This feels like something that should be handled in vim, but I need to confirm the inputs actually sent to neovim first before I can say that for sure

**Comment by Kethku** [comment]
Ok I have pushed the necessary log changes. Could you try running neovide with the --log argument and attach the resulting log file that should get written?

**Comment by Kethku** [comment]
After testing the Win + Arrow thing I mean

**Comment by kiuKisas** [comment]
There it is :
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4226790/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
I'm sorry, i pushed to the wrong branch. Could you pull from master and do it again? My bad :(

**Comment by kiuKisas** [comment]
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4227287/neovide_rCURRENT.log)
Interesting, I enter insert mode, type neovide, do the Win + direction thing, the bug doesn't occured , then going back to normal mode and the bug happen

**Comment by Kethku** [comment]
Are you using master or sdl2? Sdl2 branch was merged to master

**Comment by kiuKisas** [comment]
Yeap, I delete everything and build again just in case:
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4229916/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
Weird... looks like your key gui key isn't getting recorded properly

**Comment by Kethku** [comment]
I think it is possible that your window manager is eating the window key but still passing the arrow key in. Theres not much I can do about that. Closing for now, but totally willing to reopen if you think there is something to be done
