### ISSUE TITLE
[SDL2][ArchLinux] Incorrect mouse position + scroll issue

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#138]
When I click on a character, the cursor move to an incorrect position (some characters further). More I go down in my buffer, more the cursors shifts.
Probably due to the same incorrect position detection, when I scroll, it can scroll at the next vim window on the right when I'm not in the left border of my vim window.

With one window opened:
Click on `1:1` --> `1:4`
Click on `1:2` --> `1:6`
CLick on `3:3` --> `4:8` (even if my third ligne contains 200 characters)

**Comment by Kethku** [comment]
fixed
