### ISSUE TITLE
Strange black bars on neovide start

### ISSUE THREAD

**Issue by Arjun31415** [Kethku/neovide#1387]
**Describe the bug**
Black bars on neovide startup
**To Reproduce**
1. download neovide from source
2. build with cargo
3. launch neovide

**Expected behavior**
No black bars with proper transparency
 
**Screenshots**
![image](https://user-images.githubusercontent.com/72289243/177735841-09c09297-31c5-43f2-a768-e2c52972be0c.png)

https://user-images.githubusercontent.com/72289243/177733502-ad2a218a-5213-4328-92f3-853dff5a98ff.mp4

**Desktop **
 - OS:Garuda Linux (Arch based)
 - Neovide Version 0.9.0
 - NVIM v0.8.0-dev+572-g6b72ee1f1
- Compositor picom
### Neovide Log-
https://pastebin.com/R4QM8q6X

**Additional context**
It goes away after scrolling few times or sometimes not at all

**Comment by thomascft** [comment]
I'm working on a theme that has transparent editor windows with other section such as the file explorer and terminal opaque. Is there a way to produce this behavior on purpose?

**Comment by Arjun31415** [comment]
Yeah in the video i have shown my neovide config on the Left

**Comment by MultisampledNight** [comment]
It's not the actual issue though, I suppose dashboard-nvim does weird things with highlights in certain cases to group sections. But I haven't been able to figure out what exactly yet.

**Comment by fredizzimo** [comment]
This is an old issue, and I have not seen similar reports for a long time, so I assume it's fixed.
