### ISSUE TITLE
Neovide does not recognize path and crashes when trying to run from alacritty/kitty

### ISSUE THREAD

**Issue by RustyDev24** [Kethku/neovide#1407]
**Describe the bug**
Whenever I try to format files in Neovide (launced directly from the app launcher rofi); for example a lua file I get an error saying stylua is not in path but I have it installed and have exported it into the path variable from my bashrc.

Also whenever I try to start neovide with the command `alacritty -e neovide` it just crashes and not opens

**To Reproduce**
I do not know the steps to reproduce this. I have hopped to arch linux right now and this problem started happening (it also happened in endeavour os)

**Expected behavior**
I expected neovide to just format the code.

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Neovide Version 0.9.0
 - Neovim Version v0.8.0-dev-nightly-2-g711a6a915

**Comment by MultisampledNight** [comment]
Thanks for reporting! This actually sounds like two issues:

- `stylua` not found, Neovide not picking up the `PATH` environment variable sounds a lot like #1395. You probably want to configure that one in your shell profile or through `systemctl set-environment` instead, in case you're using systemd as your init system (and you most likely do).
- Neovide crashing upon starting. Maybe related to the one above, but I can only guess. What does the log say? Is there any additional console output if you run `neovide --nofork`?

**Comment by Black-Sirius69** [comment]
I read that issue. I removed the neofetch command from my bashrc but it still did not load until I supply the `nofork` argument but then I get two windows instead of 1

**Comment by MultisampledNight** [comment]
Two windows as in two different Neovide instances? Could you maybe share your log?

**Comment by Black-Sirius69** [comment]
Not two neovide instances. I get one neovide instance and one plain window that maybe comes from alacritty

**Comment by MultisampledNight** [comment]
That's okay, I guess. Naive question: Why do you run Neovide inside of alacritty at all? It draws its own window surface and is not bound to a terminal emulator.

**Comment by Black-Sirius69** [comment]
The point to run it from alacritty is that it does not recognize anything when I launch it from my keybindings in XMonad until I change focus and come back to it

**Comment by MultisampledNight** [comment]
I don't quite get it, if Neovide doesn't recognize any input once opened (without re-focusing), why does the opening procedure through alacritty matter?

**Comment by Black-Sirius69** [comment]
opening through alacritty helps because in my endeavour OS config opening through kitty did not sieze the input and it used to work easily

**Comment by Black-Sirius69** [comment]
Though I think it is some problem with xmonad and not neovide itself. I have been thinking to switch to some other window manager for some time

**Comment by MultisampledNight** [comment]
Hm, I'm not sure, I'm using sway and i3 for that matter. Feel free to leave anything interesting you find here.

**Comment by Black-Sirius69** [comment]
I tried sway but it does not have window transparency. I have been meaning to switch to wayland for a while now

**Comment by MultisampledNight** [comment]
Uh, Sway does have window transparency:
![neovide with transparent background](https://user-images.githubusercontent.com/80128916/180015376-061debef-e471-47fc-9c4c-6172a9b5fabb.png)

**Comment by MultisampledNight** [comment]
But to get back to the actual issue, what does the log of Neovide (`neovide --log` and then see current directory) show when crashing?

**Comment by Black-Sirius69** [comment]
Oh about that I fixed the stylua problems by putting the paths into the `~/.bash_profile` file and now everything works. The problem with XMonad is smth different tho and I will bring it up with the xmonad community
