### ISSUE TITLE
Fonts without postscript names cause neovide to crash

### ISSUE THREAD

**Issue by TristanCrawford** [Kethku/neovide#145]
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/caching_shaper.rs:160:25

Backtrace: https://pastebin.com/NxqXKKhm

https://github.com/Kethku/neovide/blob/1f0d93ca3fce5b1fcafccc6bc81bbe0da206a6f2/src/renderer/caching_shaper.rs#L159-L160

Seems to be something to do with the font asset loading? I installed the following fonts system-wide and it spun up just fine.

https://github.com/Kethku/neovide/blob/1f0d93ca3fce5b1fcafccc6bc81bbe0da206a6f2/src/renderer/caching_shaper.rs#L12-L17

https://github.com/Kethku/neovide/blob/1f0d93ca3fce5b1fcafccc6bc81bbe0da206a6f2/src/renderer/caching_shaper.rs#L25-L26

**Comment by Kethku** [comment]
Thanks for the bug report. I will look into it.

**Comment by TristanCrawford** [comment]
Adding a quick debug statement:

```rust
println!("Failed at: {}", skribo_font.font.full_name());
let font_name = skribo_font.font.postscript_name().unwrap();
```

I get:
> Failed at: Tamzen
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/caching_shaper.rs:167:25

"Tamzen" is the font I'm using in my terminal, but more specifically "TamzenForPowerline". It's an OTB font for reference, but I'm not really sure why it's being passed in, I'll update if I find the solution.

**Comment by Kethku** [comment]
That font is taken from the vim init guifont. What do you set there?

**Comment by TristanCrawford** [comment]
Nothing as far as I'm aware, nothing in my init.vim and running `:set guifont` just yields
> guifont=

**Comment by Kethku** [comment]
ooh I see now. The font doesn't have a postscript name...

**Comment by Kethku** [comment]
I will look into this further later tonight

**Comment by TristanCrawford** [comment]
Schweet. Can confirm that setting `guifont` to a font with a postscript name at least allows neovide to launch.

**Comment by Kethku** [comment]
Glad you got it working. I think there is a fix to be done here though as the app shouldn't crash when there are fonts without postscript names.

**Comment by Kethku** [comment]
Frustratingly there doesn't appear to be a way to get a unique identifier for a given font :l

**Comment by TristanCrawford** [comment]
I replaced the offending line with:

```rust
let font_name = format!("{}:{}", skribo_font.font.full_name(), self.base_size);
```

Just to see what would happen, no more crash, but the font in question isn't getting built properly so the UI just goes blank. I know the font is compatible with Freetype so I'm not sure what's going on, I'll try to familiarize myself with the codebase and see if I can come up with something.

**Comment by Kethku** [comment]
Very interesting. As some background, no one font has all of the symbols which people want in a vim client. SO to get around this we load multiple fonts with a fallback ordering. This way if a given codepoint isn't found in the first font, it can fallback to ones further down.

Unfortunately if a font earlier in the system is messed up, especially the first one which is used for grid size estimation, it can really bork the rendering.

You mentioned that the font was an "otb" font which I believe means it is a bitmap font. It is very possible that the font parsing just completely fails on such fonts. I haven't tested it locally...

**Comment by TristanCrawford** [comment]
Indeed, it's just a bitmap font in an OpenType wrapper, it appears a lot of the font loading is being delegated to `font-kit` correct? It seems they're relying on `libfreetype` for Linux, and FreeType handles the font just fine:

![image](https://user-images.githubusercontent.com/35229978/74983001-cd543a00-53fa-11ea-8478-47e25d3b0d0f.png)

I'm confused, perhaps something needs to be updated in `font-kit`?

**Comment by Kethku** [comment]
Neovide uses two font systems for its rendering: font-kit and skribo (which is a small wrapper around harfbuzz) to support a given font type, both need to have support for it. Skribo uses harfbuzz and font-kit, and honestly isn't that big, so really we just need support in font-kit and I should be able to recreate the skribo support myself.

**Comment by Kethku** [comment]
@TristanCrawford  can you point me to the font you are using? I'd like to be able to download it locally so I can test out better error messages

**Comment by TristanCrawford** [comment]
Sorry, just saw this.

The Font (BDF):
https://github.com/sunaku/tamzen-font

Which was converted to OTB using the script referenced here:
https://fedoraproject.org/wiki/BitmapFontConversion

**Comment by exoticus** [comment]
@TristanCrawford Can you verify if latest [changes](https://github.com/Kethku/neovide/commit/bea55d321f3b1d193dbf9a65280f9203c0f74233) fixed this for you?

**Comment by Kethku** [comment]
closing due to lack of response
