### ISSUE TITLE
Don't use font if it doesn't match configured name

### ISSUE THREAD

**Issue by vivlim** [Kethku/neovide#146]
Text is being rendered with strange spacing between words, and not lining up with the cursor. I think it might have something to do with a scaling setting on my machine, my machine has high dpi and the font is much bigger than I expected, so that might have something to do with it.

![image](https://user-images.githubusercontent.com/1565930/74901671-65e5ae00-5358-11ea-89b8-fc66444112f7.png)

I recorded a video of this, also.
https://www.youtube.com/watch?v=iI25kqMrEfs&feature=youtu.be

Built from master @ commit b337d835488e12a6366cb6b4df2321c5d6f767f3 on Ubuntu 19.04.
Let me know if there's any environment vars or other state you'd like me to collect.

**Comment by Kethku** [comment]
The font should absolutely not get rendered in the way you've shown and definitely represents at least one bug.

That said, the format for guifont is wrong I think. According to the guifont help page, the name should be without quotes, have escaped spaces `\ `, and specify attributes separated by colons and prefixed by a character indicating which option.

Neovide currently supports a single option: the font height option which is specified via an h prefix. As an example, this is my guifont setting in my init file:
```
set guifont=Delugia\ Nerd\ Font:h12
```

**Comment by Kethku** [comment]
I think probably what is going on is that the font selection system couldn't find a font in the way you wrote it, and so fell back to some random alternative which didn't have good monospace characteristics... maybe

**Comment by Kethku** [comment]
As for dpi issues, I think its unlikely. I use 3 monitors at home with different dpi settings on each and it transitions relatively smoothly between each. I've also had reports of the dpi settings working on other machines.

**Comment by vivlim** [comment]
ah, yep, my guifont was malformed.

**Comment by jonvaldes** [comment]
I have seen this when the font is not perfectly monospace. Harfbuzz seems to pack things tighter in some cases, and the text and the underlying grid the cursor runs on misalign.

@vivlim Which font were you using? Was it the default, or did you use something else?

**Comment by Kethku** [comment]
I chatted with @vivlim IRL and determined https://github.com/Kethku/neovide/issues/146#issuecomment-589236530 was correct. The font selection system does whatever it wants if it doesn't find something that matches.

**Comment by Kethku** [comment]
Which usually results in a non-monospace font

**Comment by exoticus** [comment]
Can you verify if latest [changes](https://github.com/Kethku/neovide/commit/bea55d321f3b1d193dbf9a65280f9203c0f74233) fixed this for you?

**Comment by Kethku** [comment]
I'm going to go ahead and close this. We chatted irl about it a while back
