### ISSUE TITLE
Crashes when Monitor Disconnects

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#147]

**Comment by Kethku** [comment]
Fixed

**Comment by Kethku** [comment]
No longer crashes, but freezes instead...

**Comment by Kethku** [comment]
This should probably wait until I can rebase on upstream skulpin instead of my hacky fork

**Comment by vivlim** [comment]
I'm hitting this very often when I do something that changes display geometry (i.e. reconnect to my RDP session after overnight) which results in the majority of my neovim sessions not closing cleanly, which results in my oldfiles not being updated :(

Is there anything I can do to help with this one?

**Comment by j4qfrost** [comment]
We could start implementing a feature for saving changes on crashes as a temporary measure, but I would imagine this would have a much broader use case. I know Sublime Text has this feature.

**Comment by Kethku** [comment]
This is most definitely a bug which should be raised upstream in sculpin. I will make an issue and start some debugging.

An auto saving feature seems interesting, but I'm nervous that for some users saving temporary files might not be desirable?

Further at the moment neovide doesn't even detect the crash which makes this harder...

**Comment by Kethku** [comment]
Also the upstream to skulpin is done now. So the above comment https://github.com/Kethku/neovide/issues/147#issuecomment-591702037 is no longer valid

**Comment by Kethku** [comment]
https://github.com/aclysma/skulpin/issues/47 Upstream issue is here

**Comment by vivlim** [comment]
Are there flags I can pass to neovide that will collect the relevant logs?

**Comment by j4qfrost** [comment]
--log

**Comment by vivlim** [comment]
Log attached, but there doesn't seem to be anything of note in here.
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4589557/neovide_rCURRENT.log)

I'm running the windows build produced by this action run: https://github.com/Kethku/neovide/actions/runs/95481207
Unfortunately, I can't get a stack trace from the dump because the action doesn't publish .pdbs. I'm setting up my environment to build neovide and I'll collect more information about where it's crashing.

**Comment by j4qfrost** [comment]
> Further at the moment neovide doesn't even detect the crash which makes this harder...

Forgot about that. Looks like this requires more print statements.

**Comment by vivlim** [comment]
Here's the stack trace I'm seeing. I was hoping I'd be able to get symbols for nvoglv64.dll from the [nvidia symbol server](https://developer.nvidia.com/nvidia-driver-symbol-server), but no luck.

![image](https://user-images.githubusercontent.com/1565930/81236128-5833e200-8fb1-11ea-8a56-c075ff2235ca.png)

If you have any logging changes you'd want me to apply and repro with, I can do that.

**Comment by Kethku** [comment]
@vivlim I just confirmed that the skulpin sdl2 example https://github.com/aclysma/skulpin/blob/master/examples/interactive_sdl2.rs exhibits the exact same issue (as far as I can tell).

**Comment by Kethku** [comment]
Discussion here: https://gitter.im/neovide/community seems to indicate that the problem is indeed upstream

**Comment by Kethku** [comment]
I believe this is fixed by https://github.com/aclysma/skulpin/pull/49 trying now

**Comment by Kethku** [comment]
Yup! On windows this no longer crashes! Once the pr merges we can update the version and close this bug. @vivlim after that happens could you try on other platforms?

**Comment by vivlim** [comment]
I changed the reference to neovide to point to aclysma/skulpin (https://github.com/vivlim/neovide/tree/point-skulpin-at-upstream) and found the following

* Windows: I was able to repro the issue, and it went away after taking the upstream change
* Linux (Ubuntu 19.10 / Intel): I wasn't able to repro the issue, no noticeable change either way.
* Mac (10.15.3): I wasn't able to repro the issue, but I wasn't able to run neovide after pointing to upstream skulpin. I tried to narrow it down with one of the skulpin examples and found https://github.com/aclysma/skulpin/issues/50

**Comment by vivlim** [comment]
Looks like the reason I wasn't able to run neovide on the Mac is because the vulkan debug layer was enabled and something's broken about my vulkan-sdk install. Disabling the debug layer allowed it to run, and everything seems fine.

**Comment by Kethku** [comment]
This is now fixed. Closing
