### ISSUE TITLE
Neovide fails to render classic unicode glyphs when using nerd font

### ISSUE THREAD

**Issue by SirJson** [Kethku/neovide#153]
I noticed that neovide seems to not render some characters correctly when I use the "[Meslo Nerd Font patched for Powerlevel10k](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k)". 

![image](https://user-images.githubusercontent.com/1042414/75340249-720ac780-5892-11ea-9ebd-da98ba271e8d.png)

Some glyphs seem to work as seen at bottom tux but the chars that I use for `listchars` are not.

When I set the same font in the "new Windows Terminal" everything renders just fine.

![image](https://user-images.githubusercontent.com/1042414/75341078-f6117f00-5893-11ea-900e-64e884c8a9d5.png)

My `listchars` variable is set to

```viml
set listchars=tab:➞\ ,space:⬝,trail:~,nbsp:+
```

I have also no idea where that "NORMAL" thing in the top right corner came from. I don't see this in other neovim clients.

I'm running Windows 10 (Build 1909) with NVIM v0.4.3 and the latest version of Neovide that I just pulled from Github and built.

EDIT: Could be related to HarfBuzz because fvim also can't render my listchars, but nvim-qt does fine.

**Comment by Kethku** [comment]
Interesting. I think its unlikely to be HarfBuzz and more likely to be the font fallback system. Qt has very comprehensive font fallback support which I approximate somewhat manually. In particular, I think its unlikely your Meslo font has that codepoint in it. Maybe I'm wrong? I'm not sure how one would check

**Comment by SirJson** [comment]
You are right!

![Screenshot from 2020-02-26 21-12-47](https://user-images.githubusercontent.com/1042414/75383700-22052280-58dd-11ea-9812-29f90e497ce4.png)

Just checked on my Linux system, the font is missing this glyph. It is the 'BLACK VERY SMALL SQUARE' (U+2B1D) from the Miscellaneous Symbols and Arrows Unicode Block.

And from the looks of it [there are very few fonts that actually include this Block](http://www.fileformat.info/info/unicode/block/miscellaneous_symbols_and_arrows/fontsupport.htm)

Since you already support font fallback I think there is no point in going full Qt here. You could include a free font as very last fallback if the char is not a emoji but a valid unicode point that people use for drawing stuff... or ignore it and tell people to go and just use simple dots :wink:

**Comment by Kethku** [comment]
Do you have a suggestion for a free font that includes the missing bits which I can embed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SirJson** [comment]
I would give [Quivira](http://www.quivira-font.com/) a try because it is public domain and still got some decent coverage for shapes and drawing characters.

I understand now why Qt's fallback system is so sophisticated... Font licensing sucks and finding the correct system integrated fallback font is often the better broad term solution.
