### ISSUE TITLE
Some keys are not working

### ISSUE THREAD

**Issue by raaffaaeell** [Kethku/neovide#154]
Hello there, first of all, great project, currently having to use a windows box, this client is the one that worked better out of the box, but I'm having trouble with some basic keys.

My keyboard layout is PTB2 (PT-BR) and when I try to use the keys "/ \ [ ] ´ ~ ^ ` ? | " nothing happens, what could be the issue ?

Without these keys I cant comment code or use the search. Some of my basic configs are

set path +=**
set wildmenu
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set relativenumber
set mouse=a
syntax on
filetype plugin indent on
set nocompatible
set ignorecase
set foldmethod=indent
set foldlevelstart=99

Outside of that just some mappings for the languageserver.

Cheers

**Comment by Delapouite** [comment]
Hi. See: https://github.com/Kethku/neovide/issues/151

**Comment by Kethku** [comment]
As mentioned, this is a repeat of #151. Closing to track there
