### ISSUE TITLE
macOS fails to render symbols

### ISSUE THREAD

**Issue by SirJson** [Kethku/neovide#157]
As mentioned in #155 symbol rendering is still not working on macOS even though the font providing the glyph is loading just fine.

<img width="1079" alt="Screenshot 2020-02-28 at 09 25 21" src="https://user-images.githubusercontent.com/1042414/75523503-75c25980-5a0c-11ea-8b7a-5b060f191bbb.png">

**Comment by Kethku** [comment]
This likely means that symbol font doesn't have the glyph maybe?

**Comment by SirJson** [comment]
The glyph should be included in STIXGeneral because that's what the Apple Text Editor switched to when I fed it the 'BLACK VERY SMALL SQUARE'. Unless of course Apple mapped that glyph to a similar looking glyph and made it look like it never happened. 

I see if I can extract both Fonts and dissect them myself to be 100% sure.

**Comment by SirJson** [comment]
Apple Symbol didn't include it, but STIXGeneral did

![image](https://user-images.githubusercontent.com/1042414/75600704-03f11b00-5ab3-11ea-98c6-e8803b63d43e.png)

Now the question is: Why doesn't macOS use that Font even though in my test build STIXGeneral is loaded.

**Comment by Kethku** [comment]
Given how niche this is. I may say that we won't fix it. Ideally we would depend on system font fallback libraries, but currently there isn't any good ones for rust. https://github.com/linebender/skribo promises to be one eventually but isn't there yet. More details here: https://raphlinus.github.io/rust/skribo/text/2019/04/04/font-fallback.html

So for now I think I'm going to close this and declare partial success. Thanks so much for the detailed investigations!

**Comment by SirJson** [comment]
Fair enough, my Mac is usually running headless tucked away so it wasn't really an issue for me. That blog post made me even more curious tho as to why it is not working on macOS right now. 

The problem is not that we can't find the system fonts it's more like what ever renders the glyphs fails at selecting the correct ones on that specific OS.

I'm 100% sure Neovide is doing the correct thing on Windows because `Segoe UI Symbols` _is_ the System Font for Symbols (thanks to the deprecation of Windows 7 earlier this year).

And on Linux you will never find the official symbol font I think. People can just install `Unifont`.

Maybe like a command line option for custom symbol fonts would be neat. But this will also not fix the macOS issue so I wouldn't stress this at the moment.
