### ISSUE TITLE
Installation on Mac OS fails due to libvulkan not being code signed

### ISSUE THREAD

**Issue by SirVer** [Kethku/neovide#167]
Following the installation instructions in the README, everything installs and builds correctly, but running the binary opens a warning window from Mac OS

![grafik](https://user-images.githubusercontent.com/140115/75651463-ccbc6e80-5c58-11ea-8078-a578d7ad27c5.png)

Canceling this opens three other windows for other Vulkan libraries. The program does not start.

Is that a known issue? I could not find an explanation on how to correctly install Vulkan on Mac with code signed binaries. 

Os: Mac OS Catalina 10.15.2

**Comment by Kethku** [comment]
The readme suggests `brew cask install apenngrace/vulkan/vulkan-sdk` but I don't have a mac so I'm not sure.

**Comment by SirVer** [comment]
Yes, that is what I did, but this led to the problems I described above. I hope somebody more Mac savvy will come by this issue and give some clue to what the solution might be.

**Comment by terhechte** [comment]
You can allow this in settings:

![Screenshot 2020-03-02 at 10 43 30](https://user-images.githubusercontent.com/132234/75664481-d3f07600-5c72-11ea-9106-a6a6bc01c131.png)

Basically:
- Try to run it
- Go to that settings screen
- Allow
- Try to run it again, a different library will pop up with an issue
- Allow again
- repeat
- You should also get dialogs with the "Open" option. Hit open in there.
- After like three runs it should run

**Comment by SirVer** [comment]
@terhechte Thanks, that did work. @Kethku, it is probably worthwhile to link this comment in the README for mac os x.

**Comment by camccar** [comment]
> You can allow this in settings:
> 
> ![Screenshot 2020-03-02 at 10 43 30](https://user-images.githubusercontent.com/132234/75664481-d3f07600-5c72-11ea-9106-a6a6bc01c131.png)
> 
> Basically:
> 
>     * Try to run it
> 
>     * Go to that settings screen
> 
>     * Allow
> 
>     * Try to run it again, a different library will pop up with an issue
> 
>     * Allow again
> 
>     * repeat
> 
>     * You should also get dialogs with the "Open" option. Hit open in there.
> 
>     * After like three runs it should run

I'm able to do this when running cargo run, but not when trying to click on the executable from a release build. That just crashes for me atm.

**Comment by baileyn** [comment]
It worked for me on Mac OS Mojave 10.14.6 using the vulkan sdk installer from [lunarg](https://vulkan.lunarg.com/sdk/home). I know it's not ideal, but it seems to work.

**Comment by terhechte** [comment]
> I'm able to do this when running cargo run, but not when trying to click on the executable from a release build. That just crashes for me atm.

I can't test this right now, but could you try right-clicking the executable and then saying "open"?

**Comment by camccar** [comment]
> > I'm able to do this when running cargo run, but not when trying to click on the executable from a release build. That just crashes for me atm.
> 
> I can't test this right now, but could you try right-clicking the executable and then saying "open"?

Yeah same thing. I installed the Vulkin sdk with `brew cask install apenngrace/vulkan/vulkan-sdk`

**Comment by Kethku** [comment]
@terhechte adding it to the readme. I will watch this issue for future developments. Thanks so much for the investigation!

**Comment by Kethku** [comment]
There is some talk about way we can switch to a library agnostic system which should remove the vulkan dependency for macos. May take a bit though

**Comment by SirJson** [comment]
That would be? OpenGL? That is even more broken on macOS from what I have heard, Apple wants to push the Metal API.

And OpenGL is hit and miss on Windows + very dependent on the driver that is running on that system. There is a reason why all major Browser Developer bundle ANGLE for WebGL Support on Windows.

**Comment by Kethku** [comment]
We're looking at wgpu

**Comment by Kethku** [comment]
Which has targets for directx, vulkan, and metal. Its still preliminary. Conversation is happening here: https://gitter.im/neovide/community

**Comment by tssm** [comment]
If you want to keep using Vulkan there's [MoltenVK](https://moltengl.com/moltenvk/) for macOS, which is an implementation of the Vulcan API on top of Metal

**Comment by Kethku** [comment]
Very interesting. Is it a drop in replacement? When installed does it run normally or do I have to add explicit support to my app somehow?

**Comment by Kethku** [comment]
Ah its a for pay product. That kinda disqualifies it

**Comment by tssm** [comment]
[It's license is Apache 2.0](https://github.com/KhronosGroup/MoltenVK#licensing). But [it is not a drop-in replacement though](https://github.com/KhronosGroup/MoltenVK#moltenvk-and-vulkan-compliance).

I'll try what @baileyn did on my machine. Maybe Neovide could be statically linked against Vulkan, at least for macOS.

**Comment by Kethku** [comment]
This is well outside my area of knowledge. If someone wanted to attempt something like that is greatly appreciate it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tssm** [comment]
I'm trying to do it, but I haven't been successful. @baileyn could you describe what you did, please? I would like to try that on my machine

**Comment by baileyn** [comment]
I'm sorry. All I did was download the latest SDK for Mac from [lunarg](https://vulkan.lunarg.com/sdk/home). After that, I just compiled again with `cargo build --release`.

It's possible our issues were slightly different?

**Comment by Kethku** [comment]
I just pushed an opengl backend to the main branch. Would folks struggling with this issue be willing to try it?

**Comment by tssm** [comment]
Does anyone have an idea of why I may be getting this error?
```
note: Undefined symbols for architecture x86_64:
        "____chkstk_darwin", referenced from:
            SkBlurMaskFilterImpl::filterRRectToNine(SkRRect const&, SkMatrix const&, SkIRect const&, SkMaskFilterBase::NinePatch*) const in libskia_bindings-f53e790636e34b91.rlib(libskia.SkBlurMF.o)
            SkBlurMaskFilterImpl::filterRectsToNine(SkRect const*, int, SkMatrix const&, SkIRect const&, SkMaskFilterBase::NinePatch*) const in libskia_bindings-f53e790636e34b91.rlib(libskia.SkBlurMF.o)
            SkCopyStreamToData(SkStream*) in libskia_bindings-f53e790636e34b91.rlib(libskia.SkStream.o)
            SkShaderMF::filterMask(SkMask*, SkMask const&, SkMatrix const&, SkIPoint*) const in libskia_bindings-f53e790636e34b91.rlib(libskia.SkShaderMaskFilter.o)
            SkPerlinNoiseShaderImpl::PaintingData::init(float) in libskia_bindings-f53e790636e34b91.rlib(libskia.SkPerlinNoiseShader.o)
            SkPicture::backport() const in libskia_bindings-f53e790636e34b91.rlib(libskia.SkPicture.o)
            OpDebug(SkPath const&, SkPath const&, SkPathOp, SkPath*) in libskia_bindings-f53e790636e34b91.rlib(libskia.SkPathOpsOp.o)
            ...
      ld: symbol(s) not found for architecture x86_64
      clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Kethku** [comment]
That is a very strange error. Is it possible a debugger is trying to attach? I'm guessing thats hiding the actual error...

**Comment by reportaman** [comment]
@Kethku "I just pushed an opengl backend to the main branch. Would folks struggling with this issue be willing to try it?" Does that mean we don't need Vulkan anymore? (I have had issues installing it on my system)

**Comment by Kethku** [comment]
@reportaman yes. Unfortunately there were some issues. This code is now held in the opengl branch.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
