### ISSUE TITLE
Can't type a / on a Norwegian keyboard layout

### ISSUE THREAD

**Issue by xyproto** [Kethku/neovide#169]
When launching `neovide`, I press `/` on my keyboard (shift-7), but no `/` appears. Same goes for pressing the key next to lower right shift (assuming it was an English layout instead), no `/` appears.

This is using Neovide 0.4.0 on 64-bit Arch Linux, using Sway and Wayland.

**Comment by Kethku** [comment]
This is probably related to https://github.com/Kethku/neovide/issues/151, but also possibly due to our sdl text handling. Can you look at that issue and give me your opinion of whether it is related?

**Comment by xyproto** [comment]
The issues seems to be related, but there's no `AltGr` involved here.

**Comment by Kethku** [comment]
Did you build from got?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xyproto** [comment]
No. I think I used the [`neovide` package](https://aur.archlinux.org/packages/neovide/) from AUR.

**Comment by Kethku** [comment]
That package is old. Please build from git

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Is your problem fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
