### ISSUE TITLE
Support GPU render

### ISSUE THREAD

**Issue by NEX-S** [Kethku/neovide#1693]
will neovide support GPU rendering? if we use `--novsync` and set the refresh_rate to `1000` to get minimal input delay, the CPU usage is very high eg. `i9-9900k : > 85%`, and in linux the GPU has a lot of free performance to use :D

**Comment by MultisampledNight** [comment]
Thanks for the suggestion!

Neovide is already using skia on OpenGL for rendering:

https://github.com/neovide/neovide/blob/37f78331232197d6d924f6943d6a4114206264be/Cargo.toml#L66-L67

So I guess your request is aimed at using GPU-driven rendering, which would likely require a full rewrite of all rendering mechanisms on top of an API like Vulkan, OpenGL or wgpu. This could be an interesting challenge though, probably having #1478 before doing so would be beneficial.
