### ISSUE TITLE
neovide will transparent `guibg="#000000"` instead `guibg="NONE"` in linux

### ISSUE THREAD

**Issue by NEX-S** [Kethku/neovide#1694]
Is it possible to set some HL's background to `none` to get transparent separately in neovide?

> for example, in kitty, we can set tabline bg the same as kitty's bg to get transparent, which is very cool when implementing it on tabline
![image](https://user-images.githubusercontent.com/97107165/209343982-673b6462-a9e1-4c5e-a957-987609061ca5.png)

**Comment by A-Lamia** [comment]
Neovide will make any HL group that is set to none transparent if the transparency setting is being used.

Example 
`let g:neovide_transparency = 0.8`

**Comment by A-Lamia** [comment]
I mean it should be 
![image](https://user-images.githubusercontent.com/6450181/209419798-b249cea4-b0f8-43a6-bef4-28eae19861c0.png)

**Comment by A-Lamia** [comment]
yeah you just have to mess around with neovim how background / forground works gets a little insane but neovide it self is doing what all the other terminals do as well so there is nothing wrong with neovide.

**Comment by A-Lamia** [comment]
I'm on windows, and all im doing is changing the HL group of active vs not active buffers.
