### ISSUE TITLE
[ BUG ] need to click neovide's window to get all key works in gnome

### ISSUE THREAD

**Issue by NEX-S** [Kethku/neovide#1709]
**Describe the bug**
need to click neovide's window to get all key works in gnome 43 ( or move the cursor on neovide)

**To Reproduce**
1. goto gnome settings ->  keyboard -> customize shortcuts
![image](https://user-images.githubusercontent.com/97107165/210107900-8f77a2a8-87fc-43a2-9117-2a45829e1935.png)

3. bind `Alt+Enter` open the neovide
4. trigger the `Alt+Enter` to open the neovide
5. some key-bindings don't work until we manually click the neovide's window

**Expected behavior**
all keybindings work without clicking neovide's window

OS: Linux UNEXPECTED 6.1.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:59 +0000 x86_64 GNU/Linux

**Comment by itaranto** [comment]
Maybe this is related to https://github.com/neovide/neovide/issues/1488
