### ISSUE TITLE
Unable to type special characters like !@#$

### ISSUE THREAD

**Issue by riginding** [Kethku/neovide#172]
I noticed that I can't use my shift key at all. For some keys using shift produces no output at all, other times it misbehaves: eg: `shift + o` behaves like `ctrl + o`

**Comment by baileyn** [comment]
What operating system are you using? I'm unable to reproduce this on Windows.

**Comment by riginding** [comment]
I'm running Manjaro Linux.

**Comment by riginding** [comment]
Other people seem to have the same problem: https://www.reddit.com/r/rust/comments/fc1l3y/no_nonsense_neovim_client_in_rust/fj9fqfp?utm_source=share&utm_medium=web2x

**Comment by baileyn** [comment]
Seems to also work fine on Mac OS as well. 

I have Manjaro, but I'm having trouble getting it to run because of some fontkit issue. I'll follow up whenever I get it running.

**Comment by Kethku** [comment]
Are you using the release build? It's old and needs updated

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
@riginding the bug you linked I believe was fixed by the switch to sdl2.

**Comment by baileyn** [comment]
I'm unable to reproduce this in Manjaro building from Git.

**Comment by riginding** [comment]
Works with the build from Git. I'm able to use shift :fireworks: 

I installed using the arch instructions in the readme, it seems to install an old version.
