### ISSUE TITLE
Neovide fails to start on Ubuntu 19.10

### ISSUE THREAD

**Issue by ABitMoreDepth** [Kethku/neovide#175]
Hi folks,

Thought i would give this project a try, I've installed the build dependencies per your instructions and compiled the application from source.  Upon running, neovide seems to error out with the following error message:
```
 RUST_BACKTRACE=full neovide
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x1c0000c
  Serial number of failed request:  239
  Current serial number in output stream:  247
```

I'm running Ubuntu 19.10, with i3 as a window manager, against the AppImage version of neovim, which is currently at version 0.4.3.

Please let me know what additional information I can provide to help diagnose!

**Comment by Kethku** [comment]
Do you have confirmation that vulkan works on your machine in other applications?

**Comment by Kethku** [comment]
A similar issue here: https://github.com/rust-windowing/winit/issues/748 appears to indicate that its a system wide vulkan issue

**Comment by SirJson** [comment]
What kind of GPU do you have? Did you install the correct drivers? I have also heard that AppImages are bad business and cause all kinds of issues. Maybe building Neovim from source can help.

**Comment by ABitMoreDepth** [comment]
I can run neovim and neovim-gtk just fine, so I believe that the neovim part of this may not be the issue, but I can try compiling neovim from source.  I'll look into the vulcan stuff as well.

The machine I am using is a Dell XPS with a discrete nvidia gpu, which to my knowledge is running appropriate drivers (not nouveau).

Thanks for the pointers, I'll do some digging. :)

**Comment by SirJson** [comment]
I'm running i3 with an Nvidia GPU and Ubuntu 19.10 so that shouldn't be the problem. Are you using plain i3 or i3 + compositor?

**Comment by ABitMoreDepth** [comment]
That's an interesting point, I am running Compton as well,

**Comment by PillTime** [comment]
I'm using KDE on Arch, same problem. Installed Neovide from the AUR.

**Comment by ABitMoreDepth** [comment]
I checked with compton disabled and the same error persists.

**Comment by Kethku** [comment]
Can you try running a debug build?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
So try building from source, or running from the build assets shown in one of the successful builds here: https://github.com/Kethku/neovide/actions

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ABitMoreDepth** [comment]
It looks like a `cargo clean && cargo build` has made no difference unfortunately. I'll try and pull the neovim source, but that from scratch and run against that, see if that somehow makes a difference after work this evening.

(But neovim-gtk runs against the appimage neovim client without issue).

**Comment by Kethku** [comment]
I meant building neovide from source just to be clear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PillTime** [comment]
Building from source still doesn't work.
```
 ~/Dow/neovide > cargo run --release    
    Finished release [optimized + debuginfo] target(s) in 1.18s
     Running `target/release/neovide`
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x580000c
  Serial number of failed request:  227
  Current serial number in output stream:  235
```

**Comment by peeweep** [comment]
@Kethku  Just mention, the AUR package is not out of date, please check [the comment](https://github.com/Kethku/neovide/commit/45ce6d932aee8c8113e20574fb8ea3878bf69316#commitcomment-37623755).

**Comment by Kethku** [comment]
Added it back but swapped to the git one so that we run into this less

**Comment by ABitMoreDepth** [comment]
kethku is there any additional diagnostics I can provide to help you find the issue?

**Comment by Kethku** [comment]
I'm not sure... Something about your graphics setup causes the renderer to not be able to create a surface I think. Running debug and getting me a stacktrace might help but I don't know...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PillTime** [comment]
My laptop has both Nvidia and Intel graphics, and I'm using [optimus-manager](https://github.com/Askannz/optimus-manager) to switch between them.
Nvidia graphics (what I was using before) doesn't work.
Intel graphics works!
I'm using the proprietary Nvidia drivers.

**Comment by Kethku** [comment]
Are the nvidia drivers up to date? I ran into this with a work machine on windows and had to update my drivers

**Comment by PillTime** [comment]
Yeah, they are.

**Comment by Kethku** [comment]
I've got nothing for you unfortunately. If intel graphics works, then youre probably good

**Comment by ABitMoreDepth** [comment]
I spent some time with the debugger this morning, I appear to get here:
![image](https://user-images.githubusercontent.com/3308997/76142711-067de280-6068-11ea-8562-7784666b3a96.png)

For some reason, the SDLPoll_Event call is what triggers the error.  I don't seem to be able to step into that call, it just bails I'm afraid.

Does that yield any useful information?

**Comment by ABitMoreDepth** [comment]
Interesting, I got neovide running by adjusting some nvidia settings, so I'm guessing something about the dual GPU laptops + vulkan isn't quite playing ball.

For anyone else who gets here, the following settings in nvidia-settings work for me:
![image](https://user-images.githubusercontent.com/3308997/76143232-7773c900-606d-11ea-9179-33ea57673310.png)


Thanks @Kethku for your help in trying to get things to behave, I don't think this is an issue specific to neovide. :)
