### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by halvnykterist** [Kethku/neovide#176]
Is fullscreen support something that exists/is planned? In nvim-qt you can launch using the --fullscreen flag, although something more ergonomic might be nicer.

**Comment by Kethku** [comment]
Hmmm. Sdl definitely has support. But we would likely want a fullscreen windowed mode instead of full take over the display.

**Comment by Kethku** [comment]
Probably I would add a toggle command as well as a command line arg

**Comment by Kethku** [comment]
Done. If you set the variable g:neovide_fullscreen to v:true it will change to fullscreen mode.
