### ISSUE TITLE
translucent background

### ISSUE THREAD

**Issue by iwikal** [Kethku/neovide#178]
I have set guibg to none, and I just get solid black instead of translucent like in my terminal. I'd like to be able to configure a translucent background colour for the window somehow. It seems like there's an SDL draft with partial support that adds a function to set window opacity, but I'm not sure that's what we want or if it works.

**Comment by Kethku** [comment]
My gut is that this will be difficult to support without proper sdl2 support

**Comment by Kethku** [comment]
Best I've got until sdl2 adds better support is setting the window opacity. This can now be set by setting the global variable g:neovide_transparency to a float between 0.0 and 1.0. I'm closing for now as anything more than that is unlikely to happen any time soon.

**Comment by axeldetlofsson** [comment]
@Kethku 
I bet you explored all ways of doing this, but came across this in a personal proj, you think this would be possible for neovide:
https://stackoverflow.com/questions/23048993/sdl-fullscreen-translucent-background

**Comment by j4qfrost** [comment]
@axeldetlofsson the future of neovide is in opengl. This issue is blocked until the opengl branch is merged into main.

**Comment by Kethku** [comment]
It's specifically complicated by the fact that we are moving back to winit which is our best hope for better keyboard handling. So upstream support would have to come from there.

The good news is that they tend to move faster than sdl on stuff like this :)

**Comment by axeldetlofsson** [comment]
Allright, thanks for the fast response guys!
