### ISSUE TITLE
Optionally Bundle Fonts

### ISSUE THREAD

**Issue by TristanCrawford** [Kethku/neovide#179]
This isn't a pressing issue, but I decided to do a little experiment today in regards to the executable size of Neovide.

These were created with `cargo build --release`

![image](https://user-images.githubusercontent.com/35229978/75865370-1330db00-5dc9-11ea-9525-21aae9629e53.png)

While the fallback fonts are nice to have, it does make the resulting executable rather large. It might be worth making a way to opt out of font bundling.

**Comment by Kethku** [comment]
I added an embed-fonts feature which triggers the font embedding.

The default features are now sdl2-static-link and embed-fonts. So doing a build without embedded fonts but normal everything else would look like this: `cargo build --release --no-default-features --features sdl2-static-link`.

Let me know if that works for you. I'm closing for now. Please reopen if you have further troubles with this feature.
