### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by mrinterweb** [Kethku/neovide#185]
I was just curious how neovide's RAM use compares to other editors. I was in shock when I realized it was at 6.4GB after only opening a few files. When I looked at how much RAM is used on just opening neovide, the initial footprint is 3.3GB, and it goes up quickly. I haven't used neovide for extended use, but I have a feeling I haven't seen it cap out. One thing that makes the memory jump dramatically is to change `guifont`. Every time I called `:set guifont=<font-name>:h<pixels>`, I saw a couple gigabyte RAM use jump.

**Comment by Kethku** [comment]
Believe it or not, this is a platform discrepancy. On windows the memory usage sticks around 200-300 MB and a chunk of that goes to nvim itself and plugins on my box.

I've seen reports though that on some linux boxes, the fonts take up a surprisingly large amount of space.

What platform are you running on?

**Comment by Kethku** [comment]
This is likely to improve a ton with the potential rewrite I'm working on.

**Comment by noamcore** [comment]
Here is random haha

The problem seems to be on startup because sometimes it consumes 200-300MB, sometimes 2GB...  and then decreases with time.

**Comment by Kethku** [comment]
What i've seen on my side is that the process itself takes around 200-300 (which is still more than I'd like, but manageable) but the child processes take up a bunch as well. In particular the tab9 plugin often takes multiple gigs. I need to know platform to see if there is a correlation though

**Comment by mrinterweb** [comment]
I should have mentioned, I'm on MacOS using the latest from master (march 7th 515535cf32c99b1e39176dee91dda8cb5265908c). For me, not even opening a file, but just adjusting font a few times, and RAM use can grow over 10GB in less than a minute. I haven't seen RAM use decrease. From what I can tell, it only grows.

**Comment by Kethku** [comment]
If you don't adjust the font at all, does it continue to grow?

**Comment by Kethku** [comment]
The numbers you are describing are very high. Any chance you could do some memory profiling to see what is taking all the space? I can't reproduce this on my windows boxes

**Comment by ericonr** [comment]
On my Manjaro machine, if the font name was configured wrong, it actually loads the Noto and Monospace in their place. And if I try to change the font to another one with the wrong name, it increases the memory consumption, by loading the default fonts once again.

**Comment by Kethku** [comment]
Interesting so the fonts don't reuse the collection. Somehow we keep a reference to the loaded fonts...

**Comment by Kethku** [comment]
I believe this was fixed by @exoticus @mrinterweb can you check and see if it is in reasonable ranges on mac now?

**Comment by noamcore** [comment]
Here seems ok now

**Comment by mrinterweb** [comment]
@Kethku sorry for the delayed response. I just built the latest, and I can no longer reproduce the issue. I'm going to close this issue. Thank you for addressing this.
