### ISSUE TITLE
Make neovide embeddable

### ISSUE THREAD

**Issue by j4qfrost** [Kethku/neovide#187]
I made some changes to the window and bridge modules that make it a bit easier to embed into a separate SDL program on my fork https://github.com/j4qfrost/neovide?organization=j4qfrost&organization=j4qfrost

I'm not sure if there would be interest in continuing this, and I am a noob with Rust, so some criticism would be welcome.

**Comment by Kethku** [comment]
I'd be interested in hearing your end goal for this. Is it to add vim support to an existing app?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j4qfrost** [comment]
Yeah, my intention is to embed this into a separate SDL game where you can program objects. I made my own text editor years back, but that was crappy and I would've had to maintain it, so I figured I would borrow yours, which looks super nice and plugs in smoothly with some tweaks. I'm using here https://github.com/j4qfrost/hello-rox. It repo won't work right now since I'm adding things midflight and haven't pushed my patches up to github yet.

**Comment by Kethku** [comment]
Could you make a PR with the changes so we can have further discussion there?

**Comment by j4qfrost** [comment]
PR: https://github.com/Kethku/neovide/pull/192

I'm currently trying to resolve an issue with dependencies. I was able to plug this in by patching the SDL library, but now that I'm adding the image feature, symbols aren't being loaded properly for SDL2_image.

**Comment by Kethku** [comment]
Thats pretty weird. We use the embedded feature flag in sdl2... Maybe that causes problems?

**Comment by j4qfrost** [comment]
That might be the cause. So what happens is when I add sdl to my Cargo.toml file I get a build error saying that there are two conflicting version of sdl. I can fix this with a patch that overrides both imports with a single sdl version. Then when I add image to the patch, it says that the symbols for all the sdl image functions aren't loaded. I can build successfully by dynamically loading the libraries, but then I run into the same issue with there being two sdl libraries again.

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/blob/master/Cargo.toml#L11 here you can see the embedded sdl2 feature flag. If you disable default features for neovide as a library, and then optionally add back the embedded fonts you should be able to only dynamically load the library.

**Comment by j4qfrost** [comment]
I think I need to go down to skulpin and reexport SDL from there. Your suggestion kind of helped, but now I'm stuck at vulkan not loading an image correctly. I think a lot of my headaches might be from developing on Mac.

These are some benign linking messages.
```
objc[69737]: Class SDLApplication is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69edc8) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fc98). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLAppDelegate is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69ee18) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fce8). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLTranslatorResponder is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69ee90) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fd60). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLMessageBoxPresenter is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69eeb8) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fd88). One of the two will be used. Which one is undefined.
objc[69737]: Class SDL_cocoametalview is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69ef08) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fdd8). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLOpenGLContext is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69ef58) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fe28). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLWindow is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69efa8) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fe78). One of the two will be used. Which one is undefined.
objc[69737]: Class Cocoa_WindowListener is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69efd0) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16fea0). One of the two will be used. Which one is undefined.
objc[69737]: Class SDLView is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10a69f048) and /Users/blah/Projects/alloy/target/debug/build/sdl2-sys-8d3ea5f38ba24bf0/out/lib/libSDL2-2.0.dylib (0x10a16ff18). One of the two will be used. Which one is undefined.
```

This seems to be indicating that vulkan isn't loading correctly.
```
The current directory is /Users/blah/Projects/alloy
"/Users/blah/Projects/alloy/assets/rust.png"
thread 'main' panicked at '"Failed loading vulkan.framework/vulkan: dlopen(vulkan.framework/vulkan, 6): image not found"', src/main.rs:59:19
stack backtrace:
   0:        0x105cfc38f - std::sys_common::at_exit_imp::push::h3f78ebb1f2499527
   1:        0x105d1fdbe - <&mut W as core::fmt::Write>::write_fmt::h967c8a6bd8f0cdf2
   2:        0x105cf9037 - std::io::Write::write_fmt::h53e556e0ac52f288
   3:        0x105cfe40a - std::panicking::default_hook::{{closure}}::h800899ae231e99aa
   4:        0x105cfe14c - std::panicking::default_hook::hfbf7f5180f0e17a6
   5:        0x105cfea78 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h6a47c2887dc44353
   6:        0x105cfe642 - std::panicking::try::do_call::h8cbc1f02caadb18b
   7:        0x105d322eb - std::panicking::begin_panic_fmt::hfd89407b41840d90
                               at src/libstd/panicking.rs:332
   8:        0x1053712c1 - alloy_v2::main::h6cd6b30ffc87852c
                               at src/main.rs:59
   9:        0x10536fc4e - std::rt::lang_start::{{closure}}::h20c54f1d8ded5369
                               at /rustc/1572c433eed495d0ade41511ae106b180e02851d/src/libstd/rt.rs:67
  10:        0x105cfe548 - std::panicking::try::do_call::h8cbc1f02caadb18b
  11:        0x105d0594b - panic_unwind::dwarf::eh::read_encoded_pointer::hdc36d99156f3793e
  12:        0x105cfee7a - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h6a47c2887dc44353
  13:        0x10536fc31 - std::rt::lang_start::he5045952f1ad3d0a
                               at /rustc/1572c433eed495d0ade41511ae106b180e02851d/src/libstd/rt.rs:67
  14:        0x105371f42 - alloy_v2::main::h6cd6b30ffc87852c
```

I have a couple ideas I want to try, but it's way past my bedtime lol. I'll try them during daylight.

**Comment by j4qfrost** [comment]
I wanted to write this before I forget. I was completely misinterpreting what all these errors meant. It was actually just me being dumb and not realizing that the problem was a linker issue. Not quite sure on the internals about how it works, but it seems like using the "use_mac_framework" feature for SDL fixes the issue with my project using two versions of SDL and vulkan not being linked properly.

**Comment by j4qfrost** [comment]
After working with neovide a bit more, I realize it's already pretty embeddable. It just requires more management on my end. I'll reframe this problem into "what do I need to expose" rather than "what do I need to change in window.rs". It turns out that I actually didn't need to make window for WindowWrapper an Option. The issues I was running into were related to how MoltenVK operated with skulpin. The dropping logic with SDL was fine.

**Comment by j4qfrost** [comment]
My approach has changed and the issue is either out of scope or is already addressed in a refactoring issue.
