### ISSUE TITLE
Update font-kit dependency to git version. 

### ISSUE THREAD

**Issue by ericonr** [Kethku/neovide#189]
Hey there! I really like this project!

I spent quite some time figuring out why I was getting strange behavior from several things. One of them was that the weight of the font was heavier on neovide than on Alacritty, despite both supposedly using the Regular fonts. A bit of investigation led me to an issue in font-kit: https://github.com/servo/font-kit/issues/118. It has been fixed already, but as there hasn't been a release since, I had to fix it locally. I realized the issue was with font-kit because alacritty uses the same backend as font-kit, but it didn't present the same issue.

I will try to change it to build from git and see if there are any regressions. If there aren't, I will make a PR for it (up to you if adding it is worth it).

That said, do you think being able to configure what the standard and bold font weights will mean when importing the fonts would be a valid feature?

And I only found out about this issue because I added some print statements to some of the renderer functions. I feel like adding some option for logging what happens to the program can really help both users and developers.

EDIT: in the matter of font configuration, it would be great if you included a simple example in the Wiki. Having to crawl through issues to find out how to properly configure fonts is a royal pain.

**Comment by ericonr** [comment]
I think one of your dependencies also uses font-kit, so we'd have to change their Cargo.toml as well. Damn.

**Comment by Kethku** [comment]
The dependencies I use that use font-kit I believe is just skribo, and we're already using my fork, so that shouldn't be a huge issue

**Comment by Kethku** [comment]
As for logging, this is already supported to some extent via the --log command argument and !debug, !warn, !trace, and !error macros

**Comment by ericonr** [comment]
I see! I believe it would be nice to add command line documentation, because currently neovide doesn't even have a help text (running it with `-h` or `--help` actually generates an error).

Would you be open to a PR adding more warning stuff? I think the fonts part could probably use some better runtime debuggability. Woulda a PR for the command line arguments stuff also interest you? I've used [clap](https://github.com/clap-rs/clap) before, but if you want to avoid other dependencies it's still possible to implement a more friendly interface.

**Comment by j4qfrost** [comment]
This issue has gone stale. @ericonr if you're still open to it, the clap stuff seems like a good idea, but it probably needs a separate issue.

**Comment by ericonr** [comment]
Sorry, I haven't used neovide in a long while. Probably won't be able to help here.
