### ISSUE TITLE
Why does the program default to Normal style fonts when using BOLD weight?

### ISSUE THREAD

**Issue by ericonr** [Kethku/neovide#190]
Me again!

The conditional block here https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L76

```rust
        let style = if !italic || bold {
            Style::Normal
        } else {
            Style::Italic
        };
```

means that the program won't search for a bold *and* italic font, instead preferring a regular italic font. Wouldn't it be better to ask for the BoldItalic variant of the font (lots of fonts have them) and instead expect that the `source.select_best_match` function will find the best compromise (probably an Italic font) if the BoldItalic variant happens to not exist? Or were there more aesthetic reasons?

**Comment by Kethku** [comment]
This was a memory saving technique. I figured bold italic weren't used frequently. Did you run into this when you expected bold italic to work?

**Comment by ericonr** [comment]
As a matter of fact, no. It was more a doubt I had while looking at the area around this code. Perhaps include a comment about it? It's not a choice I have any issues with, but it might be interesting to document the reason for your choice in the code itself.

**Comment by Kethku** [comment]
Will do!

**Comment by Kethku** [comment]
I just removed the change because I don't have actual evidence it helped anything.
