### ISSUE TITLE
Some <M- · > bindings broken after key handling change

### ISSUE THREAD

**Issue by aelkazdadi** [Kethku/neovide#191]
After commit 31f9211b687c6f49448e28e1d1bb0e6d36f483c8 , most `<M->` keybindings no longer work. (tested on Ubuntu 19.10)
Though some still do, such as `<M-CR>`, `<M-BS>` or `<M-Space>`.

`<M-C->` bindings seem to be working fine, however.

**Comment by Kethku** [comment]
This was my bad. I believe its fixed now.
