### ISSUE TITLE
Extra tab is inserted after alt-tabbing into neovide window

### ISSUE THREAD

**Issue by aelkazdadi** [Kethku/neovide#193]
OS: Ubuntu 19.10

If the window is out of focus and I alt tab to bring it into focus back again, a <tab> is received as an input in vim. It's a bit troublesome when switching to and from a browser window multiple times.

(This doesn't happen with other desktop applications or nvim-qt.)

**Comment by Kethku** [comment]
I pushed a change which might fix this. I can't repro it on my windows box though.

**Comment by aelkazdadi** [comment]
It seems to be fixed. Thanks for the hard work!
