### ISSUE TITLE
Cursor often renders incorrectly

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#194]
This is using neovim v0.4.3 and the current HEAD of neovide.   This is also running with zero configuration.

Often the cursor will become invisible or render incorrectly.  For example:

When on the 'o' character it appears:

![image](https://user-images.githubusercontent.com/810762/76707615-ebd1ec00-66ad-11ea-8feb-a2df6ef29fe5.png)

But when moved to m character it goes black:

![image](https://user-images.githubusercontent.com/810762/76707609-e1175700-66ad-11ea-9ea1-f8e89dab14cd.png)

This effect where part of the cursor appears black often occurs when moving around as well

**Comment by svermeulen** [comment]
Another example of it being half-visible:

![image](https://user-images.githubusercontent.com/810762/76707651-43705780-66ae-11ea-9f9b-3d117d210857.png)

**Comment by svermeulen** [comment]
It also inexplicably changes color sometimes:

![image](https://user-images.githubusercontent.com/810762/76707665-597e1800-66ae-11ea-9438-d6e75e696be4.png)

**Comment by Kethku** [comment]
What platform? This looks like a skia bug in vulkan

**Comment by svermeulen** [comment]
This is on macOs Catalina 10.15.3

**Comment by Kethku** [comment]
How did you install the vulkan drivers?

**Comment by svermeulen** [comment]
I followed the instructions in the readme and executed `brew cask install apenngrace/vulkan/vulkan-sdk`

**Comment by Kethku** [comment]
Hrmm. Then I'm not sure I have anything for you. This is an upstream issue with skia that has something to do with your platform. I am slowly working on an in house renderer so that we can get rid of the skia dependency but thats not going to happen for a while.

**Comment by svermeulen** [comment]
Ok no problem.  Was there a recent skia upgraded that might have caused this?  This was rendering perfectly fine fairly recently.

**Comment by Kethku** [comment]
ok interesting. Maybe it was the anti aliasing change? Gimme a bit and I'll toggle it off

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
I added a setting `g:neovide_cursor_antialiasing` which controls the antialiasing features of the cursor. Can you try setting that variable to `v:false` and see if that effects the issue?

**Comment by svermeulen** [comment]
Ok so yeah this completely fixes this issue 👍
Thanks

**Comment by Kethku** [comment]
Awesome
