### ISSUE TITLE
Start speed in macos is slow

### ISSUE THREAD

**Issue by JunfengJia** [Kethku/neovide#200]
It takes 3 seconds until ready to use.  

Anyway, the whole user experience is very good, except this lag.

**Comment by Kethku** [comment]
platform pls

**Comment by JunfengJia** [comment]
macos catalina 10.15.3, i7.

**Comment by Kethku** [comment]
this is due to font loading. Can you try building without the embedded fonts feature and see if that helps? Font fallback will be worse but we are working on addressing that. Also you'll need a guifont configured in your configs

**Comment by JunfengJia** [comment]
Compile without embedded fonts, speed don't change. I use the Fira Code font.

**Comment by svermeulen** [comment]
This is probably my only criticism of this GUI as well.  I sometimes change back to nvim-qt because of the startup lag.  Otherwise it's brilliant.

I'm on the exact same OS (macOS catalina 10.15.3)

**Comment by svermeulen** [comment]
Oh I should mention also that it takes around 3 seconds for me as well

**Comment by Kethku** [comment]
I don't have a mac. Any chance I could convince one of you folks to do a little profiling to see what is taking all the time? I believe it has to do with font loading on Mac because neovide starts up nearly instantly on Windows, but I can't be sure. I don't have a Mac to test it myself.

**Comment by JunfengJia** [comment]
https://github.com/geerlingguy/macos-virtualbox-vm, can also help you to keep running unittest.

**Comment by exoticus** [comment]
@Kethku which profiling to run, i am running Macos Mojave and having same issue, 3~4 sec startup time

**Comment by Kethku** [comment]
Awesome investigation. This gives me a lever to push. I'll fiddle with it and report back

**Comment by exoticus** [comment]
with the new optimizations Neovide startup time on MacOS is down from 2.8~3s to 750~900ms with emojis, It isn't optimal yet but a significant improve nonetheless. I suggest not closing this yet as i have some more optimizations in mind that may bring this number to ~200-300ms which would be instant, and comparable to windows/linux

**Comment by Kethku** [comment]
I'm going to close this for now as it is back in reasonable ranges.
