### ISSUE TITLE
Neovide.app silently crashes [OSX]

### ISSUE THREAD

**Issue by j4qfrost** [Kethku/neovide#202]
After bundling a .app for neovide and attempting to run the program, the app silently crashes. At first glance the problem appeared to be an error in bundling. After exploring other bundling methods, I found thread where someone had looked for crash reports via Console.app. It looks like the app is definitely crashing with 

```com.apple.xpc.launchd[1] (com.kethku.neovide.4948[59211]): Service exited with abnormal code: 101```

According to [this](http://www.cs.cmu.edu/afs/cs/user/lenzo/html/mac_errors.html) there appears to be a memory issue:
dsParityErr: memory parity error

Running the .app with ```open -a Neovide.app``` from the bundle directory or using the absolute path works through the terminal, so the program may be stable as a subprocess. Probably good to call in a Mac developer for help.

Some possible leads:
* neovim can't be called through .app as a separate process?
* some memory errors with loading SDL frameworks?
* I've already checked permissions, but this could still be an issue
* I have checked compiling SDL with use_mac_framework

**Comment by Kethku** [comment]
Given that I don't have a mac machine personally, I will need help investigating this.

**Comment by DemonCloud** [comment]
Same Here


<img width="1112" alt="Screen Shot 2020-03-23 at 4 26 06 AM" src="https://user-images.githubusercontent.com/7436361/77260046-78893500-6cc0-11ea-928f-c29d47069f35.png">

**Comment by j4qfrost** [comment]
@DemonCloud I'll make some time tomorrow to look at it. I had a busy weekend. We can communicate via gitter on the topic.

**Comment by j4qfrost** [comment]
@Kethku getting back to investigating, https://stackoverflow.com/questions/8918685/mac-app-crashes-from-finder-but-runs-inside-terminal

This seems to indicate that the app crashes due to using relative path somewhere. Is this a possibility? I can't find anywhere in the code that might be causing this.

**Comment by j4qfrost** [comment]
https://github.com/Kethku/neovide/blob/8f02cdad6b72b83dada577a74f87f57dd592b3f0/src/bridge/mod.rs#L51

Fixed on my end, that line needs a full path to be provided for neovim, e.g. 
```let mut cmd = Command::new("/usr/local/bin/nvim");```

I'll get a fix out later today.

**Comment by j4qfrost** [comment]
https://github.com/Kethku/neovide/pull/220 This should resolve the issue.

**Comment by Kethku** [comment]
So the idea is that you can specify a binary path via an environment variable? Maybe it would be better to specify it via a commandline arg?

**Comment by j4qfrost** [comment]
That would be better for commandline, but an environment variable may still be necessary for launching apps. I added the env variable as a quick, simple way to account for different installation paths in the case that someone didn't didn't install from brew, but it's not necessary to solve the pathing issue.

**Comment by scarin** [comment]
you can try this cmd:
neovide --geometry 10x10

it work for me ... save my life
