### ISSUE TITLE
Using the built-in :term doesn't render typed text

### ISSUE THREAD

**Issue by thabaptiser** [Kethku/neovide#204]
Using the built-in :term command to open a terminal buffer opens a terminal buffer correctly, but anything I type inside of it does not show. It still gets sent to the terminal itself, since I can type "ls" and have that show a list of directories. Pressing "enter" also does not result in a new line.

I'm on Lubuntu, having built neovide from source with the latest commit being 2815a28. My terminal just uses bash, nothing fancy. Neovim version is 0.5.0-418-g87d892afa.

**Comment by Kethku** [comment]
can you try with no config? I use the terminal command constantly with no issue on windows

**Comment by thabaptiser** [comment]
> can you try with no config? I use the terminal command constantly with no issue on windows

Ah, it actually works when I run `neovide --clean`. After running it once with `neovide --clean`, it all works. Now I can just run `neovide` with no issues. weird.
