### ISSUE TITLE
Issue with changing Font and font size

### ISSUE THREAD

**Issue by max1204** [Kethku/neovide#2054]
I have neovide installed on my mac and It is able to load my neovim config and the issue that I'm facing is that it has a small font size and is not able to change it I tried the config for the same to see if that will change it. It reflects all the changes but not the font size change. 

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6
 - Neovide Version neovide 0.11.2
 - Neovim Version NVIM v0.9.1

I feel like I'm missing something here.

**Comment by fredizzimo** [comment]
The most likely reason is that you have mistyped the font name. You can list all the available fonts with `set guifont=*`, and then enter the font name exactly like that.

NOTE: that if you are doing it from vimscript you need to use backslash before each space, for example `set guifont=FiraCode\ Nerd\ Font:h10`, in lua you can just copy-paste the font name.

https://neovide.dev/configuration.html#font

**Comment by luiz00martins** [comment]
I was having the same issue, and I think @fredizzimo is correct. I was using "FiraCode Nerd Font", while the font name was "FiraCode Nerd Font Mono". Switching made the font size work.

Although I still think it's a very weird behaviour from Neovide to just ignore the font size if the font name doesn't match. I feel like it would make more sense for it to just accept the font size, independent of the font name.
