### ISSUE TITLE
Issue during cargo build: runtime.spawn: cannot be shared between threads safely

### ISSUE THREAD

**Issue by quangnguyen30192** [Kethku/neovide#207]
During the installation, I got this error

![image](https://user-images.githubusercontent.com/17941233/77230714-bacf4b00-6bc8-11ea-9297-4f5e0465f4bb.png)

I checked the code and here is where it failed

```rust
impl Bridge {
    pub fn new() -> Bridge {
        let runtime = Runtime::new().unwrap();
        let (sender, receiver) = unbounded_channel::<UiCommand>();

        runtime.spawn(async move {
            start_process(receiver).await;
        });
```

@Kethku any idea why it failed, thanks

**Comment by Kethku** [comment]
Try updating your rust version maybe?

**Comment by chipaltman** [comment]
Built for me with Rust v1.42.0 (current stable).

**Comment by quangnguyen30192** [comment]
Thanks @KillTheMule, I got my rust updated to the latest version and it works
