### ISSUE TITLE
support CTRL-6 or CTRL-^ langmap switch

### ISSUE THREAD

**Issue by habamax** [Kethku/neovide#211]
When I try to switch internal lang support with `CTRL-6` or `CTRL-^` 6 is inserted instead.

![neovide-langmap](https://user-images.githubusercontent.com/234774/77402836-55de4580-6dc0-11ea-8a51-0fbe8a5e8752.gif)

PS, `set iminsert=1` works and language is switched as expected.

**Comment by Kethku** [comment]
I responded with context here: https://github.com/Kethku/neovide/issues/210#issuecomment-603522960 This is a very complicated problem for which I have no easy solution

**Comment by Kethku** [comment]
closing in favor of https://github.com/Kethku/neovide/issues/445
