### ISSUE TITLE
Resize issue using it with i3 

### ISSUE THREAD

**Issue by raaffaaeell** [Kethku/neovide#212]
Hello there, I couldnt find anything related. While using this software in Linux with i3 (tiling window manager), when I first open Neovide, it shows things one size, if I resize the windows or send them to another monitor, the font will either be too big or too small. 

The first image is when I open and it shows the font size correctly, the second is when I send to another monitor and back

https://imgur.com/HxYMNLG.png
https://imgur.com/mBzeIPC.png

**Comment by kiuKisas** [comment]
I have the same issue, also happen with alacritty

**Comment by raaffaaeell** [comment]
Interesting, I didnt think it the terminal counted for something, I thought this app ran in a different window than the terminal, I'll try it later

**Comment by kiuKisas** [comment]
No, this app doesn't run on the terminal but I experience the same issue with an other app that appear to be a terminal, `alacritty`. It is also written in rust so I though it was worth mention it.

**Comment by SirJson** [comment]
If you have the hardware try wayland / sway. It usually handles those cases better than X.

**Comment by Kethku** [comment]
Yes this strikes me as related to the dpi scaling issues. I think the correct long term fix is to bring back the winit windowing system and add a compile time feature which can decide which window to use. This will take some time to build though.

I hope one day to switch back to winit as I believe their long term design is better and it definitely handles dpi scaling way better, but until then I'm stuck with sdl2

**Comment by Kethku** [comment]
This is being worked on here: https://github.com/Kethku/neovide/pull/222 as it is at least partially an upstream issue. Once we are back to working on master, we should be able to be more principled about how we deal with dpi scaling problems. Progress is being made, sorry for the delay

**Comment by raaffaaeell** [comment]
Using the latest master, it working better now, thank you very much
