### ISSUE TITLE
Neovide does not start correctly on Linux if Noto Sans Mono font is not installed

### ISSUE THREAD

**Issue by chrisbouchard** [Kethku/neovide#213]
I've pulled the latest Neovide from `master` and compiled, but I'm having an issue launching the application.

![Image showing an unsized Neovide window](https://user-images.githubusercontent.com/4512028/77602661-5cfe7400-6ee4-11ea-864d-c0e27eadb5db.png)

The thin line inside the red rectangle is the Neovide window. The application is running; I can use `:q` to quit, and if I use Super+Up (the Gnome shortcut for maximize) the window resizes to maximize and looks fine.

I've tried the following ways to launch the application:
```
target/release/neovide
target/release/neovide -u NONE
target/release/neovide --geometry=120x40
target/release/neovide --geometry=1000x1000
```
All have the same observable effect. I've even tried moving my `init.vim` and `ginit.vim` config files, but no difference.

I don't know if it's related, but every so often I'll get a line of output in the console:
```
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
```
The application continues to run, and has the same sizing issue.

I'm running this on Fedora Linux using Gnome on X Windows. I built using
```
cargo clean
cargo build --release --no-default-features
```
as discussed in #165.

**Comment by chrisbouchard** [comment]
Huh. Changing _into_ the release directory and running it there makes the window open normally.

**Comment by chrisbouchard** [comment]
I'd commented that changing into `target/release` seems to fix it, but I was mistake. I'd accidentally run the Neovide from my path instead of `./neovide`. It behaves the same there.

**Comment by Kethku** [comment]
This is very strange. Can you give more details about your system? Which os? Graphics card/libraries? Windowing system?

**Comment by chrisbouchard** [comment]
I'm using stock Fedora 31.

```
$ uname -a
Linux <hostname> 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

According to `/proc/cpu`, I have an "AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx" (it's an integrated GPU). I'm using whatever OSS Radeon drivers come with the Linux kernel these days.

My Windowing system is Gnome 3.34.4 running on xorg-server 1.20.6.

**Comment by anteeek** [comment]
I'm running into what seems a pretty much the same issue, except the --geometry option works, but only for small values. Running on Windows 10

**Comment by chrisbouchard** [comment]
Finally got some time to look at this some more. I added some debugging output in `WindowWrapper::new`, and it looks relevant. I haven't dug further yet; just wanted to update.

```
[src/window.rs:113] window_geometry_or_default() = (
    100,
    50,
)
[src/window.rs:117] renderer.font_width = NaN
[src/window.rs:116] LogicalSize{width: (width as f32 * dbg!(renderer . font_width)) as u32,
            height: (height as f32 * renderer.font_height + 1.0) as u32,} = LogicalSize {
    width: 0,
    height: 0,
}
```

Looks like it's something to do with fonts.

**Comment by chrisbouchard** [comment]
I dug a little more, and it looks like `renderer.font_width` is derived from the default font, which on Linux is

```rust
const SYSTEM_DEFAULT_FONT: &str = "Droid Sans Mono";
```

I don't think I have that installed on my system, so I wonder if that's where the NaN is coming from.

If we set a font in `init.vim` or `ginit.vim`, it would be great if Neovide could use that font for window sizing.

**Comment by chrisbouchard** [comment]
Just to confirm, I changed that font definition to my preferred (installed) monospace font:

```rust
const SYSTEM_DEFAULT_FONT: &str = "Iosevka";
```
Then the window opened sized as expected.

**Comment by chrisbouchard** [comment]
New behavior with this one. Now, if Droid Sans Mono is not installed I get the following stack trace:

```ShellSession
$ RUST_BACKTRACE=1 target/debug/neovide
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/chris/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b75/src/collection.rs:130:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2872
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2732
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1945
  17: <skribo::collection::Itemizer as core::iter::traits::iterator::Iterator>::next
             at /home/chris/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b75/src/collection.rs:130
  18: neovide::renderer::caching_shaper::CachingShaper::metrics
             at src/renderer/caching_shaper.rs:285
  19: neovide::renderer::caching_shaper::CachingShaper::font_base_dimensions
             at src/renderer/caching_shaper.rs:351
  20: neovide::renderer::Renderer::new
             at src/renderer/mod.rs:36
  21: neovide::window::WindowWrapper::new
             at src/window.rs:115
  22: neovide::window::ui_loop
             at src/window.rs:414
  23: neovide::main
             at src/main.rs:58
  24: std::rt::lang_start::{{closure}}
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  27: std::panicking::try
             at src/libstd/panicking.rs:274
  28: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  29: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  30: std::rt::lang_start
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  31: main
  32: __libc_start_main
  33: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

After installing the font, Neovide opens correctly (with a non-zero size). Uninstalling the font brings back the stack trace.

**Comment by j4qfrost** [comment]
I'm wondering if my merge request caused the issue https://github.com/Kethku/neovide/pull/312, can you rollback before that to confirm? @chrisbouchard

**Comment by chrisbouchard** [comment]
I've rolled back to 4b58dfcc (the previous commit) and I'm building now.

**Comment by chrisbouchard** [comment]
Rolling back to 4b58dfcc does fix the stack trace, but the window is still 0×0 unless I install Droid Sans Mono.

**Comment by chrisbouchard** [comment]
I could make a separate issue for the stack trace if you'd like.

**Comment by j4qfrost** [comment]
Yeah, I'll get on that tonight or tomorrow. Looks like I made an oopsie.

**Comment by chrisbouchard** [comment]
Just an update: the required font is now Noto Sans Mono as of a871f92005406df8a052b3f39c2adc26aa5c459e &mdash; same sizing behavior otherwise.

**Comment by chrisbouchard** [comment]
Just checking in on this case. I'm still having trouble, but the stack trace is now gone when I build out of `main`. (Belated thanks to @j4qfrost.)

One new thing, though: If I don't have Noto Sans Mono installed, as before the window is created unsized, but even if I then maximize the window, the cursor does not display. I'm able to use the editor normally except that there's no cursor. Installing the required fonts makes the window open and makes the cursor show correctly.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
