### ISSUE TITLE
Linux build depends on libsndio

### ISSUE THREAD

**Issue by sebastien** [Kethku/neovide#214]
While trying to compile neovide e9808f185ff103e7e3dc2361bc5238541ccbc3e7 on Fedora 31, I got the following error:

```
  = note: /usr/bin/ld: cannot find -lsndio
          collect2: error: ld returned 1 exit status          
error: aborting due to previous error
error: could not compile `neovide`.
```
likewise, running a release build results in the following:

```
$ ./neovide 
./neovide: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory
```

I am not sure if the dependency to `sndio` is required, maybe it could be optional?

**Comment by Kethku** [comment]
Repeat of https://github.com/Kethku/neovide/issues/165
