### ISSUE TITLE
very small text on linux 

### ISSUE THREAD

**Issue by aj3423** [Kethku/neovide#216]
I downloaded from the release page, version 0.5.0, all text looks very small, and all the gui element looks small, any idea ?
Environment:  Kali Linux 64 bit
![2](https://user-images.githubusercontent.com/4710875/77763071-7b47a980-7075-11ea-839c-58084983544d.png)

**Comment by Kethku** [comment]
What happens when you run with no config?

**Comment by aj3423** [comment]
I removed the init.vim, still the same problem
![1](https://user-images.githubusercontent.com/4710875/77814243-2db95400-70ea-11ea-8731-eaed0856f724.png)

**Comment by aj3423** [comment]
It seems caused by `set guifont`,  I tried set to **50**, now it looks better :)
But why it requires such large value.
![2](https://user-images.githubusercontent.com/4710875/77821232-7d684180-7123-11ea-8b29-b94a5143a008.png)

**Comment by Kethku** [comment]
I suspect this has something to do with the dpi scaling...

**Comment by pakdev** [comment]
Yeah, it is. I have a 4K laptop with very small text even though my KDE scaling is 1.8. Is there any way to configure Skulpin to set a scale factor?

**Comment by Kethku** [comment]
We're working on some skulpin dpi related issues over at #218. It should be handled automatically and is a bug that it doesn't

**Comment by aj3423** [comment]
It seems fixed on the master

**Comment by pakdev** [comment]
@aj3423 Are you sure you don't have guifont set to 50 still? I pulled the latest and don't see it fixed...

**Comment by aj3423** [comment]
@pakdev Sorry I should mention I tried the executable from "Action" page:
https://github.com/Kethku/neovide/actions/runs/70228511

**Comment by pakdev** [comment]
@aj3423 That build has the latest commit from master and still doesn't solve the problem on my system.

**Comment by aj3423** [comment]
@pakdev Ok. I'll reopen this.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
