### ISSUE TITLE
kwin reacts to neovide in a strange way

### ISSUE THREAD

**Issue by SirJson** [Kethku/neovide#217]
I recently did some testing on KDE and found some kind of strange behavior. Every time I close neovide my screens go black for a second. 

I looked into the my log files to see if kwin is crashing but it looks more like neovide gets detected as a game because of SDL2. KDE decides then to disables compositing as much as possible and I think this is the cause. Is there a way in SDL to tell the window system "Hey I am not a game" or maybe the possibility to build neovide with winit again?

I know this is more a upstream issue and an annoyance but I still thought this is worth tracking.

**Comment by Kethku** [comment]
Maybe this would help: https://www.reddit.com/r/kde/comments/54d972/the_compositor_is_being_disabled_every_time_i/d80wvcb?utm_source=share&utm_medium=web2x ?

**Comment by SirJson** [comment]
That did the job! Thanks! I exported that rule and attached it here in case someone else might need it. 

My rule is looking for an application with the X class "neovide" so it should work even with different KDE window setups.

[neovide.kwinrule.zip](https://github.com/Kethku/neovide/files/4398193/neovide.kwinrule.zip)

**Comment by Kethku** [comment]
@SirJson is there a way we can distribute this rule for other kde window systems to automatically pick it up?

**Comment by SirJson** [comment]
Could be part of a makefile or better a [cargo-make](https://github.com/sagiegurari/cargo-make) file. Creating a something like a cargo-make file was something I wanted to do anyways because it makes following and installing from master easier.

If you are open to use cargo-make I'll I look into it. I think detecting kwin should be easy and installing some component on Linux means most of the time just copy the right thing into the right place and maybe reload a cache.

Since cargo-make is just a cargo addon it might make installing neovide on other platforms easier as well but I would start with Linux first.

**Comment by Kethku** [comment]
I'm not completely apposed to introducing a more principled build task management system, but I'd have to see what it looks like first. Introducing a non off the shelf solution like that necessarily puts barriers in front of contributing which is somewhat concerning.

¯\_(ツ)_/¯ maybe it would be fine? I haven't used cargo-make.

Makefiles on the other hand are somewhat frowned upon on windows systems just because they are often very unix/linux centric. I know they can be made to work on windows if you're careful, but it certainly isn't the happy path.

**Comment by SirJson** [comment]
> Makefiles on the other hand are somewhat frowned upon on windows systems just because they are often very unix/linux centric.

Yea, they are not complicated per se but I wouldn't want to see them on Windows either. 

>  Introducing a non off the shelf solution like that necessarily puts barriers in front of contributing which is somewhat concerning.

True, that this might be potentially another dependency but as far as I know it doesn't stop you from running cargo build or cargo run and is super easy to install on every platform. And since it can track for example other cargo related dependencies this might come handy later on. 

Another thing that could work it is to integrate it into a build.rs file. But this might get tricky and I really want to give the user a choice to install this rule set and not just do it.

I haven't written a cargo-make script myself yet, just saw other projects using it, so this would be my first time as well. But I think I starting with scratching my own itch and convering my "local install script" into something cargo make understands makes sense. I just give it a shot and see what will happen.

**Comment by Kethku** [comment]
Would it make sense to put the config rule set into the repository and just point to it in the readme or wiki? That way for the probable minority of people who are going to run into this and need it, they can manually add the rule themselves?

I don't know how these rules work or even if there is a config format that would work for that.

**Comment by SirJson** [comment]
That's what I thought you would do :smile: Just put it in the readme and it'll be fine. The only reason I zipped this was because Github complained about not letting me upload _random files_.

Now I realize I could have just as easily posted the content here.. my bad

```ini
[neovide kwin fix]
Description=neovide kwin fix
blockcompositing=false
blockcompositingrule=2
wmclass=neovide
wmclasscomplete=false
wmclassmatch=1
```

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
