### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ovidius72** [Kethku/neovide#223]
I've installed the package from arch linux AUR (the git version) and I'm seeing this error when running.
Other info:
OS: Arch Linux
WM: i3

```
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 499', /home/antonio/.cache/yay/neovide-git/src/neovide-git/CARGO/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/freetype.rs:359:29
stack backtrace:
   0:     0x558f6fbb72f4 - <unknown>
   1:     0x558f6fbdd45c - <unknown>
   2:     0x558f6fbb3fa7 - <unknown>
   3:     0x558f6fbb94ae - <unknown>
   4:     0x558f6fbb91a1 - <unknown>
   5:     0x558f6fbb9b8b - <unknown>
   6:     0x558f6fbb973e - <unknown>
   7:     0x558f6fbd97be - <unknown>
   8:     0x558f6fbd9785 - <unknown>
   9:     0x558f6f556c41 - <unknown>
  10:     0x558f6f534e08 - <unknown>
  11:     0x558f6f4dccf2 - <unknown>
  12:     0x558f6f4de353 - <unknown>
  13:     0x558f6f4fdccb - <unknown>
  14:     0x558f6f54a2dc - <unknown>
  15:     0x558f6f507bce - <unknown>
  16:     0x558f6f4fa153 - <unknown>
  17:     0x558f6fbb95d3 - <unknown>
  18:     0x558f6fbc1aba - <unknown>
  19:     0x558f6fbba020 - <unknown>
  20:     0x558f6f509122 - <unknown>
  21:     0x7f7c0856b023 - __libc_start_main
  22:     0x558f6f4c7dee - <unknown>
  23:                0x0 - <unknown>
[xcb] Unknown request in queue while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:149: append_pending_request: Assertion `!xcb_xlib_unknown_req_pending' failed.
[1]    54748 abort (core dumped)  RUST_BACKTRACE=full neovide
```

**Comment by riginding** [comment]
I had the same error on arch you have to set a guifont.
you can find more info here: https://github.com/Kethku/neovide/issues/87

**Comment by ovidius72** [comment]
@riginding Thanks. Setting guifont works.

**Comment by Kethku** [comment]
Seems like the embedded fonts are causing issues here again :( I wish there was a better way to implement system based font fallback in skia...

**Comment by ovidius72** [comment]
> Seems like the embedded fonts are causing issues here again :( I wish there was a better way to implement system based font fallback in skia...

I don't know if it's related but i see a lot of artifacts when scrolling with j,k.

**Comment by Kethku** [comment]
@ovidius72 can you give a gif of what you are seeing? "lots of artifacts" isn't helpful

**Comment by ovidius72** [comment]
@Kethku I apologize but I cannot reproduce this issue anymore. When scrolling up and down it looked like the line highlighting was drawn on each line and not cleared, leaving horizontal lines around.
For some reason I cannot reproduce this issue, so please do not take it into account.

**Comment by Kethku** [comment]
Ok I will close this then.
