### ISSUE TITLE
Built and running so smooth on Mojave, With minor issues

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#224]
First thanks for making this, i really like the idea of augmenting vim without changing it or the way it functions. I managed to build Neovide on Mojave (Because the build at releases is Catalina only) and it works very nicely however it doesn't quit cleanly. For instance if i `qa` it just freezes, and if i quit it with `CMD+Q` on mac it crashes with, it seems like something is accessed after the window is closed causing this

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```
 
Another issue is that pasting something with ctrl+v doesn't work, idk if it's supposed to work but it's quite annoying

On the suggestion side, things like popups/tabs in vim aren't quite ideal, can you implement custom renderers for them? so that popups are rendered with some styling, tabs can render file icons etc

**Comment by j4qfrost** [comment]
Duplicate of #221

**Comment by j4qfrost** [comment]
Duplicate of #113

**Comment by exoticus** [comment]
@j4qfrost thanks for pointing these out, imma close this then
