### ISSUE TITLE
Black screen on second external monitor

### ISSUE THREAD

**Issue by jamespotz** [Kethku/neovide#227]
neovide turns black once maximized or being resized in the second monitor.
![Screenshot from 2020-04-01 13-14-53](https://user-images.githubusercontent.com/4239625/78101728-04b2ff00-741b-11ea-8a6b-5642dadb23d8.png)

OS Info:
Distributor ID:	ManjaroLinux
Release:	19.0.2
Codename:	Kyria

This is under wayland, havent tried it on x11.

**Comment by Kethku** [comment]
That is very weird. Does it act like normal before you maximize or resize? This feels like a vulkan rendering issue.

**Comment by jamespotz** [comment]
No it doesn't work. The screen doesn't rerender, you can see on the video below
![neovide-bug](https://user-images.githubusercontent.com/4239625/78200932-cffa8280-74c2-11ea-9255-cef99dcc5d58.gif)

**Comment by Kethku** [comment]
By any chance do you have two gpus installed? Or maybe the rendering swaps from the discrete gpu to the an integrated one over that frame boundry?

I think this is an upstream issue with the rendering code which should be solvable, but will need to wait until we are rebased on the master version of skulpin. This is nearly merged over here: https://github.com/Kethku/neovide/pull/222

**Comment by jamespotz** [comment]
Nope, Mine is integrated only. Will be waiting for the next release. Anyway I am using it in my primary monitor, but would love I would love to use it on my second monitor :)

**Comment by jamespotz** [comment]
The latest commit from master fixed this issue, I am closing this now

**Comment by Kethku** [comment]
Glad to hear it!
