### ISSUE TITLE
`:echo has('gui_running')` returns 0

### ISSUE THREAD

**Issue by obreitwi** [Kethku/neovide#229]
When running `neovide`, my old config for `gvim` fails because `has('gui_running')` returns 0.

Is this intended?

It also changes the behavior of other plugins like [solarized](https://github.com/altercation/vim-colors-solarized) that check for a gui running.

**Comment by Kethku** [comment]
Nope not intended. I didn't know it was something that was needed. I'll add it.

**Comment by Kethku** [comment]
Apparently this is a neovim decision. They decided to never set gui_running to 1. https://github.com/neovim/neovim/pull/4155

I have confirmed the same in neovim-qt

**Comment by obreitwi** [comment]
Ah, dang, I should have checked. `neovide` is actually the first GUI project that made me come out of my "shell"…

A quick googling revealed that the solarized colorscheme apparently received an [updated fork](https://github.com/icymind/NeoSolarized) in the meantime, so I'll just use that instead.

Thanks!

**Comment by j4qfrost** [comment]
Badump tsss!

**Comment by wookayin** [comment]
How one can determine we are running a GUI or neovide? Shouldn't you have something like `has('neovide')` or `has('gui_neovide')`? (e.g. https://github.com/qvacua/vimr/issues/101)
