### ISSUE TITLE
Embed Default Font

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#23]
Currently if the default font isn't found installed on the system, the font system will default to Delugia Nerd Font with size 14. This isn't great because it assumes that the nerd font is installed on all systems.

Instead I should embed the nerd font file into the executable using one of the Rust binary embedder projects and use that for the default so that the base experience looks good, and supports powerline options.

**Comment by prabirshrestha** [comment]
Also good to do something like `wezterm`. https://github.com/wez/wezterm/issues/74

**Comment by Kethku** [comment]
Agreed. Something more flexible is definitely a good idea. I think for an initial version though using installed fonts from the system and relying on Skia's font discovery is a reasonable compromise between covering all cases and getting something out and available for folks to play with

**Comment by prabirshrestha** [comment]
If windows it could default to "Consolas" which will exist.

**Comment by Kethku** [comment]
True but then I would need to list a different default font file for every system. I would rather have a consistent look and feel if the font is not configured than create a list of default fonts which could differ in weird and frustrating ways.

**Comment by Kethku** [comment]
Decided to not embed the default font and instead use a standard base font for mac linux and windows
