### ISSUE TITLE
lag when typing on Windows

### ISSUE THREAD

**Issue by aj3423** [Kethku/neovide#235]
It randomly lags when typing, which causes miss typing or repeat typing. The lag behavior feels very much like when cpu get too high load, it freezes the cursor for about 50~300ms. 

The lag happens very frequent on Windows, almost happens on every sentence I input, but It's much better on linux, with all the same plugins. I tried to disable all the plugins, remove the vimrc, but still lag. 

My CPU is intel i9, my keyboard works fine with all other applications like typing in notepad or here reporting issue in chrome browser, it works fine with bare *nvim.exe*.

I don't use any anti-virus or anything like that, below is a screenshot when I typing, with no plugin. 

![1](https://user-images.githubusercontent.com/4710875/78556753-1db81780-7842-11ea-8432-e51b1daa1b08.jpg)

**Comment by Kethku** [comment]
This is interesting, and I've noticed something similar on my side. I thought it was my keyboard, but you're totally right, it only happens in neovide. It didn't used to happen, so let me do some investigation to figure out when it was introduced.

**Comment by Kethku** [comment]
Could you run with --log and send me the generated log file with a similar screen shot demonstrating the issue?

**Comment by aj3423** [comment]
Here's the log on Windows.
![2](https://user-images.githubusercontent.com/4710875/78584169-5f5cb880-786a-11ea-985a-daa77d44c680.jpg)
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4439747/neovide_rCURRENT.log)

**Comment by aj3423** [comment]
I noticed this happens more frequently when typing in the command mode.
And this happens more more frequently for hotkeys, I registered hotkey with *autohotkey* like *alt + j == Down*, I have to press 3~5 times *alt + j* to trigger the  *Down*

**Comment by aj3423** [comment]
Here's the log for input command
![command](https://user-images.githubusercontent.com/4710875/78600055-cd15de00-7884-11ea-932c-41e6a89fec5b.jpg)
[command.log](https://github.com/Kethku/neovide/files/4440556/command.log)

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
