### ISSUE TITLE
Optimizing the Neovide executable

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#236]
I always wondered why is the Neovide executable this big **~70mb**.. it's huge, almost Electron like. For a native app this is very alarming. So i did some tinkering and was able to get it down to only **8mb**. Below is what i did and the rationale for each edit.

### Removing Embedded Assets
It's very nice of Neovide to have good support for fonts and font ligatures; However, embedding `Fira Code` as well as a bunch others isn't particularly the way to go, Mainly because not everyone uses or like to use them anyway. Moreover they're easily installable. 

 **Fix**
I suggest exposing a Neovide variable for setting custom fonts (Falling back to system defaults) and leave it to the user to install and set their favorite fonts. _(just like any other editor or IDE)_
 - For instance vscode defines default fonts to be `Consolas` for Windows, `Menlo` for Mac and `Droid Sans Mono` for Linux

 **Result**
> This optimization reduced executable size to **22.4mb**

### Enable LTO (Link Time Optimization)
This results in a slightly increased compile time _in release mode_ but yields a very nice reduction in size

 **Result**
> Further size reduction to **10.5mb**

### Stripping Symbolic Data
Symbols are not that useful in release mode, unless you're disassembling the code, and can safely be stripped. Plus we have `debug = true` under release profile

 **Result**
> Further size reduction to **8.6mb**

---
I'll be submitting a PR with the above fixes if we reach an agreement

**Comment by exoticus** [comment]
@Kethku If there's a discord or gitter channel, i'd really appreciate a more direct way to talk

**Comment by Kethku** [comment]
https://gitter.im/neovide/community of course!

**Comment by Kethku** [comment]
As for the above changes these all look great to me so long as they are configurable via cargo features. I totally agree that the LTO and stripped symbolic data should be done in the release builds. The embedded fonts I think should be an option. Quite possibly we should produce both assets so users can pick from the release page.

Thanks again for doing such wonderful investigation. It makes a huge difference.

**Comment by exoticus** [comment]
@Kethku no problem! Why would the embedded fonts be an option though? any particular reason behind that? For instance i am pretty sure you added `NotoSansMonoCJKjp-Regular` because it includes this `ln` symbol, and for that i created a new lightweight (19kb) font which includes most of the missing symbols, and for `NotoColorEmoji` if we use each platform emoji font that would be even better and feel more integrated. FIra can be installed by the user and set through `gui font` in vim config

![image](https://user-images.githubusercontent.com/56480961/78727618-73212100-7935-11ea-8fd8-3d59920629d8.png)

**Comment by Kethku** [comment]
Fixed by recent PR. Thanks @exoticus
