### ISSUE TITLE
how do I detect neovide

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#24]
I would like to check for neovide and set appropriate settings that is only enabled in neovide.

**Comment by Kethku** [comment]
This should be pretty easy to do. I should be able to set an option on connect which can be inspected in init scripts to do neovide specific configuration.

**Comment by Kethku** [comment]
Fixed. A global variable 'neovide' is now defined on startup before the user config is loaded.

``` vimscript
if exists('g:neovide')
  " do neovide specific config
endif
```

**Comment by ErrEoE** [comment]
how to config transparency?

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/wiki/Configuration#transparency

**Comment by ErrEoE** [comment]
FullScreen can have command?------------------ 原始邮件 ------------------
发件人: "Keith Simmons"<notifications@github.com>
发送时间: 2020年3月10日(星期二) 下午3:43
收件人: "Kethku/neovide"<neovide@noreply.github.com>;
抄送: "EoE"<2304228627@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Kethku/neovide] how do I detect neovide (#24)



https://github.com/Kethku/neovide/wiki/Configuration#transparency
 
&mdash;

**Comment by ishammahajan** [comment]
Thanks for the solution @Kethku ! If this were documented I think many people would find it easier.
