### ISSUE TITLE
Cannot enter symbol from keypad area

### ISSUE THREAD

**Issue by IceNature** [Kethku/neovide#241]
I can not enter symbol `+` `-` `*` `/` from keypad area in neovide. I'm sure the Num Lock is `On` for I can enter numbers from keypad area.
I use version 0.5.0 neovide.exe downloaded from Github Release on Windows 10 1909 18363.720 x64

**Comment by IceNature** [comment]
Sorry for missing log, for i just found `--log` option. For the `+` symbol, if I input `+` by `<Ctrl-=>`, log outputs
```log
TRACE [neovide::window] KeyDown Received: =
TRACE [neovide::window] Keyboard Input Received: +
TRACE [neovide::bridge] UiCommand queued: Keyboard("+")
DEBUG [neovide::window] Render Triggered
TRACE [neovide::bridge] Executing UiCommand: Keyboard("+")
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: +
```
But if I input `+` from my keypad area by the key `+` directly, log outputs
```log
TRACE [neovide::window] KeyDown Received: Keypad +
TRACE [neovide::bridge] UiCommand queued: Keyboard("<+>")
TRACE [neovide::window] Keyboard Input Received: +
TRACE [neovide::bridge] Executing UiCommand: Keyboard("<+>")
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <+>
```
Does the `<>` around the second `+`  causes the probem or is it just as desgin?
And I found I need to use `<Shift-+>` (`+` is the `+` key on keypad) to input `+` in neovide.

**Comment by Kethku** [comment]
That looks like a bug. Let me look into it.

**Comment by Kethku** [comment]
closing in favor of https://github.com/Kethku/neovide/issues/445
