### ISSUE TITLE
Concurrent Key Press Reacts

### ISSUE THREAD

**Issue by ghost** [Kethku/neovide#244]
Hi~

The second problem was one of the plugin working problem.

The plugin, in short, provides `jk` (almost concurrent pressing down, in insert mode) map to `Esc`, and the map function provides [here](https://github.com/kana/vim-arpeggio/blob/master/autoload/arpeggio.vim#L184).

Is there any methods in this call that Vide does not support? Cause this plugin with the function does not work well.

^_^

**Comment by Kethku** [comment]
Very weird. I use a keyboard macro to achieve this functionality on my setup. Let me look into it.

**Comment by SenseiRalph** [comment]
Hi,

I noticed the same problem when pressing several keys simultaneously. For example, if I press `a`, `s`, `d`, and `f` at almost the same time, only 1 or 2 of those letters will register. It really has to be simultaneous to do that though; if they are done consecutively, all of them register.

**Comment by Kethku** [comment]
This is fixed with the move back to winit.
