### ISSUE TITLE
Won't launch on Ubuntu 20.04 daily iso

### ISSUE THREAD

**Issue by leggettc18** [Kethku/neovide#245]
It built successfully (both with cargo build --release and plain cargo build). When I try to launch it, I see a window briefly open, immediately close, and then my terminal says 

```
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window.rs:144:32
```

When run with RUST_BACKTRACE=1

```
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window.rs:144:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: core::result::Result<T,E>::expect
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:991
  15: neovide::window::WindowWrapper::new
             at src/window.rs:144
  16: neovide::window::ui_loop
             at src/window.rs:375
  17: neovide::main
             at src/main.rs:40
  18: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  22: std::panicking::try
             at src/libstd/panicking.rs:281
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This looks really cool and I'd like to try it out. Let me know if you need any more info or have any potential fixes for me to attempt.

EDIT: Forgot to mention that I get this error whether I run with `cargo run` or `cargo run --release`

**Comment by leggettc18** [comment]
In Hindsight... it's entirely possible the machine I tried building this on doesn't support Vulkan. I tried it on an old Thinkpad, I will try on a newer desktop I have and report back.

**Comment by Kethku** [comment]
This is likely the issue

**Comment by Kethku** [comment]
@leggettc18 did you get a chance to try it on your desktop?

**Comment by leggettc18** [comment]
Sorry. I did and it would launch with a bunch of FontConfig errors. It would then appear to work fine except for some weird rendering issues, like the text seemed to kind of warp when the cursor was around ligatures (I was using the Iosevka font) and parenthesis. It would end up where for instance the cursor would show the character underneath its position in the file, but the actual text was rendered such that the same text was also to the left of the cursor. So basically just really weird rendering errors. I didnt think to take screenshots or anything at the time, ended up using a different editor for the time being. I'll take a stab at recompiling it and seeing if I can recreate it and take some screenshots tonight.

**Comment by Kethku** [comment]
Compiling from scratch seems like a good strategy. What you describe seems like metric problems we've seen in the past.

**Comment by leggettc18** [comment]
Well that's weird, I tried to re-clone and build and now its not drawing any windows. It appears to launch and doesn't crash, and I see an entry in my dock (no icon, but that's normal I'm pretty sure), but no window appears on my screen, and no errors get logged in my console. The window preview looks like this: 
![Screenshot from 2020-04-18 16-59-35](https://user-images.githubusercontent.com/21345721/79671143-0eb45c00-8196-11ea-83b4-11e2fafb1e41.png)

Is that something you've seen before. It doesn't appear to be a fluke, as deleting and re-building has the same result. Also it seems to happen both with release and debug builds.

**Comment by Kethku** [comment]
I've never seen this happen before :l If you build some 10 commits back or so does the same issue occur? We just merged a pr which might effect things, though I doubt it

**Comment by unsek** [comment]
Fresh installed Ubuntu 20.04 and I think I'm getting a similar issue with this. There's no mention of the font config errors in #228 

Here's the log file from running `neovide --log`

```
INFO [neovide::bridge] Close watcher started
INFO [neovide::bridge] Neovim process attached
INFO [neovide::bridge] UiCommand processor started
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::editor] Option set GuiFontSet("")
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(false)
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
WARN [neovide::settings] Initial value load failed for transparency: Error processing request: 1 - 'Key not found: neovide_transparency')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_density')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_speed: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_speed')
WARN [neovide::settings] Initial value load failed for cursor_vfx_mode: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_mode')
WARN [neovide::settings] Initial value load failed for cursor_trail_size: Error processing request: 1 - 'Key not found: neovide_cursor_trail_size')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_phase: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_phase')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_curl: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_curl')
WARN [neovide::settings] Initial value load failed for cursor_animation_length: Error processing request: 1 - 'Key not found: neovide_cursor_animation_length')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_lifetime: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_lifetime')
WARN [neovide::settings] Initial value load failed for no_idle: Error processing request: 1 - 'Key not found: neovide_no_idle')
WARN [neovide::settings] Initial value load failed for cursor_antialiasing: Error processing request: 1 - 'Key not found: neovide_cursor_antialiasing')
WARN [neovide::settings] Initial value load failed for refresh_rate: Error processing request: 1 - 'Key not found: neovide_refresh_rate')
WARN [neovide::settings] Initial value load failed for extra_buffer_frames: Error processing request: 1 - 'Key not found: neovide_extra_buffer_frames')
WARN [neovide::settings] Initial value load failed for keyboard_layout: Error processing request: 1 - 'Key not found: neovide_keyboard_layout')
WARN [neovide::settings] Initial value load failed for cursor_animate_in_insert_mode: Error processing request: 1 - 'Key not found: neovide_cursor_animate_in_insert_mode')
WARN [neovide::settings] Initial value load failed for fullscreen: Error processing request: 1 - 'Key not found: neovide_fullscreen')
WARN [neovide::settings] Initial value load failed for cursor_vfx_opacity: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_opacity')
INFO [neovide::window] window created
INFO [neovide::window] renderer created
INFO [neovide::window] Starting window event loop
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge] UiCommand queued: FocusGained
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge] Executing UiCommand: FocusGained
TRACE [neovide::bridge] UiCommand queued: Resize { width: 0, height: 0 }
DEBUG [neovide::window] Render Triggered
TRACE [neovide::bridge] Executing UiCommand: Resize { width: 0, height: 0 }
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
TRACE [neovide::redraw_scheduler] Next frame queued
```

**Comment by Kethku** [comment]
Could you try setting the guifont? I think maybe the font metrics are getting calculated incorrectly and its doing weird things on linux

**Comment by mudassir-ahmed** [comment]
> Fresh installed Ubuntu 20.04 and I think I'm getting a similar issue with this. There's no mention of the font config errors in #228
> 
> Edit: I forgot to mention that the similarity is Ubuntu 20.04 and the weird render (against a white background for clarity).
> 
> ![image](https://user-images.githubusercontent.com/20364796/80336270-6420f500-8889-11ea-987a-3ca216e90298.png)
> 
> Here's the log file from running `neovide --log`
> 
> ```
> INFO [neovide::bridge] Close watcher started
> INFO [neovide::bridge] Neovim process attached
> INFO [neovide::bridge] UiCommand processor started
> TRACE [neovide::bridge::handler] Neovim notification: "redraw"
> TRACE [neovide::editor::grid] Editor resized
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor] Option set ArabicShape(true)
> TRACE [neovide::editor] Option set AmbiWidth("single")
> TRACE [neovide::editor] Option set Emoji(true)
> TRACE [neovide::editor] Option set GuiFont("")
> TRACE [neovide::editor] Option set GuiFontSet("")
> TRACE [neovide::editor] Option set GuiFontWide("")
> TRACE [neovide::editor] Option set LineSpace(0)
> TRACE [neovide::editor] Option set Pumblend(0)
> TRACE [neovide::editor] Option set ShowTabLine(1)
> TRACE [neovide::editor] Option set TermGuiColors(false)
> TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
> TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
> TRACE [neovide::editor::grid] Editor resized
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor] Image flushed
> TRACE [neovide::redraw_scheduler] Next frame queued
> WARN [neovide::settings] Initial value load failed for transparency: Error processing request: 1 - 'Key not found: neovide_transparency')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_density')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_speed: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_speed')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_mode: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_mode')
> WARN [neovide::settings] Initial value load failed for cursor_trail_size: Error processing request: 1 - 'Key not found: neovide_cursor_trail_size')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_phase: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_phase')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_curl: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_curl')
> WARN [neovide::settings] Initial value load failed for cursor_animation_length: Error processing request: 1 - 'Key not found: neovide_cursor_animation_length')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_lifetime: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_lifetime')
> WARN [neovide::settings] Initial value load failed for no_idle: Error processing request: 1 - 'Key not found: neovide_no_idle')
> WARN [neovide::settings] Initial value load failed for cursor_antialiasing: Error processing request: 1 - 'Key not found: neovide_cursor_antialiasing')
> WARN [neovide::settings] Initial value load failed for refresh_rate: Error processing request: 1 - 'Key not found: neovide_refresh_rate')
> WARN [neovide::settings] Initial value load failed for extra_buffer_frames: Error processing request: 1 - 'Key not found: neovide_extra_buffer_frames')
> WARN [neovide::settings] Initial value load failed for keyboard_layout: Error processing request: 1 - 'Key not found: neovide_keyboard_layout')
> WARN [neovide::settings] Initial value load failed for cursor_animate_in_insert_mode: Error processing request: 1 - 'Key not found: neovide_cursor_animate_in_insert_mode')
> WARN [neovide::settings] Initial value load failed for fullscreen: Error processing request: 1 - 'Key not found: neovide_fullscreen')
> WARN [neovide::settings] Initial value load failed for cursor_vfx_opacity: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_opacity')
> INFO [neovide::window] window created
> INFO [neovide::window] renderer created
> INFO [neovide::window] Starting window event loop
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::bridge] UiCommand queued: FocusGained
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::bridge] Executing UiCommand: FocusGained
> TRACE [neovide::bridge] UiCommand queued: Resize { width: 0, height: 0 }
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::bridge] Executing UiCommand: Resize { width: 0, height: 0 }
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::bridge::handler] Neovim notification: "redraw"
> TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
> TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
> TRACE [neovide::editor::grid] Editor resized
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor::grid] Editor cleared
> TRACE [neovide::editor] Image flushed
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::bridge::handler] Neovim notification: "redraw"
> TRACE [neovide::editor] Image flushed
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> DEBUG [neovide::window] Render Triggered
> TRACE [neovide::renderer] Rendering
> TRACE [neovide::editor] Draw commands sent
> TRACE [neovide::redraw_scheduler] Next frame queued
> ```

Same issue on

```Linux ubuntu-workstation 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

Any fixes?

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
