### ISSUE TITLE
Ubuntu 18.04, Cinnamon 4.2.4: blank window

### ISSUE THREAD

**Issue by yatli** [Kethku/neovide#251]
Hi @Kethku !

Revision: 3da11e09d8e7a784443f7474f1659368003b62c0
Hardware: 64-bit system, X11, nvidia driver v440
Installed the dependencies according to README.md
Configuration: release

When I start it up, it gives a very small window (https://github.com/Kethku/neovide/issues/213), and when I resize it, I see no text displayed. The background color is correct, and I can tell nvim is running, just not updating the framebuffer -- the evidence being the window title change when I do `:e foo.bar` blind.

I have a keybinding for changing colorscheme but that doesn't work either, so I guess the renderer has given up after painting the initial background.

**Comment by Kethku** [comment]
Howdy! Can you try running with the --log command line argument?

**Comment by yatli** [comment]
[neovide_r2020-04-22_16-33-20.log](https://github.com/Kethku/neovide/files/4514805/neovide_r2020-04-22_16-33-20.log)

Please see attached log file.
Thanks!

**Comment by yatli** [comment]
`TRACE [neovide::editor] Image flushed` doesn't appear after just the initial frames?

**Comment by PicoJr** [comment]
Hello, I had the same issue, neovide was starting completely blank.
I managed to get some text displayed by configuring the `guifont`:

init.vim:

```vim
set guifont=Fira\ Code
```

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
