### ISSUE TITLE
Setting cmdheight breaks command_line_delay logic

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#254]
This is an issue for the problem we discussed earlier where setting `cmdheight` for a value bigger than 1 will result in the [`command_line_delay`](https://github.com/Kethku/neovide/blob/3da11e09d8e7a784443f7474f1659368003b62c0/src/renderer/cursor_renderer/mod.rs#L260) not getting executed as it only accounts for last row in the editor grid, which isn't the case for `cmdheight` values over 1

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
