### ISSUE TITLE
Full screen logic breaks on macOS

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#255]
The newly added fullscreen functionality doesn't work properly on macOS because it doesn't take into account the menubar and/or the dock

![image](https://user-images.githubusercontent.com/56480961/79637346-187e9500-817f-11ea-804e-089c1d89d581.png)

Now this should've been a pretty easy fix if Rust-sdl2 had `SDL_GetDisplayUsableBounds` implemented however it looks like only `SDL_GetDisplayBounds` is implemented by [`display_bounds`](https://github.com/Kethku/neovide/blob/3da11e09d8e7a784443f7474f1659368003b62c0/src/window.rs#L183) call here

A simpler approach here is to utilize macOS built-in full screen functionality if the target platform is macOS otherwise use current implementation. This i think should be the way to go

**Comment by Kethku** [comment]
Sadly I'll have to depend on someone with access to a mac in order to get this done since I don't have one.

**Comment by exoticus** [comment]
@Kethku well i am on macOS, can you test if this code works fine on windows

```rust
pub fn toggle_fullscreen(&mut self) {
        unsafe {
            let raw_handle = self.window.raw();

            if self.fullscreen {
                // Use cached size and position
                self.window
                    .set_size(self.cached_size.0 as u32, self.cached_size.1 as u32)
                    .unwrap();
                self.window.set_position(
                    sdl2::video::WindowPos::Positioned(self.cached_position.0),
                    sdl2::video::WindowPos::Positioned(self.cached_position.1),
                );
            } else {
                // Cache the size and position
                sdl2::sys::SDL_GetWindowSize(
                    raw_handle,
                    &mut self.cached_size.0,
                    &mut self.cached_size.1,
                );
                sdl2::sys::SDL_GetWindowPosition(
                    raw_handle,
                    &mut self.cached_position.0,
                    &mut self.cached_position.1,
                );

                // Set window to fullscreen
                self.window.maximize();
            }
        }

        self.fullscreen = !self.fullscreen;
    }
```

**Comment by Kethku** [comment]
Yup will do

**Comment by exoticus** [comment]
Also there's something i can't understand about current implementation 

See [here](https://github.com/Kethku/neovide/blob/3da11e09d8e7a784443f7474f1659368003b62c0/src/window.rs#L217) and [here](https://github.com/Kethku/neovide/blob/3da11e09d8e7a784443f7474f1659368003b62c0/src/window.rs#L196) it seems to me as though it was supposed to be setting border to false to mimic borderless full screen? it just sets it to true in both branches

**Comment by Kethku** [comment]
I think settings resizable to false sets border to false. But maybe I'm wrong? Let me fiddle with it a bit

**Comment by exoticus** [comment]
@Kethku Then it'll render this code even more redundant

**Comment by Kethku** [comment]
I reworked this it here: https://github.com/Kethku/neovide/pull/256 does this work better for you?

**Comment by exoticus** [comment]
@Kethku i've added a review there, please check it out

**Comment by Kethku** [comment]
Hmmm... I'm not seeing your review

**Comment by exoticus** [comment]
my bad, didn't submit for some reason

**Comment by Kethku** [comment]
Fixed
