### ISSUE TITLE
font problem with recent fix

### ISSUE THREAD

**Issue by aj3423** [Kethku/neovide#260]
The latest release in [Actions](https://github.com/Kethku/neovide/actions) page seems have font problem on Linux. 
![neovide screenshot](https://user-images.githubusercontent.com/4710875/79845524-c55f4900-83ef-11ea-8091-8690f078847e.png)
The old version works fine, the last working master is 10 days ago:
![neovide font](https://user-images.githubusercontent.com/4710875/79845662-f8a1d800-83ef-11ea-9c2e-8de49fd8944e.png)

**Comment by exoticus** [comment]
@aj3423 can you build from source? cause i want you to test out this specific [commit](https://github.com/Kethku/neovide/tree/bea55d321f3b1d193dbf9a65280f9203c0f74233) to see if the issue is related to skripo/fontkit update or the new font loader

**Comment by aj3423** [comment]
@exoticus I tried build from different commits, seems this commit causes the problem: 90d5329b88cdf7820e4d4e92778dc0ddb9933888
![neovide font issue](https://user-images.githubusercontent.com/4710875/79870533-b4c1c980-8415-11ea-90e6-26983c1dce0f.png)

**Comment by DemonCloud** [comment]
same here, build from source

**Comment by exoticus** [comment]
@aj3423 i am not sure how would that cause any problem, it's a language feature to use aliases, what do you mean by `seems this commit causes the problem` you mean the font problem or a build problem?

@DemonCloud you mean same font issue on linux?, building specifically [this commit](https://github.com/Kethku/neovide/tree/bea55d321f3b1d193dbf9a65280f9203c0f74233)?

**Comment by exoticus** [comment]
@aj3423 apologies, i saw that you said that it caused the font issue in the photo, there's no logical explanation why that would fail except `cfg(target_os = "linux")` is not evaluating to true for some reason

**Comment by aj3423** [comment]
@exoticus I don't know Rust, how can I add some log message or popup box to check the `cfg(target_os = "linux")` ?

**Comment by exoticus** [comment]
@aj3423 alright, so i would need your assistance of we're gonna fix this as i don't have a linux machine handy, can you replace the whole `define!` block with this
```rust
    const SYSTEM_DEFAULT_FONT: &str = "Droid Sans Mono";
    const SYSTEM_SYMBOL_FONT: &str = "Unifont";
    const SYSTEM_EMOJI_FONT: &str = "Noto Color Emoji";
```

**Comment by aj3423** [comment]
> @aj3423 alright, so i would need your assistance of we're gonna fix this as i don't have a linux machine handy, can you replace the whole `define!` block with this
> 
> ```rust
>     const SYSTEM_DEFAULT_FONT: &str = "Droid Sans Mono";
>     const SYSTEM_SYMBOL_FONT: &str = "Unifont";
>     const SYSTEM_EMOJI_FONT: &str = "Noto Color Emoji";
> ```
Just tried this, same problem.

**Comment by exoticus** [comment]
@aj3423 you have set guifont in your init.vim? if so, try not to set a custom font just to see if default font loads correctly, if not can you make sure Droid Sans Mono is installed _it should be_

**Comment by aj3423** [comment]
@exoticus I ditn't set guifont, but now I tried `set guifont=Console:h14` in vimrc,  or set it at runtime,  same problem. My environment is Kali Linux, maybe it can be reproduced with Windows WSL

**Comment by exoticus** [comment]
@aj3423 can you try to set gui font to that?, i just wanna know if the font loader is totally broken on linux or is it specific to some font/font family

unfortunately i'am on macOS, but i am gonna install linux in order to see how did the font loader regress

**Comment by aj3423** [comment]
I tried  `set guifont=Droid\ Sans\ Fallback:h14` in vimrc, and no matter set it to any font, all the ame problem

**Comment by exoticus** [comment]
alright, i have to install linux to get to the root of this problem then

**Comment by aj3423** [comment]
Now I know how git works.. Previously I checked on different branch..   I'll check again, to see which commit on master caused this. I'll be back in 2 hours and check it.

**Comment by pmkap** [comment]
Just FYI, I have the same Problem on Linux and `set guifont` resolves the Problem. E.g `:set guifont=DejaVuSansMono`.

**Comment by exoticus** [comment]
@pmkap at least this tells me that font loader is working

@aj3423 can you try that, if it works then it's just the matter of adding more fallbacks for linux

**Comment by aj3423** [comment]
@exoticus  The `:set guifont=DejaVuSansMono` works !

**Comment by exoticus** [comment]
@aj3423 so here's the reasons for your findings, first if `set guifont=DejaVuSansMono` works then neovide isn't miss-behaving, and the issue is just that some distros appear to not have Droid Sans Mono pre installed, should be easy fix if we add `DejaVu` as a fallback though. For the utf8 characters and why they worked before here is an explanation.

Originally neovide shipped with a full set of fonts that covered a lot of languages _(japanese, chinese, etc)_ that's why it worked, however it was a lot to bundle built in _50+mb_ , moreover not every user would want to the use same font so we opted for a fallback system to simple system built-in fonts. Consolas (Windows), Menlo (macOS), Droid Sans Mono (Linux). 

Now the reason `DejaVuSansMono` shows only english is that it doesn't contain other characters, a simple fix would be installing [`NotoSansMonoCJKjp`](https://www.google.com/get/noto/) on your system (the font that was before bundled with neovide) and use it normally with `set guifont`

I'd really appreciate if you try the fix and report if it works for you

**Comment by Kethku** [comment]
Unfortunately that will result in less than ideal latin characters wouldn't it?

**Comment by exoticus** [comment]
@Kethku that's why i am currently thinking about the ability to specify multiple fonts, which will have the added benefit of making neovide capable of loading separate glyphs fonts etc, eliminating even the need for patched fonts as neovide will patch them together by means of fallback

**Comment by Kethku** [comment]
I like the idea, but I'm worried about coming up with the correct mechanism for configuring it. Especially when competing guis just do it by default with os font fallback

**Comment by exoticus** [comment]
@Kethku honestly things like font fallback should've been delegated to the system idk what to blame here, font-kit or skribo

**Comment by Kethku** [comment]
Its less something to blame and more the work hasn't been done yet https://raphlinus.github.io/rust/skribo/text/2019/04/04/font-fallback.html

**Comment by exoticus** [comment]
@Kethku yeah i didn't mean blame in a bad way, just that OSs deal best with all these font fallback shenanigan

**Comment by Kethku** [comment]
I wonder if the long term solution would be to do both. Add configuration for font fallback lists and then also ship a version with a ton of embedded fonts like it was previously for those who want it. Then when propper font fallback comes out we just switch to that

**Comment by exoticus** [comment]
@Kethku i'd always try to find the best possible solution without stuffing the executable with embedded fonts, and i really think that the right recipe of fallbacks can handle a wide variety of characters on each system, So for instance instead of defaulting to only 1 font for each system by default, a series of fonts should be loaded in order, and i believe that each system comes preloaded with enough fonts to do just that

**Comment by aj3423** [comment]
@Kethku I tried [noto font package  ](https://www.google.com/get/noto/) with master branch,  it works, English and Utf-8 shows correctly. But there're some new problems like window very small, no cursor, don't know if they're related to the font issue.

**Comment by exoticus** [comment]
@aj3423 
> like window very small, no cursor, don't know if they're related to the font issue.

this shouldn't be font related at all, can you attach a screenshot of that?

**Comment by aj3423** [comment]
@exoticus After installed the 1GB noto fonts, the initial Neovide window looks like this:
![small window](https://user-images.githubusercontent.com/4710875/79907707-9e833000-844c-11ea-963f-d2aa2ba7f43c.png)
The window is small no matter set guifont to anything in vimrc.
I tried uninstall the Noto font , the window becomes normal size again.
Re-install Noto font,  small again ..

And  after drag it to normal size, there is no cursor, and everything lookds very different than before.
![no cursor](https://user-images.githubusercontent.com/4710875/79908294-8fe94880-844d-11ea-8fec-87d7e36ec43f.png)

**Comment by exoticus** [comment]
@aj3423 oh, you didn't have to download the whole 1gb but won't hurt anyway. the window/cursor thing shouldn't be related to the font issue, but concentrating on fonts as a starter, the boxes in statusline are wrong, but the other arrows what do you expect there? did you have powerline glyphs there and they don't render?

**Comment by Kethku** [comment]
the window size may be related to the font size problem if the loaded font reports poor metrics

**Comment by aj3423** [comment]
The boxes is a plugin [noscrollbar ](https://github.com/gcavallanti/vim-noscrollbar), I configured like this in vimrc: `noscrollbar#statusline(20,'-','◫',['◧'],['◨'])
`,  normally it should look like:
![box](https://user-images.githubusercontent.com/4710875/79909087-f28f1400-844e-11ea-845b-f675a83f90f6.png)

But now it looks like:
![1](https://user-images.githubusercontent.com/4710875/79908962-c5dafc80-844e-11ea-9303-88e134083298.png)
And with Insert mode, seems miss aligned
![2](https://user-images.githubusercontent.com/4710875/79908968-c83d5680-844e-11ea-96b0-ea56042425ae.png)

**Comment by exoticus** [comment]
@Kethku checkout gitter please

**Comment by exoticus** [comment]
@aj3423 how do you set guifont, and to what font do you set it, can you try just Noto Sans Mono

**Comment by aj3423** [comment]
@exoticus  I tried `set guifont=Noto\ Sans\ Mono` in vimrc, only works for English characters, Utf-8 is squared. But with `set guifont=Noto\ Sans\ Mono\ CJK\ SC`, Utf-8 is ok, but the lightline bar is messed up.

**Comment by exoticus** [comment]
@aj3423 can i ask you for one more thing? can you install the noto fonts bundled with neovide master (Releases) and try to use them in your current master build?
This should give you original neovide behavior

**Comment by aj3423** [comment]
@exoticus  Downloaded and tried all of these in vimrc, 
```
	set guifont=FiraCode\ Nerd\ Font " English OK, Utf8 Square
	set guifont=Fira\ Code " English OK, Utf8 Square
	set guifont=DejaVuSansMono " English OK, Utf8 square
	set guifont=Noto\ Sans\ Mono\ CJK\ JP " text size looks strange, and in insert mode the "unix | utf8 | vim" bar is miss aligned
```
By utf-8 I mean Chinese characters, so I tried `set guifont=Noto\ Sans\ Mono\ CJK\ SC`,  I'm not sure if the "SC" means "Simplified Chinese", but this seems the closest one from that 1GB font package, but still messes up the lightline bar.

**Comment by exoticus** [comment]
@aj3423 Alright, it's just because no one of these four contain all the required character, @Kethku will be adding a new multiple fallback feature that will fix your problem, will also allow for creating or customizing your own font out of multiple ones

**Comment by aj3423** [comment]
OK, thanks, but why does Neovide requires additional font anyway? I don't see any other software ships with a font package. Can Neovide use the font that nvim uses? Or use the system font by default ?

**Comment by exoticus** [comment]
@aj3423 yeah it used to ship with fonts but the master branch now does exactly that, it uses the font you specify inside your vimrc, if there's none it'll fallback to system defaults. The issue you encountered just happened because of the way neovide fallbacks right now, however this will be alleviated with the changes mentioned above.

**Comment by aj3423** [comment]
@exoticus Looking forward to the new release, can help with test that.

**Comment by exoticus** [comment]
@aj3423 thanks, that would be nice

**Comment by pmkap** [comment]
For the current state, maybe the Droid Sans Package should be listed as a dependency.

**Comment by jamespotz** [comment]
@aj3423 do you have `unifont` fonts? 
You can install the font with
`sudo apt install ttf-unifont`

**Comment by aj3423** [comment]
> @aj3423 do you have `unifont` fonts?
> You can install the font with
> `sudo apt install ttf-unifont`

@jamespotz Thanks.  Indeed... Everything seems to work after `apt install ttf-unifont`, All fonts works correctly for English, Utf-8, and GUI element
