### ISSUE TITLE
Neovide fails to start on multi GPU Linux laptop

### ISSUE THREAD

**Issue by juho-p** [Kethku/neovide#263]
Hi,

Thanks for creating this project. Looks nice, and I can't wait to explore it more!

Trying to start Neovide results in following message:

```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x740000c
  Serial number of failed request:  226
  Current serial number in output stream:  234
```

Window flashes very briefly and then it stops running.

Now, I suspected this might have something to do with this machine having Nvidia and integrated Intel GPU, so maybe it uses wrong GPU, I thought.

I briefly look around the code, grep vulkan keyword etc, and veryr soon find following in `src/window.rs`: line 151

```
                .prefer_integrated_gpu()
```
I remove that call and now it works. Explanation for this is likely that at least for me, when the Nvidia driver is active, Intel driver can't really display windows on my screen.

I guess there's a reason for that function call, so I won't just make a PR to remove that, but you should know, that at least for my machine, that causes Neovide not to work at all.

**Comment by Kethku** [comment]
I will make this a configuration option. thanks for the investigation!

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
