### ISSUE TITLE
Build fail as consequence of updating rust skia [Windows]

### ISSUE THREAD

**Issue by j4qfrost** [Kethku/neovide#264]
This is still speculative. The Windows build workflow is running into this error after upgrading my dependencies in this branch https://github.com/j4qfrost/neovide/commit/55a98495f6db2d801b8bc3e49cec2de1e8e904a3

```
Caused by:
  failed to stat 'C:/Users/runneradmin/.cargo/git/checkouts/rust-skia-35c6c5f9d522ea9f/133682d/skia-bindings/skia/infra/bots/recipe_modules/flavor/examples/full.expected/Test-Ubuntu18-Clang-Golo-GPU-QuadroP400-x86_64-Release-All-Valgrind_AbandonGpuContext_SK_CPU_LIMIT_SSE41.json': The filename or extension is too long.
```

**Comment by Kethku** [comment]
Yeah thats not good... This should probably be raised upstream. Windows path limits are a thing that cross platform libraries need to pay attention to

**Comment by j4qfrost** [comment]
Solved, https://github.com/Kethku/neovide/pull/265
