### ISSUE TITLE
App package from Releases doesn't run on OSX 10.15.4

### ISSUE THREAD

**Issue by xiaochuanyu** [Kethku/neovide#268]
I get a generic error popup from OSX when running app package downloaded from Releases.
I'm on **macOS 10.15.4**.
## Repro Steps
1. Download the app package from Releases and move it to `Applications`.
2. Run Neovide (double-click package).
3. I get a cryptic popup "The application "Neovide" can't be opened.":
![image](https://user-images.githubusercontent.com/1718745/80932764-f136e300-8d8e-11ea-86dc-337179fadc57.png)

## Workaround
I compiled Neovide locally per instructions from readme and it works.

I also tried manually `chmod +x neovide` inside the app package. This let me launch the app but it crashed on launch immediately (didn't see a window at all).
Perhaps there is something weird with the package? Not sure if it has to do with OS version.

**Comment by j4qfrost** [comment]
The release binary is currently broken for OSX 15.15.4, and Kethku wanted to finish up some changes before pushing out a new binary release. If you want you can download a binary from the latest successful CI build https://github.com/Kethku/neovide/suites/614016249/artifacts/4740416 or build from source.
