### ISSUE TITLE
cannot copy/paste from external on Mac

### ISSUE THREAD

**Issue by w93163red** [Kethku/neovide#270]
Hi,

Just found a problem. On Mac, the cmd+c/cmd+v has been mapped to other keys. How can I copy from the external to neovide?

**Comment by Kethku** [comment]
This is not a bug. Neovim handles all keybindings and vim will not allow cmd+c/cmd+v unless your config binds them. I recommend reading up here: https://vim.fandom.com/wiki/Copy,_cut_and_paste

**Comment by v0idpwn** [comment]
cmd-c/cmd-v works fine for me both on vim, gvim and nvim. But doesn't work through neovide. Are you sure that this is not a bug?

**Comment by Kethku** [comment]
I'm almost positive. As an example, pasting with ctrl-v does work when in terminal insert mode. Its possible I have missed something but the support for paste on windows is only through vims support of it.

**Comment by rhomel** [comment]
Maybe this is a different issue but for tcp remote sessions the `*` and `+` registers refer to the system where the (headless) nvim process is running. But for this use-case I think most people want to access their system clipboard where neovide is running. Any ideas on how to support this?

**Comment by Kethku** [comment]
Unfortunately I don't have a good idea. I could imagine a system which uses https://github.com/aweinstock314/rust-clipboard and then exposes a function on the server side to pull the remote clipboard into a register, but I'm not really sure.

I know that neovim uses an external tool internally to pull the clipboard when in wsl and such so maybe we could provide our own version of that that can be swapped in? Not really sure.

**Comment by Kethku** [comment]
Either way @rhomel this would be great idea for another issue which I will mark as enhancement.

**Comment by alexventuraio** [comment]
I got the same difficulties with Neovide in Mac, I'm coming from [MacVim](https://macvim-dev.github.io/macvim/) for Vim and I'm always looking to mimic the same set of tricks MacApp does have.
To make it work in Neovide I copied this from the MacVim repo:
```vim
vnoremap <special> <D-x> "+x

vnoremap <special> <D-c> "+y
cnoremap <special> <D-c> <C-Y>

nnoremap <special> <D-v> "+gP
cnoremap <special> <D-v> <C-R>+
execute 'vnoremap <script> <special> <D-v>' paste#paste_cmd['v']
execute 'inoremap <script> <special> <D-v>' paste#paste_cmd['i']
```
Now I can copy and paste using CMD as usual in OS X.
