### ISSUE TITLE
Weird graphical artifacts on OSX 10.15.4

### ISSUE THREAD

**Issue by xiaochuanyu** [Kethku/neovide#271]
I get some weird graphics where the cursor flickers and changes color when I move it or
change between insert/normal mode.
See this GIF for what I mean:
![ezgif com-crop](https://user-images.githubusercontent.com/1718745/81124841-77c10100-8f04-11ea-957f-4cf4ddcf29b7.gif)

This is a locally compiled version from master today (738dce79e8ffdb92e227f4309d2fb652b1a70e58) on OSX (10.15.4) following instructions in README. This is with a blank `init.vim`.

**Comment by j4qfrost** [comment]
Leaving a note here before I start investigating further. It seems that this issue dates back all the way from the OSX optimization changes. It could have been introduced earlier, but that's as far as I've looked.

**Comment by Kethku** [comment]
This is due to anti aliasing and is fixed by turning it off. I believe there is already a setting for it

**Comment by j4qfrost** [comment]
Yeah, there is. Though since I looked into it, seems that the mouse clicks for macos are off by a scaling factor. Setting the scale factor to 1.0 fixes this for Mac, but I'm getting around to checking how it affects Linux and Windows.

**Comment by Kethku** [comment]
That's very strange and likely a sculpin bug

Thanks,
Keith
________________________________

**Comment by Kethku** [comment]
@xiaochuanyu could you try disabling anti aliasing by setting the global neovim variable `g:neovide_cursor_antialiasing` to `v:false`? I think this should fix your issue.

**Comment by xiaochuanyu** [comment]
Setting `g:neovide_cursor_antialiasing` to `v:false` worked.
