### ISSUE TITLE
Supplying dashed command line arguments leads to error

### ISSUE THREAD

**Issue by obreitwi** [Kethku/neovide#281]
Tested with version `0.6.0.r4.gdc399c3-1` (via [`neovide-git`](https://aur.archlinux.org/packages/neovide-git/) AUR package).

Starting `neovide` without any arguments works fine, but supplying any command line argument with a leading dash leads to an error:

```
~
❯ neovide -h
ERROR [neovide::bridge] Error: 'Error reading message'
ERROR [neovide::bridge] Neovide requires version 0.4 or higher

~
❯ neovide --help
ERROR [neovide::bridge] Neovide requires version 0.4 or higher
ERROR [neovide::bridge] Error: 'Error reading message'

~
❯ neovide --version
ERROR [neovide::bridge] Neovide requires version 0.4 or higher

~
❮ neovide -v
ERROR [neovide::bridge] Neovide requires version 0.4 or higher
```

However, specifying ex commands works fine, example: `neovide "+e ~/.vimrc"`

**Comment by Kethku** [comment]
Oh very interesting. This is definitely a bug.

**Comment by weebs** [comment]
Experiencing the same on Pop_OS 20.04 and Neovim 0.4.4

**Comment by theHamsta** [comment]
I had the same problem. I rebuild in debug mode `cargo build` and the problem disappeared. Also with another try of `cargo build --release` it worked. Only `cargo install`. Very strange. Could also be a flaky behavior.

**Comment by kalvinpearce** [comment]
Currently having the same issue on Windows 10 (OS build 19041)

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.

**Comment by amanagr** [comment]
Can you do a release?

**Comment by shaunsingh** [comment]
@amanagr https://github.com/Kethku/neovide/issues/726, soon ™️
