### ISSUE TITLE
File version not right?

### ISSUE THREAD

**Issue by geekjam** [Kethku/neovide#284]
Download:
https://github.com/Kethku/neovide/releases/download/0.6.0/neovide.exe
And i got:
0.5.0

Download:
https://github.com/Kethku/neovide/releases/download/0.5.0/neovide.exe
And i got:
0.4.0

**Comment by j4qfrost** [comment]
I think @Kethku forgot to bump the version, how are you getting the version?

**Comment by Kethku** [comment]
:( yeah that seems likely

**Comment by Kethku** [comment]
yup just confirmed that the cargo.toml reports the wrong version. I will update it in a commit so that master is up to date, but will wait to publish a new release until we have a sufficient reason. (this may come quickly given reported font bugs)

**Comment by Kethku** [comment]
This is fixed
