### ISSUE TITLE
neovide fails to start

### ISSUE THREAD

**Issue by ssxwcz** [Kethku/neovide#285]
OS: Windows 2004 19582
neovide 0.6.0
![image](https://user-images.githubusercontent.com/43665491/81493067-c3dabf80-92cf-11ea-8324-3743a9495f90.png)

This is the startup log of neovide

> INFO [neovide::bridge] Close watcher started
INFO [neovide::bridge] Neovim process attached
INFO [neovide::bridge] UiCommand processor started
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::editor] Option set GuiFontSet("")
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(false)
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set TermGuiColors(true)
TRACE [neovide::editor] Option set ShowTabLine(0)
TRACE [neovide::editor] Option set ShowTabLine(2)
TRACE [neovide::editor] Option set ShowTabLine(2)
TRACE [neovide::editor] Option set ShowTabLine(0)
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
WARN [neovide::settings] Initial value load failed for cursor_animation_length: Error processing request: 1 - 'Key not found: neovide_cursor_animation_length')
WARN [neovide::settings] Initial value load failed for cursor_trail_size: Error processing request: 1 - 'Key not found: neovide_cursor_trail_size')
WARN [neovide::settings] Initial value load failed for cursor_vfx_opacity: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_opacity')
WARN [neovide::settings] Initial value load failed for no_idle: Error processing request: 1 - 'Key not found: neovide_no_idle')
WARN [neovide::settings] Initial value load failed for refresh_rate: Error processing request: 1 - 'Key not found: neovide_refresh_rate')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_phase: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_phase')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_speed: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_speed')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_density')
WARN [neovide::settings] Initial value load failed for cursor_vfx_mode: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_mode')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_curl: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_curl')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_lifetime: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_lifetime')
WARN [neovide::settings] Initial value load failed for extra_buffer_frames: Error processing request: 1 - 'Key not found: neovide_extra_buffer_frames')
INFO [neovide::window] window created
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor on
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued

**Comment by j4qfrost** [comment]
Can you check that your build has this pull request in it? https://github.com/Kethku/neovide/pull/276

**Comment by j4qfrost** [comment]
I don't think the fix made it into the release.

**Comment by ssxwcz** [comment]
> Can you check that your build has this pull request in it? #276

I tried the version that contains #276 , but still the same error
https://github.com/Kethku/neovide/actions/runs/97913512
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4605363/neovide_rCURRENT.log)

**Comment by ssxwcz** [comment]
![2020-05-10](https://user-images.githubusercontent.com/43665491/81494475-d529c900-92db-11ea-9203-c42b31332c6c.gif)

**Comment by j4qfrost** [comment]
I would sit tight for @Kethku, because I don't currently have access to a Windows machine to help you, but if you want to try diagnosing on your end, try adding ```debug!("{:?}", event);``` before the match here: 
https://github.com/Kethku/neovide/blob/dc399c3c49db2861394c7a21f66dae3a44e193f3/src/window.rs#L438

I might add that line in a pull request in the future. It will give us some clue as to what the editor is trying to do before it crashes. Maybe a debug statement here too:
https://github.com/Kethku/neovide/blob/dc399c3c49db2861394c7a21f66dae3a44e193f3/src/window.rs#L475

**Comment by ssxwcz** [comment]
> I would sit tight for @Kethku, because I don't currently have access to a Windows machine to help you, but if you want to try diagnosing on your end, try adding `debug!("{:?}", event);` before the match here:
> https://github.com/Kethku/neovide/blob/dc399c3c49db2861394c7a21f66dae3a44e193f3/src/window.rs#L438
> 
> I might add that line in a pull request in the future. It will give us some clue as to what the editor is trying to do before it crashes. Maybe a debug statement here too:
> https://github.com/Kethku/neovide/blob/dc399c3c49db2861394c7a21f66dae3a44e193f3/src/window.rs#L475

Thanks, I do n’t understand rust at all and my computer has no rust environment,

**Comment by Kethku** [comment]
@ssxwcz can you tell me a bit about your machine configuration? Does it have a discrete gpu or is it just using integrated? Did previous builds work or is this your first time trying? Can you try setting guifont to something in your vimconfig?

**Comment by ssxwcz** [comment]
> @ssxwcz can you tell me a bit about your machine configuration? Does it have a discrete gpu or is it just using integrated? Did previous builds work or is this your first time trying? Can you try setting guifont to something in your vimconfig?

OS: Windows 2004 19582
CPU: intel i7-8750H
GPU: GTX 1050Ti

I have used neovide before and it can run normally, but after I reinstalled the system, and after upgrading to the Windows preview version, any version of neovide will not work properly on my computer. Still unable to start after setting other fonts

**Comment by sirpxl** [comment]
@j4qfrost I also experience the same issue of neovide crashing in Windows 10, and added the `debug!("{:?}", event);` to the window.rs and recompiled the program.
There is no output when launching the program from my shell. I also re-ran the program with the `--log` flag and it created this [log file](https://pastebin.com/raw/LV2Q7hUS)

@Kethku If it helps, I have in my system a 1660 ti and a Ryzen 7 3750H

**Comment by Kethku** [comment]
Any chanced your graphics driver isn't updated? I'm not sure what else would be causing this...

Do the skulpin https://github.com/aclysma/skulpin examples work?

**Comment by sirpxl** [comment]
My drivers are already updated to the latest version.
When I ran `cargo run --example physics`, it produced this this [block of text](https://pastebin.com/raw/8yDfAtKp).

**Comment by j4qfrost** [comment]
Have you updated your drivers? Looks like this thread might help https://steamcommunity.com/app/275850/discussions/0/3185654583874621079/?ctp=4

**Comment by sirpxl** [comment]
Yes, I did update my drivers. I even downloaded the latest from NVIDIA, reinstalled and rebooted my computer, and the issue still persists.
Now, here's the real kicker. I found a (very crude) fix.
I went to my device manager, right-clicked and disabled the Display Adapter that uses my discrete GPU (1660 ti for my case)...AND IT WORKS!
But here's another thing I found after experimenting. If I were to instead *enable* my discrete GPU and *disable* my integrated GPU, Neovide still works, but with stupid low FPS.
It does start up normal, it's just super slow to type or do any action inside of the program once it's loaded.

**Comment by j4qfrost** [comment]
That's bizarre. Did you reboot after enabling the discrete GPU? This still sounds like a driver issue to me, but I've never been good with hardware.

**Comment by sirpxl** [comment]
Just tried it, and the UI is still really slow.

**Comment by ssxwcz** [comment]
> That's bizarre. Did you reboot after enabling the discrete GPU? This still sounds like a driver issue to me, but I've never been good with hardware.

Neovide can be used normally when using the integrated graphics card, but now the Chinese display is wrong, and still can not input Chinese #125 

![image](https://user-images.githubusercontent.com/43665491/83317721-38ff3c00-a261-11ea-8ced-b14155edb483.png)

![image](https://user-images.githubusercontent.com/43665491/83317731-4ddbcf80-a261-11ea-9b48-7b0e2377bb23.png)

**Comment by j4qfrost** [comment]
@ssxwcz Just to clarify, was this working before and now that you've switched GPUs it doesn't or is this possibly a separate issue?

**Comment by j4qfrost** [comment]
Sorry, I got the problems mixed up. Just remembered that your issue relates to an OS switch and not a GPU switch.

**Comment by ssxwcz** [comment]
> Sorry, I got the problems mixed up. Just remembered that your issue relates to an OS switch and not a GPU switch.

Thank you. I understand that when I try to select the video card used by neovide in the Windows Settings, it can be used normally. If the Settings are determined by Windows itself, neovide will not be able to start
![image](https://user-images.githubusercontent.com/43665491/83317912-14a45f00-a263-11ea-98c1-7c529e4e32b8.png)

**Comment by ssxwcz** [comment]
> @ssxwcz Just to clarify, was this working before and now that you've switched GPUs it doesn't or is this possibly a separate issue?

My error, there was a problem with the Chinese input before I switched the graphics card, but the Chinese display was normal at the time

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
