### ISSUE TITLE
unable to use backslash `\` as localleader

### ISSUE THREAD

**Issue by diefans** [Kethku/neovide#289]
I have a breakpoint shortcut under `\b` but I cannot trigger it. neovide seems to ignore it in normal mode.

btw. if I press `\“` I get 
```
*** stack smashing detected ***: terminated
thread 'tokio-runtime-worker' panicked at 'Input failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_input")', src/bridge/ui_commands.rs:39:17
```

**Comment by Kethku** [comment]
I'm not sure I understand. Are you saying if you press the double quote key the app crashes?

Further can you give the exact nvim binding that doesn't work? I assume it does work on other nvim guis?

**Comment by diefans** [comment]
My vim config specific for this issue:
 ``` vim
let maplocalleader="\\"
au! FileType python nnoremap <silent> <buffer> <localleader>b :call Py_breakpoint_operate(line('.'))<CR>
```
I have a gernan keyboard layout and stumbled accidently over the crash, by pressing `altgr+b = “`

So I managed to crash my neovide by pressing
```
altgr+v = „
altgr+b = “
altgr+n = ”
```

**Comment by diefans** [comment]
The strange thing in command-mode I can enter a backslash

**Comment by TobiasDev** [comment]
I have a similar issue to this. When I try to do something like cd E:\Go\To\This\Folder I can't actually do \ because when I type that one it automatically adds ^ infront of it. So it looks like ^\, which then doesn't work. 
![grafik](https://user-images.githubusercontent.com/5912371/88023660-b80e4380-cb31-11ea-873a-7b35edd72721.png)

I'm on Windows 10 and using NeoVide.

**Comment by TobiasDev** [comment]
I should mention that this is with a Swedish keyboard on a german language computer. Because I believe it's the keyboard breaking it. Maybe a Swedish \ is different than in other languages.

**Comment by diefans** [comment]
Strange thing for me: I can write `\` in command mode, so there must be some difference in key handling for command mode, insert mode, normal mode, etc

if I enter insert mode and press `<c-v>\` I get `<M-Bslash>` which might be wrong, since other editors e.g. neovim-qt just result in `\`

**Comment by TobiasDev** [comment]
What keyboard do you use? E.g. is it like for me where you have "Swedish" or something else rather than english. Because I wonder if it something language specific since they have different names for some keys.

**Comment by diefans** [comment]
german

**Comment by TobiasDev** [comment]
Yeah, I think then we might have narrowed down the issue a bit more. Not sure if this was already know by you @Kethku?

Sadly I haven't ever touched Rust, otherwise I would look into it myself since I really enjoy using this NeoVim client (it is just a lot faster than all other I have tested. :D)

**Comment by Kethku** [comment]
This is unfortunately a frustrating limitation of sdl text input. Unfortunately I'm not super familiar with alternate keyboard layouts. However there is a mechanism for this: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/qwerty.rs As an example, this is how we handle all of the keyboard inputs for the qwerty layout. I would greatly appreciate it if you guys could add layouts for your setups. I believe it should be possible via the same pattern.

Steps needed:
1. add to the layouts enum here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L17
2. add an equivalent branch here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L23;
3. add a layout file here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/qwerty.rs
Note this will require some doing but isn't too bad once you get going. Each case which should return some text should return Some with a tuple containing:
a. vim text as though it were a keybinding
b. bool indicating if the keybind should be bracketed to escape it (think escape key in vim bindings)
c. three remaining booleans indicate which modifier should be reported to vim (this way you can consume them if you have ctrl and alt held for altgr)
4. add reference to the new layout file: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L8
5. add a case for the new layout: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L106

After thats done you should be able to set a setting in vim to indicate which layout to use. Ideally this would be handled by the OS, but I don't think we can do it given the current options we have with sdl2. Eventually I want to move back to winit, but I think there are still stability issues that haven't been resolved, and I'm not sure its actually better.

**Comment by TobiasDev** [comment]
Ah, okay, I'll look if I can get some time to add that for my Swedish Layout!

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if the issue persists.
