### ISSUE TITLE
AltGr doesn't work

### ISSUE THREAD

**Issue by Rhizotome** [Kethku/neovide#290]
AltGr doesn't seem to work. When I use it in combination with another key, it results in very weird behaviours (for example it use Shift+Space for <Esc>, and AltGr+Space seems to trigger it too). Furthermore, some combinations involving AltGr crash neovide. I am on archlinux.
Is there anything i didn't understand ? Thanks.

**Comment by diefans** [comment]
I guess you have the same issues like me: https://github.com/Kethku/neovide/issues/289

**Comment by Kethku** [comment]
Repeat of https://github.com/Kethku/neovide/issues/151
