### ISSUE TITLE
Issues on Pop_OS! 20.04 / Ubuntu 20.04

### ISSUE THREAD

**Issue by jsosulski** [Kethku/neovide#291]
Hi,

on my laptop running PopOS, when trying to start the 0.6.0 binary (or 0.5.0), I get the following error.

```
$ ./neovide
./neovide: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory
```

I found that on my machine libsndio7 is installed, and 6.1 is not available in the package manager.
Do you have any ideas except to downgrade the library?

**Comment by Kethku** [comment]
@j4qfrost I seem to remember you removed the static linking feature? I think that was the fix for this on other linux distros

**Comment by Kethku** [comment]
Previously there was a way to disable static linking in the sdl wrapper which would fix not having libsndio available. I don't remember for sure but I think that library is used for audio which isn't needed for neovide to function but is included in the static linking script by default

**Comment by j4qfrost** [comment]
I was tinkering with the static linking, but it looks like it's still there for the sys package https://github.com/Kethku/neovide/blob/b7b4e95ca97cc29933dd70f34c4274229a9b0d95/Cargo.toml#L44. I think at one point removing static linking worked for my mac, but it's a bit of a blur as to why. libsndio is indeed used for sound.

I'll look into spinning something up I can use for testing.

**Comment by j4qfrost** [comment]
I got it to run the tests using libsndio7. @jsosulski can you clone the source and see if you can run ```cargo test```?

**Comment by raaffaaeell** [comment]
I had the same problem in Fedora 30 and the way was to clone the project and remove static linking like j4qfrost is suggesting. I'm not running my Linux, I can look into it later (my .toml) and edit this post

**Comment by jsosulski** [comment]
> I got it to run the tests using libsndio7. @jsosulski can you clone the source and see if you can run `cargo test`?

Yes, the tests work on my machine as well.

> I was tinkering with the static linking, but it looks like it's still there for the sys package 

You're right, removing static linking makes it compile and now I get a "FontConfig" error, but I think theres another issue for this. Thanks!

**Comment by jsosulski** [comment]
So I had the FontConfig error, and manage to make it run after compiling it again after installing `libfontconfig1-dev`. However, after starting neovide, I get window that consists basically of the height of a window titlebar and 1px width. I can resize it to be larger but it shows only a blackscreen. I do not get any errors on the command line though, so I cannot comment on what the issue is.

**Comment by j4qfrost** [comment]
I made a pull request. Linux works fine without including the build dependency for sdl-sys for my Ubuntu VM and in the CI, but it would be good to test for different distros. We should leave this open until a write up for troubleshooting is made. While I was trying to get neovide working on a fresh Ubuntu install, some of the commands on the README were missing some dependencies. If someone wants to take on the installation process for linux that'd be great.

**Comment by jamespotz** [comment]
@jsosulski have you tried to create a symlink?
**`sudo ln -T /usr/lib/libsndio.so.7.0 /usr/lib/libsndio.so.6.1`**

**Comment by jsosulski** [comment]
@jamespotz I just tried again with the current master. Now it works without any issues with libsndio.

@j4qfrost Later this week I can send a PR for installing on a fresh 20.04 Ubuntu system.

**Comment by Kethku** [comment]
So wait... Does that mean that this is fixed?

**Comment by j4qfrost** [comment]
Yeah, I think I held off closing, because I wanted to wait for instruction
to install for Ubuntu. It would actually be nice if we could include an
install script.

**Comment by j4qfrost** [comment]
Going to just close this and create a new issue for more visibility. https://github.com/Kethku/neovide/issues/369

**Comment by luisiacc** [comment]
I have the release binary on ubuntu and I'm getting this error, what do I do to fix it ?

**Comment by Kethku** [comment]
could you try installing https://packages.ubuntu.com/xenial/libsndio-dev

**Comment by sohail535** [comment]
I have downloaded the latest release binary on Pop_OS! and after installing the `libsndio` package and symlinking it, this is what I get.
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x580000c
  Serial number of failed request:  249
  Current serial number in output stream:  257

```

**Comment by Valeyard1** [comment]
I just run the command below and now it's working:
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 /usr/lib/x86_64-linux-gnu/libsndio.so.6.1
```
