### ISSUE TITLE
Proportional font support?

### ISSUE THREAD

**Issue by a-vrma** [Kethku/neovide#293]
Maybe this is out of scope (this is a "No Nonsense Client" after all) but it would be cool to use a proportional font like Input Sans. Currently it looks like this:

![image](https://user-images.githubusercontent.com/29077900/82121216-5c9e8e80-9759-11ea-86ae-798c5c143766.png)

Note how the cursor is in the middle of a character.

**Comment by Kethku** [comment]
proportional fonts are fundamentally not supported in vim. Until and when we get an upstream change that allows text to not be on a strict grid, this can't be supported in a neovim gui. Unfortunately that means I'm going to close this because I don't think it will ever happen :(
