### ISSUE TITLE
Provide fallback DPI routines for Windows < W10. [FR]

### ISSUE THREAD

**Issue by ZoomRmc** [Kethku/neovide#298]
At the moment neovide fails to launch on Windows 7 since USER32.dll there lacks "SetProcessDpiAwarenessContext". A fallback or an option to launch without HiDPI support would be much appreciated.

If it's not in align with project goals, minimal required Windows version needs to be stated in project's description.

**Comment by Kethku** [comment]
Ah yes. This shouldn't be a very difficult fix.

**Comment by raaffaaeell** [comment]
Interesting issue, I have this exact problem on my Windows 8.1 install and I thought it was because my hardware wasnt supported (or bad drivers). I have a I7 4510u and a R7 M260. 

(Offtopic) Neovide works for me on linux, but I keep getting a message "vulkan support on haswell is limited".

**Comment by quantumfruit** [comment]
I would much appreciate that fix as I am on Windows 7 SP1.

**Comment by Kethku** [comment]
Note: windows 7 has gone out of long term support. I'm not sure I care to support it myself. So I'm going to close this. IF somebody feels strongly, feel free to reopen and we can discuss, but unless somebody is going to contribute a PR that implements this I find it unlikely that we will be able to get anywhere with it.

**Comment by ZoomRmc** [comment]
Please, mention the minimal required version in Readme then (or even add a link here to hint possibility of unblocking earlier versions).
