### ISSUE TITLE
Emoji rendering issue under Windows 10

### ISSUE THREAD

**Issue by spencerwooo** [Kethku/neovide#299]
I'm using neovide 0.5.0 under Windows 10 2004. (As the latest 0.6.0 has some issues with CJK rendering.) I found that neovide doesn't render Emojis inside neovim's terminal as expected.

If I spawn a PowerShell terminal inside neovide with `:split term://powershell`, the emoji that I manually added into my PowerShell `$PROFILE` doesn't render properly.

![image](https://user-images.githubusercontent.com/32114380/82731665-1d64d480-9d3b-11ea-8370-e04a757d408e.png)

However, if I open the `$PROFILE` file with neovide, the emoji renders as expected.

![image](https://user-images.githubusercontent.com/32114380/82731703-4d13dc80-9d3b-11ea-8e5e-e1148f96b7a8.png)

I guess neovide renders Emoji inside files correctly, but somehow fails to render emoji from terminal outputs.

**Comment by Kethku** [comment]
Do the emoji render properly in terminal for other guis? This feels like a limitation of the terminal feature overall

**Comment by spencerwooo** [comment]
So, I did some testing:

- neovim-qt

  ![image](https://user-images.githubusercontent.com/32114380/82852926-cd526180-9f36-11ea-95ac-7efcbf517fb4.png)

- fvim

  ![image](https://user-images.githubusercontent.com/32114380/82852989-f7a41f00-9f36-11ea-811e-2ca752068121.png)

I guess it's the terminal not rendering properly afterall.

**Comment by Kethku** [comment]
Yeah this is an upstream issue.
