### ISSUE TITLE
Allow modifying font and font size

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#3]

**Comment by Kethku** [comment]
Groundwork laid. Just need to parse options and detect font change

**Comment by Kethku** [comment]
This will probably require manual glyph layout to handle all kinds of fonts properly...

**Comment by prabirshrestha** [comment]
+1 for this. Currently it is unbearable to use it. can barely make sense of the text.

![image](https://user-images.githubusercontent.com/287744/71634780-d9c6ce00-2bd3-11ea-88da-c9625ca5f418.png)

**Comment by Kethku** [comment]
@prabirshrestha Thanks for trying! You can get a usable version by either changing the font name found here: https://github.com/Kethku/neovide/blob/master/src/renderer/mod.rs#L15 or installing the delugia nerd font from here: https://github.com/adam7/delugia-code/releases

Can you give me some information about your setup? Did you run from windows? Mac? What are you looking for in a neovim gui?

**Comment by Kethku** [comment]
Font changing support is my next priority.

**Comment by Kethku** [comment]
This should be fixed now @prabirshrestha could you try again and let me know if it works? Neovide should support the name and font size portions of the guifont option in vim.

For example, adding "set guifont=Consolas:h12" to your vim init file should cause Neovide to use the Consolas font with point size 12.

Changing the value should dynamically update the font, however it will default to Delugia Nerd Font if no font with the given name is found. If Delugia Nerd Font isn't found on your system, Neovide will default to the system default which is unlikely to be a monospace font.

I plan on embedding an open source font file into the exe which it will use in this case in the future, but for now this should get the initial beta release unblocked.

**Comment by prabirshrestha** [comment]
@Kethku It is currently crashing for me even without this changes from lastest master.

<details>
<summary>log</summary>

```
[master] d:\tmp\github\others\neovide\target\debug>neovide.exe
UI thread spawned
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13: core::panicking::panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:70
  14: core::option::Option<f32>::unwrap<f32>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\macros.rs:41
  15: neovide::renderer::Renderer::draw
             at d:\tmp\github\others\neovide\src\renderer\mod.rs:126
  16: neovide::window::ui_loop::{{closure}}::{{closure}}
             at d:\tmp\github\others\neovide\src\window.rs:169
  17: skulpin::renderer::renderer::Renderer::do_draw<closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-0.4.0\src\renderer\renderer.rs:407
  18: skulpin::renderer::renderer::Renderer::draw<closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-0.4.0\src\renderer\renderer.rs:296
  19: neovide::window::ui_loop::{{closure}}
             at d:\tmp\github\others\neovide\src\window.rs:168
  20: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:211
  21: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\liballoc\boxed.rs:949
  22: winit::platform_impl::platform::event_loop::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:595
  23: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panic.rs:317
  24: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panicking.rs:287
  25: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  26: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panicking.rs:265
  27: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panic.rs:396
  28: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:593
  29: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::process_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:517
  30: winit::platform_impl::platform::event_loop::ELRShared<()>::send_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:341
  31: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:108
  32: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:1016
  33: DefSubclassProc
  34: DefSubclassProc
  35: CallWindowProcW
  36: DispatchMessageW
  37: IsWindowVisible
  38: KiUserCallbackDispatcher
  39: NtUserDispatchMessage
  40: DispatchMessageW
  41: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:254
  42: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:199
  43: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\event_loop.rs:148
  44: neovide::window::ui_loop
             at d:\tmp\github\others\neovide\src\window.rs:62
  45: neovide::main
             at d:\tmp\github\others\neovide\src\main.rs:91
  46: std::rt::lang_start::{{closure}}<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  47: std::rt::lang_start_internal::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
  48: std::panicking::try::do_call<closure-0,i32>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
  49: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  50: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
  51: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
  52: std::rt::lang_start_internal
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
  53: std::rt::lang_start<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  54: main
  55: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  56: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  57: BaseThreadInitThunk
  58: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by Kethku** [comment]
Ah yup. My bad. Can you try setting the font size as well. I accidentally made setting the font and font size a requirement.

Specifically I follow the nvim-qt format "{font name}:h{font size}"

**Comment by Kethku** [comment]
I will make this code more resilient before closing.

**Comment by prabirshrestha** [comment]
Works now.  But the font rendering is very bad.

Left is neovide and right is vim8 gui with the same vimrc with `set guifont=Fira\ Code:h12`

![image](https://user-images.githubusercontent.com/287744/71711345-75fbfb00-2db5-11ea-804e-ea22cc6b0319.png)

**Comment by prabirshrestha** [comment]
Also one thing I noticed is that we need to call `set guifont=Fira\ Code:h12` very early in the `vimrc` else it will crash with the same error. But at least it is good that it using the same syntax `set guifont` compared to neovim-qt that uses its own syntax and my vimrc is not compatible.

**Comment by prabirshrestha** [comment]
Setting font size to 20 seems to be a better size in neovide but then the font width doesn't seem right.

![image](https://user-images.githubusercontent.com/287744/71711738-39310380-2db7-11ea-8599-06627abdaeb0.png)

**Comment by Kethku** [comment]
I really appreciate the testing. The gui font size is somewhat arbitrary. I'm not sure what the ground truth is for what font size should match what. Its further complicated by the fact that I take dpi scaling into account which I believe gvim does not? Not sure.

As for the scaling problems, yes this is a known issue that I've been fighting for about a week now. I'm pulling out bigger hammers though. My current attempt is to do the shaping of the text myself using https://github.com/linebender/skribo, but this is blocked on what I think is a bug in the Skia bindings which I have created an issue for here: https://github.com/rust-skia/rust-skia/issues/242

If that doesn't resolve itself soonish, I am also considering playing with https://github.com/servo/pathfinder to do the text and graphics rendering instead of skia. This has the added benefit of likely being faster, and pure rust (YAY)  but seems to be less documented. Further it requires an opengl context, and the way I know to do that easily doesn't work over windows remote desktop where Skia does.

Point is. I'm currently working on this and hope to have a solution soonish. Fonts are complicated :P

**Comment by prabirshrestha** [comment]
Fonts are hard and on windows it is much harder since opengl is very blurry compared to directx.

As for your previous question I use both vim8 and neovim on Mac/Linux/Windows. Yes I do use all swapping those OS and editors as I works on projects that require them so cross platform is very important. This is why I even spend time of projects like https://github.com/prabirshrestha/dwm-win32 to have consistent experience across multiple OS. To me neovide is particularly interesting because it is written in Rust which I'm replacing lot of my tools with those written in rust and also loving the language as I'm learning. The more important one is that neovim-qt is just horrible because of its defaults and seems more like a playground to experiment then use it as a default tool. Every update you get crappier experience.
I just hope neovide doesn't make decisions like neovim-qt. https://github.com/equalsraf/neovim-qt/issues/506. I just want my gui vim to look like terminal neovim primarily because of bad support in windows. GUIs are bad at navigating and if I wanted it I would had already not been using vim in the first place. Same with onvim2 I even paid for it but then it looks like vscode with showing file explorer. I don't care about it as I use fuzzy MRU and sessions and is faster. Feel free to add gui or other innovative features but please make it opt in. Just don't move my cheese by making me spend my time on my vimrc. I have other more important things to do.

Having said that it is still you project so feel free to drive however way you want. If you do add lot of features like neovim-qt just give me one flag that I can set to disable instead of trying to find the new flags I need to disable on every updates.

**Comment by Kethku** [comment]
"Fonts are hard and on windows it is much harder since opengl is very blurry compared to directx."

I'm interested in what makes you say that about opengl being blurry compared to directx. My experience has not been the same. Can you elaborate?

"The more important one is that neovim-qt is just horrible because of its defaults and seems more like a playground to experiment then use it as a default tool. Every update you get crappier experience."

I have had a very similar experience. For me the lack of ligatures, standard font rendering, and colored underlines bother me in neovim-qt. I hope to provide a base no-frills experience with neovide.

"I just hope neovide doesn't make decisions like neovim-qt. equalsraf/neovim-qt#506. I just want my gui vim to look like terminal neovim primarily because of bad support in windows."

My goals gui wise is to have as close of support to terminal vim as possible with the added niceties of faster render, ligature support, and better mouse support on windows. On top of that I am interested in building visual improvements that don't effect functionality. The animated cursor being one of them, and blurred floating window backgrounds being the other as an initial set. Beyond that I plan on supporting things in a case by case basis, but I never want the UI to be functionally different from what you get in a terminal environment.

 "Just don't move my cheese by making me spend my time on my vimrc. I have other more important things to do."

I'm interested in what the best experience for this use case would be. There are conflicting goals here because I want the flashy graphical features to be enabled by default (ligatures, animated cursor, blurred backgrounds), but I definitely understand the desire for a stripped down, just be neovim as if it were a terminal. Would a disable everything flag be the best strategy here? I'm interested in your thoughts.

Again, I want to thank you for your testing and engagement. I really appreciate the perspective and time you have put forward to try building and running the app even in its unfinished state. I am hopeful that I can get it to a place where it is useful for you in the long run.

**Comment by Kethku** [comment]
Closing this as it is now supported with the manually written harfbuzz shaper.

**Comment by prabirshrestha** [comment]
As long as you have a single flag such that can disable features by default `:h skip_defaults_vim`, it would be good. This would allow me to opt into feature manually. Also changelog would help here.

**Comment by prabirshrestha** [comment]
@Kethku finally got the windows build working. The font looks great now. Thanks for the quick fix.

**Comment by Kethku** [comment]
Out of curiosity, what build problems did you run into?

**Comment by prabirshrestha** [comment]
Sorry it was build. It was running that was crashing due to invalid set which Neovim didn’t recognize. Wasted a bit time there.

**Comment by zevaverbach** [comment]
> Closing this as it is now supported with the manually written harfbuzz shaper.

@Kethku is there any documentation for this? And while I'm asking, for where to put the .vimrc or whatever config?
