### ISSUE TITLE
Ligatures broken after updating

### ISSUE THREAD

**Issue by kirjavascript** [Kethku/neovide#303]
updated to the latest version of neovide-git and appear to be having a few font problems

here's my guifont and some example non-ligatures;

![broken font stuff](https://i.imgur.com/UxuVb9F.png)

I'm using the otf-nerd-fonts-fira-code AUR package, it all worked fine before upgrading and I haven't changed anything in my vimrc

upon closer inspection, it appears to have been caused by this commit:  [1892073c8a222e6dfd30039e7f691440533deeb5](https://github.com/Kethku/neovide/commit/1892073c8a222e6dfd30039e7f691440533deeb5)

**Comment by j4qfrost** [comment]
Merged.
