### ISSUE TITLE
Cannot build, results in linking errors.

### ISSUE THREAD

**Issue by Supernerd11** [Kethku/neovide#306]
Hello, I'm trying to build `neovide` (using `cargo build --release`), but the builing fails during linking with the following error: [It's quite long, so I put it in a paste](https://pastebin.com/kQqWUAhE). My platform is Linux & distro is Fedora 32. The reason I tried to build it myself is because the released binary depends on libsndio, which is missing from the Fedora package repositories.  

I am not very experienced with rust and thus do not really know where to look, so any help would be greatly appreciated, as I really want to try this editor.

**Comment by j4qfrost** [comment]
Are you on the latest master? I'll try to repro this in a VM tomorrow.

**Comment by Supernerd11** [comment]
I am running on the latest master.

**Comment by clason** [comment]
Just wanted to add as a data point that I have the same issue on openSUSE Tumbleweed; installing `sndio` together with the headers didn't resolve it. (I haven't done the rest of my homework here, so this is not really a bug report...)

**Comment by j4qfrost** [comment]
For sndio issues refer to this thread https://github.com/Kethku/neovide/issues/291

It appears that @Supernerd11 's issue is related to Wayland.

**Comment by clason** [comment]
oops, sorry!

**Comment by clason** [comment]
Just checked, I now do in fact have the same issue on openSUSE Tumbleweed (under X11, not Wayland).

**Comment by j4qfrost** [comment]
@clason What I'm saying is that your issue might not fall under this ticket but the other one. Also refrain from deleting comments. It might cause confusion for others trying to diagnose on their own.

**Comment by chrisbouchard** [comment]
I've tried this with the latest master in the latest nightly and latest stable, and both produce the same error as in the issue. Also on Fedora 32.

**Comment by aseyboldt** [comment]
Same issue for me, I'm on arch linux, using gnome with wayland.

**Comment by Supernerd11** [comment]
I would note that I am actually running Xorg, not Wayland.

**Comment by j4qfrost** [comment]
It looks like the issue may be linked (pun intended) to gcc. It took a bit of digging, but I found this issue https://github.com/onivim/oni2/issues/1778 This makes sense, because on more stable distros we've been able to successfully build the project.

I won't have access to my linux machine for a week, so it would be great if someone else would continue the investigation on this.

**Comment by clason** [comment]
I have indeed set the default compiler to gcc 10 (I know, I know); I didn't realize this was relevant for a rust project... I have access to my linux machine via ssh and would be happy to test things.

**Comment by j4qfrost** [comment]
No worries. It's good to address this, Arch Linux users tend to be on the
bleeding edge, so this helps cover them. I'll look into adding more OS's to
the CI.

**Comment by j4qfrost** [comment]
With the help of @clason we have found that building with ```CFLAGS="-fcommon -fPIE"``` succeeds but requires some testing with an actually screen. I won't be able to test this immediately, so you guys are free to do so.

**Comment by chrisbouchard** [comment]
Ok, with that environment variable and the latest stable Rust (1.44.0) I was able to compile and run. (Though I am still seeing #213 &mdash; initial window sized to 0x0.)

**Comment by PicoJr** [comment]
@chrisbouchard how did you set `CFLAGS`? I tried to set it via `build.rs`

```rust
───────┬───────────────────────────────────────────────────────────────────
       │ File: build.rs
───────┼───────────────────────────────────────────────────────────────────
   1 + │ use std::env;
   2 + │ 
   3   │ fn main() {
   4   │     #[cfg(windows)]
   5   │     {
   6   │         let mut res = winres::WindowsResource::new();
   7   │         res.set_icon("assets/nvim.ico");
   8   │         res.compile().expect("Could not attach exe icon");
   9   │     }
  10 + │ 
  11 + │     env::set_var("CFLAGS", "-fcommon -fPIE");
  12   │ }
───────┴───────────────────────────────────────────────────────────────────
```

rust: `v1.44.0`
neovide: 34643464
os: Arch
gcc: gcc (GCC) 10.1.0
wm: i3
Kernel: 5.7.2-arch1-1

But still no success compiling neovide =/

**Comment by clason** [comment]
just as an environment variable: `CFLAGS="-fcommon -fPIE" cargo build` (assuming bash)

**Comment by PicoJr** [comment]
@clason thanks, I'll try that

**Comment by clason** [comment]
works for me (openSUSE Tumbleweed, gcc 10.1.1, rust 1.43.0, both debug and release). Maybe you need to clean first?

**Comment by aseyboldt** [comment]
Removing target and then building with CFLAGS="-fcommon -fPIE" worked for me as well. (arch linux)

**Comment by PicoJr** [comment]
@aseyboldt thanks, I'll try, I didn't remove `target/` folder.

I use sccache btw.

**Comment by j4qfrost** [comment]
@PicoJr I had the same idea of adding the flags via build.rs, but the problem lies upstream. I'm checking the dependencies now.

**Comment by clason** [comment]
> With the help of @clason we have found that building with `CFLAGS="-fcommon -fPIE"` succeeds but requires some testing with an actual screen. I won't be able to test this immediately, so you guys are free to do so.

I just got back in front of my linux machine and can confirm that the build in fact works.

**Comment by j4qfrost** [comment]
Closing this since the issue should be resolved upstream.

**Comment by j4qfrost** [comment]
Actually, I'll leave this open for visibility until the upstream change is integrated.

**Comment by j4qfrost** [comment]
The upstream branch has be merged, if you get ```relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE``` do ```CFLAGS=-fPIE cargo run```
