### ISSUE TITLE
Neovide starting with Height and Width of 0

### ISSUE THREAD

**Issue by insipx** [Kethku/neovide#310]
Not sure why this happens, just installed yesterday, thought it didn't work until I resized the tiny black line in the middle of my screen. Here are the log files:

https://pastebin.com/PHPDPhSz

**Comment by insipx** [comment]
This actually seems to be tied with the Pop!_OS default desktop environment (gnome3)

Using the cinammon-desktop-environment neovide starts in a normal window

**Comment by j4qfrost** [comment]
This problem may be related to this https://github.com/Kethku/neovide/issues/213

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
