### ISSUE TITLE
Missing input events

### ISSUE THREAD

**Issue by roflolilolmao** [Kethku/neovide#313]
### Description
Rapidly inputting key strokes often results in missing strokes.

### Expected behaviour
All key strokes, be it by hand or macros, should get to the text editor.

### Steps to reproduce
Either mash your keyboard or use external macro software (such as AutoHotKey).

For example, mashing 'aoeu' together results in:
> uuuu

In gvim, this would result in:
> aoeuaoeuouaeaoeu

### Environment
Windows 10 build 1909, using AutoHotKey and a mecanical keyboard with N-Key rollover support.

### Plausible cause
After a quick look through the code base, I noticed that, in the `ui_loop` function in `src/window.rs`, the variables `keycode` and `keytext` are set to the last `Event::KeyDown` or `Event::TextInput` of the `event_pump` iterator, ignoring the first such events of the loop.

**Comment by j4qfrost** [comment]
@Kethku Is this caused by the animation?

**Comment by Kethku** [comment]
I don’t think so. It’s likely either a race condition or something weird about the keyboard handling. Extra weirdly I don’t really encounter the described frequency. So I’m not sure what is going on here

**Comment by j4qfrost** [comment]
@roflolilolmao You were right https://github.com/Kethku/neovide/pull/314

**Comment by roflolilolmao** [comment]
> I don’t think so. It’s likely either a race condition or something weird about the keyboard handling. Extra weirdly I don’t really encounter the described frequency. So I’m not sure what is going on here

This might be bad wording on my end: I don't actually encounter it that much by regular typing but my AutoHotKey macros work about 10% of the time. Since they are important to my workflow, I'm not really sure I can switch to neovide just yet, which is a shame because it looks really good.

**Comment by j4qfrost** [comment]
@roflolilolmao Can you check that my pull request works for you?

**Comment by roflolilolmao** [comment]
I have tried compiling it myself this afternoon but LLVM was not being cooperative so I gave up. I'll give it another shot tomorrow. Thanks

**Comment by j4qfrost** [comment]
Were you using just the binary release before? When you're ready to try again, ping me on gitter.

**Comment by j4qfrost** [comment]
Or you can use this https://github.com/j4qfrost/neovide/suites/805035516/artifacts/8725885

**Comment by roflolilolmao** [comment]
On #314, by hitting several keys at once or using a macro, I get all strokes. However, space and some shifted keys are duplicated or otherwise output weirdly.

I hit all my keys once, without modifiers, then shifted, in both my main layout and qwerty. Here is the output:
```
##  dvorak
1234567890[]
',.pyfgcrl/=
aoeuidhtns-\
\;qjkxbmwvz

##  dvorak  shifted
!!@@##$$%%^^&&**()){{}}
""<<>>PYFGCRL??++
AOEUIDHTNS__||
||::QJKXBMWVZ

##  qwerty
1234567890-=
qwertyuiop[]
asdfghjkl;'#
\zxcvbnm,./

##  qwerty  shifted
!!"@£#$$%%^^&&**())__++
QWERTYUIOP{{}}
ASDFGHJKL::@"~#
||ZXCVBNM<<>>??
```

We can clearly see that the spaces are duplicated and the shifted keys behave weirdly. I don't know how inputs should be handled with SDL2 but I suspect the `Event::KeyDown` and `Event::TextInput` events both contain the information about the key strokes and this is the reason for this behaviour. The events are later deduplicated by [`produce_neovim_keybinding_string`](https://github.com/Kethku/neovide/blob/70388e05d416b2bcec187758c1e4795ec3b9e24a/src/bridge/layouts/mod.rs#L93) called in [`window.handle_keyboard_input`](https://github.com/Kethku/neovide/blob/70388e05d416b2bcec187758c1e4795ec3b9e24a/src/window.rs#L273). This means the line `keytexts.push((keycode, None));` in the `Event::KeyDown` arm will not have the input deduplicated if a corresponding `Event::TextInput` exists.

Since this is not a trivial issue and touches the very core of the input handling, which is the most important part of any text editor, I think we should approach this very carefully. @Kethku what's your opinion on the matter?

My initial issue can be reproduced by setting the refresh rate to something low, for example `:let g:neovide_refresh_rate=1`. You will be able to type several strokes a second and see most of them fail to get there.

Thanks

**Comment by j4qfrost** [comment]
@roflolilolmao Thanks for the detailed response. I forgot the special characters, and looking back at what I wrote, it's a disgusting hack.

@Kethku What's the history behind this https://github.com/Kethku/neovide/blob/1892073c8a222e6dfd30039e7f691440533deeb5/src/bridge/layouts/mod.rs#L105 Is it necessary? I think if we get rid of this an start processing the TextEditing event instead, that would solve the problem https://wiki.libsdl.org/SDL_TextEditingEvent.

**Comment by Kethku** [comment]
the problem with textediting event is that it doesn't work modifiers held down :( so we are stuck using the manual layouts until we either swap back to winit, or consider another platform such as druid

**Comment by Kethku** [comment]
Basically we have to use some weird hacked together combination of the two events. Its a mess

**Comment by pbartyik** [comment]
This is present on linux as well, happy to help with testing.

**Comment by j4qfrost** [comment]
@roflolilolmao @pbartyik Does this fix your issue? https://github.com/Kethku/neovide/pull/322

**Comment by pbartyik** [comment]
> @roflolilolmao @pbartyik Does this fix your issue? #322

nope. spamming ":bp" yields
> pp
bppppppppppppp
p:pp:pppp
ppp:ppp

**Comment by Kethku** [comment]
In that case I believe we will need to hold off on this until we can provide a winit backed build.

**Comment by Kethku** [comment]
I haven't encountered this since the swap back to winit
