### ISSUE TITLE
Basic appearance settings

### ISSUE THREAD

**Issue by alexozer** [Kethku/neovide#317]
Hi, I just have a couple basic questions on how to change some appearance settings.

First off, I think the cursor animation looks really cool, but I'd prefer to disable it for casual use. Is there any way to disable it in all modes? I notice that typing seems to have pretty low latency for Windows in insert mode with cursor animation disabled, it would be nice to see that everywhere.

Second of all, how do I made the titlebar dark like in the screenshots?

**Comment by Kethku** [comment]
1. For now the way to turn it off for everything is via the animation length config https://github.com/Kethku/neovide/wiki/Configuration#animation-length

Setting that value to zero should turn off the animation (baring any bugs :P) 

2. Those were taken earlier in development when we were still using winit for windowing. We will likely go back to winit but for now we are using sdl2. I'm not sure but there may be a way to set the window theme with sdl2, but I don't know for sure. I'd be willing to help out if you want to investigate further, currently we don't have a way to set the windowing theme to look like the screen cap.

**Comment by alexozer** [comment]
Gotcha, thanks for the response. Not sure I'd have time to look too deeply into SDL at the moment but maybe in the future.

**Comment by Kethku** [comment]
Closing for now
