### ISSUE TITLE
g:neovide_transparency ignored under wayland

### ISSUE THREAD

**Issue by pbartyik** [Kethku/neovide#318]
I'm trying to achieve transparency under sway/wayland. As per #178 I'm trying to set g:neovide_transparency but it has no effect.
![example1](https://user-images.githubusercontent.com/39059618/86355734-6fb6e080-bc6b-11ea-8a55-4dce7ca39330.png)

The top window is running nvim within a terminal. Is there a way to accomplish the same transparency?

**Comment by Kethku** [comment]
This may be a limitation in sdl2 under wayland

**Comment by Kethku** [comment]
Yup https://wiki.libsdl.org/SDL_SetWindowOpacity this says that it is only supported in "DirectFB, X11, Cocoa (Apple Mac OS X) and Microsoft Windows" so this is not going to be possible until we swap windowing systems. I'm going to close this as we will get the feature for free once we switch.

**Comment by Mange** [comment]
Is there any tracking issue for the SDL replacement? I could not find one.

**Comment by fredizzimo** [comment]
No, there isn't, I haven't heard of anyone having problems with the transparency on Wayland, and for me it works as it should now. We even have background blur working one KDE at least.

**Comment by Mange** [comment]
Huh, it worked now. I must've made a typo when I tested the first time around.

Sorry for the necro.
