### ISSUE TITLE
file is not opened - no width or height window

### ISSUE THREAD

**Issue by kerolloz** [Kethku/neovide#319]
```
$ ➜ uname -a
Linux kerolloz 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36763164/86513468-d8888f00-be0a-11ea-803a-a9df616f6c47.gif)

**Comment by j4qfrost** [comment]
There's a temporary fix here I think https://github.com/Kethku/neovide/issues/310

**Comment by chrisbouchard** [comment]
I think this is also related to #213. There's a possibly simpler workaround for now: install Droid Sans Mono.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
