### ISSUE TITLE
Readme install instructions

### ISSUE THREAD

**Issue by PitcherTear22** [Kethku/neovide#323]
>  But if you want the latest and greatest you should clone it and build yourself.

You have GitHub Actions set up, so I think this should be changed to "get the latest and greatest from actions."

**Comment by PitcherTear22** [comment]
Ok so I get this when I try to run the one from actions: https://del.dog/creryvorew.txt
Now I don't know if this is a bug or I'm not supposed to use the binary from actions

**Comment by PitcherTear22** [comment]
OS-arch linux
Installed [`libsndio-61-compat`](https://aur.archlinux.org/packages/libsndio-61-compat) because even the one in releases wont run without this (tried normal [`sndio`](https://www.archlinux.org/packages/community/x86_64/sndio/)

**Comment by PitcherTear22** [comment]
Also the one in actions is 3 times smaller (35MB) than the one in releases (109MB)

**Comment by j4qfrost** [comment]
Sorry, both @Kethku and I have been a bit busy, I'll investigate some of these issues. Are you running into the crash with the most recent build? The arch distro tends to break often.

**Comment by PitcherTear22** [comment]
Sorry for the confusing wording, the release works fine but the build from github actions does not

**Comment by Kethku** [comment]
I think this is part of why we are using the releases as a form of "stable" while the github actions tend to fluctuate more and be closer to develop.

**Comment by j4qfrost** [comment]
@PitcherTear22 so with regard to your crash, the fix is to install ```ttf-droid```, since we default to using Droid Sans Mono. afterwards run ```fc-cache```. If you are running an nvdia graphics card and are getting a vulkan initialization error then try this ```export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json``` With regard to the sndio issue, that is a bit of an SDL compatibility issue. I will get it bundled when I make the arch package.

@Kethku do you want me to add droid fonts as a dependency for arch?

**Comment by PitcherTear22** [comment]
> the fix is to install ttf-droid

Thanks!

**Comment by PitcherTear22** [comment]
> I think this is part of why we are using the releases as a form of "stable" while the github actions tend to fluctuate more and be closer to develop.

Yeah but building from source would be unstable too right? I'm saying

**Comment by j4qfrost** [comment]
@PitcherTear22 well sometimes hotfixes come in, which means source might have fewer bugs. For arch specifically, I have only recently started tackling some of the issues and arch packages update more frequently and there are a number of blind spots that open up as a result.

**Comment by PitcherTear22** [comment]
>well sometimes hotfixes come in, which means source might have fewer bugs

So this closes it ig
