### ISSUE TITLE
Terminal buffer's stdout breaks if Neovide is not opened from another terminal

### ISSUE THREAD

**Issue by d1hasib** [Kethku/neovide#329]
When Neovide is launched from application menu (e.g. rofi) or from keyboard key (e.g. sxhkd) other than a terminal, the built in terminal buffer can not display stdout text properly. 
![1596293066](https://user-images.githubusercontent.com/38419114/89106070-9d4ca080-d448-11ea-9dc5-5e72cbe6520e.png)
(figure01- left: alacritty (idle), right- neovide (from rofi))

But if it is launched from another terminal (e.g. alacritty), the terminal buffer works as expected. 
![1596293009](https://user-images.githubusercontent.com/38419114/89106106-f1f01b80-d448-11ea-9f7e-b04bbec82a4e.png)
(figure02- left: alacrity (running neovide), right: neovide (from alacritty))

 Using Arch Linux. Neovide (0.6.0-7) has been build from AUR.

**Comment by Kethku** [comment]
Do other guis for neovim exhibit similar behaviour? I don't understand how this could possibly be on our side... Maybe try in neovim-qt as well?

**Comment by d1hasib** [comment]
@Kethku I have tried `neovim-qt` after facing this issue. But it has not that kind of problem.
But there is some font scaling issue (Maybe it is in `neovide`) - with the same font size configuration (:h22) Neovide's font is usable (like screenshot), but in `neovim-qt`, it is way more bigger. I have also tried `goneovim`, and it's font size matches with `neovim-qt` but not with `neovide`. I don't think this issues are related but I think I should mention.

**Comment by Kethku** [comment]
@j4qfrost recently merged some changes to path setup on startup. Could you pull and try again?

**Comment by d1hasib** [comment]
I have installed and tested the `neovide-git` version from AUR. But the issue is still there.

**Comment by j4qfrost** [comment]
The path setup changes I had made were for Mac. I'll look into it for
Linux. Sorry wasn't aware of this ticket.

**Comment by Kethku** [comment]
I have no idea what could be causing this... @d1hasib do you by chance still encounter this issue? Could anybody else speak up if they encounter this as well?

**Comment by d1hasib** [comment]
`neovide` aur package still has the issue and I couldn't build 'neovide-git` package. Some failure occurred .

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
