### ISSUE TITLE
neovide with nvim-qt

### ISSUE THREAD

**Issue by Mechap** [Kethku/neovide#331]
How do I manage to run neovide with nvim-qt instead of nvim ?

**Comment by Kethku** [comment]
I'm sorry, but I don't understand your question.

nvim-qt is a frontend for neovim. Neovide is an alternate frontend for neovim. The two solve the same purpose, so I don't understand what running neovide with nvim-qt instead of nvim means. Can you elaborate?

**Comment by Kethku** [comment]
I'm gonna close this as the question doesn't really make sense.
