### ISSUE TITLE
Split up bridge\mod.rs file

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#335]
Currently the bridge\mod.rs file is in charge of N different things:

1. Constructing the command to start neovim
2. Registering commands for adding and removing windows context menu integration
3. Starting the neovim process
4. Calling various startup commands (load ginit, set client info, set neovide variable, set rgb
5. Spawning the tokio runtime and initializing the command handler

I think 3, 4, and 5 could stay in the mod file, but 1 and 2 should be split into their own files for cleanliness and readability.

**Comment by Kethku** [comment]
NOTE: this is just a reminder for me

**Comment by j4qfrost** [comment]
I'd been thinking that we can replace the bridge with an off the shelf event emitter. I was shopping around for one for another project of mine. It mitigates some of the workload and helps promote componentization.

**Comment by Kethku** [comment]
Id love to outsource to an event emitter. I'm nervous though because it has to do a couple things to really work. It has to be able to queue up events and then release them synchronously. Further, it has to work well with async. Those two requirements mean it might be difficult to find something workable. That said, it would be lovely to just have a centralized authority for such things. I haven't looked...

**Comment by Kethku** [comment]
This was done in the big refactor
