### ISSUE TITLE
guifont acts differently, accordint to the compile option

### ISSUE THREAD

**Issue by andrwj** [Kethku/neovide#338]
The following setting produces as if the variable width font, if neovide is compiled with **--release** option.
But **guifont** works correctly without the option.
 
```set guifont=Noto\ Sans\ Mono\ CJK\ KR:h15```

**guifont** works correctly for macOS 10.14, but After upgrading to macOS 10.15 the weird result comes out.

The font is from [Google Fonts](https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKkr-hinted.zip)

**Comment by Kethku** [comment]
Can you give a screenshot of what it looks like?

**Comment by andrwj** [comment]
@Kethku  sure

![guifont-acts-weirdly](https://user-images.githubusercontent.com/259207/91120907-a6d8c980-e6d1-11ea-91b6-7171d6cb28e6.png)

**Comment by j4qfrost** [comment]
That's the randomization solution kicking. It means that the system can't
find the Noto font.

**Comment by j4qfrost** [comment]
Did you pull recently?

**Comment by andrwj** [comment]
@j4qfrost   yes, always.

**Comment by j4qfrost** [comment]
Can you send your hardware specs? This might be related to dpi.

**Comment by andrwj** [comment]
@j4qfrost  thank you for asking me. 

```bash
# MacBook Pro 2020, 16" LCD
# True Tone enabled
# set resolution to 2048x1280 from Preferences Panel.

$ system_profiler SPDisplaysDataType |grep Resolution
Resolution: 3072 x 1920 Retina
```

crop from [https://www.sven.de/dpi/](https://www.sven.de/dpi/)
<img width="1090" alt="DPI" src="https://user-images.githubusercontent.com/259207/91126072-1bb20080-e6de-11ea-96b1-3717a696c150.png">

**Comment by Kethku** [comment]
@j4qfrost I'm not so sure these are different fonts. THey look like the characters render the same, but are spaced differently...

**Comment by andrwj** [comment]
@Kethku  that's what I said. The characters rendered with different space.  But it's a same font.

**Comment by j4qfrost** [comment]
Yeah, I made a comment in my grogginess that I though they were different
fonts and deleted it. Not sure why the spacing is off.

**Comment by andrwj** [comment]
luckly **guifont** option started to work again well even it is comiled with `--release`. 
what I did is git pull and compile with the option. nothing more. 

Neovide commit: `6db2b50569e0e3021a800bd724bc936c57db231b`

```bash
$ nvim --version
NVIM v0.5.0-659-g7b1b271f4
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Kethku** [comment]
Ok then I think I'm going to close this
