### ISSUE TITLE
Full screen F11 does not work (Windows 10)

### ISSUE THREAD

**Issue by guillaume-tessier-cbp** [Kethku/neovide#340]
Neovide window can toggle maximise and minimize.

However, **full screen (F11 key) does not work** : window decoration + Windows 10 start bar are visible.

It could be great to have a real full screen to optimize screen space.

Platform : Windows 10
Neovide release : 0.6.0 from release file.
Nvim 0.4.4

**Comment by Kethku** [comment]
Can you try toggling fullscreen like this: https://github.com/Kethku/neovide/wiki/Configuration#fullscreen

**Comment by Kethku** [comment]
I'm gonna close this because fullscreen is supported

**Comment by guillaume-tessier-cbp** [comment]
Indeed, it works when using this instruction in vim.init.
However, it keeps Neovide in full-screen. 
It's not possible to minimize it afterward. Screen is locked with Neovide full screen.

Usually, man would toggle in between those modes:
- minimize/maximize app with top right menu on window decoration,
- maximize/fullscreen with the F11 key

**Comment by guillaume-tessier-cbp** [comment]
Actually, thanks to this, I just wrote my very first vim function to toggle full-screen and map it to F11 :wink:

**Comment by Kethku** [comment]
In general this is the preferable way to handle hotkeys. F11 makes sense on windows, but on other platforms it does not. So wherever possible I like to give the users the tools and let them configure it however they want.

**Comment by guillaume-tessier-cbp** [comment]
Actually, I thought this would not even be the app developer to care about this. 
Indeed, this is very coupled with the window manager (Gnome, KDE, windows...). 
And of course, you do not want to be opiniated at binding user keys (one of the thing I love in Neovide is its pristine vim experience... and this amazing fluidity in displaying typed character !!!)

Therefore, I thought wathever key full-screen is bound within you desktop manager, it would be his duty to just hide window decorations and startup bar. So, it should not even be your job to manage this.
Of course, I guess apps can customize its behaviour when receiving a full-screen signal : for exemple, chrome browser hides all tabs.

Kethku, thanks for Neovide !

**Comment by hgup** [comment]
In case you want that function. [Here](https://github.com/neovide/neovide/issues/356#issuecomment-921431879) it is.
