### ISSUE TITLE
Option to disable cursor animation when jumping to/from command line

### ISSUE THREAD

**Issue by oxysoft** [Kethku/neovide#341]
Just tried out Neovide today; it's awesome! I'm really fond of the cursor animation, however I find the jumps to and from the command line quite jarring. For example I have `<C-s>` mapped to `:wa<cr>` and this pretty much results in a streak of light across my screen whenever I hit save. (along with other mapped commands)

Cheers!

**Comment by jberryman** [comment]
It might be neat to have a sort of shrink-bubble-pop animation as the cursor disappears.

**Comment by Kethku** [comment]
I like this idea haha. Would require some pretty significant refactoring to work though as the current system assumes a single cursor.
