### ISSUE TITLE
Font can't be loaded.

### ISSUE THREAD

**Issue by TornaxO7** [Kethku/neovide#345]
OS: Arch Linux
![Screenshot](https://user-images.githubusercontent.com/50843046/91670220-ad28d480-eb1b-11ea-8e34-25f992e267eb.png)
As you can see I'm using `Hack Nerd Font Bold 20` and it's even "activated" but the bars on the top and on the bottom don't show any glyphs. They are shown in `gvim`. <br>
I'm using the `neoclide-git` from the AUR.

My `~/.vim/vimrc` (the necessary part):
```vim
" -----------------
"  GUI - Settings
" -----------------
set guifont=Hack\ Nerd\ Font\ Bold\ 20
set linespace=4

let g:neovide_refresh_rate=60
let g:neovide_transparency=0.85
let g:neovide_no_idle=v:false
let g:neovide_fullscreen=v:false
let g:neovide_cursor_animation_length=0.13
let g:neovide_cursor_trail_length=0.5
let g:neovide_cursor_antialiasing=v:true
let g:neovide_cursor_vfx_mode = "ripple"
let g:neovide_cursor_vfx_opacity=200.0
let g:neovide_cursor_vfx_particle_lifetime=1.2
let g:neovide_cursor_vfx_particle_density=7.0
let g:neovide_cursor_vfx_particle_speed=10.0
let g:neovide_cursor_vfx_particle_phase=1.5
let g:neovide_cursor_vfx_particle_curl=1.0
```

**Comment by Kethku** [comment]
The guifont format is incorrect.

```
set guifont=Hack\ Nerd\ Font:h20
```

might work better

**Comment by TornaxO7** [comment]
Cool thank! Now it's big enough but how can I set the style?

**Comment by Kethku** [comment]
There is not currently a way to set the weight globally, but individual syntax highlightings can set bold. For instance I see in your view that the NORMAL in the bottom is bold due to the highlighting there.

**Comment by TornaxO7** [comment]
Ok, thank you!
