### ISSUE TITLE
Pressing `\` puts back to normal mode.

### ISSUE THREAD

**Issue by TornaxO7** [Kethku/neovide#346]
OS: Arch Linux
Using: neovide-git

Keyboard-layout: german (de)
To press backslash `\` I need to press this keycombination: `Alt gr` + `ß` but it throws me back to normal mode.

**Comment by Lightosk** [comment]
Experiencing this, too. I've seen in the screenshots the maintainer uses Windows. This is most likely due to Windows and MacOSX/Linux having different sequences for Alt Gr. On Windows Alt Gr is the same as Alt + Ctrl. On Linux it is a completely own key.

**Comment by Kethku** [comment]
This is a repeat of https://github.com/Kethku/neovide/issues/151
