### ISSUE TITLE
Neovide wont start

### ISSUE THREAD

**Issue by Hamzailer** [Kethku/neovide#349]
When I try to start neovide it doesent run when I tried to run to by terminal I get this:

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0xbc0000c
  Serial number of failed request:  242
  Current serial number in output stream:  250

**Comment by j4qfrost** [comment]
OS and hardware?

**Comment by Kethku** [comment]
Can you give some details about your system? Do you have the Vulcan dependencies and or do the upstream skulpin examples work on your machine?

**Comment by Hamzailer** [comment]
system info:

System:    Host: hamzailer Kernel: 5.8.3-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.19.4
           Distro: Manjaro Linux
Machine:   Type: Desktop System: HP product: HP Pavilion Desktop 590-p0xxx v: N/A
           serial: <superuser/root required>
           Mobo: HP model: 8433 v: 11 serial: <superuser/root required> UEFI: AMI v: F.40
           date: 10/31/2019
CPU:       Topology: Quad Core model: AMD Ryzen 3 2200G with Radeon Vega Graphics bits: 64
           type: MCP L2 cache: 2048 KiB
           Speed: 1477 MHz min/max: 1600/3500 MHz Core speeds (MHz): 1: 2343 2: 1477 3: 1477
           4: 3478
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 450.66
           Device-2: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
           driver: amdgpu v: kernel
           Display: x11 server: X.Org 1.20.8 driver: modesetting,nvidia FAILED: ati
           unloaded: nouveau resolution: 1440x900~60Hz
           OpenGL: renderer: GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 450.66
Audio:     Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio driver: snd_hda_intel
           Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor
           driver: snd_rn_pci_acp3x
           Device-3: AMD Family 17h HD Audio driver: snd_hda_intel
           Sound Server: ALSA v: k5.8.3-2-MANJARO
Network:   Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter driver: rtl8821ce
           IF: wlo1 state: up mac: b6:64:6f:bf:8f:4a
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8168
           IF: enp46s0 state: up speed: 100 Mbps duplex: full mac: 10:e7:c6:13:39:6f
Drives:    Local Storage: total: 1.03 TiB used: 201.12 GiB (19.1%)
           ID-1: /dev/sda vendor: Samsung model: MZ7PD128HCFV-000H1 size: 119.24 GiB
           ID-2: /dev/sdb vendor: Seagate model: ST91000640NS size: 931.51 GiB
Partition: ID-1: / size: 116.38 GiB used: 35.97 GiB (30.9%) fs: ext4 dev: /dev/sda1
           ID-2: /home size: 915.89 GiB used: 165.14 GiB (18.0%) fs: ext4 dev: /dev/sdb1
Swap:      ID-1: swap-1 type: file size: 256.0 MiB used: 256.0 MiB (100.0%)
           file: /var/lib/systemd-swap/swapfc/1
           ID-2: swap-2 type: file size: 256.0 MiB used: 256.0 MiB (100.0%)
           file: /var/lib/systemd-swap/swapfc/2
           ID-3: swap-3 type: file size: 256.0 MiB used: 256.0 MiB (100.0%)
           file: /var/lib/systemd-swap/swapfc/3
           ID-4: swap-4 type: file size: 256.0 MiB used: 231.6 MiB (90.5%)
           file: /var/lib/systemd-swap/swapfc/4
           ID-5: swap-5 type: file size: 256.0 MiB used: 148.3 MiB (57.9%)
           file: /var/lib/systemd-swap/swapfc/5
           ID-6: swap-6 type: file size: 256.0 MiB used: 0 KiB (0.0%)
           file: /var/lib/systemd-swap/swapfc/6
Sensors:   System Temperatures: cpu: 55.2 C mobo: N/A
           Fan Speeds (RPM): N/A
           GPU: device: nvidia screen: :0.0 temp: 38 C fan: 37% device: amdgpu temp: 55 C
Info:      Processes: 299 Uptime: 11h 27m Memory: 6.76 GiB used: 4.44 GiB (65.7%) Shell: Zsh
           inxi: 3.1.05

**Comment by j4qfrost** [comment]
Seems to be a similar setup to mine. Though I haven't run into this error before. @Hamzailer have you had neovide working before? Did you install from source or aur?

**Comment by Hamzailer** [comment]
No it hasnt worked before and I got it from the AUR also I'm sorry right now as Its really late and i need to sleep but if you do need more info please do comment it I will reply in the morning

**Comment by j4qfrost** [comment]
When you get the chance, try installing from source and see if it works. Then, we can narrow down the cause.

**Comment by Hamzailer** [comment]
I tried to build from source but wasnt successful I guess i'll just stick with regular neovim thanks for trying to help

**Comment by j4qfrost** [comment]
I still would like to figure out the root cause of this issue, not only to help fix it for you but also to get it running for other in the future. Though it's up to you whether you want to help me fix it, since I can't reproduce it myself. I'll leave this open for a while longer. Perhaps a driver issue? https://github.com/VCVRack/Rack/issues/115

**Comment by Hamzailer** [comment]
ok sure lemme check

**Comment by Hamzailer** [comment]
yes glxgears works and other open gl applications also work for me

**Comment by Kethku** [comment]
neovide doesn't use opengl to render but instead uses vulkan which causes problems on many systems.

**Comment by Kethku** [comment]
@j4qfrost  think this might be integrated vs discrete again?

**Comment by Hamzailer** [comment]
that could be
i could try and delete prime drivers and try just decrete ones

**Comment by Kethku** [comment]
The system is configured to prefer the integrated gpu. I think we should just swap this. It was originally done to improve battery life, but I'm not sure people care that much (and honestly it doesn't take thaaat much).

**Comment by j4qfrost** [comment]
Possibly, there are a lot of weird issues having different vulkan installations too. The machine has both an Nvidia card and an AMD card, could be any number of things. Might even be that the machine needs a hard reset. Arch Linux is weird.

**Comment by Hamzailer** [comment]
If it helps ive played games like dota 2 using vulkan and it worked perfectly

**Comment by Kethku** [comment]
That seems to point toward the integrated vs not issue more. But what do I know. I'm not a linux expert :P

**Comment by Hamzailer** [comment]
Okay i figured it out it was just the prime drivers because when i tried the normal ones it worked
