### ISSUE TITLE
DPI Handling with Window Manager

### ISSUE THREAD

**Issue by antaxiom** [Kethku/neovide#351]
I'm on a HDPi display (4k) and I'm using a window manager (I know, small niche) and neovide is basically unusable it's at the size 1080p would be but on a 4k display so It's unredable. I haven't seen any font scaling but I may be missing something, please tell me if that's the case.

**Comment by Kethku** [comment]
you can specify the font size in the guifont. This effectively sets the zoom

**Comment by Kethku** [comment]
Some linux window managers don't interact with sdl's dpi reporting properly. So for those cases it the font scaling has to be done manually

**Comment by Kethku** [comment]
Can you tell me what platform you are running on so I can change the issue name to represent it?

**Comment by antaxiom** [comment]
> you can specify the font size in the guifont

I'm sorry where exactly would the be or what command is it?

> Some linux window managers don't interact with sdl's dpi reporting properly. So for those cases it the font scaling has to be done manually

yeah I'm used to that

**Comment by Kethku** [comment]
https://vim.fandom.com/wiki/Change_font

Neovide only supports the h{size} modifier currently

**Comment by antaxiom** [comment]
Ah but this would change the size in all situations for nvim, not just neovide, is there some kind of check I can make so this only runs on neovide?

**Comment by Kethku** [comment]
yes you can check if g:neovide is defined to specialize to it

**Comment by Kethku** [comment]
g:neovide is set to v:true on startup

**Comment by antaxiom** [comment]
Perfect, thanks if I end up using neovide I'll add it. Although I wish I could do the smooth cursor on the terminal. Thanks for all the hard work.

**Comment by Kethku** [comment]
I use the built in vim terminal emulator ;)

**Comment by Kethku** [comment]
Can you share details about your system so I can get a handle on what systems have the dpi issue?

**Comment by antaxiom** [comment]
I'm not sure exactly what to say other than I use the dwm window manager, I set my DPI using xrandr, and I run a 4k display.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
