### ISSUE TITLE
How do I start neovide maximised in Windows?

### ISSUE THREAD

**Issue by lucypero** [Kethku/neovide#356]
I have not found how to do this in the documentation, and the way to do it for `neovim-qt` does not work. Note that I do not mean `fullscreen`, I just want the window maximised.

**Comment by j4qfrost** [comment]
I'm actually surprised that we don't have any code around this. Do you have a preferred use case? I have a couple ideas on how to implement this, but it would be nice to know your workflow more for the PR.

**Comment by lucypero** [comment]
It could be a command argument like `neovide --maximized`. Or it could be set in one's `init.vim` or `ginit.vim` file.

For `neovim-qt`, what i do is write `call GuiWindowMaximized(1)` on `ginit.vim`.

**Comment by Kethku** [comment]
Yeah defining a function which maximizes the window on call seems like the best way to do this.

**Comment by j4qfrost** [comment]
I'm looking into an SDL solution right now. Passing --maximized is the
easiest way to do this. I think at some point we need to slow down feature
implementation though. The window code is getting a bit messy.

**Comment by Kethku** [comment]
I'm working on some significant refactoring that will help with that in my "multigrid" branch. Its not done yet though, but I agree. addressing the tech debt in both the window and the bridge are my next priorities after I merge multigrid

**Comment by j4qfrost** [comment]
@lucypero https://github.com/Kethku/neovide/pull/357 this allows --maximized to be used.

**Comment by j4qfrost** [comment]
Closing this issue, as I have made a quick hack. A better solution will hopefully present itself during a refactoring phase.

**Comment by hgup** [comment]
Hey there, I just learnt a little bit of vim-script for this. 
> Just paste it in your `init.vim` and source it.
> Then after you can press `F11` to toggle fullscreen mode.

*Here is how it goes:*

````
function Neovide_fullscreen()
    if g:neovide_fullscreen == v:true
        let g:neovide_fullscreen=v:false
    else
        let g:neovide_fullscreen=v:true
    endif
endfunction
map <F11> :call Neovide_fullscreen()<cr>
````
**Explanation:**
`g:neovide_fullscreen` is a neovide variable which is either `v:true` for fullscreen or `v:false` for the opposite.

We create a simple function called `Neovide_fullscreen`, and change `g:neovide_fullscreen` to `v:false` if `v:true` and vice versa.
*Hope it helps ;)*

**Comment by SpyrexDE** [comment]
> Hey there, I just learnt a little bit of vim-script for this.
> 
> > Just paste it in your `init.vim` and source it.
> > Then after you can press `F11` to toggle fullscreen mode.
> 
> _Here is how it goes:_
> 
> ```
> function Neovide_fullscreen()
>     if g:neovide_fullscreen == v:true
>         let g:neovide_fullscreen=v:false
>     else
>         let g:neovide_fullscreen=v:true
>     endif
> endfunction
> map <F11> :call Neovide_fullscreen()<cr>
> ```
> 
> **Explanation:** `g:neovide_fullscreen` is a neovide variable which is either `v:true` for fullscreen or `v:false` for the opposite.
> 
> We create a simple function called `Neovide_fullscreen`, and change `g:neovide_fullscreen` to `v:false` if `v:true` and vice versa. _Hope it helps ;)_

For me it says `g:neovide_fullscreen is a not defined variable` and `g:neovide_fullscreen == v:true is not a valid expression`. :/
Any idea?

**Comment by hgup** [comment]
> Thanks for the support, Hursh! I followed the instructions and now I've got the newest neovim .exe file, but it doesn't accept any inputs. Not even the windows close/maximize/minimize buttons are interactive anymore.

This shouldn't be happening though. @Kethku any thoughts?

**Comment by Kethku** [comment]
To be honest I don't have an idea what's going on here. I'm running win11 on my machine and it seems to work fine... What version of neovim do you have installed?

**Comment by SpyrexDE** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/57133330/136647239-17d5c043-f9c9-4335-a4e3-c1dfa3b962f9.png)

**Comment by sivaplaysmC** [comment]
> Closing this issue, as I have made a quick hack. A better solution will hopefully present itself during a refactoring phase.

pls share ur quick hack pls

**Comment by sisrfeng** [comment]
any update?  
Now I use autohotkey as a work around:
https://stackoverflow.com/questions/32397032/run-a-powershell-command-through-autohotkey-script

```ahk
        ~space & i::
            if WinExist("ahk_class Window Class")  {
                WinActivate, ahk_class Window Class
                            ; 用这个不行: ahk_exe neovide.exe
           }
            else{
                Run, PowerShell "neovide --remote-tcp=localhost:6602", , Max
            }
            ; WinMaximize, A
            return
```
