### ISSUE TITLE
Rectangles instead of letters.

### ISSUE THREAD

**Issue by omega16** [Kethku/neovide#363]
Hi. I'm changing from vim to neovim and choose neovide as gui but it renders rectangles instead of letters.
I'm using Arch linux and installed from AUR.
Installation was right, without error or warring (a big surprise since it compile 301 packages).
At launch it outputs:

```
INTEL-MESA: warning: ../mesa-20.1.7/src/intel/vulkan/anv_device.c:160: The kernel reported a GTT size larger than 2 GiB but not support for 48-bit addresses
```
But neovide opens and this is how it looks:
[![Deepin-Screenshot-Seleccionar-rea-20200917153817.png](https://i.postimg.cc/3J53WMKF/Deepin-Screenshot-Seleccionar-rea-20200917153817.png)](https://postimg.cc/QVb2nyKF)

I suppose neovide can't find my fonts or is something related to vulkan-intel package.

I don't have any config for neovide.

**Comment by j4qfrost** [comment]
Yeah, this looks like a Vulkan issue. Arch Linux is tricky to get right sometimes. What are your hardware specs and what does ```pacman -Ss vulkan``` give you?

**Comment by omega16** [comment]
That was fast (thanks!) 

I have a intel n3060 without dedicated graphics.
Here is the output of `pacman -Ss vulkan`

```
extra/amdvlk 2020.Q3.5-1
    AMD's standalone Vulkan driver
extra/nvidia-utils 450.66-1
    NVIDIA drivers utilities
extra/spirv-tools 2020.4-1 (vulkan-devel) [instalado]
    API and commands for processing SPIR-V modules
extra/vulkan-extra-layers 1.2.148.1+10736+3ce31c1c2-1 (vulkan-devel)
    Extra layers for Vulkan development
extra/vulkan-extra-tools 1.2.148.1+10736+3ce31c1c2-1 (vulkan-devel)
    Vulkan lunarg tools
extra/vulkan-headers 1:1.2.152-1 (vulkan-devel)
    Vulkan header files
extra/vulkan-html-docs 1:1.2.152-1 (vulkan-devel)
    Vulkan html documentation
extra/vulkan-icd-loader 1.2.151-1 [instalado]
    Vulkan Installable Client Driver (ICD) Loader
extra/vulkan-intel 20.1.7-1 [instalado]
    Intel's Vulkan mesa driver
extra/vulkan-mesa-layers 20.1.7-1
    Mesa's Vulkan layers
extra/vulkan-radeon 20.1.7-1
    Radeon's Vulkan mesa driver
extra/vulkan-tools 1.2.151-1 (vulkan-devel)
    Vulkan Utilities and Tools
extra/vulkan-validation-layers 1.2.146-2 (vulkan-devel)
    Vulkan Validation Layers
community/primus_vk 1.5-1
    Nvidia Vulkan offloading for Bumblebee
community/python-glfw 1.11.0-1
    Module for OpenGL, OpenGL ES, Vulkan, window and input support
community/vkd3d 1.1-1
    Direct3D 12 to Vulkan translation library By WineHQ
multilib/lib32-amdvlk 2020.Q3.5-1
    AMD's standalone Vulkan driver
multilib/lib32-nvidia-utils 450.66-1
    NVIDIA drivers utilities (32-bit)
multilib/lib32-primus_vk 1.5-1
    Nvidia Vulkan offloading for Bumblebee
multilib/lib32-vkd3d 1.1-2
    Direct3D 12 to Vulkan translation library By WineHQ
multilib/lib32-vulkan-icd-loader 1.2.151-1 [instalado]
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
multilib/lib32-vulkan-intel 20.1.7-1 [instalado]
    Intel's Vulkan mesa driver (32-bit)
multilib/lib32-vulkan-mesa-layers 20.1.7-1
    Mesa's Vulkan layers (32-bit)
multilib/lib32-vulkan-radeon 20.1.7-1
    Radeon's Vulkan mesa driver (32-bit)
multilib/lib32-vulkan-validation-layers 1.2.146-1
    Vulkan Validation Layers (32-bit)
```

**Comment by j4qfrost** [comment]
I jumped the gun, it might not related to vulkan actually. Though that was an error, not a warning. As for the rectangles, do you know what fonts you have installed? Also did you install neovide from the neovide package or neovide-git?

**Comment by omega16** [comment]
neovide 0.6.0-7 from [here](https://aur.archlinux.org/packages/neovide/) using pikaur.

After this I attempted to install neovide-git and it shows the missing dependence:
```
La nueva dependencia se instalará desde el repositorio:
 noto-fonts (por neovide-git)                               -> 20190926-4
```

So instead I did a `sudo pacman -S noto-fonts` and now works!

So, just to be curious, Can I change the font? How? 

Thanks for the help!

**Comment by j4qfrost** [comment]
Something like this ```set guifont=FiraCode\ Nerd\ Font\ Mono,Gulim,Yu\ Mincho,NSimSun:h16``` for the neovim config.

This issue goes over some of the problems we faced with setting font https://github.com/Kethku/neovide/issues/327.
