### ISSUE TITLE
Windows: neovide version

### ISSUE THREAD

**Issue by VladimirMarkelov** [Kethku/neovide#365]
I downloaded the binary from 0.6.0 releases, but in resources it states that it is 0.5.0.
Do releases contain correct binary?

Extra question: how to check neovide version? `neovide --version` does not show anything. Inside neovide `:version` shows neovim version.

Edit: a built-in `--help` to list all available options is good to have as well. I had to look through issues searching for "how to enable logging?"

**Comment by j4qfrost** [comment]
I'll look at adding this as a feature. For now you can get the most up-to-date build from the actions. https://github.com/Kethku/neovide/actions/runs/256882562

We are still trying to get the project in a stable state. There is a big merge incoming.

**Comment by VladimirMarkelov** [comment]
Thank you for the information. With the binary from action I see another trouble: I can run it only if the current directory is the directory where `neovim` is and only from `cmd`, in powershell console it does not run at all:

```
PS D:\> cd D:\Utils\neovim\bin\
PS D:\Utils\neovim\bin> d:/Utils/neovim/bin/neovide.exe --log
PS D:\Utils\neovim\bin> ls .\nvim.exe
    Directory: D:\Utils\neovim\bin
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------          1/9/2020   8:28 AM        4083712 nvim.exe

PS D:\Utils\neovim\bin> type .\neovide_rCURRENT.log
ERROR [neovide::bridge] nvim not found!
PS D:\Utils\neovim\bin>
```

So, `ls` shows `neovim.exe` but neovide cannot run it. Double-click in Explorer starts neovide successfully, but it is not sufficient. Going back to stable.

**Comment by j4qfrost** [comment]
Does it work with stable?

**Comment by VladimirMarkelov** [comment]
> Does it work with stable?

Yes. I added to FAR a menu item to open any file with neovide like `"d:\Utils\neovim\bin\neovide.exe" "!\!.!"` and have been using it for months. After replacing the old binary with a new one, my menu item stopped working. After a little investigation, I found out that neovide on my machine starts only from Explorer by double-click or from `cmd` when the current directory is `nvim` one.

**Comment by j4qfrost** [comment]
Does neovim exist in PATH? This may require someone with more Windows experience. @Kethku

**Comment by VladimirMarkelov** [comment]
> Does neovim exist in PATH?

No, it does not. 

On the other hand, it did not work even when the current directory was `neovim/bin` where neovim binary was. The strangest thing is that stable works great.

**Comment by j4qfrost** [comment]
When you say stable, you mean the binary from the release download right?

**Comment by VladimirMarkelov** [comment]
Yes. The latest from releases 0.6.0

**Comment by VladimirMarkelov** [comment]
Just downloaded from actions, the newest binary (from the younger action that passed). It works from current directory. So, it gets better, but from an arbitrary directory it still does not work.

**Comment by VladimirMarkelov** [comment]
Yes, maybe it is PATH-related. Just tried to set environment variable `NEOVIM_BIN` and it started to work

**Comment by VladimirMarkelov** [comment]
What if for Windows look for  `nvim` binary in the directory from which `neovide` has started?

Kind of:

```rust
// let's assume, previous `which::which` failed, so for Windows we do extra check after that
   let s = std::env::current_exe()
            .expect("Can't get the exec path")
            .parent()
            .expect("Can't get the directory");
   let nvim_dir = which::which_in( s );  // it is incorrect call, but I think, you get the idea
````

**Comment by j4qfrost** [comment]
The ```which``` function doesn't work if nvim isn't in your PATH, so it's a bit of a moot point.

FYI: you can get a permalink to a codeline, so it's easier to figure out what you're referencing. Just hover to the left of the code until three little dots show up and select permalink.

**Comment by VladimirMarkelov** [comment]
Sorry, I forgot about permalinks. Here it is the `else` I proposed to update for `windows` case:
https://github.com/Kethku/neovide/blob/b3729681d37a679412cff565809389dc560e5400/src/bridge/mod.rs#L77

I did not check how `nvim-qt` is implemented, but as it works fine from `nvim/bin` without changing `PATH` and wihout setting env variable, I supposed that besides `PATH`, it checks its starting directory for `nvim` binary as well.

**Comment by j4qfrost** [comment]
So if I understand correctly, you have built the neovide binary and moved it to neovim/bin where nvim lives, and neovide doesn't run because it can't find nvim?

**Comment by VladimirMarkelov** [comment]
> So if I understand correctly, you have built the neovide

No. I took it from latest successful github actions

**Comment by j4qfrost** [comment]
Did you try moving back to the old version?

**Comment by VladimirMarkelov** [comment]
> Did you try moving back to the old version?

Yes, after "nightly" version acted up, I redownloaded 0.6.0 and use it now.

**Comment by j4qfrost** [comment]
I don't have access to a Windows machine, and it sounds like your case is a bit unusual, so if you could check this branch for me https://github.com/j4qfrost/neovide/tree/issue-365 and verify that it works, I'll submit a PR.

**Comment by VladimirMarkelov** [comment]
I see, now if it fails to detect the binary by provided path, it uses default `nvim` (as if running from the current directory). On the one hand, it may work. On the other hand, the current working directory is not `nvim` one, so it may fail in the same way. 

I wanted to download a new binary but it seems github action fails for some reason.

**Comment by j4qfrost** [comment]
Forgot to fetch upstream. A binary should be building now. Give me a heads up when you try it out. The change I made basically adds back similar functionality to what we had before but specifically for Windows.

**Comment by VladimirMarkelov** [comment]
```diff
- return Some("nvim");
+ return Some(Command::new("nvim"));
```
?

**Comment by j4qfrost** [comment]
Yup, thanks for the catch.

**Comment by j4qfrost** [comment]
Double checked. This won't fix your issue. One sec.

**Comment by j4qfrost** [comment]
@VladimirMarkelov I think this should solve your problem now. I wasn't reading my own error messages correctly.

**Comment by VladimirMarkelov** [comment]
I've get binary when it build and try it

**Comment by VladimirMarkelov** [comment]
It seems working. Thanks!

**Comment by Kethku** [comment]
This has been fixed

**Comment by sharpchen** [comment]
never mind, works in 0.13.3
