### ISSUE TITLE
Windows 10 + Sleep mode

### ISSUE THREAD

**Issue by VladimirMarkelov** [Kethku/neovide#367]
I know a new version is coming and it may be already fixed in the master, but it is true for the current stable release 0.6.0.

I do not power off my laptop when I am done. I minimize most of the applications(including `neovide`) and close laptop's lid. Default action in power management for this is 'Sleep'. Most of the time after opening the lid, `neovide` restores its window without any issue. Once in a while (maybe once in 2-3 weeks), `neovide` "refuses" to restore its windows. When switching with `Alt+Tab`, it looks like the window is zero size(no window preview in Alt+Tab list) or somewhere outside the screen. So, the only way to fix it is to make `neovide` active, blindly type ":q" a few times until all files are closed and `neovide` exits. Then start `neovide` again.

Due to the trouble is random and rare, I am unsure how to reproduce it easily.

**Comment by Kethku** [comment]
Interesting. Maybe it has to do with the dpi? I haven't encountered this before.

**Comment by VladimirMarkelov** [comment]
Maybe even not once in 2-3 weeks, maybe once in 1-2 months. 

As of dpi, I use 100% scaling (it looks like DPI=127:  1920x1080 - 17.3'').

**Comment by benwainwright** [comment]
> blindly type ":q" a few times until all files a blindly type ":q" a few times until all files are closed re closed

You are aware that you can do `:qa` to quit everything and `:qa!` to quit everything regardless of save status?

**Comment by VladimirMarkelov** [comment]
> You are aware that you can do :qa to quit everything and :qa! to quit everything regardless of save status?

Thanks, I did not know about it(or I forgot about it) as I rarely need to exit vim/neovim with closing everything immediately. When having two splits, typing `:q<enter>` twice vs `:qa<enter>` once is not a big difference.

**Comment by f6ll** [comment]
how did you get it working on windows, i couldn't work it

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
