### ISSUE TITLE
Cannot build on void linux

### ISSUE THREAD

**Issue by xa888s** [Kethku/neovide#371]
Since this crate depends on openssl, the build fails when it can't find openssl.

**Comment by xa888s** [comment]
Looking in cargo tree, apparently skulpin depends on openssl-sys

**Comment by xa888s** [comment]
Offending line:
https://github.com/rust-skia/rust-skia/blob/277d86cdea5a30022d39c6411a3e9d7579a8d3d3/skia-bindings/Cargo.toml#L62

**Comment by Kethku** [comment]
Its likely a build time dependency

**Comment by j4qfrost** [comment]
https://github.com/rust-skia/rust-skia/pull/426 take it upstream @xa888s

**Comment by j4qfrost** [comment]
@xa888s I am curious as to why you don't want to install openssl.

**Comment by xa888s** [comment]
Void Linux does not provide an OpenSSL package, and they provide reasoning here: https://voidlinux.org/

```
LibreSSL
We were the first distribution to switch to LibreSSL by default, replacing OpenSSL.

Due to the Heartbleed fiasco, we believe that the OpenBSD project has qualified and pro-active developers to provide a more secure alternative.
```

**Comment by Kethku** [comment]
I'm reopening this as it seems that other folks are struggling with the openssl support. Seems like the upstream has been merged in. I'll look to see if its a feature flag we can just use

**Comment by Kethku** [comment]
Yeah looks like it should be supported by default. SO I guess I'm closing again
