### ISSUE TITLE
[Question] What is the style/name of the airline in README.md

### ISSUE THREAD

**Issue by TENX-S** [Kethku/neovide#375]
Sorry for the noise. 
I just like the airline style in the README, can someone tell me its name or how to get it?
Thanks a lot!

**Comment by Kethku** [comment]
Its my personal config :P

Its written in fennel here: https://github.com/Kethku/vim-config/blob/master/fnl/dotfiles/module/settings.fnl
The airline and tabline settings are at the top of that file.
The colorscheme is https://github.com/morhetz/gruvbox
The font is delugia code https://github.com/adam7/delugia-code/releases
