### ISSUE TITLE
Powerline font was rendered incorrectly, so does the Chinese

### ISSUE THREAD

**Issue by TENX-S** [Kethku/neovide#376]
OS: macOS 10.15.7
Neovide: Build from source(rustc 1.48.0-nightly (d006f5734 2020-08-28))

* Can't render powerline font (right pane/airline)
<img width="1440" alt="Screen Shot 2020-10-07 at 11 27 27 PM" src="https://user-images.githubusercontent.com/40336192/95352296-af3d3a80-08f4-11eb-9aee-3e936f86c489.png">

* Can't render chinese character (line 8 13 14)
<img width="1440" alt="Screen Shot 2020-10-07 at 11 29 39 PM" src="https://user-images.githubusercontent.com/40336192/95352694-0e02b400-08f5-11eb-8ddd-05cd59706b09.png">

There is no such problem if I switch to iTerm2(But I'd love to use Neovide, it looks amazing!)

Here's my configuration files (I'm new to vim)
* $HOME/.vimrc
```shell
syntax on
execute pathogen#infect()
filetype plugin indent on


set nu
set hidden
set mouse=a
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=3
set encoding=UTF-8
set guifont=Fira\ Code\ Retina\ Nerd\ Font

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()


autocmd vimenter * NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let g:NERDTreeWinPos="right"
let g:airline_powerline_fonts = 1


let mapleader=','
inoremap jj <Esc>`^

map <C-t> :NERDTreeToggle<CR>
```

* $HOME/.config/nvim/init.vim
```shell

autocmd vimenter * colorscheme gruvbox
set background=dark
syntax enable
filetype plugin indent on


let g:gruvbox_bold = 0
let g:gruvbox_italic = 0
let g:gruvbox_italicize_comments = 0
let g:gruvbox_italicize_strings = 0
let g:gruvbox_contrast_light = "soft"

let g:neovide_no_idle = v:true
let g:neovide_transparency = 1.0
let g:neovide_fullscreen = v:true
let g:neovide_refresh_rate = 144
let g:neovide_cursor_vfx_mode = "torpedo"


set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

**Comment by benwainwright** [comment]
I get the same problem

**Comment by benwainwright** [comment]
A scratch that - it just wasn't reading my `.gvimrc`, so I moved `set guifont` into my main vimrc

**Comment by TENX-S** [comment]
> I get the same problem

The [Delugia Nerd Code](https://github.com/adam7/delugia-code/releases) works.
But I'm trying to set two fonts Fira Code Retina and Nerd Font to show the code and powerline symbols, respectively.

**Comment by Kethku** [comment]
You have to specify a font which contains those glyphs. Unfortunately neovide does not have a way to use the system's font fallback, so you have to specify it manually via the guifont option inside of neovim.

Neovide has an extension that lets you specify a list of fonts as a sort of manual fallback. You do it by separating the font names by commas in the guifont setting.
