### ISSUE TITLE
failed to parse manifest 

### ISSUE THREAD

**Issue by benwainwright** [Kethku/neovide#377]
Hi there

In trying to test the fix for https://github.com/Kethku/neovide/issues/368, I'm now getting a different error that seems to be unrelated. The following is from a fresh clone of the repository:

![image](https://user-images.githubusercontent.com/3321885/95451069-2b6c6800-095f-11eb-82e8-0cb0f7517e9c.png)

**Comment by j4qfrost** [comment]
It's all cleaned up. Sorry for the chaos.
