### ISSUE TITLE
Support for navigation keys?

### ISSUE THREAD

**Issue by Jaimeloeuf** [Kethku/neovide#386]
Hello, this is a feature suggestion/question.

Is navigation keys (home/end/PageUp/PageDown) supported to jump around the text in both normal and insert mode?

I understand that when using (n)vim these keys should be avoided and are not considered "standard" but as a long time user of other editors like sublime and vs code where they are not modal editors, it seems much easier to transition if we could keep as least some of the navigation keystrokes that have become muscle memory for most people.

Comparing to other similar projects, this works for both neovim-qt and fvim, so perhaps it is a difference in the underlying window lib used? Am not too sure too. The behaviour of these keys are the same in both of these alternatives. Let me know if a Gif is needed.

If this does not exist yet, I would love to help implement it if needed, but might need some guidance on that, as I am fairly new to rust/nvim/windows development 😅

Thanks for your time 🙏🏻

**Comment by Kethku** [comment]
Hmmm. This appears to be working on my machine. Pressing home sends the cursor to the beginning of the line, end sends it to the end in normal and insert mode. Similarly pressing pagedown scrolls the screen down.

Can you give some details about your OS? I suppose its possible that non windows versions of the window system don't handle those keybindings properly.

**Comment by Kethku** [comment]
Closing as it seems like this isn't an issue on our side.
