### ISSUE TITLE
'{' in insert mode act like in normal mode.

### ISSUE THREAD

**Issue by GGCristo** [Kethku/neovide#388]
When I try to write '{' it behave like '{' in normal mode, this mean that it leaves Insert mode and go one paragraphs backward.
Edit : Others keys like '\' doesn't work either.

**Comment by nilsmartel** [comment]
I have the same problem.

Using a MacBook Pro 2019 with German keyboard Layout.

The `"` character works fine for me, but neither `{`, nor `}` can be entered into text

**Comment by nilsmartel** [comment]
just checked, the combination option/alt ⌥ + any other key seems to fail, no characters get inserted, the editor jumps into normal mode

**Comment by keithsim-msft** [comment]
What keyboard layout do you folks use?

**Comment by Kethku** [comment]
what keyboard layout do you folks use? This feels like a layout issue

**Comment by Kethku** [comment]
Currently we have infrastructure for specifying more keyboard layouts here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/sdl2.rs but today we only have qwerty mostly because I haven't spent the time to add more

The hope is that we can add common layouts and then let users configure them via a global vim variable. Its not the nicest solution, but as far as I can tell its the best we've got with Rust windowing systems.

**Comment by GGCristo** [comment]
As you would have expected, I use the Spanish layout.

**Comment by nilsmartel** [comment]
Thanks for the quick answer, it's German Mac Layout for me

**Comment by nilsmartel** [comment]
Only thing I could figure out so far is, that characters like `{` don't even get propagated to that handler function

**Comment by nilsmartel** [comment]
to be continued

**Comment by nilsmartel** [comment]
I did some science and figured out that English keyboard layouts (which are heaven to work with for programming tasks, you wouldn't believe just how bad German is at this actually) get's recognised like this:

```
keycode: LeftBracket
keytext: "{"
``` 

where in the German layout the key get's recognised as

```
keycode: Num8
keytext: "{"
```

Now, here's why this is fantastic news:

I think the most straightforward thing to do is not creating individual handlers for all layouts, but a simple function `fn (KeyCode, KeyText) -> (KeyCode, KeyText)` that can be used to unify across all keyboards at this point.

a simple implementation might be
```rust
fn unify_layouts(code: KeyCode, text: &str) -> (KeyCode, &str) {
 match (code, text) {
   (_, "{") => (LeftBracket, "{")
  ...
   (code, text) => (code, text)
 }
}
```

**Comment by nilsmartel** [comment]
part of the problem lies in `append_modifiers`.
On German keyboards the keytext is proper, but the alt key is set to true
Result of calling the method is (for example) `"<M-{>"` where `"{"` is to be expected

**Comment by nilsmartel** [comment]
So far I've got a dumpfuck solution, but the problem pinned down.
So, what I did is create this method:

```rust
fn discard_alt(text: &str) -> bool {
    match text {
        "¡" | "“" | "¶" | "¢" | "[" | "]" | "|" | "{" | "}" | "≠" | "¿" => true,
        _ => false,
    }
}
```

Which returns true for all inputs _on the num pad_ where I'd have to press alt (and alt only).
In the function `produce_neovim_keybinding_string` I've modified the `alt` variable like this: 
```rust
let alt = alt & !discard_alt(&text);
```
meaning alt gets set to false if one of these special keys gets recognised.

Of course this breaks as soon as I use any character not in the numpad or include the shift key, but for today it's good enough. (== Good enough so I can continue editing this inside neovide itself. Nice)

**Comment by nilsmartel** [comment]
I don't know much about this, but would it work to simply set alt and shift to false for all non-standard characters? 
E.g. `keytext`∉ ElementsWhichCanBeAccessedWithoutAlt ?

Nah... On English keyboards on doesn't even need to press alt to reach {, but COULD in theory by using alt-8

**Comment by Kethku** [comment]
I think the way to fix this is to introduce a new layout in the place I linked above? We can't rely on the OS to handle turning key codes into characters for us, so we have to make an exhaustive list for each keyboard layout. At least this is the best I've come up with which works the same on all operating systems.

The layout for qwerty is defined here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/sdl2.rs. For your layout I would do the same thing but name the function for your keyboard layout. Then I would add an entry to this enum https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L26 for your layout, add a debug writeout here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L32, add a string version here: https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L44, and add a match case here https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L116 and here https://github.com/Kethku/neovide/blob/master/src/bridge/layouts/mod.rs#L147

This way you can then set the layout property in your init script and you should be golden. Does that make sense?

**Comment by Kethku** [comment]
That said, I would LOVE a solution which doesn't require an exhaustive list like the qwerty layout. I've just spent a fair bit of time ramming my head through this particular wall and then gave up. A fresh set of eyes very well might see a solution I missed though

**Comment by Kethku** [comment]
Btw the purpose of that handler function is to take non "complex" characters, modify them via whatever modifiers are past in, and return the correct "complex" character. The idea is that rather than relying on an OS method to do this conversion (which we don't have access to because the winnit and sdl are limiting), we have to do the conversion manually.

**Comment by nilsmartel** [comment]
I see the problem and I think you're about right. Though the current check doesn't call these handler functions, since `keytext ≠ None`. Unsure about the proper way to introduce this in first place, because the problematic inputs don't rely on the querty handler function so far. I feel like I am missing something obvious here, but a keyboard layout might well be the answer.

By the way, thanks for these very friendly replies

**Comment by ref209** [comment]
I have been testing this issue and I found that the problem resides in how the Right Alt key is handled. 

In case of many European countries, the keyboard doesn't has a Right Alt key but an Alt Gr. Sadly, for sdl2 the Mod code is the same: RALTMOD.

In `src/window/sdl2/layouts.mod.rs` there is a function that transforms sdl2's Mod struct to the local Modifiers struct, and it's there when Alt Gr it's marked as a meta key, when in this case it shouldn't.

I tested this by removing RALTMOD from being considered as a meta modifier and it worked perfectly with a Spanish keyboard on Linux.

```
impl From<Mod> for Modifiers {
    fn from(mods: Mod) -> Modifiers {
        Modifiers {
            shift: mods.contains(Mod::LSHIFTMOD) || mods.contains(Mod::RSHIFTMOD),
            control: mods.contains(Mod::LCTRLMOD) || mods.contains(Mod::RCTRLMOD),
            meta: mods.contains(Mod::LALTMOD),
            logo: mods.contains(Mod::LGUIMOD) || mods.contains(Mod::RGUIMOD),
        }
    }
}
```
I understand that this will break the right alt key in some other layouts (US), but I think that creating a different layout per language it's maybe too extreme. I tested it with the Spanish Dvorak and qwerty layout and it works in both cases, probably on other European languages too. 

I am not an expert on this subject, but maybe there is a way to detect if the keyboard has an Alt Gr key (ANSI/ISO) and set the meta attribute only when necessary.

**Comment by Kethku** [comment]
Interesting. I personally don't use the right alt key ever, but I imagine some people do. Maybe a quick fix to unblock folks would be to introduce a vim setting which toggles this behavior until we get a fix upstream?

**Comment by takd** [comment]
I had a similar problem on a Hungarian layout, the `#` symbol needs to be input as AltGr+X. @ref209's modification does solve the problem.

**Comment by Kethku** [comment]
I believe this is fixed in main. Please reopen if not.

**Comment by GGCristo** [comment]
Testing it out a little, it looks like it works fine. Thanks
