### ISSUE TITLE
tabp/tabn breaks neovide

### ISSUE THREAD

**Issue by SkyLeach** [Kethku/neovide#392]
I'm not really sure at this point what is going on, but my best guess is that somehow this is breaking the Rust UI access to the Neovim session.  `gT/gt` seem fine, as is `[0-9]{2.0}gt`

**Comment by SkyLeach** [comment]
Managed to break it without `tabp/tabn` and I've managed to get a warning with `tabp` that makes me think the problem may be related to memory.  Here it si locking up with UltiSnips:

![image](https://user-images.githubusercontent.com/940228/97196304-b2547980-1782-11eb-9d4f-df6da8e72993.png)

I'll try to get a ss of the warning message next time.

**Comment by Kethku** [comment]
I'm not sure I understand. What do you mean it breaks neovide. What happens when you do that?

**Comment by Kethku** [comment]
I'm closing this due to lack of response
