### ISSUE TITLE
Not responding after resume from suspend

### ISSUE THREAD

**Issue by cdfa** [Kethku/neovide#393]
Hi, thank you for this beautiful Neovim client!

I'm having a weird issue where Neovide does not respond anymore after my laptop resumes from sleep. I'm happy to help debugging, but I don't really know where to start.

Some basic info:
Neovide version: 0.6.0.r32.g0203d02
`uname -or`: 5.4.72-1-MANJARO GNU/Linux

**Comment by Kethku** [comment]
Hmmm. I'm not sure what would be causing this. Is it consistent every time you resume from sleep? This seems like an upstream issue in Skulpin

**Comment by cdfa** [comment]
Yup 100% consistent. When you responded I thought maybe the problem is that I prevent neovide from blocking compositing with a KWin rule, but the only difference is that the window is completely black instead of showing the contents from before suspend, so I don't think it had anything to do with it.

Anyway, I'll create an issue upstream.

**Comment by Kethku** [comment]
I think it may be smart for us to create a minimum viable repro of the issue. For instance I'd be curious if the demos in skulpin exhibit the same issue when using sdl2 window

**Comment by Kethku** [comment]
Cause if the answer is no, it may be something we are doing strangely on our side

**Comment by cdfa** [comment]
Good idea! I just tried it and it happens with on of their examples too. (see my comment in the skulpin issue)

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.

**Comment by cdfa** [comment]
I checked and it's fixed! How did you do it?

**Comment by Kethku** [comment]
We swapped to winit, reworked the renderer to use opengl, and reworked all of the window event management.

**Comment by cdfa** [comment]
Wow, sounds like a lot of work. Thank you!
