### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by 4ydx** [Kethku/neovide#395]
Just displays an entirely blank screen.

- Debian GNU/Linux 10 (buster)
- rustc 1.47.0 (18bf6b4f0 2020-10-07)
- neovide c47c235a961d82316def38222b8a1af2cff523d5

**Comment by TamaMcGlinn** [comment]
Same here; no error message either. Neovide only outputs:

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

The window manager shows that a window has been opened, but nothing was drawn to it.

I'm also on debian buster, using rustc 1.48.0 and the same neovide commit.

**Comment by j4qfrost** [comment]
Can you both post your GPU specs and vulkan info? I'll be back next week to
take a look.

**Comment by 4ydx** [comment]
OpenGL version string: 4.6.0 NVIDIA 418.152.00
VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 980] (rev a1)

[vi.txt](https://github.com/Kethku/neovide/files/5635514/vi.txt)

**Comment by tarunzoot** [comment]
can you please try to run `neovide -u NONE` and see if it works

**Comment by Kethku** [comment]
Maybe I'm silly, but I don't know what -u NONE does. @tarunzoot any help?

**Comment by tarunzoot** [comment]
when I was looking into the bug 281, I got a blank screen too. in that bug
neovim exited, and a blank screen was all that remained, so -u NONE just
starts nvim by not using default neovim config. I just want to see if
neovim is exiting prematurely or not. if that is the case we will for sure
know what is the problem.

**Comment by lafleurdeboum** [comment]
Hello, just to mention, I had the same issue, installing `noto-fonts` solved it for me.

Running on Arch latest, using neovide 0.6.0-8, noto-fonts 20201206-1. Hope it helps.

**Comment by Kethku** [comment]
I think this issue can happen if neovim requires input before the first screen is displayed

I'm not sure why that would happen, but -u NONE does seem like a good choice to see if that fixes the problem. If it does then the startup logic needs reworked.

**Comment by x37v** [comment]
> Hello, just to mention, I had the same issue, installing `noto-fonts` solved it for me.
> 
> Running on Arch latest, using neovide 0.6.0-8, noto-fonts 20201206-1. Hope it helps.

on ubuntu I had the same issue and resolved it with `sudo apt install fonts-noto`

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.

**Comment by nonetrix** [comment]
I am having this issue 
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
```

I already have noto-fonts on my install
