### ISSUE TITLE
Neovide won't show some symbols & characters

### ISSUE THREAD

**Issue by ReneganRonin** [Kethku/neovide#396]
- Some symbols and characters in neovide (left) are not showing. Using neovim on the terminal (right) however shows it correctly.
![image](https://user-images.githubusercontent.com/66054069/98944986-d9ee6480-252c-11eb-89e3-d6e4ab11b6ca.png)
- Fonts used during the session is FantasqueSansMono Nerd Font. I tried out using other fonts and Nerd Fonts but they do not work as well.

More information:
- Running on Manjaro i3 using 5.10.0-1-MANJARO kernel
- CPU: Intel Pentium N3530 (4) @ 2.582GHz 
- GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display 
- GPU: NVIDIA GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M

**Comment by Kethku** [comment]
This is a font fallback issue. Closing in favor of https://github.com/Kethku/neovide/issues/444
