### ISSUE TITLE
sdl 0.34.3 vs 0.34.2

### ISSUE THREAD

**Issue by uhuntu** [Kethku/neovide#397]
Hi there,

I realized that recently you rollback sdl from 0.34.3 to 0.34.2, what's happening ?

--
hUNt0

**Comment by j4qfrost** [comment]
https://github.com/Kethku/neovide/issues/368

**Comment by uhuntu** [comment]
Then what should I do if I want to input CJK in Linux ? https://github.com/Kethku/neovide/pull/360

**Comment by j4qfrost** [comment]
Is it only fixed in 0.34.3? We should handle it upstream.

**Comment by uhuntu** [comment]
Yes, https://github.com/Rust-SDL2/rust-sdl2/pull/1027

**Comment by uhuntu** [comment]
Okey, probably we need to wait 0.34.4

**Comment by j4qfrost** [comment]
Yeah, this probably needs to be handled upstream :/ sorry about the quick
close.
