### ISSUE TITLE
why not suppport gbk charset

### ISSUE THREAD

**Issue by paopaol** [Kethku/neovide#400]
![neo](https://user-images.githubusercontent.com/6983082/100947105-e409ee80-353f-11eb-85b6-c41204e47110.png)
![veoide](https://user-images.githubusercontent.com/6983082/100947112-e79d7580-353f-11eb-9e33-e685efa4301c.png)

**Comment by Kethku** [comment]
gbk charset is supported. But font fallback has to be done manually. You can specify a font which the desired characters in the guifont setting by separating the font names in the fallback list by a comma

**Comment by paopaol** [comment]
> gbk charset is supported. But font fallback has to be done manually. You can specify a font which the desired characters in the guifont setting by separating the font names in the fallback list by a comma

how can i do this
