### ISSUE TITLE
Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)'

### ISSUE THREAD

**Issue by intendednull** [Kethku/neovide#401]
Unable to start on manjaro:
```
$ neovide
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window.rs:156:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I suspect it has something to do with my wm xmonad.

**Comment by issadarkthing** [comment]
I experience the same issue with same wm (xmonad)

**Comment by Kethku** [comment]
Can you give some details about your machine? Do you have an integrated and discrete gpu? Could be that neovide is trying to use the integrated gpu to save power but is running into driver issues for that device.

**Comment by intendednull** [comment]
@Kethku using discrete gpu, don't think I have integrated.
```
 OS: Manjaro 20.2 Nibia
 Kernel: x86_64 Linux 5.8.18-1-MANJARO
 WM: XMonad
 CPU: AMD Ryzen 7 1700X Eight-Core @ 16x 3.4GHz
 GPU: GeForce GTX 1070 Ti
```

**Comment by issadarkthing** [comment]
```
OS: Artix Linux x86_64
Kernel: 5.9.14-artix1-1
WM: XMonad
CPU: Intel i5-8265U (8) @ 3.900GHz
GPU: Intel UHD Graphics 620
```

**Comment by Kethku** [comment]
Very interesting. Do the skulpin examples here https://github.com/aclysma/skulpin work?

**Comment by intendednull** [comment]
[they do not](https://pastify-app.web.app/show/KsHa95DXSJF6B8Za98S5)

**Comment by intendednull** [comment]
Okay this seems to be an issue with vulkan. Switching to proprietary drivers fixed the issue.

**Comment by Kethku** [comment]
awesome. Closing this

**Comment by fuelen** [comment]
I had the same problem on Arch Linux, installing `vulkan-intel` package solved the issue
