### ISSUE TITLE
pressing n-dash (option+minus) crashes neovide on macos

### ISSUE THREAD

**Issue by kiil** [Kethku/neovide#403]
Pressing '–' (that is an n-dash symbol - in my case from option + minus (minus is also sometimes called hyphen)) causes neovide to immediately crash.

Then this error is given in the terminal from which neovide was started

> thread 'tokio-runtime-worker' panicked at 'Input failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_input")', src/bridge/ui_commands.rs:39:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(I get the same crash when starting the program directly from its icon)

**Comment by lattenwald** [comment]
Same, crashes on m-dash or n-dash on Linux.

Terminal shows

```
thread 'tokio-runtime-worker' panicked at 'Input failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_input")', src/bridge/ui_commands.rs:39:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: segmentation fault (core dumped)  neovide
```

Not sure if related, but when pressing `«` or `»` , it just exits insert mode.

**Comment by Kethku** [comment]
Thats wild. I don't even know how to produce such a character on my windows box

The message linked feels like a neovim protocol thing...

**Comment by Kethku** [comment]
This should be fixed in main
