### ISSUE TITLE
Window Clearing

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#41]
Sometimes remnants of popup windows are kept around. I'm not sure what causes this, but this shouldn't happen.

This will be fixed with the multigrid support in the future, but it is indicative of an algorithm problem.

**Comment by jonvaldes** [comment]
I've seen similar things when autocompleting with <Tab>. Sometimes the autocompletion doesn't show up, and it just shows a dot for each character. Sounds like it could be a clearing issue too?
Example:
![image](https://user-images.githubusercontent.com/48644/73435794-9cc43780-4349-11ea-9d20-05f554c45863.png)

**Comment by Kethku** [comment]
Closing in favor of https://github.com/Kethku/neovide/issues/86
