### ISSUE TITLE
Polish characters

### ISSUE THREAD

**Issue by Grzanka99** [Kethku/neovide#412]
It's impossible to insert polish characters in insertmode. You or have to replace for example `L` with `Ł` or use console version of nvim. I realy would like to insert characters from my language ;P. Typing `Ł` (right-alt + shift + l) exits insert mode. same with most other polish characters.

**Comment by agraven** [comment]
I have the same issue with any character that requires holding down `AltGr` to enter (which includes things like \ on a danish keyboard layout)

**Comment by Kethku** [comment]
This is a repeat of https://github.com/Kethku/neovide/issues/151
