### ISSUE TITLE
Command Arguments

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#413]
Currently command arguments are processed adhoc wherever needed by pulling the argument list and filtering it in each location.

This is inefficient and requires listing the arguments in multiple places which isn't great. I'd like to make a single place which does the command line argument filtering all at once and provides a struct with properties for each argument.

Similarly it would be nice to expose an optional environment variable which will set the value for the command line arguments permanently without having to pass them in. Ideally all of the arguments (aside from information arguments) would have these equivalent variables.

**Comment by ErikMayrhofer** [comment]
Is this resolved by #680?
