### ISSUE TITLE
Cannot enter Korean

### ISSUE THREAD

**Issue by GG-O-BP** [Kethku/neovide#415]
![스크린샷, 2020-12-25 21-58-35](https://user-images.githubusercontent.com/36529903/103135658-1650db00-46fd-11eb-82b9-1cbc432d903a.png)

**Bug contents**
When inputting with iBus-hangul, input cannot be switched and always input only in English.
In neovim it works fine.

**keyboard Input**
iBus-hangul

**OS**
ubuntu 20.10

**version**
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9/build/config -I/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9/src -I/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9/build/src/nvim/auto -I/build/neovim-5OF80e/neovim-0.5.0+ubuntu2+git202011201114-480b04122-d569569c9/build/include
Compiled by buildd@lcy01-amd64-023

**Comment by Kethku** [comment]
I'm closing this in favor of https://github.com/Kethku/neovide/issues/445
