### ISSUE TITLE
Error compiling for linux

### ISSUE THREAD

**Issue by QuinnFreedman** [Kethku/neovide#42]
When I compile on Linux (Ubuntu 19.10 Gnome) it successfully compiles a long list of dependencies but eventually gets stuck with:

```
error: failed to run custom build command for `atk-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/home/quinn/neovide/target/release/build/atk-sys-268e6b6307e121eb/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "atk" "atk >= 2.4"` did not exit successfully: exit code: 1
--- stderr
Package atk was not found in the pkg-config search path.
Perhaps you should add the directory containing `atk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atk' found
Package atk was not found in the pkg-config search path.
Perhaps you should add the directory containing `atk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atk' found
```
Is there an extra step I need to do to make sure atk is installed? I don't have the `PKG_CONFIG_PATH` variable set. It seems like I could just set it to point to this `'atk.pkg'` file, but I don't know where it is and/or how to download it.

**Comment by Kethku** [comment]
I'm investigating now. First step is figuring out why it got included

**Comment by Kethku** [comment]
Ok looks like the msgbox library I use requires gtk. The instructions [here](https://github.com/bekker/msgbox-rs) say to install it via `libgtk-3-dev`. Can you try that? I will also add a compiler flag which compiles without it.

**Comment by QuinnFreedman** [comment]
`sudo apt install libgtk-3-dev` first fixes the problem. Thanks!

**Comment by Kethku** [comment]
Beautiful. Adding it to the instructions.
