### ISSUE TITLE
Blurry font, possibly because of scaling?

### ISSUE THREAD

**Issue by kirawi** [Kethku/neovide#424]
![Capture](https://user-images.githubusercontent.com/67773714/103329052-17e61000-4a29-11eb-8736-f3a836b31be6.PNG)
![Capture1](https://user-images.githubusercontent.com/67773714/103329057-1a486a00-4a29-11eb-893e-01eaa9f97045.PNG)

Neovide vs. Neovim-qt

I'm using Windows 10, with a custom scaling size of 125% (inside 'Advanced scaling settings'), and building neovide from `c63b054`.

**Comment by Kethku** [comment]
If you temporarily set the scaling to 100% does it look better? I think I messed up dpi scaling on master with my most recent refactor

**Comment by kirawi** [comment]
I'll check in a few hours, but on my main desktop that has no scaling, it looks absolutely fine.

**Comment by Kethku** [comment]
Yeah looks like scaling is screwed up. I'm investigating
