### ISSUE TITLE
Switch default branch to Main

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#425]
I would like to switch our main branch away from using master to instead use a branch called main.
@peeweep I think this would require a change to the AUR package which you created. Can I help swap it in some way? Other than that I don't think there are any other dependencies on the master branch so I can make the change whenever.

**Comment by peeweep** [comment]
OK we can switch to special branch like `smooth-scrolling` in PKGBUILD like this:
``` diff
diff --git a/PKGBUILD b/PKGBUILD
index 99f2b2b..efc8a47 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,7 +3,7 @@
 # Contributor: peeweep <peeweep at 0x0 dot ee>
 
 pkgname=neovide-git
-pkgver=0.6.0.r15.gd406cf6
+pkgver=0.6.0.r63.g5667515
 pkgrel=1
 pkgdesc='No Nonsense Neovim Client in Rust'
 arch=('x86_64')
@@ -13,7 +13,7 @@ depends=('neovim' 'fontconfig' 'freetype2' 'libglvnd' 'sndio' 'noto-fonts')
 makedepends=('git' 'rust' 'gtk3' 'cmake' 'sdl2' 'make')
 provides=("neovide")
 conflicts=("neovide")
-source=("${pkgname}::git+${url}")
+source=("${pkgname}::git+${url}#branch=smooth-scrolling")
 sha1sums=('SKIP')
 
 pkgver() {
```
Also you can set the default branch to `main`, then PKGBUILD does not need to be modified.

**Comment by peeweep** [comment]
@Kethku If you need me to specify a branch, please mention me here.

**Comment by Kethku** [comment]
Beauty. Done. Thanks for the help!
