### ISSUE TITLE
Minimap for active buffer

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Kethku/neovide#429]
There already exists [minimap.vim](https://github.com/wfxr/minimap.vim) which uses[code-minimap](https://github.com/wfxr/code-minimap) but I think neovide could probably do a better job at rendering. The minimap.vim plugin currently makes all lines except the currently line one color and the current line another color.

**Comment by Kethku** [comment]
In general I feel like this should be a plugin rather than a top level feature like some other guis implement. I have some ideas for how I might expose a drawing api to vim so that plugins could be implemented with vector graphics output to a given window, but I think this is a ways out.

**Comment by Th3Whit3Wolf** [comment]
That sounds awesome! Can't wait for that feature.

**Comment by ogios** [comment]
how was it, has it been added?
