### ISSUE TITLE
Option for disabling animations in insert mode, or possibly based on distance

### ISSUE THREAD

**Issue by jberryman** [Kethku/neovide#431]
When typing in insert mode I don't love the way the cursor moves smoothly. It would be nice to be able to disable animation when in insert mode, or perhaps based on some approximate pixel or character-based distance (e.g. no animation if cursor jumps less than 5 characters).

similar ticky-tack animation issue: https://github.com/Kethku/neovide/issues/341

Thanks!

**Comment by Kethku** [comment]
There is some code today which tries to remove animations when in insert mode. I'm confused why that isn't working. I have reproed on my local build so I think this is just a bug.

**Comment by jberryman** [comment]
(thanks for your responsiveness; I'm new to Rust and also swamped setting up a new machine, etc. but aspire to be contributing patched to neovide for issues like this)

**Comment by rnevius** [comment]
I'm also new to Rust, but would at least like to see if I can play around with a solution... @Kethku can you point us in the direction of the current code you mentioned?

**Comment by Kethku** [comment]
Neovide now changes the animation speed based on the distance of the jump. I think that closes this in a satisfactory way.
