### ISSUE TITLE
[Wiki] replace `--multigrid` with `--multiGrid`

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#435]
The wiki says to use `--multigrid` parameters but it's actually `--multiGrid`.
I had to check the code to figure it out, I think it can be great to update it soon.
Though about editing myself but we can't make PR on the wiki right ?
Also, up for #430

Suggestion: maybe it's time for a proper help page with the argument `-h` ?

**Comment by Kethku** [comment]
Done. Re the help argument. I agree that seems like a good idea, but its a little complicated. I probably want to add a help doc as well somehow inside of neovim since most of the configuration is done via global variables.

**Comment by Kethku** [comment]
Closing for now. I am thinking about the help menu though.
