### ISSUE TITLE
Floating point errors accumulate after multiple scroll operations with dpi scaling

### ISSUE THREAD

**Issue by duvallj** [Kethku/neovide#436]
Here is a short gif demonstrating the issue:
![2021-01-04-neovide-scrolling-smaller](https://user-images.githubusercontent.com/10897431/103595883-97ad2800-4eca-11eb-966e-e052b5153c37.gif)
Basically, it seems the previously-rendered text gets cut-and-pasted over and over again when scrolling, and is slightly off due to floating point errors, resulting in entire lines being off when the effect compounds.

This could be a Skia limitation, but is it be possible to work around it?

**Comment by Kethku** [comment]
Woah. This is wild. Mind sharing what font you're using? feels like maybe the font calculations are wrong. I don't see how this could be floating errors that quickly.

**Comment by Kethku** [comment]
But also I rewrote all of the rendering just recently, so who knows.

**Comment by duvallj** [comment]
(Ah sorry for the late response) `guifont` isn't set, so it should be using the default for Windows, Consolas.

I mention floating point errors because while I was poking around the rendering code trying to fix #424 starting from <https://github.com/Kethku/neovide/commit/8580ca065007c3e63ada85d5b20c2b2af593220c>, I noticed that [pixel_width and pixel_height](https://github.com/Kethku/neovide/blob/8580ca065007c3e63ada85d5b20c2b2af593220c/src/renderer/rendered_window.rs#L55) calculated from the font have to be cast to integers, while [the actual scrolling code](https://github.com/Kethku/neovide/blob/8580ca065007c3e63ada85d5b20c2b2af593220c/src/renderer/rendered_window.rs#L478) used the raw floats. It's just a hypothesis but I think it's at least plausible.

**Comment by Kethku** [comment]
I think https://github.com/Kethku/neovide/pull/438 might fix this issue, but I'm not sure because I can't really reproduce the problem on my machine.

**Comment by Kethku** [comment]
It fixes a ton of other issues with regard to dpi scaling though so maybe it fixes this as well?
