### ISSUE TITLE
Neovides uses cpu while idle

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#440]
Looks like the most recent rewrite broke the idle pausing of the renderer. I'll need to track down why that is and fix it.

**Comment by RedBeard0531** [comment]
On windows it shows using ~95% of the GPU in addition to ~1.5% of CPU when idle and in the background. If I lower the framerate to 20, it goes down to ~40%. The very high GPU usage seems more concerning than the CPU usage.

**Comment by Kethku** [comment]
Yeah I need to track down what exactly is going on

**Comment by Kethku** [comment]
It also appears to increase over time indicating a leak of some sort

**Comment by kirawi** [comment]
I don't really understand the codebase, but it looks like idle events are created, but never handled.

https://github.com/Kethku/neovide/blob/68582e05516fd3f6744752d8198ff3016d2190b9/src/editor/window.rs#L381-L383
https://github.com/Kethku/neovide/blob/68582e05516fd3f6744752d8198ff3016d2190b9/src/renderer/rendered_window.rs#L551
https://github.com/Kethku/neovide/blob/68582e05516fd3f6744752d8198ff3016d2190b9/src/window/winit/mod.rs#L252-L254

**Comment by kirawi** [comment]
It seems to be related to multigrid. Scrolling down, as in to render the next line, with it enabled triggers it. On another note, neovide seems to using quite a bit of GPU power compared to something like Chrome. It's fairly negligible for me, topping out at ~5.5% GPU, but something I noticed.

**Comment by jonvaldes** [comment]
Found the issue :)
https://github.com/Kethku/neovide/pull/482
