### ISSUE TITLE
Multiple issues while building with `winit` backend

### ISSUE THREAD

**Issue by Stupremee** [Kethku/neovide#449]
I tried to build Neovide using the `winit` backend, because I can't build `sdl2-sys` on my system.

While I tried to build it using the `winit` backend, I encountered multiple issues:
- the `skulpin/sdl2` feature is enabled, even if the `winit` feature is chosen, because `default-features = true`, and `skulpin/sdl2` is enabled by default
- `skulpin` currently fails to build with every winit feature they provide. This has to be fixed in skulpin directly

**Comment by Kethku** [comment]
Interesting. Do the skulpin upstream examples fail with the winit features?

**Comment by Stupremee** [comment]
Yes. I also changed the version and used `0.11` instead of the commit that is provided

**Comment by Kethku** [comment]
Thats very strange because I just ran winit locally (and discovered a build error with the feature enabled which I fixed and pushed).

I have to run using `cargo run --features=winit --no-default-features` for the reasons you highlighted. Could you pull from main and try building again? If it fails, could you give me the failure message?

**Comment by Stupremee** [comment]
Oh wait. Nevermind. It is not caused by skulpin directly, but neovide fails to build with winit

**Comment by Kethku** [comment]
Also note: the winit builds are somewhat more buggy than the sdl2 ones currently. I think keyboard handling is somewhat shaky as well as closing is not very smooth currently. I believe the existing bugs should be pretty easy to fix, but you should be aware of them.

**Comment by Kethku** [comment]
Awesome. I just fixed that issue. Should build now

**Comment by Kethku** [comment]
Closing as I think these the default features problem is expected, and the build error is now fixed.

**Comment by Stupremee** [comment]
Yea seems to build now. Just the fix for the features is missing.
But it's an easy fix too, by just disabling default features, and enabling the `winit` feature:

```toml
[features]
winit = ["skulpin/skulpin_winit", "skulpin/winit-23"]

[dependencies]
skulpin = { git = "https://github.com/aclysma/skulpin", branch = "master", default-features = false }
```

**Comment by Kethku** [comment]
No its a good point! I thought it was required, but looking back at it, you're right

**Comment by Kethku** [comment]
let me try it and push a change real quick

**Comment by Kethku** [comment]
hrmmm. I can't seem to figure out what combination of features lets me build sdl2 by default, but not require the no-default-features when building winit. Its very possible that I'm too tired to figure it out tonight.

If you've got an idea for it, I'd love to review and take a PR though!
