### ISSUE TITLE
Can't get Neovim from GitHub over SSH

### ISSUE THREAD

**Issue by basus** [Kethku/neovide#451]
I am trying to build Neovide on macOS Catalina. I am getting the following error when trying to run `cargo build --release`:

```

    Updating crates.io index
    Updating git repository `https://github.com/kethku/nvim-rs`
    Updating git submodule `https://github.com/neovim/neovim/`
error: failed to get `nvim-rs` as a dependency of package `neovide v0.6.0 (/Users/basus/src/neovide)`

Caused by:
  failed to load source for dependency `nvim-rs`

Caused by:
  Unable to update https://github.com/kethku/nvim-rs#109feea9

Caused by:
  failed to update submodule `neovim`

Caused by:
  failed to fetch submodule `neovim` from https://github.com/neovim/neovim/

Caused by:
  failed to authenticate when downloading repository: git@github.com:neovim/neovim/

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  ERROR: Repository not found.
  ; class=Ssh (23); code=Eof (-20)
```

It looks like Git is failing when trying to check out the repo using SSH authentication. I can successfully check out and update other GitHub repositories over SSH just fine, so I don't know why this is failing.

**Comment by Kethku** [comment]
Honestly I think this is a configuration problem on your side. Theres not much I can do to effect how github responds to ssh based clones...

Its possible that one of the repos is misconfigured, but I kinda doubt it? Not sure how to procede

**Comment by rjshrjndrn** [comment]
But is it possible to add the ssh-keys from ssh-agent.
Usually, In terminal, I'll have ssh-agent holding my ssh-keys, and git push will work with that key( especially with fugitive). But now, I'm getting auth error. I guess no ssh keys. I don't know how the integration works, but pretty sure, no ssh keys. That'll be a huge blocker if you're using nvim + fugitive for coding.

**Comment by Kethku** [comment]
Yeah cloning the github repo isn't something I can fix and I am far from a linux expert, so I'm going to close this.

**Comment by olablt** [comment]
I resolved this problem. remove/comment these lines in ~/.gitconfig
```
[url "git@github.com:"]
       insteadOf = https://github.com/
```
