### ISSUE TITLE
Small (subscript) characters on some particular font do not render monospaced

### ISSUE THREAD

**Issue by rabirabirara** [Kethku/neovide#452]
![image](https://user-images.githubusercontent.com/59306451/105628499-26d69d00-5df2-11eb-8526-c6c44378f726.png)

The font used is called `Hack Nerd Font Mono`.  It's a monospaced font.  The above is a picture of how subscript (top row) Unicode renders in Neovide.

Now, for an image of how subscript Unicode renders in terminal Neovim:

![image](https://user-images.githubusercontent.com/59306451/105628484-17575400-5df2-11eb-8b59-d63d3fe82c44.png)

What is responsible for the spacing of the character rendered?

EDIT: superscript renders consistently with Terminal behavior, actually.  Superscript characters are cut off at the top with certain font sizes; the same is true in terminal.  In Neovide, the superscripts are correctly monospaced.  However, this issue still applies to the subscript characters.

Additionally, this issue only applies to the font I'm using; it doesn't apply to the default fallback font.

![image](https://user-images.githubusercontent.com/59306451/105628690-3bfffb80-5df3-11eb-88b4-9f2046744022.png)

The font I normally use (Hack NF) doesn't work right with subscripts, as I presented above - but it does work in terminal Neovim.  So I don't think it's a font problem, despite this.  What is the possible cause?

EDIT 2: In fact, the subscripts work right with pretty much any other font I try.  I'm beginning to think it is a font issue, and I will probably close this in some time.  It may be that this patched font is some case that Neovide doesn't cover at the moment, or maybe the font is just broken.  Which is odd, because it works for `nvim-qt`.

**Comment by Kethku** [comment]
The spacing for a given font is determined by https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/caching_shaper.rs#L155

I'm honestly pretty surprised that the spacing would be effected per character given that I thought that spacing was constant for the entirety of a font (actually I think its determined by the set guifont)

THis definitely represents a bug that should probably be fixed, so I'm hesitant to close it

**Comment by Kethku** [comment]
The cutting off at the top of the line is a result of a hack to prevent rendering artifacts sticking around. Rather than redrawing the entire screen every time, neovide renders to an image which is that reused over and over for performance reasons. This works 99% of the time with monospace fonts because they are meant to stay in a regular grid

However occasionally there are characters that don't behave and stray out of their boxes. THese get cut off

**Comment by Kethku** [comment]
I believe some vim guis (maybe even gvim?) allow configuring the line spacing to try to address this. Give a little extra buffer room between lines. I always felt like that was a hack, but I guess it makes sense given how loosy goosy "monospace" fonts are

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
