### ISSUE TITLE
Use italic version of the font for italic text

### ISSUE THREAD

**Issue by tejasvi** [Kethku/neovide#458]
On gVim and nvim-qt italicized text looks like this. 
![image](https://user-images.githubusercontent.com/45873379/106101296-b0c09600-6163-11eb-9c79-16134a6867c9.png)
On neovide:
![image](https://user-images.githubusercontent.com/45873379/106110337-94772600-6170-11eb-9313-f7ebc9241f15.png)

**Comment by PyGamer0** [comment]
For me italics work, do you have the Italic of the font version installed?

**Comment by tejasvi** [comment]
@PyGamer0 I tried it with a different font and it indeed works. Probably connected to #457.
