### ISSUE TITLE
Update Mac OS build documentation

### ISSUE THREAD

**Issue by HallerPatrick** [Kethku/neovide#460]
The documentation refers to running:
```bash
brew cask install apenngrace/vulkan/vulkan-sdk
``` 
to install vulkan.

But brew is telling that using `brew cask install` is disabled. Instead `brew install --cask` should be used.

Therefore the documentation has to be updated with a:
```bash
brew install --cask apenngrace/vulkan/vulkan-sdk
```

I am not sure since which version this is changed, but I am using Hombrew `2.7.7`

EDIT:
Seems `brew cask install` is disabled since `2.7`. Which was released in Dec 2020.

**Comment by Kethku** [comment]
@HallerPatrick could you make a PR with this change?
