### ISSUE TITLE
How to set font ?

### ISSUE THREAD

**Issue by peach-lasagna** [Kethku/neovide#468]
how I run neovde:
```bash
$ neovide.exe --wsl file.txt
```
where is my font? In windows terminal it works correctly.
![изображение](https://user-images.githubusercontent.com/59787538/107240042-0fd3b400-6a5c-11eb-928f-ca9d1d8a8a0b.png)

**Comment by chama-chomo** [comment]
hey, I have the same problem on Arch Linux, icons in airline's bar are replaced by squares. In terminal with the same font all is working

**Comment by chama-chomo** [comment]
After I wrote this I made one more attempt with Hack\ Nerd\ Font\ Mono and all is working

**Comment by neelkarma** [comment]
In your `init.vim`:
```vim
set guifont=font:hsize
```
For example, if I wanted to use `FiraCode NF` at 16pt size:
```vim
set guifont=FiraCode\ NF:h16
```
(the backslash is used to escape the space)

**Comment by Kethku** [comment]
the font names may need to be slightly different for skia to pick them up. Do you encounter the same issue with other more standard fonts such as consolas?

If swapping that way works, I think probably you got the font name wrong.

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/113783967-92968980-9702-11eb-85e1-18484934821c.png)

I seem to be having the same issue with:

```
vim.o.guifont = "JetBrainsMono Nerd Font"
```

and the mono variant as well.

**Comment by Kethku** [comment]
Does the alphabetic text match the set font in your screen cap? If so, then the squares represent glyphs not present in the font and other systems are using some form of font fallback to render them. There is ongoing work tracked here: https://github.com/Kethku/neovide/issues/444 to add better font fallback, but its going to be a bit to get it right

**Comment by peach-lasagna** [comment]
Thanks for your help! The last question: how to zoom out and zoom in on the text?

**Comment by neelkarma** [comment]
@peach-lasagna afaik you can't; the closest you can get is `:set`ting `guifont` with your preferred font size.

**Comment by peach-lasagna** [comment]
oh, exactly!

**Comment by Luke1433** [comment]
Kethku made a comment elsewhere about how to set the font size in neovide. If you have a config in lua you can use this command and it should work. Just substitute out the "Source Code Pro" for your personal font.

`vim.opt.guifont = { "Source Code Pro", ":h12" }` - Kethku

I think the import part is to include the colon before the h like so ":h12"

Post I'm referencing:
https://github.com/neovide/neovide/issues/1211#issuecomment-1037457034

**Comment by SohailHaqyar** [comment]
This worked for me:  
```
  vim.o.guifont ="UbuntuMono Nerd Font Mono:h12"

```

**Comment by Kethku** [comment]
Btw I don't recommend setting the guifont to a table. Under the covers that just gets concatenated, but we use the ':' separator to find the font size, so the result is confusing. Using a string like @SohailHaqyar suggests avoids that ambiguity.

**Comment by pr1mal** [comment]
I'd love to be able to set "Thin" or "ExtraLight" font width, but I'm only able to choose between normal and bold font versions. Is there any way to do this?
Thank you!

**Comment by deekshithanand** [comment]
Anyone knows how to set the light or extraalight version of the nerd font?
