### ISSUE TITLE
Send clipboard to remote neovim process

### ISSUE THREAD

**Issue by peach-lasagna** [Kethku/neovide#469]
Run neovide from wsl:
```bash
$ neovide.exe --wsl file.txt
```
1)write random symblos
2) press `v` in normal mode 
![изображение](https://user-images.githubusercontent.com/59787538/107288796-9f965400-6a96-11eb-99f9-5f17afb3791f.png)
3) "+y
4) doesn't copy to clipboard.

With the paste the situation is similar.
if i run without `--wsl` flag this will work correctly.

**Comment by Kethku** [comment]
Does the same thing happen with other neovim guis? I believe this is an upstream issue that can't be fixed in neovide.

**Comment by peach-lasagna** [comment]
No! this is doesn't work only in neovide's wsl mod! in nvim-qt and neovide without wsl flag its works correctly

**Comment by Kethku** [comment]
The struggle is that unless the neovim process can get access to the os clipboard from within wsl, I don't think this is something that can be solved...

I think this would require an upstream implementation of externalizing of the clipboard which to my knowledge doesn't exist today.

**Comment by djsavvy** [comment]
This is possible on WSL2 --- I have it currently working with just a `set clipboard+=unnamedplus` in my `init.vim`

**Comment by peach-lasagna** [comment]
@djsavvy  ,thanks, but it didn't work

**Comment by Kethku** [comment]
I'm closing this as I believe it is a user level issue. Neovide doesn't touch clipboards at all. That is the responsibility of the neovim process itself. SO I would investigate solutions in neovim for this sort of problem

**Comment by ianpan870102** [comment]
@djsavvy Sadly didn't work for me either

**Comment by datwaft** [comment]
For posterity, a solution would be to do what **ianyepan** says [here](https://github.com/Kethku/neovide/issues/544#issuecomment-820519937), but you need to add it to a folder like `/usr/local/bin`, it cannot be a folder you artificially added to path in `.profile` or the like.

My problem was that I added `win32yank.exe` to `~/.local/bin`, which was a folder I added to path in `.profile`.
