### ISSUE TITLE
Error in nvim-rs dependency

### ISSUE THREAD

**Issue by wbthomason** [Kethku/neovide#47]
When running `cargo build --release` from a fresh clone, there's an error on fetching the `nvim-rs` dependency. Looking at `Cargo.toml`, it appears that this dependency is from https://github.com/KillTheMule/nvim-rs and specifies the branch "futures". However, it looks like this branch was merged a few days ago: https://github.com/KillTheMule/nvim-rs/pull/11

Fixing this dependency fixes the build, though!

**Comment by Kethku** [comment]
Awesome. Would you mind creating a quick PR with the fix? If not I can get to it shortly

**Comment by wbthomason** [comment]
Sure, will do!
