### ISSUE TITLE
mouse selection in wsl mod doesn't work

### ISSUE THREAD

**Issue by peach-lasagna** [Kethku/neovide#470]
If i run neovide without `--wsl` flag i can make selection with right mouse button:
![изображение](https://user-images.githubusercontent.com/59787538/107289359-7de99c80-6a97-11eb-9b52-a8580cbc344f.png)
with flag - no.

**Comment by Kethku** [comment]
Are the versions of neovim the same between the two?

**Comment by peach-lasagna** [comment]
yep

**Comment by Kethku** [comment]
That is strange and I can reproduce it. I have honestly no idea why this would happen...

**Comment by calvinkosmatka** [comment]
@peach-lasagna @Kethku I couldn't get selection to work under Windows or WSL at first - `:set mouse=a` made it work on both for me, does that fix it for you?

**Comment by Kethku** [comment]
duh. That makes a ton of sense! @peach-lasagna I can no longer reproduce this.

**Comment by Kethku** [comment]
@peach-lasagna I think I'm going to close this because I'm pretty sure @calvinkosmatka pointed out the issue.

**Comment by peach-lasagna** [comment]
Oh, yes! this works. Thank you!
