### ISSUE TITLE
CTRL-^ Doesn't Work Without SHIFT

### ISSUE THREAD

**Issue by ewhac** [Kethku/neovide#473]
Identical issue as I reported against goneovim here:  https://github.com/akiyosi/goneovim/issues/109

> In Vim, the default binding of CTRL-^ switches to the "alternate" file, something I use a lot. On a normal console, pressing CTRL-6 is sufficient to yield ASCII 0x1e (a/k/a control-uparrow). This also works in GVim and nvim-qt.
>
> However, [neovide] interprets CTRL-6 as if one had simply pressed `6` (you can see sixes accumulating as a count in the command bar). To get CTRL-^ behavior, you must also hold down SHIFT.

**Comment by Kethku** [comment]
what keyboard layout are you using? Maybe I'm crazy but I think ctrl-6 should result in C-6 input to neovim unless I super misunderstand how keyboards work which is entirely possible :P

**Comment by ewhac** [comment]
Nothing unusual.  Layout is Generic 105-key PC (intl.), US-English.

**Comment by Kethku** [comment]
https://vi.stackexchange.com/questions/22587/ctrl-6-doesnt-switch-to-the-last-buffer-neovim

According to this neovim doesn't support this. Ctrl-6 mapping to Ctrl-^ is incidental and not intended.

**Comment by Kethku** [comment]
Feel free to reopen if you wanna chat about it more though.

**Comment by ewhac** [comment]
> justinmk (current neovim leader?) states
>
>>    ctrl-6 only works by accident in some terminals.

No.  While core Neovim may not handle the key combination specifically, the majority of terminal consoles very deliberately handle CTRL-6 to generate ASCII code 0x1E (control-uparrow) without the need to hold SHIFT (at least on real operating systems; I have no idea what braindamage Microsoft is inflicting on everyone).  It works in the Linux console, it works in `xterm`, `rxvt`, and `kitty`.  Hell, it even works on ancient ADM-3A serial terminals, and I remember it working on my SOL-20 that was built in 1979.

Further, if you run a late release of `nvim` from the console or from an `xterm`, you'll find that pressing CTRL-6 is received as 0x1E and correctly swaps buffers; and if you run a recent release of `nvim-qt`, you'll see it also properly treats CTRL-6 as control-uparrow.  It's also worked in "real" Vim for decades, including `vim-gtk`.

So, um...  pretty please?

**Comment by Kethku** [comment]
nvim doesn't actually handle this in console versions. xterm does the mapping before the data arrives to nvim. I believe nvim-qt special cases this.

I don't understand the bounds of the special casing you are expecting. Should all characters that are input via a shift modifier implicitly apply the modifier when control is held down? What if somebody has bound ctrl-6. I believe your request would break that binding would it not?

I guess I just don't understand why the gui would do this type of remapping. Especially since it can be down in the individuals vim config like the stack exchange thread said.

I'm not against fixing bugs, this one just feels underspecified. I'd appreciate some more details

**Comment by Kethku** [comment]
Some more details over on the oni repo https://github.com/onivim/oni/issues/2002#issuecomment-377691048

**Comment by Kethku** [comment]
Given these, I don't think its the responsibility of the gui to make this happen as its a side effect of older terminals.

**Comment by ewhac** [comment]
Some history.  Apologies in advance if this comes off as "Well, actually..." mansplaining.

If you look at an [ASCII chart](http://www.asciitable.com/), you'll see the first 32 codes are control characters.  And two columns over, you'll see the upper-case English alphabet, plus some symbols -- `@`, `[`, `\`, `]`, `^`, and `_`.  You'll see there is a direct mapping from the ASCII range 0x40 - 0x5F to 0x00 - 0x1F -- e.g. if you press CTRL with A (ASCII 0x41), you get SOH (ASCII 0x01), G (0x47) + CTRL == BEL (0x07), etc.  Thus, CTRL is essentially a form of SHIFT key, except it subtracts 0x40 from the key you typed.  So far, so obvious.

However, the characters `@`, `^`, and `_` on US keyboards are usually accessed via SHIFT.  What do you generate if the user presses CTRL-6?  Well, the control mappings only apply to that single ASCII column, from 0x40 - 0x5F.  CTRL-6 doesn't mean anything, because `6` (ASCII 0x36) is not in that range.  Neither does CTRL-; or CTRL-=.  This is why the original vi and EMACS don't have any commands mapped to CTRL-0 through -9 because they were designed to work over ASCII serial terminals and, according to the rules above, pressing those buttons together can't be mapped to a single ASCII byte code.

So when a user types CTRL-6, what do they *mean?*  Well, CTRL-6 by itself has no ASCII mapping, but the character `^` usually (but not always) lives above `6`, so probably they were hoping for CTRL-^.  And this is the assumption that has been baked into nearly every keymap table and terminal emulator written since X11 was first created.

So, for Vim or Neovim running in a console, it doesn't really know how it was generated; all it sees is 0x1E come over the wire, and act accordingly.  And all the terminals, as a courtesy, emit 0x1E when you press CTRL-6.

(Some trivia:  Not all terminals put `^` or even `@` in the same place.  If you look at the keyboard layout for the venerable [ADM-3A](https://en.wikipedia.org/wiki/File:KB_Terminal_ADM3A.svg), you'll see that *all* the control characters can be generated using CTRL and an *un-shifted* keycap (except for underscore, which seems to be missing).)

**Comment by Kethku** [comment]
Wouldn't doing this mapping by default break keybindings mapped to Ctrl + 6? I understand where this came from historically, but I don't understand why Neovide should follow this pattern when operating systems don't handle text input in this way any longer. I don't think its that hard to rebind this in your vim config though. I think `noremap <C-6> <C-^>` should work for most cases.
