### ISSUE TITLE
Crash when running "neovide --multiGrid" on Windows 10

### ISSUE THREAD

**Issue by neelkarma** [Kethku/neovide#475]
When I run `neovide --multiGrid`, the Neovide window opens for a split second (with a black screen) then closes. I would send error logs, but I don't really know how to enable them - if someone could tell me that would be great.

Neovide Version: 0.6.0
NeoVim Version: 0.4.4
OS: Windows 10

**Comment by Kethku** [comment]
Was this built from source, or from the releases page?

Multigrid isn't supported in the released version, as its still a feature that is being iterated upon

**Comment by neelkarma** [comment]
Oh, it was the version from the releases page, soz

**Comment by Kethku** [comment]
Its all good! You can get a recent development build from the actions tab
