### ISSUE TITLE
opening problem with Manjaro OS

### ISSUE THREAD

**Issue by RomjanHossain** [Kethku/neovide#477]
I've recently installed `neovide` on my Manjaro(KDE) for the handsome gui of nvim.
But when i run neovide my compositor changes `OpenGL 3.1` to `XRender` and my `latte-dock` freeze. i get this message from the terminal:
`Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
`

Everything becomes normal when i close `neovide`.

**Comment by Kethku** [comment]
neovide uses vulkan today. Not opengl. I suspect that is the reason. I know nothing about Manjaro though so I'm not sure how to help debug further.

I am investigating an opengl backend, but I wouldn't hold my breath for it in the immediate short term.

**Comment by Kethku** [comment]
@RomjanHossain would you be willing to try the new main branch? It introduces an opengl renderer.

**Comment by RomjanHossain** [comment]
i just updated the `neovide` pkg from [AUR](https://aur.archlinux.org/packages/neovide) and it's all OK. I've no longer any rendering issue.

**Comment by j4qfrost** [comment]
Aur is actually running an older version that is somewhat stable, it just
has a couple rendering quirks and isn't internationally friendly ie it
doesn't have multiple keyboard support.
