### ISSUE TITLE
Can't pass cli args.

### ISSUE THREAD

**Issue by TENX-S** [Kethku/neovide#478]
Neovide: Build from [source](https://github.com/Kethku/neovide/releases/tag/0.6.0) 
Rust: rustc 1.49.0 (e1884a8e3 2020-12-29)
OS: macOS 10.15.7 / Windows 10 Version 20H2 Build 19042.804

* macOS:
<img width="1440" alt="Screen Shot 2021-02-21 at 2 17 16 PM" src="https://user-images.githubusercontent.com/40336192/108617247-a0909380-744f-11eb-84d1-2e73133bd610.png">

* Windows 10
![crash](https://user-images.githubusercontent.com/40336192/108617368-bc486980-7450-11eb-8979-7b2f9a8d3817.gif)

**Comment by JakubKoralewski** [comment]
Same here when downloaded from releases (Windows 10). Just doing `.\\neovide.exe` (from cmd.exe) works but `.\\neovide.exe --version` returns nothing on console and just flashes a window for split second, redirecting the output `.\\neovide.exe --version 2> cmd.txt` to a file shows the content `ERROR [neovide::bridge] Neovide requires version 0.4 or higher`.

However for me after building from source (5c6d84a4f1cbec26ed72f41a0c1f058aaaaeffd8) it works fine for `neovide -v`.

**Comment by Kethku** [comment]
I can't reproduce this error when built from main source. Does it still happen from current main?

**Comment by JakubKoralewski** [comment]
Not sure about @TENX-S but as I said it worked for me on the HEAD commit given in my comment, 0.7.0 from releases also works. 0.5.0, 0.6.0 did not work.

**Comment by TENX-S** [comment]
I think it's fixed.
