### ISSUE TITLE
Invalid menu position when using multiGrid

### ISSUE THREAD

**Issue by last-partizan** [Kethku/neovide#480]
When using multiGrid, command menu suddenly appears at the center of window, not at the bottom.

I'm using gnome on wayland, with 4k display.

![image](https://user-images.githubusercontent.com/301015/109297840-4de21d80-783b-11eb-8e6e-158ade9ecfd2.png)

**Comment by Kethku** [comment]
This is a known issue. I believe it is an upstream issue, but I haven't done the necessary work to determine for sure.

**Comment by last-partizan** [comment]
@Kethku upstream for what? neovim?

In case it might help, I encountered it in gnvim also (https://github.com/vhakulinen/gnvim/issues/80#issuecomment-675689996).

**Comment by Kethku** [comment]
Upstream in neovim. And yes, that is helpful that its in gnvim too.

**Comment by last-partizan** [comment]
It's already reported to neovim repository as well. But, unfortunately, received no attention.

https://github.com/neovim/neovim/issues/12985

**Comment by last-partizan** [comment]
I fixed it, now we're waiting for fix to be merged :)

**Comment by Kethku** [comment]
Amazing. Thanks so much for digging in!

**Comment by Kethku** [comment]
@last-partizan I noticed that the characters are positioned incorrectly vertically on the screencap to the PR you made. Do you have any details about what that font is?

**Comment by last-partizan** [comment]
@Kethku what do you mean by _incorrectly_? it looks fine for me. I'm using JetBrains Mono Nerd Font, with Iosevka fallback.

```vim
set guifont=JetBrains\ Mono\ Nerd\ Font,Iosevka:h24
```

And this is how it looks with my patch.
![image](https://user-images.githubusercontent.com/301015/111898764-a1a5e800-8a30-11eb-9c86-80ef93e30a1f.png)

**Comment by Kethku** [comment]
https://user-images.githubusercontent.com/301015/111036752-7ec07600-8429-11eb-8662-d257ed03895e.png

I was looking at the positioning here

**Comment by Kethku** [comment]
which looks somewhat different from the example you've linked. Not sure why

**Comment by last-partizan** [comment]
Some differences are:

- screenshot in the PR using neovim from build folder, not installed globally, so it can't load some plugins.
- my scrrenshot here is the same version, but already installed, so everything loaded correctly. Most notably: vim-airline.

But aside from that, i don't see any differences. Menu is positioned at the same correct spot.

Height of the font is exactly right. This is somewhat mysterious fontconfig shit, previously in `gnvim` i was setting font size to floats, to get this look, but now when i changed monitor to 4k and gnvim to neovide, h24 gives me what i want. Previously, i was using h11.25 with gnvim, becouse with just 11 and with 1080p resolution font was too wide.

Here is my [gnvim screenshot](https://user-images.githubusercontent.com/301015/111955370-11c87280-8af2-11eb-8eee-5ef53a390d7f.png), it's using h12 (neovide and gnvim using differen't font size scales, probably becouse gnvim respects gnome scaling settings, and neovide is not). Font is wider than neovim.

**Comment by last-partizan** [comment]
This is fixed now in [neovim#master](https://github.com/neovim/neovim/commit/db83be2daba27b36e69fe4dbcb8e565b18da7f2e) :)
