### ISSUE TITLE
Keys allover the place

### ISSUE THREAD

**Issue by tyrdal** [Kethku/neovide#488]
I tried Neovide under Win10 by building from source and had a really hard time quitting this verion version of vim :). The reason being that the keycode are allover the place. It took me while to find out that to type ":" in normal mode I had to use "Shift-Q". Everal other keys are in unknown locations too.

**Comment by Kethku** [comment]
That is very strange. Does the same issue occur with the version I just released 0.7?

**Comment by Kethku** [comment]
@tyrdal could you also give some details about your keyboard layout?

**Comment by tyrdal** [comment]
I am using a typical german (QUERTZ) keyboard. 

I'll test the new version and report back.

**Comment by tyrdal** [comment]
Ok, after updating and building the new version behaves as expected. The issue can be closed and I can start to use neovide.
