### ISSUE TITLE
Insert in wiki how i can use harfbuzz

### ISSUE THREAD

**Issue by sphynx79** [Kethku/neovide#489]
Sorry but I did not understand how i can use the harfbuzz in Windows 10.
I put the harfbuzz in my PATH folder, but now how i can configure Neovide for use??

Thanks

**Comment by Kethku** [comment]
I don't understand the question. Harfbuzz should be built into the exe. No need to install anything.

**Comment by sphynx79** [comment]
Sorry if I didn't make myself clear.
My question was whether I had to configure something in neovide to use harfbuzz, or is automaticly, 
How can I check if Neovide is using harfbuzz.
Thanks

**Comment by Kethku** [comment]
It works automatically. You can tell if it works by using a font with ligatures and typing the ligatures out. I use https://github.com/adam7/delugia-code

**Comment by Kethku** [comment]
I'm going to close this as a noop
