### ISSUE TITLE
why prefer discrete gpu?

### ISSUE THREAD

**Issue by JakubKoralewski** [Kethku/neovide#490]
Found this commit https://github.com/Kethku/neovide/commit/5c6d84a4f1cbec26ed72f41a0c1f058aaaaeffd8, and it bothers me because on laptops with an integrated and discrete GPU there often is a hybrid mode, in which the integrated GPU is always chosen first to save battery life. The choice puzzles me.

I have managed to overwrite this setting in NVIDIA's drivers, but I'm still curious why this choice?

**Comment by Kethku** [comment]
The system doesn't prefer discrete or integrated gpu anymore. This was old.

The original purpose of that change was to make it more likely that vulkan driver would be supported as many integrated Gpus do not.
