### ISSUE TITLE
Key AltGr not work

### ISSUE THREAD

**Issue by sphynx79** [Kethku/neovide#492]
I use Italian layout for my Keyboard, in nvim-qt i use AltGr for insert square brackets  and work fine.

But in Neovide not work, the application exit from insert mode and and nothing happens.

This problem exist also in old version of Neovide, i try also neovide.exe -u NORC, but same problem.

Please help me.

**Comment by bert1337** [comment]
Hi,
add this to your init.vim

imap <M-Esc> [
imap <M-C-]> ]

**Comment by Kethku** [comment]
repeat of https://github.com/Kethku/neovide/issues/445
