### ISSUE TITLE
Way to disable smear effect on echo?

### ISSUE THREAD

**Issue by neelkarma** [Kethku/neovide#494]
![2021-03-10 21-04-00_Trim](https://user-images.githubusercontent.com/59462098/110613032-e5088700-81e4-11eb-8a33-a251d9e1923b.gif)
As you can see above, I have a plugin (ALE) that echoes details about the current symbol being hovered on. However, Neovide's smear effect jumps down to the status bar and back up when the details update. Is there a way to disable the smear effect on echoes so that it just shows me the details without the smear effect?

**Comment by neelkarma** [comment]
Also, forgot to mention, using Neovide version 0.7.0 (from releases) and NeoVim 0.4.4

**Comment by Kethku** [comment]
This is fixed in main
