### ISSUE TITLE
Enable Remote Neovim Process Connection

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#50]
It would be cool to be able to connect to a remote neovim process such as one in wsl or over the network.

**Comment by KillTheMule** [comment]
That should be pretty easy using [tcp](https://github.com/KillTheMule/nvim-rs/blob/master/src/create/tokio.rs#L44). I tried investigating using UDS, but there does not seem to be a library providing those as `AsyncWrite/AsyncRead`ers.

**Comment by Kethku** [comment]
Do you mean UDP? Just trying to follow. I think tcp is probably the way to go as I don't want to have to track lost packets

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KillTheMule** [comment]
No, [UDS](https://lib.rs/crates/uds_windows). UDP is unsuitable indeed, but afaiu UDS is just like a unix socket, just on windows. No matter, doesn't look like I can support it anyways.

**Comment by Kethku** [comment]
Oh I see! Yes that makes sense.

**Comment by awlayton** [comment]
I am not able to compile on Windows to try, but can you not simply run `wsl nvim --embed` instead of `nvim --embed` to attach to the wsl one?

**Comment by Kethku** [comment]
This is a very good question to which I have no answer

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
I will attempt it shortly. I think it might work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Blocked on https://github.com/Kethku/neovide/issues/97

**Comment by BatmanAoD** [comment]
The trivial approach of hardcoding `wsl` as the command and `nvim` as the first argument doesn't seem to work for me. I've printed the debug representation of `cmd` just as a sanity-check:

```
     Running `target\debug\neovide.exe`
Command { std: "wsl" "nvim" "--embed", kill_on_drop: false }
```

A window appears briefly, but then disappears, and the app exits without showing any error output. The exit code is 0.

**Comment by Kethku** [comment]
wsl seems to work now.

**Comment by BatmanAoD** [comment]
What is the command-line argument for it? Do I need to have neovim installed on the non-WSL side?

**Comment by Kethku** [comment]
Reopening to remind myself to respond when I get back to the computer

**Comment by BatmanAoD** [comment]
Is there a command line argument in the 0.6.0 release for this?

**Comment by Kethku** [comment]
I believe it is. 

https://github.com/Kethku/neovide/blob/master/src/bridge/mod.rs#L37

I haven't tested it myself though as I don't have a wsl install on my home machine. Looks like you can just add --wsl? Also possible that there is a bug given https://github.com/Kethku/neovide/issues/281

**Comment by BatmanAoD** [comment]
Thank you! I am probably running into that bug, because running with any command line arguments does indeed cause the process to exit prematurely, sometimes without even opening a window first. I don't see any error output, though; is there some way to turn on log output?

**Comment by jlugao** [comment]
I am having a similar problem. Whenever I type neovide followed by any command line argument on cmd neovide opens with a blank screen and closes. 
Has anyone been able to run neovide on windows and connect to vim on wsl?

**Comment by dakom** [comment]
I naively just ran the command mentioned [above](https://github.com/Kethku/neovide/issues/50#issuecomment-580627000) and nothing happened.

Would it be possible to list step-by-step WSL-based instructions to the main Readme, alongside the current environments?

Am I correct in understanding that this would basically give the same power as the somewhat popular "remote VSCode" solution?

**Comment by keepitsane** [comment]
When using Node Version Manager (NVM) on WSL side Neovide seems to default to the system Node version rather then the version that has been selected by nvm to use. I believe the same issue exisits when using pyenv for Python.
