### ISSUE TITLE
Ctrl+Forward Slash doesn't work in Neovide

### ISSUE THREAD

**Issue by djsavvy** [Kethku/neovide#503]
Apologies for opening yet another one of these keyboard input issues, since I know there's already quite a few, but I didn't see one for this specific issue. 

It seems that my `ctrl+/` is getting interpreted as just a `/`. I'm on Windows 10, using neovide 0.7.0.

**Comment by Kethku** [comment]
What keyboard layout are you using?

**Comment by Kethku** [comment]
Im going to close this in favor of the main keyboard issue https://github.com/Kethku/neovide/issues/445
