### ISSUE TITLE
Missing screen refresh

### ISSUE THREAD

**Issue by jneem** [Kethku/neovide#508]
After updating from 0.6.0 to 0.7.0 (or alternatively, git master), I occasionally observe neovide failing to refresh the screen when it should. This may be related to the setting
```
let g:neovide_cursor_animation_length=0.05
```
At least, I can't reproduce if I delete this setting.

I can reproduce this issue in the following way:
1) open the attached file in neovide
[numbers.txt](https://github.com/Kethku/neovide/files/6214317/numbers.txt)
On my screen, I can see the numbers 1 through 53
2) Put the cursor on the last visible line (53 in my case)
3) Press "page down" twice as fast as possible. Sometimes after doing this, I see lines 52 through 104, with my cursor on 52. However, I *should* see lines 103 through 155, with my cursor on 103.
4) Press the right arrow. Now I see lines 103 through 133, with my cursor on the "0" of 103.

Alternatively, instead of step 4, if I change virtual desktops and then change back, I see the correct behavior again.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
