### ISSUE TITLE
Can't access the maps for < (less than key)

### ISSUE THREAD

**Issue by kylechui** [Kethku/neovide#509]
OS: Windows 10
Using the Neovim 0.5 beta
When I try to remap `<` in Neovide, I'm able to see the maps, but am unable to use them. The `<` key just behaves as its default. I tested this on nvim-qt and in terminal, both of which handle `<` correctly.

In the following clip, I have to press `gv` to re-highlight text after dedenting it (`:vnoremap > >gv` works fine).
https://user-images.githubusercontent.com/48545987/112877030-c136b380-90b5-11eb-9170-6c8e1a6612f4.mp4

**Comment by svermeulen** [comment]
Yeah I found I had to map using `<S-lt>` for this to work.  I'm on macOS

**Comment by Kethku** [comment]
I think this has been fixed in main. If it hasn't please reopen.
