### ISSUE TITLE
Neovide crashes/hangs when using lsp (rls).

### ISSUE THREAD

**Issue by PyGamer0** [Kethku/neovide#510]
OS: Windows 10
Neovim: Version 0.5 nightly
Neovide: Version [taken from actions](https://github.com/Kethku/neovide/actions/runs/669994502)

Neovide crashes with the builtin LSP (neovim, using rls). 
Strange thing that it does not hang nor crash when I use Neovide (or terminal neovim or nvim-qt) from releases.

**Comment by PyGamer0** [comment]
Hmmm strange, grabbing the latest build by Actions seems to fix it.

**Comment by PyGamer0** [comment]
Also it hangs when i press `I`

**Comment by PyGamer0** [comment]
OK I found something, whenever I use `input` as a variable, it crashes. I dont know how but it does.
The way I fixed it was change the name of the variable.

**Comment by Kethku** [comment]
@PyGamer0 can you verify it doesn't happen with nvim in terminal? I recently had a similar issue with rust-analyzer in coc and was able to fix it by updating the plugin.

Also does the crash have any message? Does the app just close?

**Comment by PyGamer0** [comment]
Apparently it crashes (hangs a LOT) only when `completeopt` has `preview` in it.

> can you verify it doesn't happen with nvim in terminal?

It doesnt crash.

> Also does the crash have any message? Does the app just close?

Crash has no message, the app closes.

Last 2 lines of LOG
```
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
```

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
