### ISSUE TITLE
Resizing cmdline using mouse on Windows 10 with multigrid results in about half of requested size

### ISSUE THREAD

**Issue by EtiamNullam** [Kethku/neovide#511]
Dragging cmdline down will result in about half of requested size. Resizing splits works fine.

![caNT2sxLrB](https://user-images.githubusercontent.com/10875340/113234138-ffdc9180-92a0-11eb-81c8-1d14797c47db.gif)

Minimal vimrc: `mouse=a` just to enable mouse. Running with `--multiGrid` switch enabled.

Neovide 0.7.0. Windows 10. Neovim both 0.4.3 and 0.5-nightly.

**Comment by EtiamNullam** [comment]
Looks like https://github.com/yatli/fvim has multigrid support (as opt-in, WIP feature) and despite rendering issues dragging cmdline works fine there.

Tell me if you have any suggestion what other GUIs I should try. Is this an issue only on Windows?

**Comment by Kethku** [comment]
This has been fixed. It was an issue with multigrid handling. Turns out there are a series of bugs with how the mouse position is handled. I think I've finally come up with a series of hacks to work around them
