### ISSUE TITLE
Multigrid: telescope.nvim plugin text is burred

### ISSUE THREAD

**Issue by chrisbouchard** [Kethku/neovide#512]
When I enable multigrid, the [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim/) plugin's popup windows have blurred text. The popup window outlines are solid, but the contents are blurred and dimmed, as if they are in the background.

I'm reporting this here, but I'm not really sure if this is a telescope issue or a Neovide issue.

![Screenshot from 2021-04-03 12-43-39](https://user-images.githubusercontent.com/4512028/113486430-aaf77180-9480-11eb-9961-4d2868612cbf.png)

I'm using Neovide built today from e1d8d404167f5c6d5471ce1404493eb1805e94d2 (`main`) on Linux using Rust 1.50.0 stable.

**Comment by chrisbouchard** [comment]
I only just noticed, but further, the actual buffer is _not_ blurred.

![Screenshot from 2021-04-03 13-38-01](https://user-images.githubusercontent.com/4512028/113486625-d9c21780-9481-11eb-893d-e63eb6691ccd.png)

**Comment by chrisbouchard** [comment]
(I deleted a comment about the buffer behind not being blurred because I was just crazy&nbsp;&mdash; it's not supposed to be.)

**Comment by Kethku** [comment]
This is a known issue. Telescope renders two windows, and neovide doesn't have a way to turn off window background blurring on a per window basis. The change to enable that is somewhat involved because it requires reworking the setting syncing logic. Its in progress, but I haven't gotten the time to go hammer it out yet.

**Comment by chrisbouchard** [comment]
Understood. Thanks for letting me know; I'm happy to use Neovide without multigrid until that's resolved, but I get it may be low priority.

**Comment by Kethku** [comment]
its actually relatively high priority. The new multigrid stuff is awesome and I'd like to get it running for most people

**Comment by p13nty** [comment]
I really love multiGrid mode and can't work without smooth scroll anymore!

So maybe someone would be interested in quick and dirty workaround for this - I disabled border from `plenary.nvim` that is used by `popup.nvim` plugin and use builtin `neovim` border. It does not support window titles but it looks like this:

![image](https://user-images.githubusercontent.com/76395103/116663383-b2d30480-a99f-11eb-9a9c-0df006267c8d.png)


To apply this go to directory where popup plugin sits, for me its `~/.local/share/nvim/site/pack/paqs/start/popup.nvim`
Create file `no-border.patch` with diff below and `git apply no-border.patch`
```diff
diff --git a/lua/popup/init.lua b/lua/popup/init.lua
index 8d8fe6e..d036700 100644
--- a/lua/popup/init.lua
+++ b/lua/popup/init.lua
@@ -157,6 +157,10 @@ function popup.create(what, vim_options)
 
   win_opts.style = 'minimal'
 
+  if vim_options.border then
+      win_opts.border = 'single'
+  end
+
   -- Feels like maxheigh, minheight, maxwidth, minwidth will all be related
   --
   -- maxheight  Maximum height of the contents, excluding border and padding.
@@ -328,7 +332,7 @@ function popup.create(what, vim_options)
 
   local border = nil
   if should_show_border then
-    border = Border:new(bufnr, win_id, win_opts, border_options)
+    --border = Border:new(bufnr, win_id, win_opts, border_options)
   end
 
   if vim_options.highlight then
```

**Comment by Kethku** [comment]
Closing in favor of more detailed issue https://github.com/Kethku/neovide/issues/589

**Comment by chrisbouchard** [comment]
@Kethku I had a look at #589, and that seems to be more about font rendering than multigrid. It's possible I'm missing a more fundamental issue that underlies both, but I feel like this is different.

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/issues/720 woops this is the one I meant

**Comment by last-partizan** [comment]
```
let g:neovide_window_floating_opacity=1
```

I'm using this as workaround, floating windows are not longer transparent, but other features of multigrid working fine.

**Comment by Shatur** [comment]
> I'm using this as workaround

Tried it, but the telescope windows just become the same color as the background instead of transparency.

**Comment by last-partizan** [comment]
Hmmm, i must've changed some other option too. Yes.

```
let g:neovide_window_floating_blur=0
```

This one.

**Comment by Shatur** [comment]
> let g:neovide_window_floating_blur=0

Tried this one too. The result is the same as above :(

**Comment by last-partizan** [comment]
Oh, i found one more constraint. It works only until you resize neovide window :)

**Comment by last-partizan** [comment]
Or maybe you should resize it to some magick size.

Better to wait for proper fix :)

**Comment by m8dotpie** [comment]
> Hmmm, i must've changed some other option too. Yes.
> 
> ```
> let g:neovide_window_floating_blur=0
> ```
> 
> This one.

I noticed that this fix with opacity fix works nicely, but randomly
Simply reopening popup window until text is rendered correctly solves the issue :D
However it can mean that it somehow depends on the order or priority of settings. May be some neovide or Neovim settings cause a bug if loaded in wrong order?
