### ISSUE TITLE
Preview Images

### ISSUE THREAD

**Issue by ChristianChiarulli** [Kethku/neovide#516]
With Ueberzug you can preview images with things like ranger or the media plugin with telescope.

The seems to work out of the box with Neovide but, them image is a bit off

Any idea how to fix this? The plugin is rnvimr btw.

![image](https://user-images.githubusercontent.com/29136904/113785608-79dba300-9705-11eb-81a7-055776eb67e9.png)

**Comment by Kethku** [comment]
uhhhhh I have absolutely no idea how this would possibly work... I'm guessing that the tool renders images overtop of the main window?

If you could give some more details about how it works under covers I might be able to help out.

**Comment by ChristianChiarulli** [comment]
This is the best direction I can point you in for now: 

[ranger plugin](https://github.com/kevinhwang91/rnvimr)
[ueberzug](https://github.com/seebye/ueberzug)

**Comment by Kethku** [comment]
I have no idea what algorithm they use to decide where to put the images. I'm not sure what I can do to help you with this issue as positioning of external windows over top of the neovide window, isn't something we are supporting directly.

Eventually we may expose the ability to render images directly in a neovide buffer, but thats likely a ways out.

**Comment by vn-vna** [comment]
I have tried starting neovide from a terminal has the same size with neovide and surprise the image preview position is correct. But i still have no idea why it happen.
![image](https://user-images.githubusercontent.com/63695659/171913712-f79a94d9-61fa-4b35-b924-3efc2749963a.png)
