### ISSUE TITLE
linker `link.exe` not found

### ISSUE THREAD

**Issue by JosefBH** [Kethku/neovide#529]
I am a Windows 10 user and i want to use neovide, i installed rust, cmake and llvm. cloned the repository. when i cd into it and type 
cargo build --release i have error : linker `link.exe` not found several times in the output . at the end it says build failed. can someone help me please ?

**Comment by Zohnannor** [comment]
The error message clearly says "note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option"

You can follow [these instructions](https://stackoverflow.com/a/62817909/11294165).

Download [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) and install "C++ build tools".

**Comment by Kethku** [comment]
Yeah I agree with @Zohnannor I would try either installing the build tools for visual studio or visual studio community. Also once those are installed I have found running the developer command prompt that comes with it sometimes fixes this sort of issue.

**Comment by Kethku** [comment]
Closing as no response was given.
