### ISSUE TITLE
W10: Could not load configured font

### ISSUE THREAD

**Issue by jacola** [Kethku/neovide#53]
When starting on windows I get the following error:
![image](https://user-images.githubusercontent.com/941214/73158761-2694ba80-4128-11ea-8c33-f11530747bff.png)

When I looked at caching_shaper.rs, it says "Segoe UI Emoji" which I have.
![image](https://user-images.githubusercontent.com/941214/73158786-3e6c3e80-4128-11ea-9c89-e1dc479db121.png)

I removed my ginit.vim too which had guifont inside.

**Comment by Kethku** [comment]
Weird. That shouldnt cause an error. I will fix this soon

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
I actually think this has already been fixed. Is it possible you haven't pulled recently? Could I bother  you to try again on the current master?

**Comment by jacola** [comment]
I rebuilt it with the latest code and this issue is fixed.

On a side note, it doesn't seem to process 'ginit.vim', and I need to specify everything (ex: guifont) in 'init.vim'.
