### ISSUE TITLE
src/window/sdl2/mod.rs:459:14

### ISSUE THREAD

**Issue by petermeng** [Kethku/neovide#530]
When I running the neovide on Ubuntu 20.04(vm), it shows the following error, how can I solve this problem? Thanks!
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window/sdl2/mod.rs:459:14
stack backtrace:
   0:     0x5585c43c2630 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5585c43c2630 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5585c43c2630 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5585c43c2630 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5585c43e654c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x5585c43be912 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x5585c43c47e5 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5585c43c47e5 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5585c43c47e5 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x5585c43c4343 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x5585c43c4f81 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x5585c43c4ac7 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x5585c43c2acc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5585c43c4a29 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x5585c43e4541 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x5585c43e4363 - core::option::expect_none_failed::hf37eebedadde29e6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
  16:     0x5585c36c7805 - core::result::Result<T,E>::expect::h66c8269bc33232fd
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/result.rs:997:23
  17:     0x5585c36ae299 - neovide::window::window_wrapper::start_loop::h7531a76ae3bf74f5
                               at /home/michael/Documents/neovide/src/window/sdl2/mod.rs:453:9
  18:     0x5585c35f841d - neovide::window::create_window::h9b0a8828679a533b
                               at /home/michael/Documents/neovide/src/window/mod.rs:112:5
  19:     0x5585c35fd852 - neovide::main::haf8ec3afb13ce1ee
                               at /home/michael/Documents/neovide/src/main.rs:180:5
  20:     0x5585c36dadfb - core::ops::function::FnOnce::call_once::hb6785905322eea85
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  21:     0x5585c36ba01e - std::sys_common::backtrace::__rust_begin_short_backtrace::h42f129b811fd54f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  22:     0x5585c3746721 - std::rt::lang_start::{{closure}}::h965ac603d2559e50
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:66:18
  23:     0x5585c43c5497 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h527fb2333ede305e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  24:     0x5585c43c5497 - std::panicking::try::do_call::h309d8aee8149866c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  25:     0x5585c43c5497 - std::panicking::try::h75a60c31fd16bfc6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  26:     0x5585c43c5497 - std::panic::catch_unwind::h1f9892423e99bc00
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  27:     0x5585c43c5497 - std::rt::lang_start_internal::hd5b67df56ca01dae
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  28:     0x5585c37466f7 - std::rt::lang_start::h82ced888c60786c7
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:65:5
  29:     0x5585c35fdb7a - main
  30:     0x7f4e82d170b3 - __libc_start_main
  31:     0x5585c35ce3ee - _start
  32:                0x0 - <unknown>

**Comment by CedBri** [comment]
did you try [issue 126](https://github.com/Kethku/neovide/issues/126)?

**Comment by Kethku** [comment]
This looks like a vulkan driver issue. Were you able to install the dependencies in the readme?

**Comment by aspersieman** [comment]
I'm experiencing the same issue on Ubuntu 18.04 (elementary OS 5.1.7 Hera).

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window/sdl2/mod.rs:458:14
stack backtrace:
   0:     0x556700b25c40 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556700b25c40 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556700b25c40 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556700b25c40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556700a4bdac - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x556700b254b1 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x556700b24e15 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556700b24e15 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556700b24e15 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x556700b244fa - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x556700b244fa - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x556700b43858 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x556700b437cc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x556700b4377d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x556700a4a0f0 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x556700a50342 - core::option::expect_none_failed::hf37eebedadde29e6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
  16:     0x55670098fe25 - core::result::Result<T,E>::expect::hfe29a6676d3ae4e2
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/result.rs:997:23
  17:     0x55670098fe25 - neovide::window::window_wrapper::start_loop::he7fa0ca421742d7d
                               at /home/nicol/Documents/src/neovide/src/window/sdl2/mod.rs:452:9
  18:     0x556700a0a9c3 - neovide::window::create_window::hacb0b65581e3eb3e
                               at /home/nicol/Documents/src/neovide/src/window/mod.rs:112:5
  19:     0x556700a0a9c3 - neovide::main::he893f76d78a48233
                               at /home/nicol/Documents/src/neovide/src/main.rs:180:5
  20:     0x556700a0ee43 - core::ops::function::FnOnce::call_once::he66c949272bb2772
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  21:     0x556700a0ee43 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a5c38e55a462cd4
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  22:     0x556700a07ca5 - main
  23:     0x7f07aef5bbf7 - __libc_start_main
  24:     0x55670097892a - _start
  25:                0x0 - <unknown>
```

**Comment by edTheGuy00** [comment]
seeing the same issue on macOS Big Sur 

```
thread 'main' panicked at 'Failed to create window: SdlError("Vulkan support is either not configured in SDL or not available in current SDL video driver (cocoa) or platform")', src/window/sdl2/mod.rs:442:10
```

**Comment by edTheGuy00** [comment]
> seeing the same issue on macOS Big Sur
> 
> ```
> thread 'main' panicked at 'Failed to create window: SdlError("Vulkan support is either not configured in SDL or not available in current SDL video driver (cocoa) or platform")', src/window/sdl2/mod.rs:442:10
> ```

Compiled it myself and it works fine

**Comment by LamprosPitsillos** [comment]
How did you compile it your self? thanks

**Comment by CedBri** [comment]
> How did you compile it your self? thanks
> 

Clone the repo and follow the instructions in the ReadMe

**Comment by LamprosPitsillos** [comment]
Oh , already did that with no results.

**Comment by keyboard-clacker** [comment]
I had the issue where it kept saying `Vulkan support is either not configured in SDL or not available`, I was able to fix this by doing `cargo update -p sdl2-sys --precise 0.34.4` and rebuilding with `cargo build --release`, as suggested in #453

**Comment by Kethku** [comment]
Can you folks try the opengl branch?

**Comment by keyboard-clacker** [comment]
Unsure if me running that `cargo update` command changed anything before, but that opengl branch worked for me @Kethku !

**Comment by keyboard-clacker** [comment]
idk if this is relevant but I just saw this error pop up in my terminal while having neovide open on the opengl branch, not sure if it's relevant:
<details><summary>Error</summary>

```
[src/bridge/events.rs:928] event_parameters = [
    Integer(
        PosInt(
            5,
        ),
    ),
    Ext(
        1,
        [
            205,
            3,
            234,
        ],
    ),
    String(
        Utf8String {
            s: Ok(
                "NW",
            ),
        },
    ),
    Integer(
        PosInt(
            1,
        ),
    ),
    F64(
        10.0,
    ),
    F64(
        5.0,
    ),
    Boolean(
        true,
    ),
]
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format [Integer(PosInt(5)), Ext(1, [205, 3, 234]), String(Utf8String { s: Ok("NW") }), Integer(PosInt(1)), F64(10.0), F64(5.0), Boolean(true)]
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format [Integer(PosInt(5)), Ext(1, [205, 3, 234]), String(Utf8String { s: Ok("NW") }), Integer(PosInt(1)), F64(10.0), F64(5.0), Boolean(true)]', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</details>

**Comment by Kethku** [comment]
we no longer use sdl2 or vulkan. This has been fixed in main. Please reopen if you continue to see this issue.
