### ISSUE TITLE
'pacman' failed to install missing dependencies

### ISSUE THREAD

**Issue by jackwootton** [Kethku/neovide#532]
Running `makepkg -si` as per the instructions 

```
git clone https://aur.archlinux.org/neovide-git.git
cd neovide
makepkg -si

==> Making package: neovide-git 0.7.0.r3.ge1d8d40-1 (Sun Apr 11 12:07:27 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...

resolving dependencies...
looking for conflicting packages...

Packages (4) jsoncpp-1.9.4-1  rhash-1.4.1-1  cmake-3.19.6-1  rust-1:1.50.0-2

Total Download Size:     7.91 MiB
Total Installed Size:  614.85 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
```

results in

```
=> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> rust
  -> cmake
==> ERROR: Could not resolve all dependencies.
```

I'm on Arch Linux (GNOME: 3.38.4, BUILD_ID: rolling).

The packages that can't be retrieved:

- `cmake-3.19.6-1-x86_64.pkg.tar.zst`

**Comment by CedBri** [comment]
did you try installing it using Yay?

**Comment by jackwootton** [comment]
No. Is it a dependency?

**Comment by CedBri** [comment]
No but it might fix the missing dep.

**Comment by Kethku** [comment]
I don't know anything about archlinux or its packaging system, so if anybody finds a solution for this issue, I'm happy to add instructions to the readme. But I'm not likely to be of much help here.

**Comment by CedBri** [comment]
The official arch package should be available [here](https://archlinux.org/packages/extra/x86_64/cmake/)
First, make sure to refresh your package list:
`sudo pacman -Syy`
then
`sudo pacman -S cmake` should do it.
