### ISSUE TITLE
Window is not tiled in dwm

### ISSUE THREAD

**Issue by leanderbes** [Kethku/neovide#535]
When I open neovide in dwm the window will appear in floating mode in the center of the screen instead of tiling like it should.

**Comment by CedBri** [comment]
I don't think that's a neovide issue.
You should be able to change this by changing your DWM config.

**Comment by Kethku** [comment]
Unless theres an action we can take in neovide I think this isn't something we can solve. I'm closing this, but feel free to reopen if you want to chat further or have ideas.
