### ISSUE TITLE
Doesn't work in MacOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by singlexyz** [Kethku/neovide#538]
<img width="799" alt="截屏2021-04-12 上午5 42 33" src="https://user-images.githubusercontent.com/4456413/114322310-fe894f80-9b51-11eb-84bc-005d157b5409.png">
<img width="698" alt="截屏2021-04-12 上午5 42 45" src="https://user-images.githubusercontent.com/4456413/114322307-fcbf8c00-9b51-11eb-93af-282b6f0b7b36.png">

**Comment by jheysonsaav** [comment]
I suggest adding the "bug" tag to this issue
