### ISSUE TITLE
How disable VFX?

### ISSUE THREAD

**Issue by lbiaggi** [Kethku/neovide#539]
Hi I would like to have  any VFX disabled, is it possible?

**Comment by PyGamer0** [comment]
Do you mean the cursor animation?

If so add this to `init.vim`
```
let g:neovide_cursor_animation_length=0
```

**Comment by lbiaggi** [comment]
> Do you mean the cursor animation?

Yes, thanks

**Comment by gordonrust** [comment]
This setting does not disable the cursor animation. My system is arch linux. Any pointers??

**Comment by PyGamer0** [comment]
> This setting does not disable the cursor animation. My system is arch linux. Any pointers??

?? where did you put the setting, init.vim?
