### ISSUE TITLE
[MacOSX] Cannot open neovide after build, got `Saving session...completed.`?

### ISSUE THREAD

**Issue by nyngwang** [Kethku/neovide#540]
I have no problem when building:
![image](https://user-images.githubusercontent.com/24765272/114331439-8f722200-9b76-11eb-9f76-226eebd5e90e.png)

But it directly exit after I open it: 
![image](https://user-images.githubusercontent.com/24765272/114331370-6ea9cc80-9b76-11eb-94e8-757f8b371912.png)

**Comment by Kethku** [comment]
I'm not sure whats going on here. Can somebody with more mac experience (or a mac to test on) give some assistance?

**Comment by j4qfrost** [comment]
How exactly are you opening neovide?

**Comment by jadireddi** [comment]
I am assuming, you are doing double click on the `neovide` to open. Can you open using Terminal  with command`./neovide`

**Comment by Kethku** [comment]
Closing as no response was given.

**Comment by zsmatrix62** [comment]
the same problem
