### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by prajwalprabhu** [Kethku/neovide#543]
I am in Fedora I built from opengl branch & when I run ./target/release/neovide
I got this :
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14

**Comment by Kethku** [comment]
Interesting. I think this means that the font set in the vim config (or defaulted to Noto Sans Mono) isn't installed. Do you have a guifont variable set in your vim config? If not, can you try installing Noto Sans Mono font? https://www.google.com/get/noto/

**Comment by prajwalprabhu** [comment]
It was my mistake i set guifont and itis working
