### ISSUE TITLE
[WSL2] Can't copy-paste to/from System Clipboard (Windows 10)

### ISSUE THREAD

**Issue by ianpan870102** [Kethku/neovide#544]
I'm using Windows 10 with WSL2 Ubuntu 20.04, with X-Server VcXsrv.

I tried `"*y`, `"*p`, `"+y`, "+p`, which all work in terminal neovim (using Windows Terminal as the emulator), but don't work with Neovide.

I downloaded neovide.exe from this GitHub page and put it on my Windows PATH. I invoke neovide with `neovide.exe --wsl --multiGrid`

Any help is appreciated!

**Comment by Kethku** [comment]
This is a repeat of https://github.com/Kethku/neovide/issues/469. Handling paste from wsl processes is not something we can solve in the neovim gui. Somebody suggested a solution in 469 though. Maybe that will help.

**Comment by ianpan870102** [comment]
Thanks for the pointer. Sadly, the solution didn't work for me either.

**Comment by Kethku** [comment]
Maybe bring up the issue in the main neovim channels? Somebody over there may have better advice than I can provide

**Comment by ianpan870102** [comment]
With the following code, I was able to yank from Neovide to the system clipboard and paste it in Windows 10.

```vim
let s:clip = '/mnt/c/Windows/System32/clip.exe' 
if executable(s:clip)
  augroup WSLYank
    autocmd!
    autocmd TextYankPost * call system('echo '.shellescape(join(v:event.regcontents, "\<CR>")).' | '.s:clip)
  augroup END
end
```

I'm still looking for a workaround for pasting stuff from Windows 10 into Neovide.

**Comment by ianpan870102** [comment]
> Maybe bring up the issue in the main neovim channels?

I'm afraid this is a Neovide issue. Because copy/pasting to/from system clipboard is fine with neovim in the terminal (Windows Terminal in my case), as long as the user remembers to `set clipboard=unnamedplus`

**Comment by Kethku** [comment]
What happens if you run nvim in headless mode and connect to it with the newly merged https://github.com/Kethku/neovide#remote-tcp-support? I'm wondering if its possible that the clipboard yank utility isn't on the path when neovide runs nvim under wsl directly.

**Comment by ianpan870102** [comment]
Hey @Kethku Keith, sorry but installing the latest build on Windows requires too much Windows-side setup for me at this point (rust, git etc.) I was actually using the directly-downloaded neovide.exe v0.7.0 as I prefer to have my "Windows side" clean with little to no programming utils/dependencies.

I can wait until you release the TCP support as a beta binary release though.

> I'm wondering if it's possible that the clipboard yank utility isn't on the path when neovide runs nvim under wsl directly.

I'm no expert in this, but I think that if that's the case, then my yanking snippet above wouldn't have worked either. Because it's using clip.exe under the hood. But the issue right now is that yanking out of Neovide does work (with the s:clip snippet), but pasting into Neovide does not.

**Comment by ianpan870102** [comment]
I solved the issue completely. All we need is `win32yank`. Note: I'm using the latest version of neovim (i.e. nightly)

Please ignore the previous snippet I pasted regarding `s:clip`. The perfect solution I found is to execute the following 4 lines in the terminal:

```text
curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
chmod +x /tmp/win32yank.exe
sudo mv /tmp/win32yank.exe /usr/local/bin/
```

You could change `/usr/local/bin/` in the last line to any directory, as long as it's on your PATH.

**Comment by HUAHUAI23** [comment]
sadly, it is seem not work for me

https://user-images.githubusercontent.com/43649186/220327268-cc18288d-266d-4c9c-90c6-d497cabb083b.mp4

i set clipboard+=unnamedplus on my init.lua
![image](https://user-images.githubusercontent.com/43649186/220327509-a6eab079-acc4-49a5-af25-4dbcc56cc132.png)
