### ISSUE TITLE
release binary does not work on debian buster

### ISSUE THREAD

**Issue by ahmadie** [Kethku/neovide#546]
i get the following error:

>> ./neovide
>> ./neovide: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./neovide)

**Comment by Kethku** [comment]
could you try installing glibc using the package manager?

**Comment by ahmadie** [comment]
According to this: https://packages.debian.org/source/buster/glibc, debian buster uses glibc (2.28-10) which is older I guess.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you continue to see this issue.
