### ISSUE TITLE
Unable to input certain characters on Scandinavian keyboard 

### ISSUE THREAD

**Issue by JonasUJ** [Kethku/neovide#547]
On a Scandinavian keyboard with Danish layout you have to press `Ctrl` + `Alt` (or just `AltGr`) + one of `<`, `2`, `8`, `9` to type one of `\`, `@`, `[`, `]` respectively. In Neovide none of these characters can be typed. Trying to type `\` results in `^\` appearing in the bottom right corner and insert/replace/command mode is exited.

I have never encountered this anywhere else.

**Comment by Kethku** [comment]
This is a repeat of https://github.com/Kethku/neovide/issues/445. The current solution would be to contribute a keyboard layout similar to this one https://github.com/Kethku/neovide/blob/main/src/window/sdl2/layouts/qwerty.rs, but eventually we will rely on winit to handle keyboard layouts correctly as outlined in the keyboard handling issue

**Comment by Kethku** [comment]
I would be happy to give pointers for how to contribute a Danish keyboard layout if you are interested in doing that

**Comment by JonasUJ** [comment]
I looked into it, but I don't think I can justify doing it if that winit pr is merged soon, which it looks like it is.
