### ISSUE TITLE
Graphical artifacts when scrolling on windows

### ISSUE THREAD

**Issue by moadfakhri** [Kethku/neovide#548]
when I scroll, the texts become all messed up

![image](https://user-images.githubusercontent.com/37900094/114462508-a8102580-9bd2-11eb-98d6-b03edee151f1.png)

this only happens with v0.7.0
previous versions are fine, so I suspect it has something to do with the smooth scrolling.

**Comment by Kethku** [comment]
Are you running with the multigrid enabled?

**Comment by moadfakhri** [comment]
no, I'm running it without enabling multigrid.
when I run it with `--multiGrid` I get #483

**Comment by Kethku** [comment]
Can you record a gif (I find https://www.screentogif.com/ to be very easy) of both multigrid and non multigrid? That might help me debug what is going on. Is this on a high dpi monitor? What about when you run from current main? https://github.com/Kethku/neovide/actions/runs/746999264

It seems like the background surfaces are using the wrong resolution and are being scaled up.

**Comment by moadfakhri** [comment]
okey here is a screen record
![record](https://user-images.githubusercontent.com/37900094/115061493-c62e9c00-9ed8-11eb-991f-aafd8c0398cf.gif)
also i noticed that the blurred floating windows are not working properly.

**Comment by Kethku** [comment]
Collapsing under https://github.com/Kethku/neovide/issues/537
