### ISSUE TITLE
Executable doesn't accept arguments in Windows

### ISSUE THREAD

**Issue by datwaft** [Kethku/neovide#550]
I don't know if I am doing something wrong (probably), but I can't get the executable to accept arguments, not even `--version` or `--help`, it just doesn't do anything if I include an argument.

Here is an example:
![image](https://user-images.githubusercontent.com/37723586/114476993-a2a5e180-9bb8-11eb-9607-2fbff01d038b.png)

And, as you can see here, if I don't use any argument it runs properly.

![image](https://user-images.githubusercontent.com/37723586/114477047-c49f6400-9bb8-11eb-8737-6b5a56c0e51b.png)

**Comment by ErikMayrhofer** [comment]
Should in theory be fixed by #680 in the current opengl branch. Should be worth another try from someone running windows.

**Comment by datwaft** [comment]
Seems to work with 0.6.0.
Thanks!

**Comment by Kethku** [comment]
This has been fixed in main. Please reopen if you continue to see this issue.
