### ISSUE TITLE
No Binary for OpenGL Windows 10

### ISSUE THREAD

**Issue by MR-TLL** [Kethku/neovide#553]
When I try to run the release binary on my machine which has no support for vulkan ( on windows 10 OS), the application simply doesn't starts. Unfortunately I can not build the source code on Win 10 since it requires too many components (cmake +rust + llvm + msvs build tools etc. )  I request to please add the binary packages for OpenGL for major Operating Systems.

**Comment by Kethku** [comment]
CI builds binaries here: https://github.com/Kethku/neovide/actions if you scroll down you can find one for opengl.
