### ISSUE TITLE
vim linespace setting doesn't work.

### ISSUE THREAD

**Issue by singlexyz** [Kethku/neovide#554]
They use the same config, and the `linespace` is 10, but neovide doesn't set it.
`linespace` setting only in the GUI, neovide is the GUI 😅

Neovide:
<img width="818" alt="截屏2021-04-13 下午8 27 23" src="https://user-images.githubusercontent.com/4456413/114552052-bc1d5b00-9c96-11eb-8d00-5fa85b5e1b44.png">

Neovim in terminal:
<img width="788" alt="截屏2021-04-13 下午8 27 09" src="https://user-images.githubusercontent.com/4456413/114552122-d2c3b200-9c96-11eb-987e-b0716b63e594.png">

**Comment by Kethku** [comment]
This is repeat of https://github.com/Kethku/neovide/issues/481
