### ISSUE TITLE
neovide doesn't start

### ISSUE THREAD

**Issue by bsjaramillo** [Kethku/neovide#558]
**I follow this instructions for windows:**
_Install the latest version of Rust. I recommend https://rustup.rs/
Install CMake. I use chocolatey: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
Install LLVM. I use chocolatey: choco install llvm -y
Ensure graphics libraries are up to date.
git clone https://github.com/Kethku/neovide
cd neovide
cargo build --release
Copy ./target/release/neovide.exe to a known location and enjoy._

but the ./target/release/neovide.exe not open any file or any window

**Comment by Kethku** [comment]
do you have neovim installed and on the path?

**Comment by bsjaramillo** [comment]
@Kethku yes, i had installed with choco

**Comment by Kethku** [comment]
Can you paste the output file if you run with --log?

**Comment by bsjaramillo** [comment]
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
INFO [neovide::window::window_wrapper] window created

thats the log

**Comment by Kethku** [comment]
Hmmm. Thats strange. Do you have a font configured via the guifont option in your vim config?

Does it still fail when run with --clean? (this disables your user profile)

**Comment by bsjaramillo** [comment]
I dont have set the guifont option in the vim config, and yes, doesn't works with --clean

**Comment by Kethku** [comment]
Ok another question. Do any of the release versions work? Maybe this issue is recent

**Comment by bsjaramillo** [comment]
no, the last release did not works for me either

**Comment by Kethku** [comment]
any earlier ones? Things changed significantly in 0.7

**Comment by bsjaramillo** [comment]
no, any version dont works hahah, thats strange...

**Comment by Kethku** [comment]
Very weird :( Ok different strategy. Does alacritty work? What about the opengl branch?

**Comment by joncarr** [comment]
I am having same issue. Built on Windows from source. The window opens then immediately closes.  Neovim is installed and is on the Path

**Comment by latkinsv** [comment]
I am having same issue. Any release version dont works.
OS is Win10 20H2 19042.928
Log file the same as posted by bsjaramillo but without this row: 
INFO [neovide::window::window_wrapper] window created

Additionaly i have next messeges if i start neovide in windows terminal with -h

dpi fix applied
thread 'main' panicked at 'Failed to create window: SdlError("Getting Vulkan extensions failed: vkEnumerateInstanceExtensionProperties returned VK_ERROR_INITIALIZATION_FAILED(-3)")', src\window\sdl2\mod.rs:442:10
stack backtrace:
   0:     0x7ff63b48a898 - <unknown>
   1:     0x7ff63b37b8cb - <unknown>
   2:     0x7ff63b4897c8 - <unknown>
   3:     0x7ff63b488d4c - <unknown>
   4:     0x7ff63b487eb2 - <unknown>
   5:     0x7ff63b4915a5 - <unknown>
   6:     0x7ff63b4914ff - <unknown>
   7:     0x7ff63b49149f - <unknown>
   8:     0x7ff63b379d50 - <unknown>
   9:     0x7ff63b37ff33 - <unknown>
  10:     0x7ff63b2f5174 - <unknown>
  11:     0x7ff63b2889ac - <unknown>
  12:     0x7ff63b2d9a66 - <unknown>
  13:     0x7ff63b2858c9 - <unknown>
  14:     0x7ff63b9e8bc0 - SDL_wcsstr
  15:     0x7ffe79fc7034 - BaseThreadInitThunk
  16:     0x7ffe7bfc2651 - RtlUserThreadStart

**Comment by Kethku** [comment]
@latkinsv thats a vulkan error and likely unrelated to the other issues here. Can you try the opengl branch?

**Comment by bsjaramillo** [comment]
with opengl branch neovide does start right, but how i can go to command mode ?, shift + ":" not work xd

**Comment by Kethku** [comment]
@bsjaramillo are you using a non qwerty keyboard layout? https://github.com/Kethku/neovide/issues/445

**Comment by Kethku** [comment]
This has been fixed in main. Please reopen if you continue to see this issue.
