### ISSUE TITLE
[Solved - Linux] ld: cannot find -lbz2

### ISSUE THREAD

**Issue by maxdevjs** [Kethku/neovide#56]
During compilation, I received a `/usr/bin/ld: cannot find -lbz2`. 

In this case, was missing `bzip2-devel` (this on [Solus](https://getsol.us/home/)), perhaps is worth to add to instructions.

Then compiled successfully (even if I can not [exit](#55) from it).

**Comment by Kethku** [comment]
Good to know. I'd really appreciate a PR adding instructions to the readme. I will make the change to instructions later if not :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maxdevjs** [comment]
One moment, please :)

**Comment by Kethku** [comment]
Can you give more details about the "I can not exit from it" comment? Maybe open an issue?

**Comment by Kethku** [comment]
Closing because the docs have been updated.
