### ISSUE TITLE
Compilation errors on fresh clone due to unconstrained dependencies

### ISSUE THREAD

**Issue by bltavares** [Kethku/neovide#561]
Hello there, the screenshots of the project look amazing!

I'm trying out the project on a Mac, from a fresh clone, and it seems that `skulpin` has been updated and the compilation don't work anymore due to rename of the features for sdl on version 0.12.0.

This led me trying to update to a fixed version of `skulpin`, which requires an upgrade of `skia-safe` and `rafx`, which then led me into errors on the project imports.

I haven't been able to try to fix it further, but I thought of letting you know about fresh clones.

**Comment by Kethku** [comment]
Very weird. https://github.com/Kethku/neovide/runs/2339693780?check_suite_focus=true the CI seems to indicate that the mac build is working fine. What branch were you building from?

**Comment by bltavares** [comment]
I'm running from `main`


```
 ~/repos/neovide % (main=) cargo install --git https://github.com/Kethku/neovide --branch main
    Updating git repository `https://github.com/Kethku/neovide`
  Installing neovide v0.7.0 (https://github.com/Kethku/neovide?branch=main#d8d6f4ea)
    Updating crates.io index
    Updating git repository `https://github.com/kethku/nvim-rs`
    Updating git repository `https://github.com/linebender/skribo`
    Updating git repository `https://github.com/aclysma/skulpin`
error: failed to compile `neovide v0.7.0 (https://github.com/Kethku/neovide?branch=main#d8d6f4ea)`, intermediate artifacts can be found at `/var/folders/3l/gmb8fzc51qsg2mf4426vn80c0000gn/T/cargo-installv1DR50`

Caused by:
  failed to select a version for `skulpin`.
      ... required by package `neovide v0.7.0 (/Users/bruno/.cargo/git/checkouts/neovide-35332cc81b2f0340/d8d6f4e)`
  versions that meet the requirements `*` are: 0.13.0

  the package `neovide` depends on `skulpin`, with features: `skulpin_sdl2` but `skulpin` does not have these features.


  failed to select a version for `skulpin` which could resolve this conflict
```

**Comment by bltavares** [comment]
Interesting... `cargo build` works, but `cargo install --path .` don't 🤔 

Maybe there is something different on how `cargo` uses `Cargo.lock` on those processes.

**Comment by bltavares** [comment]
Ah! Found it! https://github.com/rust-lang/cargo/issues/7169

**Comment by bltavares** [comment]
🎉 `cargo install --path . --locked` works :)

I'll close the issue - it was my mistake.
