### ISSUE TITLE
how to make nvim server not to shutdown when a neovide client closes connection

### ISSUE THREAD

**Issue by LXYYY** [Kethku/neovide#566]
Hello, I am using neovide with remote tcp mode. When I start `nvim --headless --listen localhost:6666` in a remote machine, I can connect to it with neovide just as introduced. But I wonder if there is a way to leave remote nvim still running, when I close neovide in my end? So far, the remote nvim automatically stops, when neovide is closed.

**Comment by Kethku** [comment]
This is an interesting point. I think this should be fixable

**Comment by rashil2000** [comment]
Is there any update on this? This is really essential :(

**Comment by Kethku** [comment]
No update. I'm happy to take a PR though. It shouldn't be too hard to adjust
