### ISSUE TITLE
[Linux] Vulkan SDK

### ISSUE THREAD

**Issue by maxdevjs** [Kethku/neovide#57]
Steps I took on [Solus](https://getsol.us/home/), but should be the same for other distros: 

- downloaded [Vulkan SDK for Linux](https://vulkan.lunarg.com/sdk/home)
- sourced /PATH/TO//vulkansdk-linux-x86_64-1.1.130.0/1.1.130.0/setup-env.sh in the shell in which I'd compile `Neovide`
- enjoyed 

I can send a PR, if worth for you.

**Comment by Kethku** [comment]
That would be great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Merged.
