### ISSUE TITLE
Some fonts missing

### ISSUE THREAD

**Issue by LXYYY** [Kethku/neovide#570]
Hello, I am using nerdtree, its git and dev_icon pluggins. But there is some fonts missing in neovide window, which works fine in terminal however.
for example, in neovide window:
![image](https://user-images.githubusercontent.com/15899704/115107798-a615e000-9f9f-11eb-976e-17a94498fdd9.png)
![image](https://user-images.githubusercontent.com/15899704/115107835-cba2e980-9f9f-11eb-8fc8-0da00281c173.png)

in terminal:
![image](https://user-images.githubusercontent.com/15899704/115107812-b1690b80-9f9f-11eb-9806-5221cf00529c.png)
![image](https://user-images.githubusercontent.com/15899704/115107831-c34aae80-9f9f-11eb-9ab2-ffa40cd650b4.png)

I already set guifont to jetbrain mono nerd which I think should work well with these plugins, but still missing some fonts.

Any idea?

**Comment by LXYYY** [comment]
FYI its in remote tcp mode

**Comment by Kethku** [comment]
This is due to font fallback. If you can find what font produces those glyphs you can add the font name to your guifont setting by separating font names by a comma. This will be fixed eventually by https://github.com/Kethku/neovide/issues/444

Closing as repeat
