### ISSUE TITLE
Cursor jumps around aimlessly

### ISSUE THREAD

**Issue by SirJson** [Kethku/neovide#58]
I noticed that the cursor stops working correctly as soon as I maximise the application window. 
It's not gone completely, it feels more like it doesn't know where it should be.

![max](https://user-images.githubusercontent.com/1042414/73191028-2647ef80-4127-11ea-9f83-350854c5305b.png)

As soon as I make the window smaller the cursor is back.

![small](https://user-images.githubusercontent.com/1042414/73191043-2ba53a00-4127-11ea-9650-3db3a43cf624.png)

This might be related to my vim settings and the resolution I'm running, because as soon as I disable my init.vim the cursor works. I'm not using any Windows UI scaling.

I'm running NVIM 0.4.2 on Windows Build 19041.21.

I will update this later issue if I find the setting which is causing this behaviour. I have a huge rcfile so going trough everything will need some time.

**Comment by Kethku** [comment]
This is interesting. It looks like it is trying to jump to the line number at the bottom. I'll probably have to configure a deadzone of some sort...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
I rewrote the animation loop. Could you try again? I do think this is related to the line number, but it may also be the cursor not animating back to the text location.

**Comment by SirJson** [comment]
Still the same behaviour. I started with removing subfiles from my config to find more information but nothing yet. I will probably start searching again tomorrow or the day after.

**Comment by Kethku** [comment]
Any chance you could make a gif? I'm struggling to understand all of the details.

**Comment by SirJson** [comment]
Yea this is kinda hard to describe and english isn't my first language but I managed to record it.

![cursor-on-caffeine](https://user-images.githubusercontent.com/1042414/73285785-d6d0f480-41f6-11ea-9449-ff3cb344cd53.gif)

The bad part about it is that it looks like it also happens on any window size. 

But I did some testing today on another computer, same NVIM Version, same neovide build running on Windows 10 1903 with an Intel iGPU and I had no cursor bug with my rc file.

I also tried just running nvim + my config in a terminal on my machine  and there is no cursor bug.

So still think the cause must be a plugin or something because without init.vim everything works. But since your app is Vulkan as I'm understand it and I'm running a 144hz display with an Nvidia GPU that this combination might be the source.

I will update you when I know more...

**Comment by Kethku** [comment]
Just some extra details. This happens because neovim jumps the cursor to any place the text changes in the command line. I'm not really sure why it does this, but if this becomes an issue for other folks we could play with a black list of regions where the cursor should not go.

**Comment by svermeulen** [comment]
Just to give my two cents here, I think it'd be useful to disable doing the cursor blend effect to the command line completely.  I get similar issues and its jarring to see and not helpful

**Comment by Kethku** [comment]
I'm torn. For some the big selling point is learnability and for that situation, when the cursor jumps for search, an arrent command etc it is nice for the cursor to animate down. I will definitely add an option but I'm not sure disabling it for all situations is the play

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SirJson** [comment]
Mh now I'm confused. My problem that was as seen in the gif (or not) was when I go in the insert mode and move the cursor it just jumps somewhere else but not where I am in insert mode.

I understand that the cursor might jump to the line number for updating (after all neovim at it's core is a terminal application). But shouldn't it:

1. be so fast that you don't see it
2. in the end be back at the actual cursor position I would be at the moment?

**Neovim running directly in the Terminal didn't show my problem and worked fine**. That's why I think this wasn't user error but some hard to find bug.
