### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by noponn8000** [Kethku/neovide#580]
I am running Pop!_OS and compiled neovide from source. It also has a lot of other errors regarding Fontconfig:
`Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file`
I do not include all of them because it is a few hundred lines.

**Comment by Kethku** [comment]
I'm not sure what would be causing this as I don't know how linux machines handle fonts. I made some changes to the way fonts are loaded on linux in the Opengl branch. Can you try there?

**Comment by noponn8000** [comment]
I have compiled it again, this time running into a different error:
`Ignored client type property: "methods"
Ignored client type property: "attributes"
fish: “target/release/neovide” terminated by signal SIGSEGV (Address boundary error)`

**Comment by fedusiv** [comment]
Hi! I have the same issue.
I checkouted to opengl branch and have same issue as @noponn8000

**Comment by Selich** [comment]
Same issue here

**Comment by j4qfrost** [comment]
I am investigating this in relation to creating a snap. I'll probably have
more to say after this weekend.

**Comment by fedusiv** [comment]
I also have  Pop!_OS 20.10.

**Comment by fedusiv** [comment]
Checked on ubuntu 20.04.2
Same error on from master branch build.
From opengl build missing -lfontconfig. I installed libfontconfig1 libfontconfig1-dev it helped to build. but then segmentation fault error.

Build from master gives these errors.
```
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file
Ignored client type property: "methods"
Ignored client type property: "attributes"
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

RUST_BACKTRACE returns nothing more.

**Comment by Kethku** [comment]
A fix for font_config issues is described here: https://github.com/Kethku/neovide/issues/465
Surface creation errors will be addressed here: https://github.com/Kethku/neovide/issues/491
