### ISSUE TITLE
Minimap not rendering on OpenGL branch

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#581]
When using the OpenGL branch on macOS, my minimal plugin is not rendering (supposed to be in the bar on the right hand side): 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/115821771-68ff8280-a3d1-11eb-8193-a4a8f3f9843a.png">

The minimal works fine in the Vulkan build, the plugin in question is this: https://github.com/wfxr/minimap.vim

Not sure what is causing the issue, but as the plugin relies on rust, maybe its a communication issue with rust?

**Comment by Kethku** [comment]
This is actually a font fallback issue. Can you try looking up which font has the relevant glyphs and add it to your guifont configuration?

**Comment by Kethku** [comment]
You can specify multiple font names by separating them with commas

**Comment by shaunsingh** [comment]
The issue occurs with both the FiraCode Nerd Font, and the SFMono Nerd Font, I have my font configuration set here: 
![image](https://user-images.githubusercontent.com/71196912/116613071-40faac80-a906-11eb-8c58-938612deadd7.png)

**Comment by Kethku** [comment]
Yes, but both of those fonts neglect to add the relevant braille. Neovide fails to do automatic font fallback as outline here: https://github.com/Kethku/neovide/issues/444, so you need to find a font which supports those glyphs and then add it to the manual fallback list.

**Comment by Kethku** [comment]
At least thats my current theory. I could very well be wrong.

**Comment by shaunsingh** [comment]
I see, so in the guifont option, I should just add multiple fonts with commas?

**Comment by Kethku** [comment]
thats right. Something like `Fira_Code,Consolas:h12` or whatever for your font list

**Comment by shaunsingh** [comment]
Are there any fonts that you know of and recommend? Ive tried adding Apple Braille, as well as Monaco, but neither corrected the issue

**Comment by shaunsingh** [comment]
I changed it to the following line in my init.vim

'set guifont=FiraCode\ Nerd\ Font:h13,Courier:h13,Menlo:h13,Monaco:h13,Apple\ Braille:h13,SF\ Mono:h13'

Now some characters show with a question mark like this: 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/71196912/116616150-52de4e80-a90a-11eb-8d4b-9918df0d06ba.png">

**Comment by Kethku** [comment]
Ah yeah. Don't set the size for all of them. 
'set guifont=FiraCode\ Nerd\ Font,Courier,Menlo,Monaco,Apple\ Braille,SF\ Mono:h13'
do something like this instead.

**Comment by shaunsingh** [comment]
Sadly that still results in the same issue

**Comment by shaunsingh** [comment]
![image](https://user-images.githubusercontent.com/71196912/116621049-9c319c80-a910-11eb-8893-d4f879a8b1be.png)

If I set DejaVu as the only font, it works perfectly. Not sure what's going wrong when I add both fonts

**Comment by Shatur95** [comment]
I have problems with fonts too. How to use the application correctly to avoid font issues?

**Comment by shaunsingh** [comment]
I never figured out how to fix the issue, sorry. 1 font at a time seems to work fine but more than one at a time doesn't work

**Comment by Shatur95** [comment]
In my case, it does not work even with the indication of single font.

**Comment by Kethku** [comment]
Closing as repeat of https://github.com/Kethku/neovide/issues/444
