### ISSUE TITLE
Character set issue on macOS?

### ISSUE THREAD

**Issue by pkout** [Kethku/neovide#585]
I built Neovide from the source code on macOS, but when I open the program, all characters look like it's using the wrong font or character set.![Screen Shot 2021-04-23 at 7 45 06 PM](https://user-images.githubusercontent.com/4543279/115944842-1a072b00-a46d-11eb-882f-f8b27c659cca.jpg)

**Comment by Kethku** [comment]
What do you have guifont set to in your vim config? Can you try a different font?

**Comment by pkout** [comment]
I have this font

```
set guifont=Droid\ Sans\ Mono\ Slashed\ for\ Powerline:h13
```

Removing that font made it work. Thank you! Is there anything I can do to make it work with that font? That font is important for the theme I am using for my neovim setup.

**Comment by haringsrob** [comment]
@pkout can you try with Lua:

```
vim.o.guifont = "Droid Sans Mono Slashed for Powerline"
```

**Comment by pkout** [comment]
@haringsrob Sorry, where do I enter this? I tried to add it to vimrc config, but it didn't recognize it.

**Comment by SergeyPoznyakAkvelon** [comment]
Having the same issue.

> @pkout can you try with Lua:
> 
> ```
> vim.o.guifont = "Droid Sans Mono Slashed for Powerline"
> ```

This suggestion produces the same result

**Comment by SergeyPoznyakAkvelon** [comment]
One workaround is to use a non powerline/nerdfont by default and a nerdfont as a fallback:

```viml
set guifont=Fira\ Code,FiraCode\ Nerd\ Font\ Mono:h15
```

Or lua:
```viml
lua <<EOF
vim.o.guifont = 'Fira Code,FiraCode Nerd Font Mono:h15'
EOF
```

**Comment by Kethku** [comment]
This has been fixed in main. Please reopen if you continue to see this issue.
