### ISSUE TITLE
Selecting previous visual region canceled after indent

### ISSUE THREAD

**Issue by ijimiji** [Kethku/neovide#587]
Consider the following remap
```
vnoremap > >gv
vnoremap < <gv
```
This should keep region selected after shifting it.
The problem is that it doesn't work with shifting region to the left, but works fine with shifting to the right:
![neovide](https://user-images.githubusercontent.com/70969307/115981273-2e494600-a59b-11eb-83d0-13408f2eccce.gif)
It works fine in terminal like so:
![vim](https://user-images.githubusercontent.com/70969307/115981326-841dee00-a59b-11eb-9ef8-0aa6650e7f0c.gif)

Neovide version: `0.7.0`
AUR package I'm using applies the following patch `  sed -i 's/debug = true/opt-level = 3\ndebug = false/' Cargo.toml`.
And builds with 
```
  export CFLAGS="-fcommon -fPIE"
  export RUSTUP_TOOLCHAIN=stable
  cargo build --release
```
Neovim version:
```
NVIM v0.5.0-dev+1267-g7bf62ab02
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -
Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagno
stics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN
_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim
/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/ne
ovim/build/include
Compiled by runner@fv-az166-102
Features: +acl +iconv +tui
```
System:
`Linux archlinux 5.11.11-arch1-1`

**Comment by Kethku** [comment]
This is definitely a bug with the mouse handling somehow. Does it occur with multigrid enabled and disabled?

**Comment by Kethku** [comment]
Actually thats likely unrelated. I'm guessing its because we send angle brackets escaped when open but not when closed or something similar.

**Comment by Kethku** [comment]
This is fixed in main
