### ISSUE TITLE
numlock does not toggle

### ISSUE THREAD

**Issue by azarmadr** [Kethku/neovide#588]
numlock toggling does not change the keypad working. when numlock is off, i should get ohter functions like `home` for 7 key, `page up` for 9 so on. is there a setting i am missing.

**Comment by PyGamer0** [comment]
Pretty sure, related to #445

**Comment by Kethku** [comment]
That seems possible. May also just be an sdl2 thing... Can you try on with the winit feature flag, or on the opengl branch?

**Comment by Kethku** [comment]
I believe this is fixed in main, but I don't have a numpad to test it with. Please reopen if the problem persists.
