### ISSUE TITLE
Treat spelling squiggles as squiggles and not straight underline

### ISSUE THREAD

**Issue by epage** [Kethku/neovide#59]
Just having an underline is a huge improvement over a TUI which uses fg and bg colors and a lot of themes don't deal with it properly, but using squiggles instead of straight underline will also help make these distinctive to scan for.

**Comment by Kethku** [comment]
Weird question, but I don't have a reliable way to test squiggles. Is there a config that will make them show up every time?

**Comment by epage** [comment]
1. Open a file with a `.txt` extension
2. `:set spell`
3. Type `Helo World`

and in MacVim I get a spelling error

(apparently, MacVim, unlike gvim, does an underline instead of a squiggle)

**Comment by Kethku** [comment]
Ok awesome. I will get it working soonish

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Done. Implemented via a dash effect as that was easiest for now and I think it looks nicer even though its not exactly standard.
