### ISSUE TITLE
Unable to launch neovide on the opengl branch

### ISSUE THREAD

**Issue by Mango0x45** [Kethku/neovide#591]
After installing neovide following the instructions for arch and running it, neovide instantly crashes. Here is the output.
```
[thomas@mango-os neovide-git $] RUST_BACKTRACE=full neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14
stack backtrace:
   0:     0x55faa14e93a0 - <unknown>
   1:     0x55faa137394c - <unknown>
   2:     0x55faa14e8c11 - <unknown>
   3:     0x55faa14e8575 - <unknown>
   4:     0x55faa14e7c5a - <unknown>
   5:     0x55faa150713e - <unknown>
   6:     0x55faa15070dc - <unknown>
   7:     0x55faa150708d - <unknown>
   8:     0x55faa1371100 - <unknown>
   9:     0x55faa1370f1c - <unknown>
  10:     0x55faa12caae6 - <unknown>
  11:     0x55faa12ca84a - <unknown>
  12:     0x55faa12bcb79 - <unknown>
  13:     0x55faa129c543 - <unknown>
  14:     0x55faa12b9d55 - <unknown>
  15:     0x7f1c1d18eb25 - __libc_start_main
  16:     0x55faa1280d5e - <unknown>
  17:                0x0 - <unknown>
```
I also edited the PKGBUILD to get the opengl branch.
```bash
source=("${pkgname}::git+${url}#branch=opengl")
```

**Comment by ErorHandler** [comment]
I think that if you have the ubuntu font family installed in your system (as stated here: https://github.com/Kethku/neovide/issues/491#issuecomment-825061755) the problem goes away, as neovide consider this font to be the default fallback and if it can't find it, it crashes.

**Comment by Mango0x45** [comment]
I installed the fonts package mentioned there, and I am now segfaulting when trying to run it.
```
[thomas@mango-os Ban-Player $] neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
Segmentation fault (core dumped)
```

**Comment by ErorHandler** [comment]
Are you on master or opengl branch? I only experienced and fixed it on the opengl branch.

**Comment by Mango0x45** [comment]
I am on the opengl branch

**Comment by Kethku** [comment]
I currently see that segfault on my local ubuntu install but have no idea how to debug it. Weirdly when I run with a debugger attached such as https://rr-project.org/ the bug goes away.

As a side note, I have exactly zero idea how to debug something like this on linux, so if anybody encountering this would be able to give some pointers or suggestions, it would be greatly appreciated.

**Comment by mr-chrome** [comment]
> I installed the fonts package mentioned there, and I am now segfaulting when trying to run it.
> 
> ```
> [thomas@mango-os Ban-Player $] neovide
> Ignored client type property: "methods"
> Ignored client type property: "attributes"
> Segmentation fault (core dumped)
> ```

Exactly the same for me. Running on Arch Linux, opengl branch.

**Comment by Kethku** [comment]
CLosing this issue as repeat of the main opengl issue. Progress is being made there.
