### ISSUE TITLE
Blurrying broken in neovim

### ISSUE THREAD

**Issue by mnowotnik** [Kethku/neovide#592]
![Screenshot from 2021-04-26 00-36-19](https://user-images.githubusercontent.com/8244123/116011872-b15bb200-a616-11eb-97bc-0301fbf2aff9.png)
It's a screenshot of a file searching dialog from nvim plugin, [Telescope](https://github.com/nvim-telescope/telescope.nvim) .

**Comment by PyGamer0** [comment]
Related to #512, happens even for me.
