### ISSUE TITLE
command line menu renders in incorrect position

### ISSUE THREAD

**Issue by mnowotnik** [Kethku/neovide#593]
![Screenshot from 2021-04-26 00-38-34](https://user-images.githubusercontent.com/8244123/116011973-4068ca00-a617-11eb-8d7e-0fd994fcff7d.png)
The longer the list, the higher it gets rendered. I think some control characters are wrongly interpreted.
![Screenshot from 2021-04-26 00-37-37](https://user-images.githubusercontent.com/8244123/116011988-58d8e480-a617-11eb-9a3b-6a656731feaf.png)

**Comment by PyGamer0** [comment]
Upstream Issue.
https://github.com/neovim/neovim/pull/14128

**Comment by mnowotnik** [comment]
``
