### ISSUE TITLE
I can't open the neovide after compling it

### ISSUE THREAD

**Issue by Logan147** [Kethku/neovide#595]
#I can't open the neovide after compling it as the installing , these are my computer config  and the error info /who can help me please!!!     

when  i  try to open the neovide ,it just appear and disapper very fast and give me an error
![2021-04-26_13-05](https://user-images.githubusercontent.com/58822519/116031525-7007e880-a690-11eb-8528-9437441d44aa.png)
![2021-04-26_13-05_1](https://user-images.githubusercontent.com/58822519/116031570-84e47c00-a690-11eb-8d70-21611de65346.png)

**Comment by MartinJindra** [comment]
Hi @Logan147,
I also have this exact problem while installing neovide version 0.7.0 . I assume that you also installed it through the AUR. But I found a work around. I modified the PKGBUILD of the AUR script to compile and install neovide version 0.5.0 . 
[PKGBUILD.txt](https://github.com/Kethku/neovide/files/6376563/PKGBUILD.txt)
Just rename the file `PKGBUILD.txt` to `PKGBUILD` (I had to name it that way because Github needs a file extension) and then compile it with `makepkg -si`.

**Comment by Kethku** [comment]
THis is a vulkan error. Means that your machine doesn't have proper libraries installed, or maybe an incompatibility with the vulkan renderer.

Could you try the opengl branch?

**Comment by Logan147** [comment]
OK,i wiil try it

**Comment by Logan147** [comment]
thankyou for your help

**Comment by Logan147** [comment]
i have tryed the PKGBUILD.txt method but it alse give me the same error, then how to use the opengl branch to compile it?
![2021-04-27_09-57](https://user-images.githubusercontent.com/58822519/116173558-65585c80-a73f-11eb-90f6-e6ce081f6cb3.png)

**Comment by Kethku** [comment]
Try downloading a binary from https://github.com/Kethku/neovide/actions/runs/787373460

**Comment by Chaitanyabsprip** [comment]
fails with the following error
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
output from `RUST_BACKTRACE=full ./neovide`
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14
stack backtrace:
   0:     0x559fcd589a00 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x559fcd589a00 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559fcd589a00 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x559fcd589a00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x559fcd43a20f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/fmt/mod.rs:1094:17
   5:     0x559fcd589234 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/io/mod.rs:1580:15
   6:     0x559fcd588ccb - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x559fcd588ccb - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x559fcd588ccb - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:208:50
   9:     0x559fcd587fe5 - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:225:9
  10:     0x559fcd587fe5 - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:591:17
  11:     0x559fcd5a38ee - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:495:13
  12:     0x559fcd5a388c - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x559fcd5a383d - rust_begin_unwind
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
  14:     0x559fcd333b00 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
  15:     0x559fcd333a4c - core::panicking::panic::h3de4db67bd397eb3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
  16:     0x559fcd3a483a - neovide::renderer::fonts::caching_shaper::CachingShaper::metrics::h21c66c10e86cc428
  17:     0x559fcd3a45b7 - neovide::renderer::fonts::caching_shaper::CachingShaper::font_base_dimensions::h7b0face31d325eff
  18:     0x559fcd42945f - neovide::renderer::Renderer::new::h4ea05dcc1b34feaf
                               at /home/runner/work/neovide/neovide/src/renderer/mod.rs:64:49
  19:     0x559fcd42945f - neovide::window::create_window::h8a42fe13390a95ed
                               at /home/runner/work/neovide/neovide/src/window/mod.rs:97:20
  20:     0x559fcd42945f - neovide::main::ha868c9eca264ad98
                               at /home/runner/work/neovide/neovide/src/main.rs:179:5
  21:     0x559fcd3d3136 - core::ops::function::FnOnce::call_once::h6453fe15a924a0f1
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/ops/function.rs:227:5
  22:     0x559fcd3d3136 - std::sys_common::backtrace::__rust_begin_short_backtrace::hce363a05a07b2790
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x559fcd425886 - main
  24:     0x7f7db2bffb25 - __libc_start_main
  25:     0x559fcd34a16e - _start
  26:                0x0 - <unknown>
```

**Comment by danielnehrig** [comment]
https://github.com/Kethku/neovide/actions/runs/787373460
linux bin segfaults for me
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
[1]    73722 segmentation fault (core dumped)  ./neovide
```

**Comment by Logan147** [comment]
i have download the binary and try it, but the result is the same as <danielnehrig > ,this is my flameshot
![2021-04-28_18-20](https://user-images.githubusercontent.com/58822519/116388484-747a0000-a84e-11eb-98a0-cccee9237ae2.png)

**Comment by Kethku** [comment]
@Chaitanyabsprip your issue is that you need to set the guifont in your vim config.

@danielnehrig @Logan147 I need some help from you if you are willing. I have encountered this issue in the opengl branch on some linux machines, but not others (it doesn't happen in my wsl install). I don't have the relevant experience to debug this myself on linux so any investigation you would be willing to do would be greatly appreciated.

**Comment by Chaitanyabsprip** [comment]
let me know what you want me to do

**Comment by Lord-Valen** [comment]
@Logan147 Try this:
```sh
git clone https://aur.archlinux.org/neovide-git.git
cd neovide-git
nvim PKGBUILD
:%s/l}/l}#branch=branch-name-here/
:wq
makepkg -si
```

**Comment by Lord-Valen** [comment]
Where it says "branch-name-here" substitute "opengl".

**Comment by Kethku** [comment]
@Chaitanyabsprip try installing noto sans mono, or adding set guifont="{font name}:h12" in your vim config

**Comment by Chaitanyabsprip** [comment]
so I tried installing noto fonts, and now neovide is working. but before I installed the fonts. I tried setting the font name as `set guifont="Hack\ Nerd\ Font:h12"` and it wasnt working then, even after it is working now, it is not respecting the guifont option of nvim

**Comment by Chaitanyabsprip** [comment]
got it working
the issue was I was using quotes to set guifont, the correct way is `set guifont=Hack\ Nerd\ Font:h12`

**Comment by danielnehrig** [comment]
using lua
`vim.cmd('set guifont=Hack Nerd Font Mono:h12')`
even with escaping \
it does not work for me still seg fault on opengl branch
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
[1]    141649 segmentation fault (core dumped)  ./neovide
```

**Comment by Chaitanyabsprip** [comment]
You have to escape the spaces
`vim.cmd('set guifont=Hack\ Nerd\ Font Mono:h12')

**Comment by Kethku** [comment]
the segfault is a different known issue with the opengl branch. A fix has been proposed but I haven't gotten the time to add it in yet.

**Comment by Kethku** [comment]
I just merged a pr with the fix. @danielnehrig can you try the new commit in the opengl branch?

**Comment by Lord-Valen** [comment]
@Kethku With the latest version of the OpenGL branch, I no longer segfault. Your pr probably fixed the issue. @danielnehrig If you could compile the latest version of the OpenGL branch to confirm, that would be great.

**Comment by Kethku** [comment]
I just merged opengl into main. I'm going to close this, but if anybody continues to have issues here building from main, either reopen here or create a new issue.
