### ISSUE TITLE
Movements are not being repeated when the keys remain presssed

### ISSUE THREAD

**Issue by itaranto** [Kethku/neovide#600]
For example, to scroll down, I cannot press `j` and leave it pressed, I have to constantly press the button.

The same with other movements like `h`, `k`, `l`, `w`, `b`, etc.

Environment:
OS: Arch Linux
DE/WM: Sway
Neovide version: 0.7.0-1

**Comment by SuperBo** [comment]
I have the same issue

**Comment by itaranto** [comment]
This seems to be a Wayland issue, since I'm not able to reproduce it using i3.

**Comment by Kethku** [comment]
I am not a linux person. Can you help me understand, I thought wayland was a window rendering system while i3 was a window manager. Are they the same thing?

**Comment by itaranto** [comment]
> I am not a linux person. Can you help me understand, I thought wayland was a window rendering system while i3 was a window manager. Are they the same thing?

You are totally right. I thought it was understood, i3 is an X11 WM, it depends on X11, while Sway is a Wayland compositor and also a WM.
So, neovide doesn't seem to have this bug under X11 (using i3 in my case).

**Comment by Kethku** [comment]
Does the same problem happen in the opengl branch?

**Comment by itaranto** [comment]
> Does the same problem happen in the opengl branch?

I didn't try. I'll check later.

**Comment by SuperBo** [comment]
> Does the same problem happen in the opengl branch?

opengl branch does not have this issue. I have just tested with opengl branch, everything is fine except `app_id` is set to null.

**Comment by SuperBo** [comment]
Update: Shift+key doesn't work in opengl branch. Can't input some character like ~,!

**Comment by ferreus** [comment]
> Update: Shift+key doesn't work in opengl branch. Can't input some character like ~,!

I had the same problem, tracked it down to winit issues, they have a bunch of problems on their github.
Solved it for now with this change:
```diff
diff --git a/src/window/window_wrapper/mod.rs b/src/window/window_wrapper/mod.rs
index 0569c74..615b658 100644
--- a/src/window/window_wrapper/mod.rs
+++ b/src/window/window_wrapper/mod.rs
@@ -13,7 +13,7 @@ use glutin::{
     dpi::{LogicalPosition, LogicalSize, PhysicalSize},
     event::{
         ElementState, Event, ModifiersState, MouseButton, MouseScrollDelta,
-        VirtualKeyCode as Keycode, WindowEvent,
+        VirtualKeyCode as Keycode, WindowEvent, DeviceEvent
     },
     event_loop::{ControlFlow, EventLoop},
     window::{self, Fullscreen, Icon},
@@ -302,8 +302,8 @@ impl GlutinWindowWrapper {
                     ))
                     .ok();
             }
-            Event::WindowEvent {
-                event: WindowEvent::KeyboardInput { input, .. },
+            Event::DeviceEvent {
+                event: DeviceEvent::Key(input),
                 ..
             } => {
                 if input.state == ElementState::Pressed {
```

The DeviceEvent for now appears to work correctly, but if i understood correctly, they going to break it too.

**Comment by Kethku** [comment]
This issue is in progress in the keyboard rework pr. Also opengl has been merged to main and is being iterated on there

**Comment by Kethku** [comment]
This bug has been fixed in main. Please reopen if it persists

**Comment by SuperBo** [comment]
Great, I confirm neovide now work correctly under Wanland
