### ISSUE TITLE
Segmentation Fault on OpenGL branch.

### ISSUE THREAD

**Issue by Lord-Valen** [Kethku/neovide#614]
Running Artix Linux with the OpenGL branch.
Appears to be a guifont issue, but I can't seem to get around it.

`neovide` returns:
```sh
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14
```

Noto fonts are installed.
I have tried `set guifont=Inconsolata:h12`, `set guifont=Inconsolata\ Nerd\ Font:h12` and `set guifont=Inconsolata\ Nerd\ Font\ Mono:h12` in my init.vim. All of which should be real fonts with the correct names as shown by `fc-list | grep -i "inconsolata"`.

**Comment by Lord-Valen** [comment]
I've also tried the same config on a Manjaro machine to no avail.

**Comment by Lord-Valen** [comment]
The font issue is resolved after discovering Ubuntu fonts were not installed. Since `neovide` now results in a segmentation fault, I can't verify whether Neovide will use Inconsolata.

**Comment by Lord-Valen** [comment]
Duplicate of #591

**Comment by Kethku** [comment]
This segfault is referenced in the main opengl issue. closing as duplicate.
