### ISSUE TITLE
support bidirectional language 

### ISSUE THREAD

**Issue by hemedani** [Kethku/neovide#623]
please support bidirectional (right-to-left) language like `Persian` `Arabic` `Hebrew` and some others

with this font configuration :
```
set guifont=Cascadia\ Code\ Light,Hack\ Nerd\ Font,Adobe\ Arabic:h14
```
the rtl text shown like these
<img width="304" alt="Screen Shot 1400-02-14 at 14 05 23" src="https://user-images.githubusercontent.com/6236123/116985885-52ff9500-ace2-11eb-967a-bdfc34252e5b.png">

but in vscode text shown fine
<img width="514" alt="Screen Shot 1400-02-14 at 14 06 48" src="https://user-images.githubusercontent.com/6236123/116985952-6f033680-ace2-11eb-9865-7b6b2f038bee.png">

**Comment by Kethku** [comment]
To my knowledge, neovim does not support bidirectional language, or if it does I haven't seen good example of how it is done in guis. I think this is out of scope for neovide unfortunately unless somebody else is going to drive this. So I'm going to close this unfortunately. But if somebody wants to take this on, I'm all ears.
