### ISSUE TITLE
Backslash character \ doesn't work

### ISSUE THREAD

**Issue by AlexisFinn** [Kethku/neovide#630]
I can't use the backslash charater, `\`
This is currently mapped to my leader key which means I can't use <leader> shortcuts. I first noticed this with NerdCommenter not working but neither does Easymove or any other shortcuts.

I could remap my leader to something else, but actually even in Insert mode the key doesn't work, when i type a `\` in Insert mode it puts back in to Normal mode.

Funny thing it works fine in the command line (eg: I can search for `/\` or do `:\?...` just fine )
And of course it works fine in nvim or vim on the terminal (otherwise I wouldn't be bothering you)

My guess is it has something to do with the keyboard layout as I'm using French AZERTY, explaining why I can't seem to come across anybody else having issues. But the rest of the keys (event the french éêï etc...) work just fine.

If it helps, I'm running Ubuntu 20.04 with XMonad and I compiled from source.

**Comment by AlexisFinn** [comment]
P.S: I really want to make this work, I just came accross this gui this morning and already can't live without that fancy cursor movement. 
This project is just awesome

**Comment by Pebor** [comment]
Probably #445 ?
Currently waiting for winit to merge a fix to stable to implement

**Comment by AlexisFinn** [comment]
Nice. 

I'll be waiting expectantly as the absence of backslash character currently makes this unusable and me very sad.
Hope it gets merged soon.

**Comment by AlexisFinn** [comment]
Closing this for now at least untill can confirm whether #445 fixes the issue.

**Comment by gmr458** [comment]
I have the same problem, I use Neovide 0.7.0 and Windows 10, Is this fixed?

**Comment by Kethku** [comment]
Could you try building from main?
