### ISSUE TITLE
M1 mac cannot build 

### ISSUE THREAD

**Issue by Kotodian** [Kethku/neovide#637]
![image](https://user-images.githubusercontent.com/22030659/117561265-c9780a80-b0c7-11eb-8043-8ed41d111b96.png)

**Comment by j4qfrost** [comment]
Can you try the opengl branch? There is currently not a clean way to resolve this. Here is an artifact for the latest opengl build https://github.com/Kethku/neovide/suites/2663669197/artifacts/58642909

**Comment by Kotodian** [comment]
> Can you try the opengl branch? There is currently not a clean way to resolve this. Here is an artifact for the latest opengl build https://github.com/Kethku/neovide/suites/2663669197/artifacts/58642909

it's not useful.It cannot be installed

**Comment by Kotodian** [comment]
![Uploading image.png…]()

**Comment by Kotodian** [comment]
![image](https://user-images.githubusercontent.com/22030659/117562547-56c05c80-b0d2-11eb-8147-c0b54d842ded.png)

**Comment by Kotodian** [comment]
> Why did you close the issue? Is it resolved?

yes

**Comment by freefly801213** [comment]
Could you share with us how to solve this problem? thanks.

**Comment by Kotodian** [comment]
> Could you share with us how to solve this problem? thanks.

I just built the program in opengl branch

**Comment by freefly801213** [comment]
> > Could you share with us how to solve this problem? thanks.
> 
> I just built the program in opengl branch

thanks.
