### ISSUE TITLE
Cursor is not aligned when I input Chinese

### ISSUE THREAD

**Issue by supikachu** [Kethku/neovide#638]
cursor is not aligned when i enter some Chinese. Sometimes, word will be covered by the previous word
![2](https://user-images.githubusercontent.com/39306199/117561556-75baf080-b0ca-11eb-8410-46ed134b123c.gif)

**Comment by Kethku** [comment]
This is likely due to double width character handling.

**Comment by notfornothing** [comment]
> cursor is not aligned when i enter some Chinese. Sometimes, word will be covered by the previous word
> ![2](https://user-images.githubusercontent.com/39306199/117561556-75baf080-b0ca-11eb-8410-46ed134b123c.gif)

hi,how did you solve the Chinese garbled problem?
My Chinese characters will be replaced with ``? ``
And I cannot input Chinese in neovide.

On the left is the normal display of notpad, and on the right is the neovide error display.
![image](https://user-images.githubusercontent.com/43561526/121798776-cf2eb600-cc5a-11eb-8b03-d4020a0de68d.png)

**Comment by Kethku** [comment]
This has been fixed
