### ISSUE TITLE
Nerd Fonts not working

### ISSUE THREAD

**Issue by codic12** [Kethku/neovide#639]
~~Installed and configured Neovide, mostly going smoothly so far. I'm not insane enough to use emojis in source code, but in the off chance I run into it in a comment or something, it seems to render as a box. (Just encountered while installing coc.nvim) This is strange, because my regular terminal displays the emoji (and it is set to the same font, Noto Sans Mono), plus Neovide has some fallback emoji font hardcoded in :thinking: 

I have my fontconfig set to prefer Twemoji for emojis, that works fine elsewhere.~~

**Comment by codic12** [comment]
Never mind, it wasn't an emoji, but a nerd font symbol; I feel silly now. Closing this

**Comment by codic12** [comment]
I'm reopening this, because after setting my font explicitly to a Nerd one, Neovide still doesn't display those glyphs but other neovim guis do...

**Comment by Kethku** [comment]
This is a repeat of https://github.com/Kethku/neovide/issues/444. In the meantime you can specify multiple fonts by separating the font names by commas in the guifont option.

**Comment by codic12** [comment]
Got it, thanks
