### ISSUE TITLE
Cursor freezes sometimes

### ISSUE THREAD

**Issue by Kotodian** [Kethku/neovide#640]
![image](https://user-images.githubusercontent.com/22030659/117564561-39de5600-b0df-11eb-8103-895c8cd06976.png)
![image](https://user-images.githubusercontent.com/22030659/117564572-4c588f80-b0df-11eb-9c0a-cc720c25938c.png)

**Comment by j4qfrost** [comment]
Is this using opengl?

**Comment by Kotodian** [comment]
> Is this using opengl?

yes

**Comment by j4qfrost** [comment]
Making a note for investigation later: https://github.com/flutter/flutter/issues/73339

I don't know if I'll be able to help much as I don't have an M1 chip.

**Comment by shaunsingh** [comment]
Try using it with a clean Init.vim. This occasionally happens on my openGL build with an m1 Mac, I found it was because of the YCM plugin (which I replaced with nvim-lsp)

Not sure why it happens

**Comment by shaunsingh** [comment]
Looks like it was fixed a while back though: https://skia-review.googlesource.com/c/skia/+/350336, are the dependencies up to date?

**Comment by Kethku** [comment]
The weird thing is resizing the window sorta unblocks it on my machine. I'm very confused by this issue...

**Comment by Kethku** [comment]
I may try to make a minimal repro of this in a demo app and then raise an issue upstream at skia-safe. I figure just an animating circle using glutin and our basic window setup should be enough.

**Comment by PyGamer0** [comment]
For me it happens with a plugin that consistently write output to the command line .

**Comment by Kethku** [comment]
I believe this has been fixed. I haven't been able to repro it all day
