### ISSUE TITLE
Control zoom using Ctrl+<PLUS> and Ctrl+<MINUS>

### ISSUE THREAD

**Issue by luisiacc** [Kethku/neovide#645]
Would be great to have a control of the zoom, or font size, or maybe font size + scaled linespace(when linespace is implemented) by using the regular controls for that, Ctrl + <PLUS> to zoom in, Ctrl + <MINUS> to zoom out.

**Comment by PyGamer0** [comment]
You can use a plugin for this behavior [drzel/vim-gui-zoom](https://github.com/drzel/vim-gui-zoom] and map the 2 provided functions to c+`+` and c+`-`.

```
nmap <c-+> :ZoomIn<CR>
nmap <c--> :ZoomOut<CR>
```
**NOTE**: You have to define `guifont` in your init.vim for this to work as this plugin parses the guifont and changes the size.

**Comment by Kethku** [comment]
Yeah I agree with @PyGamer0 this is a vim question not a neovide question.
