### ISSUE TITLE
Neovide not reading .~/bashrc nor ~/.profile when using --wsl

### ISSUE THREAD

**Issue by luisiacc** [Kethku/neovide#647]
When running with the --wsl option, startup dotfiles like ~/.bashrc or ~/.profile are not read, causing to not have them by default on neovide.

**Comment by PyGamer0** [comment]
Neovide doesn't read `~/.bashrc`. I dont understand; what do you mean?

**Comment by luisiacc** [comment]
> Neovide doesn't read `~/.bashrc`. I dont understand; what do you mean?

Sorry if I didn't explain correctly, what I mean is, for example, I run a command like this `:r!poetry install something` and it says that `poetry command not found` , which is wrong because poetry is in the path, once I source ~/.profile file, poetry starts working again.

I choose `poetry` as an example, it happens with most commands that should be on the PATH.

**Comment by Kethku** [comment]
This will likely require starting the neovim process differently. It shouldn't be too hard to change. Currently the neovim process is started here: https://github.com/Kethku/neovide/blob/main/src/bridge/mod.rs#L72 via the wsl command. A different argument should be used instead?
