### ISSUE TITLE
Smooth scrolling jumps when a fold exits the screen above

### ISSUE THREAD

**Issue by hixan** [Kethku/neovide#648]
When any type of fold is scrolled out of view (when scrolling down only) the view jumps as if the view had been jumped the number of lines in the fold.
![smooth-scrolling-bug](https://user-images.githubusercontent.com/23721253/117902116-249c3e00-b310-11eb-8c64-8572aedc4da2.gif)

**Comment by Kethku** [comment]
Unfortunately I don't see a way around this. We hack in smooth scrolling by animating the window when the scroll position changes. I'm not sure how to hack around this issue since the scroll position changes when the fold closes

**Comment by Kethku** [comment]
Closing in favor of https://github.com/Kethku/neovide/issues/794
