### ISSUE TITLE
Doesn't start under wslg

### ISSUE THREAD

**Issue by purpleP** [Kethku/neovide#649]
I'm on thinkpad x1 carbon gen 8 with intel drivers installed.
```
./neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
Ignored style attribute: "standout"
thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window/sdl2/mod.rs:459:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems like this has something to do with vulkan drivers.

**Comment by Kethku** [comment]
try the opengl branch.

**Comment by Kethku** [comment]
I have gotten this running under wslg. You have to also install the graphics drivers for the wsl instance. In the meantime the expectation is that this will be supported from https://github.com/Kethku/neovide/issues/491
