### ISSUE TITLE
Compatible with skia-safe 0.35.1

### ISSUE THREAD

**Issue by ck3d** [Kethku/neovide#653]
I only want to mention, that neovide is compatible up to skia-safe version 0.35.1 . My PR to package neovide in Nix uses this version: https://github.com/NixOS/nixpkgs/pull/122998
It would be great if you could update skia-safe.

**Comment by Kethku** [comment]
I'm not sure I understand. Are you looking for us to update skia-safe to 0.39.1? Or are you looking for backwards compat?

**Comment by ck3d** [comment]
Your main branches uses skia-save version 0.32.1, which can be updated to 0.35.1 . In your opengl branch you use 0.39.1, which I did not look at.

**Comment by Kethku** [comment]
I'm trying to merge opengl soon, but its diverged somewhat. Thanks for the suggestion tho
