### ISSUE TITLE
Neovide doesn't use the configured font

### ISSUE THREAD

**Issue by brymer-meneses** [Kethku/neovide#660]
I am using the nightly builds for neovim and I have this on my `init.lua`

```
vim.cmd("source ~/.config/nvim/lua/extensions/neovide/init.vim")
```
This file contains the following command
```
set guifont=FiraCode\ Nerd\ Font\ SemiBold:h18
```

However the nerd font icons still won't appear

**Comment by PyGamer0** [comment]
Try removing `SemiBold` from the line

**Comment by brymer-meneses** [comment]
thank you @PyGamer0 !
