### ISSUE TITLE
Latest Neovim panicks when trying to load nvim-telescope

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#662]
Hi! When trying to run nvim-telescope in neovide I get the following error in the terminal: 

`ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

And the screen looks something like this: 

<img width="844" alt="image" src="https://user-images.githubusercontent.com/71196912/118583251-c41f5d80-b762-11eb-9724-4aa3a8870018.png">

This only started happening once I updated to the latest neovim --HEAD with Homebrew. Everything works fine under iterm2,  it only comes up when trying to launch from neovide

System Specifications: 
OS - macOS 11.3
neovide - latest commit from the OpenGL branch, launched with --multigrid 
nvim --version: 

```
NVIM v0.5.0-dev+1327-gdc18c1e3e
Build type: Release
LuaJIT 2.1.0-beta3
``

**Comment by shaunsingh** [comment]
Looks like it only happens when multigrid is enabled, it works without it. However, multigrid was working just a few days ago

**Comment by Kethku** [comment]
I'm guessing they broke the format in some strange way

**Comment by Kethku** [comment]
I just pulled recent neovim nightly and encountered a bunch of floating window related issues. Seems like something significant changed upstream that I missed.

**Comment by shaunsingh** [comment]
Yeah, looks like which key and the lsp popup menus are broken as well

**Comment by Kethku** [comment]
They get positioned in the top left of the screen which is super weird. I'll take a look

**Comment by Kethku** [comment]
I have identified the problem and have a fix locally.

**Comment by Kethku** [comment]
I pushed to opengl branch. Can you try it @shaunsingh

**Comment by shaunsingh** [comment]
Sure, ill get back to you once it finishes building

**Comment by shaunsingh** [comment]
same issue, 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/119197179-5bcbc700-ba55-11eb-8804-c856fca43d90.png">

**Comment by shaunsingh** [comment]
after a while, looks like the issue comes up at random
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/119205964-d7367400-ba67-11eb-93c3-b858efb311a0.png">
Sometimes it seems to work, sometimes it doesnt

**Comment by shaunsingh** [comment]
I think I found out how to replicate the issue 

If you open neovide from the terminal by launching the binary, then it works fine as long as the terminal is also open while the app is running. However, once you close the terminal, the app breaks.

**Comment by shaunsingh** [comment]
(closed by accident)

**Comment by shaunsingh** [comment]
Neovide also crashes sometimes while scrolling with multiGrid enabled, but 1. I can't seem to replicate it and 2. I'm not sure if it was caused by fix or present earlier

**Comment by Kethku** [comment]
I've been working on this. Its complicated by the fact that I can't find the breaking change list. Maybe I'm blind...

**Comment by Kethku** [comment]
I found https://github.com/neovim/neovim/issues/14090 but I think something else broke...

**Comment by SirJson** [comment]
I just made my daily neovim build to `NVIM v0.5.0-dev+1357-g192f89ea1` and the issue disappeared. Meaning in my case it looks like coincidence from using unstable daily build neovim, and not an issue with neovide. I wonder how much longer it will take to see a stable nvim 0.5 with LSP, but that's off-topic.

**Comment by shaunsingh** [comment]
I just updated both neovide and neovim, and looks like the issue is fixed now, must have been something upstream.

**Comment by Shatur** [comment]
> I just updated both neovide and neovim, and looks like the issue is fixed now, must have been something upstream.

Can confirm.

This only issue with Telescope I have now is a blurred background.

**Comment by shaunsingh** [comment]
> Is it possible to fix it for Vulkan version too? 

I would just switch over to openGL, its going to be the main branch soon enough

**Comment by Shatur** [comment]
> I would just switch over to openGL, its going to be the main branch soon enough

Vulkan branch just do not have blurred background issue, this is why I basically asking :)

**Comment by shaunsingh** [comment]
> Vulkan branch just do not have the blurred background issue, this is why I basically asking :)

Is that with multiGrid enabled?

**Comment by Shatur** [comment]
> Is that with multiGrid enabled?

Yep.

**Comment by last-partizan** [comment]
Oh, here it is! i forget to search issues before reporting my, i'll close it as duplicate :))

https://github.com/Kethku/neovide/issues/714

It should be fixed with this:
https://github.com/last-partizan/neovide/commit/ef487f13179418957bae941c80b12a1119169b04

Here's my PR: https://github.com/Kethku/neovide/pull/715

**Comment by Kethku** [comment]
Neovide no longer panics, but the floating window blur interacts pretty poorly with nvim-telescope.

I'm going to create a new issue talking about that problem

**Comment by aprowe** [comment]
Hello, 
I am using neovide 0.7.0 and neovim v0.5.0 on windows using `--multiGrid`. 
Telescope doesn't work, I get a blank telescope window in the top right. Can't interact with it, but esc closes it. 
It does however work without multiGrid

I see some related issues are tracked, but they seemed to funnel back here, couldn't find this specific combination being tracked.
