### ISSUE TITLE
Incorrect Font Rendering of Neovim's Integrated Terminal

### ISSUE THREAD

**Issue by brymer-meneses** [Kethku/neovide#663]
Opening the integrated terminal using [this plugin](https://github.com/akinsho/nvim-toggleterm.lua)
I get the following,

![2021-05-18_21-30](https://user-images.githubusercontent.com/68867487/118660421-c47e2e00-b820-11eb-857d-e757a40f4735.png)

Expected

![2021-05-18_21-31](https://user-images.githubusercontent.com/68867487/118660446-c9db7880-b820-11eb-885c-b5ecd63a08d2.png)

**Comment by Kethku** [comment]
Does this same color issue happen in terminal neovim?

**Comment by brymer-meneses** [comment]
It's also the same when I execute  `:terminal` 
![2021-05-19_12-41](https://user-images.githubusercontent.com/68867487/118757463-bcb19e80-b89f-11eb-925d-a01d65a850e1.png)

**Comment by brymer-meneses** [comment]
For context, I am using this [command prompt](startship.rs).

**Comment by Kethku** [comment]
ah my bad. I meant if you run neovim via nvim.exe (or whatever the executable extension is for your system) and then look at the terminal inside that. Do the colors mess up there? I'm trying to understand if this neovide specific or possibly upstream.

**Comment by brymer-meneses** [comment]
It seems that my colorscheme has to do with the incorrect colors I was seeing. But the incorrect font rendering is exclusive to neovide.

**Comment by Kethku** [comment]
in that case I will close. The core issue is split across font fallback, subpixel font rendering, and possible dpi problems which are all covered in other issues.
