### ISSUE TITLE
Feat: Frameless/no-toolbar mode?

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#664]
Hi! Is it possible to hide the toolbar at the top of neovide? When using tiling window managers (e.g. yabai), its unnessecary and doesn't look as good. 

For example emacs vs neovide: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/118671478-80117480-b7c5-11eb-9c96-71da9234a77c.png">

As you can see, emacs on the left doesn't have the top toolbar part, and looks a tad bit better. 

If this isn't possible as a toggle, by any chance can there be a script to build the app without toolbars? For example with emacs-plus, you can build it without toolbars by adding a --no-toolbar flag

**Comment by keithsim-msft** [comment]
repeat of https://github.com/Kethku/neovide/issues/67

**Comment by Kethku** [comment]
repeat of https://github.com/Kethku/neovide/issues/67
