### ISSUE TITLE
GitHub sponsorship

### ISSUE THREAD

**Issue by gshpychka** [Kethku/neovide#666]
Hi, thanks for the project. Consider enabling GitHub sponsorship for the project.

I know you have a page on KoFi, and this is just my personal opinion, but I'd like to have all my GH donations on GH.

I cannot use it yet (on Linux) due to font rendering issues, but would be happy to sponsor once the OpenGL and Font fallback work is done, which is not that far off, from what I can see.
Thanks.

EDIT: Ooh, nice issue number.

**Comment by dabing1022** [comment]
666

**Comment by Kethku** [comment]
I appreciate the kind words and will look into setting github sponsors up soon!

**Comment by Kethku** [comment]
I have started a sponsor page, but theres a fair bit of boiler plate. I hope to have it up in the next couple days

**Comment by Kethku** [comment]
Done. Thanks for the push :)

**Comment by j4qfrost** [comment]
https://ebay.to/3fiAKTB Those M1 Macs are expensive af.

**Comment by Kethku** [comment]
Yeah but I think its worth while in the end. I recently just got a patent grant for my day job that I'm also throwing into the pot ;)

**Comment by j4qfrost** [comment]
@Kethku Nice, and yeah I think with the amount of time everyone spends on this, it is well worth it. Also slipped my mind that we could've qualified for Google Summer of Code. I wish OSS qualified as charity work, though that's definitely vulnerable to abuse.
