### ISSUE TITLE
Telescope window opened at wrong position when Multigrid is enabled

### ISSUE THREAD

**Issue by Shatur95** [Kethku/neovide#673]
**Steps to reproduce**

1. Run `:Telescope planets` command

**Expected behavior**

![изображение](https://user-images.githubusercontent.com/22453358/119254182-9d778180-bbbd-11eb-990c-f53067a90cb2.png)

**Current behavior**

![изображение](https://user-images.githubusercontent.com/22453358/119254203-b1bb7e80-bbbd-11eb-955b-6d15ae5ad1e5.png)

**Version:** 0b976c3d28bbd24e6c83a2efc077aa96dde1e9eb (latest commit at the time of writing.
**OS:** Linux

**Comment by shaunsingh** [comment]
Duplicate of https://github.com/Kethku/neovide/issues/662

**Comment by Shatur95** [comment]
Missed it, thanks!
