### ISSUE TITLE
Override default mapping for the `/` key

### ISSUE THREAD

**Issue by brymer-meneses** [Kethku/neovide#674]
I use the mapping `<C-/>` for commenting several lines. However, I noticed that neovide maps the `/` key to the `Command Mode` making it impossible to remap `/`.

**Comment by Kethku** [comment]
I'm guessing that this is actually a keyboard handling issue rather than explicit keybinding because to my knowledge neovide doesn't bind any keybindings itself.

**Comment by brymer-meneses** [comment]
I found the solution to this, it turns out that for some reason the mapping `<C-/>` doesn't work for neovim on the terminal. So I had to use `<C-_>` which is exactly the same thing, in my neovim config. But now that I have `<C-/>` on my neovim config, it all works out.
