### ISSUE TITLE
Multigrid scrolling not working with trackpad/Magic Mouse (macOS) on the openGl branch

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#679]
Hi, sorry to bother you with another issue! scrolling doesn't seem to work with my MacBook trackpad or my Magic Mouse on the openGL branch, It works fine on the Vulcan branch, and a regular mouse seems to work fine too

**Comment by Kethku** [comment]
Interesting. I'm guessing this is an upstream issue. Would you be able to look at the winit docs and try some of the sample apps there to see if scrolling works as expected upstream? Its likely that there is a window event that we need to track

**Comment by shaunsingh** [comment]
I was looking at the source code and I found [here](https://github.com/Kethku/neovide/blob/54b967f41afa72f0148bce4217055134a2cb1aec/src/window/winit/mod.rs#L306) that you use lineDelta for getting scrolling information. 

I don't have much experience with winit, but from what I remember PixelDelta is used for touchpad scrolling, while lineDelta is used for the "stepped" scrolling you find in most mice. It should be a simple enough fix.

**Comment by Kethku** [comment]
I'll try to take a look in the not too distant future. Juggling a lot of other live issues though so it may be a bit. I'd be happy to give some pointers if you felt like opening a PR though!

**Comment by shaunsingh** [comment]
Sure! I found a simple implementation Alacritty uses so I'll quickly update my fork and get to work. I'll update you if theres any progress

**Comment by Kethku** [comment]
Let me know if you have any questions.

**Comment by shaunsingh** [comment]
Looks like this file: https://github.com/shaunsingh/neovide/blob/main/src/window/winit/mod.rs, is only in the Vulcan branch. Could you guide me as to what file handles mouse input in the openGL branch?

**Comment by shaunsingh** [comment]
Found it, no worries
