### ISSUE TITLE
Github Actions not working 

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#682]
Sorry to both you once again. Github actions seems to fail on working builds. Its a very minor issue (everything still builds fine locally) just something I thought I should let you know as it may initially be confusing to those newly forking the project 

The build fails under the `check formatting` section with the following output 

```
Diff in /Users/runner/work/neovide/neovide/src/bridge/events.rs at line 36:
             ParseError::InvalidWindowAnchor(value) => {
                 write!(f, "invalid window anchor format {}", value)
             }
            ParseError::InvalidFormat(debug_text) => write!(f, "invalid event format {}", debug_text),
            ParseError::InvalidFormat(debug_text) => {
              write!(f, "invalid event format {}", debug_text)
           }
         }
     }
 }
```

**Comment by PyGamer0** [comment]
and then some unused variables in the clippy section

**Comment by Kethku** [comment]
On it

**Comment by Kethku** [comment]
I just fixed the formatting and clippy errors. Should be working shortly
