### ISSUE TITLE
Scrolling doesn't work in Mac OS

### ISSUE THREAD

**Issue by Midren** [Kethku/neovide#683]
Neovide version: 0.7.0
OS: macOS 11.3.1 20E241 x86_64

NVIM v0.5.0-dev+1336-g045e47ec5
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by Midren** [comment]
It doesn't work only in opengl branch, as in master I have a blurry fonts

**Comment by Kethku** [comment]
@Midren interesting. Do you use a touch pad? Just recently a change went in to opengl branch to try to add scrolling support on macos when using a touch pad or magic mouse

**Comment by Midren** [comment]
Updated to the last version and it started working. And it works amazingly comparing to master!
