### ISSUE TITLE
Cursor does not move in the command line.

### ISSUE THREAD

**Issue by AlexApps99** [Kethku/neovide#685]
![Peek 2021-05-26 19-12](https://user-images.githubusercontent.com/30854646/119617907-67086380-be56-11eb-85b6-bd6b2564f5ed.gif)

To be clear, I was using the left arrow key to move the caret within the command.

Sorry if this is a duplicate, but I couldn't find one (I'm new to (Neo)Vim and its terminology)

**Comment by PyGamer0** [comment]
which version of neovide

**Comment by AlexApps99** [comment]
I got it from the AUR, was the git version so I assume its latest

**Comment by PyGamer0** [comment]
hmm can you try from opengl branch by building it yourself

**Comment by AlexApps99** [comment]
AUR already builds from source, so unless the branch contains a bugfix I don't expect the result to be any different

**Comment by PyGamer0** [comment]
does the aur use `main` branch by default?
he opengl branch is way different then the main

**Comment by AlexApps99** [comment]
It does not, though I do not have the time to test the branch right now, I suspect it may contain a potential fix (feel free to test if you wish)

**Comment by Kethku** [comment]
in the meantime you can fix the issue by setting g:neovide_animate_command_line to false

https://github.com/Kethku/neovide/blob/main/src/renderer/cursor_renderer/mod.rs#L30

**Comment by AlexApps99** [comment]
I got the OpenGL branch, this bug is fixed (though there is a worse one to take its place)
I won't open an issue because you are probably already aware of it
Thanks

![Peek 2021-05-26 19-12](https://user-images.githubusercontent.com/30854646/119768877-88785680-bf0d-11eb-9086-a1101a5f9ab4.gif)

**Comment by AlexApps99** [comment]
Oh and here's another weird bug
![Peek 2021-05-27 17-07](https://user-images.githubusercontent.com/30854646/119769232-3421a680-bf0e-11eb-9abc-74a2f6e1d663.gif)

I forgot to enable mouse capturing, but I was just dragging the window around
Note how the cursor also becomes misaligned to the grid while doing this

**Comment by AlexApps99** [comment]
Text rendering looks weird if it flows onto multiple lines (probably due to misalignment as shown earlier)
![image](https://user-images.githubusercontent.com/30854646/119769338-67fccc00-bf0e-11eb-8b09-bcbed19237af.png)

**Comment by AlexApps99** [comment]
![image](https://user-images.githubusercontent.com/30854646/119769416-895db800-bf0e-11eb-919e-eb6384216da7.png)
The gap can get really wide (cursor all the way at the edge of the screen in this case)

**Comment by AlexApps99** [comment]
Oh I should mention it's not even possible to type anything that requires shift too, in this branch (<>?:"{}|_+)
I'm using xfce4 and x11

**Comment by PyGamer0** [comment]
are you using a different keyboard layout

**Comment by AlexApps99** [comment]
I am using plain old QWERTY, and everything works as it should on `nvim-qt`.
If I had to guess, this is a problem with how input is handled via SDL2
