### ISSUE TITLE
Neovide runs as an xwayland window in Wayland (linux)

### ISSUE THREAD

**Issue by 21eleven** [Kethku/neovide#697]
I use the sway window manager which runs atop Wayland instead of X11. It appears that when I launch neovide it runs as an xwayland application meaning that on a high resolution monitor (ie 3840x2160) it looks low res/pixelated.

Is there a way to run neovide as a native Wayland application?

**Comment by shaunsingh** [comment]
The Vulcan (master) branch has issues with HiDPI displays, maybe try the openGL branch?

**Comment by Kethku** [comment]
Closing as I'm pretty sure this isn't a problem with the opengl change. @21eleven if you come back to this and find otherwise please reopen.

**Comment by 21eleven** [comment]
@shaunsingh I can confirm the `opengl` branch looks high res on a 4k monitor and runs as a wayland app in swaywm, thanks for the suggestion.

**Comment by Kethku** [comment]
We have merged the opengl branch to main now so there are further fixes there
