### ISSUE TITLE
[Linux] Text is always italic

### ISSUE THREAD

**Issue by osa1** [Kethku/neovide#70]
One of your recent commits made neovide usable for me (previously rendering was too slow, it was impossible to use).

Current problem is the text is always italic. My ginit.vim is empty, and I don't have any guifont-related lines in my init.vim. Here's a screenshot:

![Screenshot_2020-01-28_17-40-42](https://user-images.githubusercontent.com/448274/73273637-6675a380-41f5-11ea-9311-72a816fbdf21.png)

I'd be happy to help with diagnosing or fixing the issue if you give me some pointers.

**Comment by Kethku** [comment]
I'm going to fix the default font problem by embedding one. For now setting guifont would fix the issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by osa1** [comment]
Unfortunately setting guifont doesn't fix it, everything is still italic. Here's a screenshot after adding

```
set guifont=Iosevka\ SS10\ Medium:h13
```

to my init.vim:

![Screenshot_2020-01-28_22-21-26](https://user-images.githubusercontent.com/448274/73297372-8a001480-421c-11ea-9a79-31e9425bbd82.png)

**Comment by Kethku** [comment]
This is interesting. I think the problem comes from https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L43 where I access the first font in the list with a given name. I think there is a way to filter beyond just the first one which might fix the problem. Let me try that and report back.

**Comment by Kethku** [comment]
I believe this should be fixed now.

**Comment by Kethku** [comment]
I'm going to go ahead and close this. If you still run into it, let me know here though as I will be overhauling the fonts again soonish
