### ISSUE TITLE
[Linux OpenGL] Shift+Key doesn't work

### ISSUE THREAD

**Issue by ergpopler** [Kethku/neovide#700]
Shift+1 (!) doesn't work.
Shift+2(@) oddly does work.
Shift+r(R) works, so it is just about the special characters, not normal letters.

Linux(Ubuntu 20.04)
OpenGL Branch.
Regular en-us qwerty keyboard.

**Comment by Kethku** [comment]
repeat of https://github.com/Kethku/neovide/issues/691
