### ISSUE TITLE
When Building There Are a Lot Of Mismatched Type Errors With Bool To Integer (OS: Big Sur on M1)

### ISSUE THREAD

**Issue by Nejat88** [Kethku/neovide#702]

**Comment by PyGamer0** [comment]
Can you tell which branch/versoon ylu are trying to build?

**Comment by Nejat88** [comment]
It was on opengl branch but I deleted opengl thing because I was working on the wrong files but I solved the bool to i8 mistypes by hand

**Comment by Nejat88** [comment]
btw I managed to build
