### ISSUE TITLE
OpenGL: Cursor sometimes disappears when jumping around with the mouse quickly 

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#705]
When jumping around with the mouse the cursor sometimes disappears. I can't really reproduce the problem, it happens randomly. There isn't any feedback in the terminal either 

The cursor still exists as the particle trail can still be seen. 

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/71196912/120900616-b5aac000-c603-11eb-9b1b-19bc30b4a04e.png">

System Info: 
Latest Neovim + LuaJIT
Latest build of the neovide openGL branch
M1 on macOS 11.4

**Comment by Kethku** [comment]
I've noticed this as well. I think it has to do with the cursor blink logic.

Also I notice this happens frequently after the cursor freeze bug

**Comment by Kethku** [comment]
I just fixed this. Turns out we didn't expect the log component of the distance dependent animation length feature to go negative. It only happens rarely, but when it does, the cursor flys off into infinity and sometimes never comes back. A quick call to max(0.0) fixed the issue on my machine.
