### ISSUE TITLE
[Linux] Ctrl key doesn't work

### ISSUE THREAD

**Issue by osa1** [Kethku/neovide#71]
Under Linux it neovide simply doesn't understand the ctrl key, as a result some of the basic commands like `C-w h` etc. don't work.

Not sure if this is a duplicate of #27, please feel free to close if it is.

Again, I'm happy to help with diagnosing/fixing the issue if you give me some pointers.

**Comment by osa1** [comment]
I just realized that the Shift key works as CTRL..

**Comment by osa1** [comment]
It seems like Alt works as Shift.

**Comment by Kethku** [comment]
That's an interesting issue... Seems like on some systems the keyboard virtual keys from winit work incorrectly. Out of curiosity have you tried alacritty and does the keyboard work as expected there?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by osa1** [comment]
> Out of curiosity have you tried alacritty and does the keyboard work as expected there?

Yep, alacritty works as expected.

**Comment by Kethku** [comment]
Swapping over to https://github.com/Kethku/neovide/issues/27 which is my catch all "overhall the keybindings" issue
