### ISSUE TITLE
Multigrid is broken with latest neovim-git

### ISSUE THREAD

**Issue by last-partizan** [Kethku/neovide#714]
I'm using latest neovim#master, with my patch to fix menu rendering in multigrid mode and neovide#main

```
neovide-git 0.7.0.r24.g51fa8c0-1
neovim-git 0.4.0.r3810.gd09b8ad71-1
```

But when i trigger completion menu (or command completion menu), it doesn't appears, and i see this in terminal:

```
 ~ > export RUST_BACKTRACE=full
 ~ > /usr/bin/neovide --multiGrid
Ignored client type property: "methods"
Ignored client type property: "attributes"
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
stack backtrace:
   0:     0x556054a9cf70 - <unknown>
   1:     0x556054941dff - <unknown>
   2:     0x556054a9c7b1 - <unknown>
   3:     0x556054a9c115 - <unknown>
   4:     0x556054a9b46a - <unknown>
   5:     0x556054ab9288 - <unknown>
   6:     0x556054ab91fc - <unknown>
   7:     0x556054ab91ad - <unknown>
   8:     0x5560548f2fb0 - <unknown>
   9:     0x5560549cef27 - <unknown>
  10:     0x556054a01c80 - <unknown>
  11:     0x556054ad52d4 - <unknown>
  12:     0x556054accbf1 - <unknown>
  13:     0x556054ad0354 - <unknown>
  14:     0x556054acac0a - <unknown>
  15:     0x7f5ddca6a259 - start_thread
  16:     0x7f5ddc84f5e3 - __GI___clone
  17:                0x0 - <unknown>
```

**Comment by last-partizan** [comment]
```
nvim --version
NVIM v0.5.0-dev+1398-gd09b8ad71-dirty
```

nvim version is actually this, (for some reason PKGBUILD shows it as 0.4 ...)

**Comment by last-partizan** [comment]
https://github.com/neovim/neovim/commit/edb5864a29ec0d1049c4674afb75c8279301446c

probably this commit is related, they added z-index to ui_call_win_float_pos call.

**Comment by Kethku** [comment]
This has been fixed in the opengl branch. Let me find the commit

**Comment by Kethku** [comment]
The commits between https://github.com/Kethku/neovide/commit/19001398f2dc915c31a697fe4c3fb6b454ba7993 and https://github.com/Kethku/neovide/commit/8fe82c6ed9b60d532cff3dbe1fcbdbf657a2c3cf contain the fix for the z index problem.

Am I remembering correctly that you had issues with the opengl branch because of keyboard input problems?

**Comment by last-partizan** [comment]
Hmm, i don't remember exactly.

Yesturday i was trying opengl branch, and it failed to start becouse of my font settings.

After making this change, it works, i'll give it a try.

```vim
  set guifont=monospace:h24
  "set guifont=JetBrains\ Mono\ Nerd\ Font,DejaVu\ Sans\ Mono,Iosevka,DejaVu\ Sans,Droid\ Sans\ Fallback:h24
```

**Comment by last-partizan** [comment]
Oh, yes, and there is keyboard input problems in opengl branch.

I'll describe them in https://github.com/Kethku/neovide/issues/691
