### ISSUE TITLE
Neovide crash silently randomly

### ISSUE THREAD

**Issue by pencilcheck** [Kethku/neovide#727]
After building from stretch on mac, both master and opengl branch will exhibit the same issue that after opening a file and scroll around a bit the window will just suddenly crash and disappear. No error shown in the terminal though.

**Comment by Kethku** [comment]
@pencilcheck what version of neovim are you using? Could it be related to https://github.com/Kethku/neovide/issues/718? Do you have multigrid enabled?

**Comment by Kethku** [comment]
@pencilcheck I think I fixed the issues I knew would cause a crash. Can you try again and report if they are still happening?

**Comment by Kethku** [comment]
Closing as I'm pretty sure this fixed it. Please reopen if thats not the case.

**Comment by pencilcheck** [comment]
Sorry just saw the messages will try the latest version and reopen if it still crash
