### ISSUE TITLE
Couldn't find any available vsync extension

### ISSUE THREAD

**Issue by AnatoleLucet** [Kethku/neovide#729]
I built Neovide from source on Ubuntu 20.04 (in a virtualbox vm) but when I try to run it, I get the following error:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t find any available vsync extension")])', src/window/window_wrapper/mod.rs:452:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kethku** [comment]
This is weird. Does virtualbox normally have opengl support? I feel like thats probably not a supported platform.

However the vsync issue is interesting. I'm guessing we can turn that off

**Comment by AnatoleLucet** [comment]
> Does virtualbox normally have opengl support?

I really don't know about that 😕

**Comment by Kethku** [comment]
Some basic searching seems to indicate to me that virtualbox does not support opengl sufficiently for us to have a reasonable hope of running. I'm closing this as out of scope since we need gpu access to run
