### ISSUE TITLE
neovide panicked when loading font

### ISSUE THREAD

**Issue by befedo** [Kethku/neovide#732]
Hi there,

I get
```{text}
$ RUST_BACKTRACE=1 neovide 
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Could not load font', src/renderer/fonts/caching_shaper.rs:50:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
when starting neovide. `guifont` is set to Fira Code Nerd Font.

Best Regards
befedo

**Comment by Kethku** [comment]
What's the actual text set in the guifont option?

**Comment by Kethku** [comment]
Also what version of neovide are you using?

**Comment by befedo** [comment]
> What's the actual text set in the guifont option?

It’s `set guifont=Fira\ Code\ Nerd\ Font` and I’m on master.

Thanks for your time.

**Comment by shaunsingh** [comment]
Can you try `set guifont=FiraCode\ Nerd\ Font:h14` instead? I believe there isn't a space between `Fira` and `Code` for that font.

**Comment by Kethku** [comment]
Its a good point though. Looks like main crashes if guifont is invalid. That definitely needs fixed.

**Comment by befedo** [comment]
Hi there,

I'm on g51fa8c0 and have `set=guifont FiraCode\ Nerd\ Font:h14` and no panic occurs. When switching to g59629eb I'm not able to insert a `!` (for example), but this might be another issue and I'm looking into #445.

Thanks for your time and quick responses,
befedo

**Comment by verajosemanuel** [comment]
same here after upgrade to g8168023-1 any font issues panic
