### ISSUE TITLE
Cannot type most special characters (like `!`, `{`, etc) on linux.

### ISSUE THREAD

**Issue by rentruewang** [Kethku/neovide#735]
## Describe the bug

Some special characters that are typed with `shift + key` does not work.

## To Reproduce
Try typing any of `~!#$%^&*()_+{}|`, these are simply ignored (because the editor does not freeze after).
Weirdly enough, `@` seems to work.
This issue is only present on my Ubuntu 21.04 device. It works fine on Macs.

## Expected behavior
Should be able to type those characters. `nvim` has no problem handling these.

## Screenshots
After I typed `~!@#$%^&*()_+{}|`, only `@` shows.
Please not that it's not related to the theme. Completely remove `$HOME/.config/nvim` does not solve this.
![image](https://user-images.githubusercontent.com/32859905/122640687-76b45880-d133-11eb-9311-3eaed1e8870b.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 21.04
 - Neovide Version: 0.7.0
 - Neovim Version 0.5.0-dev

## Please run `neovide --log` and paste the results here:
Does not log anything after start.

**Comment by PyGamer0** [comment]
#445

**Comment by rentruewang** [comment]
@PyGamer0 Thanks for the quick response! However, I'm not sure these two are the same issue since I'm using en_US keyboard layout.

**Comment by jjhayes84** [comment]
I have the same issue on Arch Linux. US keyboard layout. If you find a solution let me know!

**Comment by jjhayes84** [comment]
I spoke too soon! Rebuilt today and it's working fine. Thanks!
