### ISSUE TITLE
Font italics not working in compiled app but working in app downloaded from releases

### ISSUE THREAD

**Issue by dineshKumar777** [Kethku/neovide#739]
**To Reproduce**
open the same file in both version of neovide (compiled and downloaded) with same neovim settings

**Expected behavior**
Gruvbox theme supports italicize for comment and string, which is working as intended in downloaded but not in compiled app

**Screenshots**
![image](https://user-images.githubusercontent.com/21097695/122704305-0e6b9100-d271-11eb-878b-dfde5d5aba2b.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Neovim Version [e.g. 0.5.0]
 - Neovide [0.5.0](https://github.com/Kethku/neovide/releases/tag/0.5.0)
 
**Please run `neovide --log` and paste the results here:**
[neovide_compiled.log](https://github.com/Kethku/neovide/files/6683908/neovide_compiled.log)
[neovide_downloaded.log](https://github.com/Kethku/neovide/files/6683918/neovide_downloaded.log)

Let me know if you need any other info regarding this.

**Comment by shaunsingh** [comment]
Can someone try this with bold/underlined fonts/themes as well?

**Comment by Kethku** [comment]
Underline works. Bold does not. This was a regression because I forgot to track it while reworking the font shaper.

**Comment by dineshKumar777** [comment]
@PyGamer0 @Kethku This is fixed with latest commit. we can close this one.
But other issue I am noticing is same font is displayed in different size.
My font is Hack:13. I think characters have less space compared to before??? 
hack font is correctly displayed in vulkan release. If there is no open bug already means I can create one too if you need.

**Comment by Kethku** [comment]
That would be great

**Comment by dineshKumar777** [comment]
#769 
This issue is resolved now. Closing.
