### ISSUE TITLE
Error while building Neovide on M1 Mac.

### ISSUE THREAD

**Issue by IBS27** [Kethku/neovide#741]
### I have been wanting to try out Neovide for the past few days. I followed all the instructions in the readme to install it. But when I run `cargo build --release` I get a huge error. 

The error is quite long so I put it in the file below.
[error.txt](https://github.com/Kethku/neovide/files/6695817/error.txt)

I tried many things but it just doesn't seem to work

### Since this didn't work I installed the .app file from the releases. After installation when I tried to open it, I get the following error. 
![Screenshot 2021-06-22 at 9 40 20 PM](https://user-images.githubusercontent.com/65481813/122961866-72da3d80-d3a2-11eb-892f-6e840a3726ba.png)

After looking at some other issues I went into the `Neovide.app/Contents/MacOS` directory and ran `chmod +x neovide`.
It started launching after the usual macOS security stuff. But it crashes immediately after launching.

**I have Xcode installed.
I am running macOS 11.4 on an M1 Mac Mini.** 

(Btw I used the 0.7.0 version of Neovide. I tried this with other versions too. No luck!)

@Kethku I just wanted to know when the homebrew cask for Neovide will come out. It will be much easier.

**Comment by shaunsingh** [comment]
> I have been wanting to try out Neovide for the past few days. I followed all the instructions in the readme to install it. But when I run cargo build --release I get a huge error.

Please try downloading the prebuilt binary from here: https://github.com/Kethku/neovide/suites/3053893722/artifacts/69453974, it should run natively as well. The download on the releases page is fairly outdated and is still based on the Vulkan platform 

> Since this didn't work I installed the .app file from the releases. After installation when I tried to open it, I get the following error.

The issue should be fixed (https://github.com/Kethku/neovide/issues/447) with the latest release 

> @Kethku I just wanted to know when the homebrew cask for Neovide will come out. It will be much easier.

I'm working on adding homebrew support. We will likely wait until a stable release is created, which should happen very soon. I expect the homebrew cask to be out sometime in the next week or two.

**Comment by IBS27** [comment]
I downloaded the prebuilt binary but I get this error.
![Screenshot 2021-06-22 at 10 46 54 PM](https://user-images.githubusercontent.com/65481813/122970599-c00edd00-d3ab-11eb-8f31-71d0abebae9a.png)

Great to see homebrew support is on the way!!

**Comment by shaunsingh** [comment]
Looks like theres an issue with code signing the app during the build process, ill take a look at it soon. 
 
In the meantime, can you try running the following commands? 

```zsh
sudo xattr -lr /path/to/neovide.app
sudo xattr -cr /path/to/neovide.app
sudo codesign -f -s /path/to/neovide.app
```

**Comment by IBS27** [comment]
I tried all three commands. Nothing worked. Earlier I had also installed the Gatekeeper helper tool and tried it. But, even that didn't work.

**Comment by shaunsingh** [comment]
Can you try downloading the [intel version](https://github.com/Kethku/neovide/runs/2882952951?check_suite_focus=true), and see if it launches, or does it give the same error?

**Comment by IBS27** [comment]
I tried it. It doesn't give me any error saying it is damaged. But, it crashes immediately if I open it from the finder. But I tried to open it from the terminal with `open Neovide.app` and it worked.

**Comment by IBS27** [comment]
But there are some errors with rendering NERDTree. 

This is how it looks in terminal Neovim:
![Screenshot 2021-06-23 at 7 41 51 PM](https://user-images.githubusercontent.com/65481813/123112355-433b3c00-d45b-11eb-9b6c-0b7b5bc897fb.png)

This is how it looks in Neovide:
![Screenshot 2021-06-23 at 7 42 53 PM](https://user-images.githubusercontent.com/65481813/123112402-4b937700-d45b-11eb-8355-d983308ebecb.png)

**Comment by shaunsingh** [comment]
I'm currently working on fixing the macOS build issue, so that should be resolved soon. As for the icons, make sure you have `guifont` set to a font that supports those glyphs (e.g. a nerd font)

> Also, I can't open it in the directory I want to. It always opens in the root directory.

Alias the neovide exutable itself to `neovide` for the time being. You can then open files in directories using 
```zsh
cd (wherever) 
neovide (filename)
```
(to locate the executable right click on .app, show package contents, there should be a thing with the terminal icon that says `neovide`, then add it to your `zshrc`.)

**Comment by IBS27** [comment]
I have set it to the JetBrainsMono nerd font.

**Comment by IBS27** [comment]
Can you assist me on how to create an alias for opening neovide in the current terminal directory?

**Comment by shaunsingh** [comment]
Assuming your using `zsh`, open your ~/.zshrc file (e.g. `nvim ~/.zshrc`) and add the following line 

`alias neovide="/Users/shauryasingh/IdeaProjects/neovim/neovide/target/release/neovide"`

where `neovide` at the end is the path to the executable. If you have neovide in your application folder, it may look something like 

`alias neovide="/Applications/Neovide.app/Contents/MacOS/neovide"`

**Comment by IBS27** [comment]
But, when I do that even though the app opens and runs, I get this in the terminal:
![Screenshot 2021-06-23 at 7 57 01 PM](https://user-images.githubusercontent.com/65481813/123114838-3c152d80-d45d-11eb-90a6-376c0edcb712.png)

**Comment by shaunsingh** [comment]
Thats normal behavior.

**Comment by IBS27** [comment]
By when do you think the native M1 build can be fixed?

**Comment by shaunsingh** [comment]
Most likely after https://github.com/Kethku/neovide/pull/746 is done, reviewed, and merged.

**Comment by IBS27** [comment]
Ok. And do you have any suggestions for the icon rendering issue. I tried a few other nerdfonts but none of them worked.

**Comment by IBS27** [comment]
And, the smooth scrolling is not that smooth. It says multigrid has to be enabled. I just wanted to know how to do that.

**Comment by IBS27** [comment]
> And, the smooth scrolling is not that smooth. It says multigrid has to be enabled. I just wanted to know how to do that.

Never mind. I got to know.

**Comment by shaunsingh** [comment]
> Ok. And do you have any suggestions for the icon rendering issue. I tried a few other nerdfonts but none of them worked.

No idea, sorry. You can try changing the icons in your configuration if you would like 

> And, the smooth scrolling is not that smooth. It says multigrid has to be enabled. I just wanted to know how to do that.

You have to launch neovide with the multigrid flag (`neovide --multiGrid)

**Comment by IBS27** [comment]
I'll try that. Thanks

**Comment by IBS27** [comment]
Is there any way I could add a padding to the windows?

![Screenshot 2021-06-23 at 9 54 01 PM](https://user-images.githubusercontent.com/65481813/123133594-869ea600-d46d-11eb-873b-46a59a86141d.png)
As you can see in the above pic the window seems to be cut a bit on the top and even on the left. Is there any way to solve this?

**Comment by IBS27** [comment]
In Neovide the auto brackets plugin isn't working.

In terminal neovim if I type `{` or `"` or something like that, the second bracket is automatically typed. For this functionality, I use this plugin `'jiangmiao/auto-pairs'`.

However, the same functionality doesn't work in neovide. I tried a bunch of plugins with similar features but none of them worked. 

What could be the reason for this?

**Comment by IBS27** [comment]
Sorryyy. Closed it by mistake.

**Comment by shaunsingh** [comment]
I would take a look at this issue: https://github.com/Kethku/neovide/issues/445, its a bug with dead keys.

**Comment by IBS27** [comment]
> But there are some errors with rendering NERDTree.
> 
> This is how it looks in terminal Neovim:
> ![Screenshot 2021-06-23 at 7 41 51 PM](https://user-images.githubusercontent.com/65481813/123112355-433b3c00-d45b-11eb-9b6c-0b7b5bc897fb.png)
> 
> This is how it looks in Neovide:
> ![Screenshot 2021-06-23 at 7 42 53 PM](https://user-images.githubusercontent.com/65481813/123112402-4b937700-d45b-11eb-8355-d983308ebecb.png)
> 
> Also, I can't open it in the directory I want to. It always opens in the root directory.

Regarding this problem, I found out that some glyphs were not rendering in neovide. I used the same font in both terminal and neovide and it renders without problems in the terminal. I think this is an issue with rendering in neovide.

Do you have any suggestions as to what I can do?

**Comment by IBS27** [comment]
> I would take a look at this issue: #445, its a bug with dead keys.

But is there a solution already implemented for this?

**Comment by shaunsingh** [comment]
> But is there a solution already implemented for this?

Not yet. You can make some basic autopair functionality with nnoremap (`nnoremap [ []` for example) and see if it works. 

> Regarding this problem, I found out that some glyphs were not rendering in neovide. I used the same font in both terminal and neovide and it renders without problems in the terminal. I think this is an issue with rendering in neovide.

I would create a separate issue for this. Describe what build of neovide and neovim you're using, as well as exactly what font. Certain fonts (isoveka for example) have edge cases where they don't function correctly

**Comment by IBS27** [comment]
I am using the latest prebuilt binary for intel macs as the m1 build didn't work on my m1 mac. My neovim version is 0.5.0.
The font I am currently using is CaskaydiaCove Nerd Font. But I have also tried it with the FiraCode, FuraCode and JetBrainsMono nerd fonts. None of them worked.

**Comment by shaunsingh** [comment]
@IBS27 you can continue the discussion here: https://github.com/Kethku/neovide/issues/748, if you would like.
