### ISSUE TITLE
Debounce Cursor Moves When Jumping To Message/CommandLine

### ISSUE THREAD

**Issue by dineshKumar777** [Kethku/neovide#743]
**Describe the bug**
mouse scrolling animation is triggered randomly when typing. This is so distracting.

https://user-images.githubusercontent.com/21097695/123016096-81971380-d3e7-11eb-8c6c-d33c400245aa.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version [built from source]
 - Neovim Version [0.5.0]

**Please run `neovide --log` and paste the results here:**
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6698055/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
Do you have lsp enabled? I think what might be happening is there is a message which is sending the cursor to the commandline every time it pops up.

I'll have to think a bit about how to fix that...

**Comment by dineshKumar777** [comment]
yes I have nvim builtin lsp enabled. You are correct. this is not reproducible in :new buffer

**Comment by shaunsingh** [comment]
If you're using `nvim-compe`, for now put `set shortmess+=c` in your init.vim/.vimrc.

**Comment by dineshKumar777** [comment]
Thanks for the workaround @shaunsingh . Adding shortmess cmd minimized issue.. But still issue is there.

**Comment by PyGamer0** [comment]
is this somehow related to #341 ?

**Comment by dineshKumar777** [comment]
@PyGamer0 @Kethku For me issue is still there even after this fix. Is it working for you guys with lsp enabled?

https://user-images.githubusercontent.com/21097695/123539555-f8217180-d757-11eb-9888-b9f29ebc767a.mp4

**Comment by dineshKumar777** [comment]
@Kethku Is this fixed completely. I am still seeing debounce effect randomly. But its not frequent as before but it still exists.
