### ISSUE TITLE
Shift key is not working for most (but not all) symbols

### ISSUE THREAD

**Issue by chrisbouchard** [Kethku/neovide#744]
**Describe the bug**
When using Neovide, if I hold shift to type a symbol on my US English keyboard&nbsp;&mdash; e.g., shift+\` for ~ or shift+1 for !, or shift+' for "&nbsp;&mdash; nothing happens in any mode (as if the keypress was ignored). I can still type `, 1, and ' normally. I can use shift with any letter to get a capital letter, and oddly I *can* use shift+2 for @ and shift+; for :.

**To Reproduce**
1. Open Neovide.
2. Enter insert mode.
3. Hold shift and press 1.
4. See that nothing happens.

**Expected behavior**
We should see a ! typed in this particular example.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 34 (GNOME on X.org, Radeon with the built-in `amdgpu` driver)
 - Neovide Version: 0.7.0 (built from `main`, commit 113a3f4, [copr build](https://copr.fedorainfracloud.org/coprs/chrisbouchard/neovide-nightly/build/2285820/))
 - Neovim Version: v0.5.0-dev+1429-gb585f723b

**Please run `neovide --log` and paste the results here:** [See gist](https://gist.github.com/chrisbouchard/91d9d3c016d4e3774f3f87fd18bd1405)

**Additional context**
This happens with both left and right shift, and it happens even if I run Neovide with the `--clean` Neovim flag to disable my config and plugins. It does *not* happen if I run `nvim` in my terminal emulator (clean or otherwise) or in any other program that I've noticed.

**Comment by bnjmnt4n** [comment]
Seems like you just missed PR https://github.com/Kethku/neovide/pull/736 which should address this.

**Comment by chrisbouchard** [comment]
Yep, pulled the new build and the problem is resolved. Sorry for the noise.

**Comment by Kethku** [comment]
All good! Closing this.
