### ISSUE TITLE
Hitting the + button sends `<S-+>`, which appears to behave differently from just `+`

### ISSUE THREAD

**Issue by Resonious** [Kethku/neovide#750]
**Describe the bug**
Neovide appears to be sending `<S-+>` instead of `+`.

Normally this is not a problem. Other symbols that require shift seem to work fine (e.g. `*` sends `<S-*>` but works as expected)

**To Reproduce**
1. Use a keyboard layout where "+" requires you to hold shift
2. Press +
3. Instead of the normal `+` behavior, my cursor moves down one screen.

**Expected behavior**
I jump to the beginning of the next line.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 4159c47ff4f30073b92b9d63fc6ab70e07b74b6d
 - Neovim Version v0.4.4

**Please run `neovide --log` and paste the results here:**

If you want the whole thing, let me know, but this line stood out to me:
```
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <S-+>
```

**Additional context**
I have some free time right now and am messing with the Neovide source code as I write this :grin:.

I added a quick hack like this and it fixed the problem:
```rust
// src/bridge/ui_commands.rs
            UiCommand::Keyboard(input_command) => {
                trace!("Keyboard Input Sent: {}", input_command);
                if &input_command == "<S-+>" {
                    nvim.input("+").await.expect("Input failed");
                } else {
                    nvim.input(&input_command).await.expect("Input failed");
                }
            }
```

But I'm wondering if we should just not wrap shifted keys with `<S-` at all. Will continue playing around and update this if I find any good ideas.

**Comment by Kethku** [comment]
I have merged your proposed change into https://github.com/Kethku/neovide/pull/752

**Comment by Kethku** [comment]
The change has merged.

**Comment by Resonious** [comment]
Works for me ™️
