### ISSUE TITLE
[Request] Delete OpenGL branch

### ISSUE THREAD

**Issue by shaunsingh** [Kethku/neovide#754]
**Describe the bug**

Is it fine if we delete the OpenGL branch and leave a note on the README that the feature is merged into Main? Quite a few issues in the past week have been from people using the outdated branch.

**Comment by j4qfrost** [comment]
Sounds like a good idea, but I would actually leave the opengl branch open with just a README there instead, that way the main branch's README doesn't have any clutter. @Kethku sound good to you?

**Comment by Kethku** [comment]
I've been meaning to do this for a while 😅 I think its a great idea. But honestly we should just delete the branch and leave the readme as is. I think people will get the idea if the branch is just missing.

I don't feel strongly about it through. I'll delete the branch now, but if either of you want to edit the main readme/revive the branch with a readme, go ahead.

**Comment by Kethku** [comment]
Done. I also cleaned up a bunch of merged pr branches. Thanks for the poke

**Comment by j4qfrost** [comment]
I just didn't want people to start creating issues saying "OpenGL branch is missing"
