### ISSUE TITLE
Bracket Autocomplete Issue in Neovide

### ISSUE THREAD

**Issue by MR-TLL** [Kethku/neovide#756]
When using the Neovim configuration [link](https://github.com/siduck76/NvChad) , the pair auto completion does not works in the latest version of neovide , whereas pair autocompletion works in terminal and older builds of Neovide.

**To Reproduce**
1. Go to  [link](https://github.com/MR-TLL/NvChad/tree/7464358bbf29e8ce4ca0a84e9de60263649dfa95) and clone this particular commit. (Do not clone the latest commit)
2. Install latest neovim-nightly and Neovide-git (aur)
3. Install the configuration  by running ./install.sh (Back up your previous nvim config)
4. Open a C++ file and open a bracket , the closing bracket won't be autocompleted.

**Expected behavior**
When opening a bracket like "{" , a corresponding "}" must appear , this behavior is followed in terminals, nvim-qt and older version of neovide (0.5) using the same configuration as provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/76173714/123479180-97881c80-d611-11eb-849b-d72adcd49a8b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Neovide-git ( Precompiled build from chaotic-aur , date of build : 25-06-2021 , version : 0.7.0.r48.g7a1fa12-1 )
 - Neovim Version : Neovim nightly bin 0.5.0+dev+1434+g24e0c16fd-1

**Please run `neovide --log` and paste the results here:**
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6718498/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
I believe this is fixed in https://github.com/Kethku/neovide/pull/752

**Comment by Kethku** [comment]
Can you try there?

**Comment by MR-TLL** [comment]
I tried the latest binary from here #752 : [link](https://github.com/Kethku/neovide/actions/runs/970298572) and this seems to have fixed the problem. Thank you so much :+1: 
I request to you also merge this PR with main branch , so that it can be reflected in the neovide-git aur package.

**Comment by Kethku** [comment]
I will do that. It doesn't fix all the issues highlighted in that thread, but I might as well since it seems to fix problems for others.
