### ISSUE TITLE
Neovide will not run on NixOS

### ISSUE THREAD

**Issue by wrkzk** [Kethku/neovide#758]
**Describe the bug**
I have installed Neovide through nixpkgs, and when I try to start it, it gives me this error:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. `nix-env -iA nixos.neovide`
2. `neovide`

**Expected behavior**
Neovide begins running and opens a window.

**Desktop (please complete the following information):**
 - OS: NixOS unstable
 - Neovide Version: 0.7.0
 - Neovim Version:  0.5.0

**Additional context**
I have seen lots of people mentioning similar scenarios to this all over, and I was wondering if this issue varies case-by-case or if there had been any progress made on getting Neovide to work on nixos.

**Comment by bnjmnt4n** [comment]
https://github.com/NixOS/nixpkgs/pull/127506 will fix the current issue.

**Comment by teto** [comment]
if you think it's a nixos issue, you should report it there. I've just merged a neovide update in nixpkgs so you can try that instead, I know the recent neovide (~this week) fixed most of my issues, which were similar to what yo u faced. I think this can be closed.
