### ISSUE TITLE
Incorrect window size when using font scaling under Gnome/Xwayland

### ISSUE THREAD

**Issue by last-partizan** [Kethku/neovide#771]
I use 4k display, with font scaling set to 1.6, when neovide opens new window, i don't see statusline, it's somewhere below window border. When i resize window, it will correct itself, and i see statusbar.

When i set scaling to 1.0, neovide starts with correct window size and statusbar is visible.

**To Reproduce**
1. In Gnome, use tweak-tools to set scaling to something bigger than 1.0
2. export WINIT_UNIX_BACKEND=x11
3. Run neovide

**Screenshots**
- [Incorrect size with 1.6 scaling](https://user-images.githubusercontent.com/301015/123742528-772bbc80-d8b4-11eb-8d83-af5579a1a4fb.png)
- [Correct size with 1.0 scaling](https://user-images.githubusercontent.com/301015/123742570-8b6fb980-d8b4-11eb-85ca-5f14beb47c8e.png)

**Desktop (please complete the following information):**
 - ArchLinux (Gnome/Wayland)
 - neovide-git 0.7.0.r61.gbc1009b-1
 - neovim-git 0.4.0.r3826.g141647cfb-1

**Additional context**
I use WINIT_UNIX_BACKEND=x11 to fix window decorations #728, and looks like it cannot resize properly in this case. Without this, on wayland session - size is correct.

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6731300/neovide_rCURRENT.log)

**Comment by last-partizan** [comment]
It happens when using Xorg session too, so that's probably not related to Xwayland specifically, but to Xorg in general.

**Comment by Kethku** [comment]
I've encountered this issue on windows as well. I'm hopeful that in progress work to get the size to actually match the passed geometry, and equivalent work to get the start menu to start correctly will address this problem as well.

**Comment by last-partizan** [comment]
![image](https://user-images.githubusercontent.com/301015/124360165-ff052400-dc30-11eb-9975-174b5f5bb175.png)


I've added some debug `println` into handle_new_grid_size, and this is what i get on start:

wayland:
```
Renderer font 8x18
Send resize 100x50
```

x11:
```
Renderer font 8x18
Send resize 160x80
```

If i change window size just a little, next update is correct for both cases (100x50).

Oh! i found why it was happening. First handle_grid_size was using logical, and second was using physical.

![image](https://user-images.githubusercontent.com/301015/124360410-4b049880-dc32-11eb-8032-3688c4f5dc61.png)


This fix takes care of the problem. But, maybe it's better to pass `LogicalSize` to `handle_new_grid_size`? @Kethku what do you think?
