### ISSUE TITLE
Text is not rendered vertically centered on each line, but is rendered too high up

### ISSUE THREAD

**Issue by Hubro** [Kethku/neovide#775]
**Describe the bug**

Text is not rendered at the vertical center of each line, but is instead rendered near the top:

![image](https://user-images.githubusercontent.com/597206/123876465-b05b3f80-d93b-11eb-974d-fd5087adf005.png)

Here's how it looks in xfce4-terminal:

![image](https://user-images.githubusercontent.com/597206/123876503-bc470180-d93b-11eb-8a34-c9292c54d07a.png)

Font used in both pictures: Liberation Mono (size 10 in terminal, h14 in Neovide)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: main branch (b0222d206e6c0775d0f75a470bdca355251e7713)
 - Neovim Version master branch (v0.5.0-dev+1459-g384f9870f)

**Please run `neovide --log` and paste the contents of the `.log` file here:**

https://gist.githubusercontent.com/Hubro/d53c69b04bb71035accc021790ffe1db/raw/066de6b886f69fa1bac5642660787bee5bfcb8f8/neovide_rCURRENT.log

**Comment by Kethku** [comment]
This is a known issue. I haven't quite figured out what combination of metrics gets the desired effect from swash.

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/pull/795 Could folks try this branch? It seems to act closer to what I expect, but I'm not sure if its the right fix.

**Comment by clason** [comment]
Yes, that is much better but not perfect yet:

<img width="350" alt="Screenshot 2021-07-05 at 22 30 13" src="https://user-images.githubusercontent.com/2361214/124515779-9197f580-dde0-11eb-882a-b4c360a12ec8.png">

(Look at the parentheses)

**Comment by Kethku** [comment]
Can you grab a comparison screen cap? It's hard to tell what the difference is

**Comment by clason** [comment]
Yeah, the difference is smaller than I made it out to be ;) But at least the top of the parentheses no longer touch the border of the cell. Here's the same on `main`:

<img width="352" alt="Screenshot 2021-07-05 at 22 58 12" src="https://user-images.githubusercontent.com/2361214/124517529-7a5b0700-dde4-11eb-9380-8385f4adf4b0.png">

**Comment by Kethku** [comment]
Ah sorry I meant a comparison to a terminal ground truth

**Comment by Hubro** [comment]
@Kethku 

Terminal ground truth (Alacritty, Liberation Mono 10pt):

![image](https://user-images.githubusercontent.com/597206/124520340-792dd800-ddec-11eb-8749-2b0e8f903227.png)

Neovide `gd2e33b8` (Liberation Mono h14):

![image](https://user-images.githubusercontent.com/597206/124520369-96fb3d00-ddec-11eb-8ddd-5483ee948471.png)

Seems to consistently draw everything 1px too high up on the line.

Neovide `vertical-positioning-fix` (Liberation Mono h14):

![image](https://user-images.githubusercontent.com/597206/124520686-69fb5a00-dded-11eb-89b7-2c2a2e5f1241.png)

Neovide now draws the text positioned more or less identical to Alacritty! I tested this and got the same results with Roboto Mono and Source Code Pro as well. It definitely seems to me like this patch fixes the vertical positioning issue.

**Comment by Kethku** [comment]
This is merged, so I think this is fixed.
