### ISSUE TITLE
Font size changes drastically based on resolution

### ISSUE THREAD

**Issue by codic12** [Kethku/neovide#779]
**Is your feature request related to a problem? Please describe.**
The font size of neovide, when set to an arbitrary value (using h18 as an example here) drastically changes on my 1920x1080 and 1920x1200 displays.

**Describe the solution you'd like**
The font size remains the same, as is done with most terminal emulators and other vim GUIs I've tried.

**Additional context**
On 1200p with h18:
![image](https://user-images.githubusercontent.com/48339289/124160533-3321ee80-da51-11eb-91ab-0af379cda329.png)
On 1080p with h18:
![image](https://user-images.githubusercontent.com/48339289/124160663-551b7100-da51-11eb-8f85-6381d946d673.png)
The difference should not be so drastic.

**Comment by Kethku** [comment]
What operating system are you using? looks like some form of linux? X11? Wayland?

**Comment by codic12** [comment]
I'm using X11 with the latest Xfce desktop on Arch Linux.

Sorry about the enhancement label, missed that!

**Comment by Kethku** [comment]
Is there any dpi scaling being done by your OS? I'm not sure how resolution of the monitor could effect text size without scaling of some sort going on.

**Comment by codic12** [comment]
I'm not using any type of scaling at all.

It's possible maybe that neovide treats the font size as relative to the resolution?

(the 1080p monitor is my laptop's inbuilt panel, the 1200p one an external one)

**Comment by Kethku** [comment]
No I don't think so. Neovide gets a scaling factor from winit which is equivalent to the dpi scaling. Other than that, font size is just consistent.

I'm not sure what is going on here...

**Comment by codic12** [comment]
It may be something odd about my setup then but I can't think of anything.

**Comment by codic12** [comment]
Actually, maybe winit detects my laptop is a High-DPI display and as such gives neovide a scaling factor > 1.0, even though I don't have scaling enabled?

**Comment by codic12** [comment]
Forgot to mention the font I'm using is Jetbrains Mono, but the behavior is reproducible with any font for me.

**Comment by last-partizan** [comment]
I think neovide is using some weird way to scale fonts.

I'm using gnome with 4k display, and scaling set to 1.6

In my terminal i use font size 11, but in neovide before opengl was merged i was using h25, in current master with x11 i use h18, but in wayland it must be h25 to get roughly same font size as 11 in terminal.

**Comment by last-partizan** [comment]
How does it work now?

Also, run neovide with `--log`, and show `grep scale neovide_rCURRENT.log`

**Comment by codic12** [comment]
I uninstalled and reinstalled neovide as well as did a pacman -Syu and I can't reproduce this issue :thinking: 
Weird, I'll close it for now.

**Comment by samuelabreu** [comment]
For others with font scaling issues.

On my built-in screen it was fine, but on my external monitor font size was really big, to fix it i have to use:

`WINIT_X11_SCALE_FACTOR=3 neovide`

**Comment by codic12** [comment]
I found the solution for this when using another editor; I just set the Xft.dpi property in .Xresources. Pretty sure this will work for neovide too.
