### ISSUE TITLE
file path in the window title

### ISSUE THREAD

**Issue by Stanislav-Lapata** [Kethku/neovide#78]
planning to add the file path to the window title?
<img width="795" alt="path-to-file@2x" src="https://user-images.githubusercontent.com/12072329/73392184-5f7c8d00-42ea-11ea-96d3-771dee57afb9.png">

**Comment by Kethku** [comment]
Sure. Done.

**Comment by mmstick** [comment]
Doesn't seem to be working on Linux

![Screenshot from 2021-09-16 18-23-42](https://user-images.githubusercontent.com/4143535/133649623-ecd9febd-8f42-4e0b-b81e-6171b43f74ba.png)

**Comment by Kethku** [comment]
What version are you using?

Note: you have to use `set title` in your config
