### ISSUE TITLE
Keyboard layout on macOS

### ISSUE THREAD

**Issue by kropper** [Kethku/neovide#79]
I have a non-English keyboard layout on my MacBook, and some keys (especially in combination with Alt, or Shift+Number) do not yield the expected characters in the neovide window. Is there any documentation / hints available on how this could be solved?

Thanks!

**Comment by Kethku** [comment]
repeat of https://github.com/Kethku/neovide/issues/27 I'm aware of the issue and have been brainstorming issues over there
