### ISSUE TITLE
Using alt gr + q starts search instead of writing a slash on br keyboard

### ISSUE THREAD

**Issue by Diegovsky** [Kethku/neovide#796]
**Describe the bug**
When writing commands (e.g: `:cd` ) it starts a search, as if a slash (/) was pressed in normal mode. 

**To Reproduce**
1. Be in normal mode;
2. Start to type a command using ':';
3. Input said combination;
4. It starts a search.

**Expected behavior**
A slash to be written instead of starting a search.

**Desktop (please complete the following information):**
 - OS: Arch Linux, 
 - Neovide Version: 0.7.0
 - Neovim Version: 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Not much happened but here's a log anyway:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

**Additional context**
On ABNT keyboards (qwerty Brazillian keyboard, layout `br` of xkb) it's possible to enter a slash by pressing Alt Gr + Q and it works perfectly in terminal emulators so I'm not sure that's a feature.

**Comment by Diegovsky** [comment]
More info: it also happens when using insert mode.

**Comment by Kethku** [comment]
Please try using main. I think this has been fixed

**Comment by Diegovsky** [comment]
It has been fixed in main. However I'm experiencing significant stuttering and slowdowns; should I open a new issue?

**Comment by Kethku** [comment]
That would work. If you can provide some examples of the slow down, that would help a bunch
