### ISSUE TITLE
Neovide resizes after going into maximized

### ISSUE THREAD

**Issue by PyGamer0** [Kethku/neovide#803]
**Describe the bug**
I usually use neovide with `--maximized`. After pulling from main and building neovide, I opened it with `--maximized` and it starts and maximized and then **resizes**.

**To Reproduce**
1. Open neovide usin `--maximized`

**Expected behavior**
Neovide to start in maximized

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version `main`
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by last-partizan** [comment]
Should be fixed now.
