### ISSUE TITLE
Neovide first line placed in middle of the screen at launch after latest update

### ISSUE THREAD

**Issue by dineshKumar777** [Kethku/neovide#807]
**Describe the bug**
This used to work correctly. After taking latest today, noticing first line is placed in middle of the screen. Upon toggling fullscreen, first line goes back to top of the screen.

![image](https://user-images.githubusercontent.com/21097695/124864226-2f084a80-dfd6-11eb-8bdc-d53a7be9e1df.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by Kethku** [comment]
I noticed this as well. I believe it only happens when you have scaling enabled. But I'm not sure...

**Comment by Kethku** [comment]
Can confirm, this just happens all the time. Very weird...

**Comment by dineshKumar777** [comment]
Yes.. Only workaround is toggling full screen for now.

**Comment by Kethku** [comment]
Fixed
