### ISSUE TITLE
DPI scaling does not update when moving the window to another monitor

### ISSUE THREAD

**Issue by fredizzimo** [Kethku/neovide#810]
**Describe the bug**
Neovide always seem to use the DPI settings of the monitor it was launched on. So if you are using monitors with different DPI settings and drag the window to another montitor, then the text will probably be either too big or too small.

**To Reproduce**
1. Launch Neovide on one monitor
2. Draw the window to another monitor with a different DPI
3. Notice that the text size changes to be either too big or too small

But note:

4. Close Neovide and launch it on the other monitor
5. Notice that the text size is correct according to the DPI settings

**Expected behavior**
The text size should be the same for step 3. and 5.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version: Manually built Git commit abb05ab7b80393958413c67dd94270fa9336a8f1
 - Neovim Version v0.5.0

**Additional context**
Note that it also doesn't react to changing the scaling in the Windows settings. Most apps seems to react to that too without a need for restart, so I believe that Neovide should handle that case too.

**Comment by fredizzimo** [comment]
I just noticed that this is a known issue with the newly merged scaling fixes https://github.com/Kethku/neovide/pull/793#issuecomment-875022483

**Comment by last-partizan** [comment]
Could you please check how it works with `scale-factor-updates` branch?

**Comment by last-partizan** [comment]
Also note, initial font size will be smaller comparing to `main` branch, and similar to other apps.

**Comment by fredizzimo** [comment]
@last-partizan,

It works a little bit better, but there are still problems

I have two montiors one 28" 4k at 175% scaling, and another 22" 1050p, so both have a PPI of around 90, or in other words the same text size in other applications. 

If I start Neovide on my 4k display with 175% scaling, it initially has the correct text size, and it's the same as notepad with the same text size. When I drag it to the other display, it still stays correct (which it didn't do before). But once I drag it back to the 175% display, the font gets bigger, I think it's 75% too big. However, if I drag it back to the 100% display the text is correct, but once again wrong when I move the window to the 175% display.

If I start it on the 100% display, then the text size is correct, just like it was before, but it immediately gets doubled when I move it to the 175% display, and back to normal when I move it to the 100% display again.

Next I tested setting the scaling to 125% on my smaller monitor. And I got the same problem, once I moved the window back, the font became 25% too big.

After that, I tested changing the scaling on the fly in the Windows settings. That also behaves the same way, it scales too much, but at least it properly reacts to the setting change now.

I'm not fully sure about the 75% and 25%, but I compared both with notepad, by changing the font 1.75 times and  1.25 times respectively (well as close as I could, since notepad does't support fractional sizes), and they both seem to match, at least by a quick visual inspection, and it also makes sense for a potential bug to behave this way.

**Comment by last-partizan** [comment]
@fredizzimo your report was very useful, i found bug in my calculations and fixed it.

I updated `scale-factor-updates` branch, please check again. (you may need to do `git reset --hard origin/scale-factor-updates`, becouse i rebased it few times).

**Comment by fredizzimo** [comment]
@last-partizan,

Thank you, the scaling seems to work fine now
