### ISSUE TITLE
Cannot press * from numpad

### ISSUE THREAD

**Issue by shift-d** [Kethku/neovide#815]
**Describe the bug**
If i wish to press `"*` combination, or type `*`, i can't press `*` from numpad

**To Reproduce**
1. Open neovide
2. Try to type `*` from numpad in any mode

**Expected behavior**
`*` on numpad should work

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.5.0
 - Neovim Version 0.5.0

**Additional context**
I've installed neovide from scoop

**Comment by PyGamer0** [comment]
Try building from the main branch. Or get one from [here](https://github.com/Kethku/neovide/actions/runs/1016440448).

**Comment by Kethku** [comment]
This is fixed in main. Not sure how we can help beyond that other than update scoop once a new version is out which we are already planning on doing.
