### ISSUE TITLE
Immediate crash upon left clicking on window title bar

### ISSUE THREAD

**Issue by krage** [Kethku/neovide#82]
Any kind of click seems to do it.  Checked back through recent commits and it appears to have started with 29dc2c766b8432c7e6af45b527464d51ae9fde56.

**Comment by Kethku** [comment]
Arg. Winit strikes again

**Comment by Kethku** [comment]
What platform?

**Comment by Kethku** [comment]
I'm not seeing it on windows...

**Comment by krage** [comment]
Windows 10 here.

**Comment by Kethku** [comment]
Thats very strange... Give me a sec

**Comment by Kethku** [comment]
No error or anything? I'm not seeing it at all

**Comment by Kethku** [comment]
https://github.com/rust-windowing/winit/issues/1391

**Comment by krage** [comment]
Nothing displayed in any way, as soon as left mouse is pressed on that titlebar there's a very brief delay and then the whole window (and process) vanishes.

**Comment by Kethku** [comment]
Arg. Looks like this is a bug in current master of winit https://github.com/rust-windowing/winit/pull/1422

**Comment by Kethku** [comment]
Hasn't been reviewed yet. I suppose I can revert the winit upgrade, but I wish I wouldn't have to

**Comment by krage** [comment]
From a bit more poking at it in my environment:

Various window manipulations that still works without crashing:
- minimize/maximize/restore via both titlebar buttons and keyboard shortcuts
- resize to left/right half of monitor via Win+Left/Right Arrow
- move to other monitors via Win+Shift+Left/Right Arrow
- repositioning window via [altdrag](https://stefansundin.github.io/altdrag/)
- right-clicking on titlebar and using the move/size options from that context menu to move/resize the window

Other manipulations that are crashing:
- resize via dragging window edges
- resizing via [altdrag](https://stefansundin.github.io/altdrag/)

Happy to try out other suggestions/fixes here.

**Comment by Kethku** [comment]
Just tried the PR. It doesn't fix the issue :l

**Comment by Kethku** [comment]
And it looks like its a problem for all versions of 0.20.0

**Comment by Kethku** [comment]
Fixed this by reverting.
