### ISSUE TITLE
Panic at startup: "Failed to initialize any backend"

### ISSUE THREAD

**Issue by bitterjug** [Kethku/neovide#820]
**Describe the bug**

Having installed Neovide 0.7.0 from snap store I get  a thread panic on startup:
_Failed to initialize any backend!_

**Screenshots**
```
❯ RUST_BACKTRACE=1 neovide
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
Ignored client type property: "methods"
Ignored client type property: "attributes"
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: winit::platform_impl::platform::EventLoop<T>::new_any_thread
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
   3: winit::platform_impl::platform::EventLoop<T>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:581:9
   4: winit::event_loop::EventLoop<T>::with_user_event
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:134:25
   5: winit::event_loop::EventLoop<()>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:120:9
   6: neovide::window::window_wrapper::start_loop
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:204:22
   7: neovide::window::create_window
             at /root/parts/neovide/build/src/window/mod.rs:50:5
   8: neovide::main
             at /root/parts/neovide/build/src/main.rs:198:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Desktop (please complete the following information):**
 - OS: Ubunu 18.04.5 (but same error on my 21.04 machine)
 - Neovide: 0.7.0
 - Neovim:
```
NVIM v0.5.0-654-g3acfefb63
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include
Compiled by root@lgw01-amd64-012
```

**Please run `neovide --log` and paste the contents of the `.log` file here:**

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
```

Installed with `snap install neovide`, could this be a snap sandbox issue?

**Comment by Mate2xo** [comment]
I have the exact same error, with the snap package, on Ubuntu 20

**Comment by bitterjug** [comment]
Today I build Neovide from source, at commit  `f58b947`, and now it works ok.
My nvim is also installed as a snap --thought I'd mention as @Mate2xo mentioned appimage.

**Comment by Kethku** [comment]
> I have the exact same error, with the snap package, on Ubuntu 20.
> The Neovim I have on my system is an `.appimage`, I wonder if that could be the problem.
> 
> I have then built Neovide from source, and when lauching it I got this error
> 
> ```
> ERROR [neovide::bridge] nvim not found!
> ```
> 
> Is there a way to configure Neovide to point to my Neovim appimage? I couldn't find anything related to that in the Wiki.
> 
> Using the [remote TCP](https://github.com/Kethku/neovide/blob/main/README.md#remote-tcp-support) option on `localhost` works though, it's apparently the only way I can launch Neovide on my sytem

It must be on the system path. Thats how neovide knows where to find it

**Comment by Kethku** [comment]
> Today I build Neovide from source, at commit `f58b947`, and now it works ok.
> My nvim is also installed as a snap --thought I'd mention as @Mate2xo mentioned appimage.

Interesting. Not sure what would have fixed that... But I guess your problem is fixed now?

**Comment by bitterjug** [comment]
Well, this was on my home machine and I was wondering if I could install this on my work laptop in which case snap would be preferable to building from source. If I find another Ubuntu box to play with I might try and snap install neovide and nvim and see if they play nice together.

**Comment by Mate2xo** [comment]
> 
> It must be on the system path. Thats how neovide knows where to find it

Actually, it was on my system path, but my appimage file was named `nvim.appimage`. Renaming it to just `nvim` made it visible by neovide. Thanks :+1:

**Comment by Kethku** [comment]
Closing as I think both problems are resolved. Feel free to reopen if not
