### ISSUE TITLE
0.7 version can enter chinaese?

### ISSUE THREAD

**Issue by guolimin1995** [Kethku/neovide#830]
**Describe the bug**
can not enter chinaese.  this version fixed or not?
verison: 0.7
neovim: 0.5
macos: 10.15.4

thanks.

**Comment by guolimin1995** [comment]
0.7 version in my system macos 10.15.4 can not enter chinaese. it is not fixed or its my init.vim config problem.

**Comment by PyGamer0** [comment]
0.7 from releases? or from main branch?

**Comment by guolimin1995** [comment]
> 0.7 from releases? or from main branch?

follow the install steps
git clone https://github.com/Kethku/neovide
then  build

**Comment by guolimin1995** [comment]
main branch not fixed this problem?

**Comment by Kethku** [comment]
ime support required to type chinese characters is not yet done. The issue tracking this work is here: https://github.com/Kethku/neovide/issues/243
