### ISSUE TITLE
Neovide-specific config

### ISSUE THREAD

**Issue by albert-ying** [Kethku/neovide#835]
Hi, I want to have separated configurations for neovim and neovide in init.vim.

Is there any condition I can use to separate them?

For example, for the configurations specific to neovim-vscode plugin in init.vim, I use:

```
if exists('g:vscode')
  " something....
else
  " something....
```

**Comment by jairovsky** [comment]
Neovide defines `g:neovide`. This has been mentioned in other issues but I think it's not in the wiki.

**Comment by comiluv** [comment]
This needs to be documented!
