### ISSUE TITLE
Can't open neovide

### ISSUE THREAD

**Issue by Empathy117** [Kethku/neovide#840]
**Describe the bug**
I'm using neovide from aur and I can't open it after the update.

**To Reproduce**
1. open neovide

**Screenshots**
![can't open neovide](https://user-images.githubusercontent.com/60363116/126901521-aa8196d4-f46c-48b5-b35a-0d4fcd8da036.png)

**Desktop (please complete the following information):**
 - OS: Arch linux 5.12.15-arch1-1
 - Neovide Version 0.7.0.r103.gf6a8ffc-1
 - Neovim Version 0.5.0-1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
`.log` file is empty.

**Comment by dineshKumar777** [comment]
For me adding guifont in Init.vim as mentioned in Readme solved this problem.

**Comment by Empathy117** [comment]
> For me adding guifont in Init.vim as mentioned in Readme solved this problem.

I already add it.
