### ISSUE TITLE
Discrepancy with nvim-qt regarding command key mappings on osx

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#90]
I've been playing with this today and seems awesome so far.  I found that my config seems to completely work with neovide except for cases where I bind something to the OSX command key.

The issue seems to be caused by the fact that, for example, the mapping for osx-command-key+m (aka `D-M`) needs to be lower case with neovide but needs to be upper case for nvim-qt.

This can be reproduced by executing `<c-v>` inside insert mode and then holding down the osx command key then hitting any key (eg. `m`).  On nvim-qt this prints `<D-M>` and on neovide this prints `<D-m>`.  I am not sure if this is a bug in nvim-qt or neovide, but currently this behaviour forces me to have two different configs for each neovim GUI in order for meta key bindings to work

**Comment by justinmk** [comment]
it's a bug in nvim-qt.  

- `cmd-shift-m` should send `<D-M>`
-`cmd-m` should send `<D-m>`.

Tested with:

```
nn <D-m> <cmd>put ='lower'<cr>
nn <D-M> <cmd>put ='upper'<cr>
call nvim_input('<D-M><D-m>')
```

I'm a bit surprised that `nvim` itself cares about sensitivity for `<D-..>` but that's a happy accident. The only reason `<C-..>` is case-insensitive is historical/legacy. Super key doesn't have such baggage.


> but currently this behaviour forces me to have two different configs for each neovim GUI in order for meta key bindings to work

Do you mean "super"? Meta would be `<A-..>` (aka `<M-..>`)

**Comment by svermeulen** [comment]
Oops, sorry, I meant command key, not meta key, in that last sentence.  Ok thanks, I'll move this over to neovim-qt.
