### ISSUE TITLE
Add command args and help via clap

### ISSUE THREAD

**Issue by Kethku** [Kethku/neovide#97]
General command line argument parsing

**Comment by Kethku** [comment]
Done. Had to roll my own as clap does too much and I couldn't figure out a way to filter out some args and pass the rest through.

**Comment by Kethku** [comment]
Reopening as the current solution is very much a hack and I would greatly prefer to use clap.

One proposed solution that I liked is to use -- to separate neovide arguments from neovim arguments. We would probably special case opening a given file, but this solution is likely something clap supports.

**Comment by ErikMayrhofer** [comment]
I drafted up a PR to fix this: #680

**Comment by PyGamer0** [comment]
@Kethku we can now close this issue right??

**Comment by Kethku** [comment]
Yes! Thanks for the reminder
